### ISSUE TITLE
Bypassing AllowReflection = false via exceptions

### ISSUE THREAD

**Issue by MissyMelissa** [Microsoft/ClearScript#1]
It looks like it's possible to bypass AllowReflection = false via exceptions. Here is a very basic example that demonstrates the problem:

```C#
using System;
using Microsoft.ClearScript.V8;

namespace ClearScriptTest2
{
	public class Test
	{
	}

	class Program
	{
		static void Main(string[] args)
		{
			using (var engine = new V8ScriptEngine()) {
				engine.AddHostType("Console", typeof(Console));
				engine.AddHostObject("test", new Test());
				engine.AllowReflection = false;

				engine.Execute("try { test.GetType(); } catch (ex) { Console.WriteLine(ex.hostException.GetType().Assembly.FullName); }");
			}

			Console.ReadLine();
		}
	}
}
```

The first `GetType()` will throw an exception (and it is caught by javascript), but the second `ex.hostException.GetType()` does not throw an exception.

**Comment by ClearScriptLib** [comment]
Nice find! The problem is that ClearScript traps `Object.GetType` but not `Exception.GetType`.

**Comment by Rene-Sackers** [comment]
@ClearScriptLib I assume you're overriding `GetType` on that exception, maybe check if the calling method is an override of `Object.GetType` using [this](http://stackoverflow.com/a/2932448/439094) on [this](https://github.com/Microsoft/ClearScript/blob/47c60bd7c85012ff02c76875d69ff303b681c174/ClearScript/HostItem.InvokeMethod.cs#L477)?

**Comment by ClearScriptLib** [comment]
@Rene-Sackers `Exception.GetType` isn't an override of `Object.GetType`; in fact, the latter isn't virtual. `Exception.GetType` is an implementation of an interface method (`_Exception.GetType`). It calls `Object.GetType` internally, but otherwise the methods are unrelated. Our [fix](https://github.com/Microsoft/ClearScript/commit/98656144dfc87af0082e216847bc9256d2268a12) simply blocks all three.

**Comment by MissyMelissa** [comment]
Thank you for the quick fix!

**Comment by Rene-Sackers** [comment]
Cool! One more question though.

![image](https://cloud.githubusercontent.com/assets/5124807/25749084/89290b48-31ad-11e7-8c7e-05f9aa67824f.png)

Shouldn't all these be checked/blocked, in case any are exposed through `AddHostType`? It might be irrelevant, only a question/suggestion :)

**Comment by ClearScriptLib** [comment]
@Rene-Sackers You make a good point, but most of the remaining `GetType` methods are reachable only if the script has already gained access to a reflection object. We also don't expect hosts to expose JScript.NET internals for scripting. `AppDomain` is an interesting case, but `Object` and `Exception` should cover most things likely to be made scriptable.
