### ISSUE TITLE
Including new c++ routine inside ClearScript/V8

### ISSUE THREAD

**Issue by neutronhive** [Microsoft/ClearScript#10]
Hi,
I have some functions that I want to call whenever a some javascript is loaded. Those functions are written in C.
1- I don't want those function visible to .NET framework.
2- I want those function to be part of the V8 engine somehow...
3- I am wondering even how to start and achieve this kind of work.

I need some help and guidance.
Please don't throw us on to some abstract links to compile and build the V8 from scratch.
We have a product almost in completion stages and this the last thing we want to achieve ASAP.

Thanks in Advance.

**Comment by ClearScriptLib** [comment]
A couple of questions:
1. Is your product a .NET application? If so, is it already using ClearScript?
1. Are you looking to expose C/C++ resources so that they're visible to script code? Or do you just need to run some native code before and/or after script execution?

**Comment by neutronhive** [comment]
The product is build using C#.Net and Windows Forms and uses ClearScript. We want some API to be part of the scripting engine. The reason for that is we want in no way that those API should be called by some hacker from outside the application using reflection or something.... 
I also would like that no one can use proxy dlls in between our application and V8 engine.

To be straight forward, The scripts that are loaded are our algorithms and we do not want anyone to know about them in anyway.

So, yes, as you said in statement 2- "Are you looking to expose C/C++ resource so that they're visible to script code?" Yes..
I will call those resources a C/C++ function.

So, when we call in .NET , engine.Execute(script_code)...

this script_code at some point passed to the V8.. for example... v8engine.execute(script_code).
inside the implementation of this V8 code, we want to make our own certain call on the script_code...
v8::execute(script_code)
{
   bool is_finalized = false;
   while(!is_finalized) {
   our_proprietary_process1_execute(script_code);
   is_finalized = our_proprietary_process1_execute(script_code);
   } 

   v8::orignal_execute(script_code);
}

At the moment, we are doing this processing inside the .Net Framework... Just before calling the 
clearScriptEngine.execute call. But we want to change it to the one stated above ?

**Comment by ClearScriptLib** [comment]
If you wish to add custom _unmanaged_ pre-processing of script code, you'll have to modify ClearScript's V8 bridge (ClearScriptV8), probably somewhere inside [`V8ContextImpl::Execute`](https://github.com/Microsoft/ClearScript/blob/master/ClearScript/V8/ClearScriptV8/V8ContextImpl.cpp#L420).

**Comment by neutronhive** [comment]
Perfect. It will almost solve the problem. I have one more question on the same line:
We will release the product out for evaluation.
When we load a script into the V8 Engine, there is a small problem,
customer can load his own code and call our algorithm.
Instead of calling our code... user can do this (for example our algorithm is algo1):
alert(algo1) or console.print(algo1)...
This will print out the source code for our algorithm.

How do we deal with this ? so, that when user tries to print algo1, instead of seeing source code, he sees something as object or see native object?

We really appreciate you help on this. This should have been our first thing to focus in the beginning of the project... but somehow it was dragged to the end of all the task with assumptions that we can handle it later...

**Comment by ClearScriptLib** [comment]
A couple more questions:
1. In your description above, what is `algo1`? Is it a JavaScript function? How does your application create and invoke it?
1. It sounds like your application runs both system and customer script code within the same engine instance, and you'd like to protect the system code from customer inspection or meddling. Is that correct?

**Comment by neutronhive** [comment]
You are very much correct. 

> algo1 

is javascript code and it was processed by some of function. But yes it is javascript function inside the same engine instance. Currently, algo1 is loaded the same way as any other code... that is clearScriptEngine.execute(strAlgo1);
Now this is available to the JavaScript code executed in the same Java Script engine...

**Comment by ClearScriptLib** [comment]
Continuing your example, `strAlgo1` probably looks something like this:
```JavaScript
function algo1(a, b, c) {
    /* do stuff */
}
```
This does the job, but as you've realized, it allows untrusted customer code to inspect your function's source code or clobber it with another function or value.

Instead, try something like this:
```JavaScript
Object.defineProperty(this, 'algo1', {
    value: (function (a, b, c) {
        /* do stuff */
    }).bind(this)
});
```
This way your algorithm is hidden, and `algo1` cannot be reassigned, redefined, or deleted.

**Comment by neutronhive** [comment]
I tested this approach and it works great... I really appreciate your help and effort on this.
Thanks a lot guy. Will keep you updated 👍
