### ISSUE TITLE
Clearscript holding references to CLR instances

### ISSUE THREAD

**Issue by andrejpk** [Microsoft/ClearScript#100]
Hi everyone.. I've been using ClearScript for a project where I need to share validation and calculation code between server and client. Overall this has worked very well. 

The one challenge has been an ongoing memory leak. I'm calling Javascript functions hosted by ClearScript, passing in some Entity Framework objects. I think ClearScript is holding references to those instances because the ClearScript runtime has no way of knowing if Javascript is holding those references anywhere. That hunch was supported by this profiler trace where ClearScript.HOstItem/HostObject was keeping a strong handle on my entity instance: 

![image](https://user-images.githubusercontent.com/1774478/52177362-ba3de000-278d-11e9-9e9e-3f220bdf9ef0.png)

So I need to work out a way to release these references. So far I can think of a few ideas:

1. Marshal these entities into simpler types that could be passed by value -- but ultimately I still have complex types so I'd have to use structs here. I'm not sure I can map everything into value types and structs

2. Create/destroy a new instance of the ClearScript host for each call. -- This would add some overhead because I have to inject my model code with every call.

3. Use a different hosting model (e.g. out-of-process Node.js I call with the data)

I don't know if there's a easy solution here but I need to resolve this memory leak. Does anyone have experience with this or suggestions on a good approach?

**Comment by andrejpk** [comment]
Thinking about this a little more, maybe the best way to handle this is to stringify in incoming and outgoing data in JSON.. that would solve this issue and let me use complex data while keeping ClearScript and staying in process.

**Comment by andrejpk** [comment]
Thanks, this is great information!!  I didn't see it in any docs unless I missed something. Would it help if I wordsmithed this into a PR for the docs?

**Comment by ClearScriptLib** [comment]
Thanks @andrejpk. We have indeed found that some questions pop up repeatedly, but so far we've just let the information sit in the Issues section, not knowing where else to put it.

We already have an API reference, tutorial, samples, and build/deployment guide. Maybe we should have another document for implementation notes and/or best practices? Another possibility might be to enable GitHub's project-level Wiki.

We'd love to hear your thoughts!

**Comment by andrejpk** [comment]
I'll think through the best way.. my immediate thought is a deeper/best practices doc would be a good place for this.

Another question: am I safe in assuming that if I pass a value type like a string into a Javascript function, that holds no references to objects on the CLR side, right?

**Comment by jerrys-msft** [comment]
>Another question: am I safe in assuming that if I pass a value type like a string into a Javascript function, that holds no references to objects on the CLR side, right?

Strings, numbers, and bools are passed by value; that is, they're converted to JavaScript values and detached from any managed data.

Other CLR values, including all structs and enums, are [boxed](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing) and held by reference, although there's some machinery in place to enable "natural" comparison (e.g., `x === DayOfWeek.Thursday`) for enums and some other values. See [`ImmutableValueAttribute`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ImmutableValueAttribute.htm
) for more information.

That's the default behavior, and there are ways to override it in specific situations - e.g., if you need to preserve the exact managed type of a numeric value, or provide access to a CLR-specific string method. `V8ScriptEngine` also supports optional timestamp conversion (see [here](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngineFlags.htm)).

**Comment by ClearScriptLib** [comment]
>Another question: am I safe in assuming that if I pass a value type like a string into a Javascript function, that holds no references to objects on the CLR side, right?

Strings, numbers, and bools are passed by value; that is, they're converted to JavaScript values and detached from any managed data.

Other CLR values, including all structs and enums, are [boxed](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/boxing-and-unboxing) and held by reference, although there's some machinery in place to enable "natural" comparison (e.g., `x === DayOfWeek.Thursday`) for enums and some other values. See [`ImmutableValueAttribute`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ImmutableValueAttribute.htm
) for more information.

That's the default behavior, and there are ways to override it in specific situations - e.g., if you need to preserve the exact managed type of a numeric value, or provide access to a CLR-specific string method. `V8ScriptEngine` also supports optional timestamp conversion (see [here](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngineFlags.htm)).

**Comment by ClearScriptLib** [comment]
Created Issue #101 to track the best practices documentation. Feel free to reopen this if you have additional questions about the original topic. Thanks!
