### ISSUE TITLE
How to await/flush promises?

### ISSUE THREAD

**Issue by danielelkington** [Microsoft/ClearScript#103]
Suppose I have something like this:
`engine.Execute("myAsyncFunction(); // returns a promise")`
On the .net side, is there a way to wait for the promise to be resolved? Is there any way to await pending promises?

**Comment by ClearScriptLib** [comment]
Hi @danielelkington,

>On the .net side, is there a way to wait for the promise to be resolved? Is there any way to await pending promises?

Sure. You can call JavaScript methods directly, and you can pass delegates in place of JavaScript functions. Here's a quick example:

``` C#
Action<object> onResolved = value => Console.WriteLine("Resolved: " + value);
Action<object> onRejected = reason => Console.WriteLine("Rejected: " + reason);

dynamic promise1 = engine.Evaluate("Promise.resolve(123)");
promise1.then(onResolved, onRejected); // writes "Resolved: 123"

dynamic promise2 = engine.Evaluate("Promise.reject('failed')");
promise2.then(onResolved, onRejected); // writes "Rejected: failed"
```

Good luck!

**Comment by danielelkington** [comment]
Thanks for your assistance.
