### ISSUE TITLE
VBScriptEngine Line Numbers of Script errors 

### ISSUE THREAD

**Issue by NickJWilliams** [Microsoft/ClearScript#105]
It is possible to get the line number of a syntax error when using the VBScriptEngine?

Ideally I would like to inform the user that the script they have entered has an issue, and display the line where the issue occurred.

When I try to execute a bad script, an exception is thrown but it does not contain the line number of the error.

**Comment by ClearScriptLib** [comment]
Hello @NickJWilliams,

Unfortunately Windows Script engines only provide detailed error information when debugging features are enabled (see [`WindowsScriptEngineFlags.EnableDebugging`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_WindowsScriptEngineFlags.htm)).

You can then use [`ScriptEngineException.ErrorDetails`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngineException_ErrorDetails.htm) to access syntax or runtime exception details. For example, this code:

``` C#
using (var engine = new VBScriptEngine(WindowsScriptEngineFlags.EnableDebugging)) {
    try {
        engine.Execute("Sample.vbs", @"
            a = 1
            b = 2
            c = ""hello""
            d = ^*&(bogus
        ");
    }
    catch (ScriptEngineException ex) {
        Console.WriteLine(ex.ErrorDetails);
    }
}
```

produces the following output:

```
Syntax error
    at (Sample.vbs:4:28) -> ^*&(bogus
```

Good luck!

**Comment by NickJWilliams** [comment]
Thank you,

I have one other question. Is there anyway to force a debugger to launch, or to force a break on the next statement?

Many Thanks
Nick

**Comment by ClearScriptLib** [comment]
Hi Nick,

If you enable VBScript debugging as shown above, executing a [`stop`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/zw86czy2(v%3dvs.84)) statement should give you a chance to launch and attach Visual Studio in script mode:

``` C#
engine.Execute("stop");
```

Unfortunately newer Visual Studio versions are a bit flaky here. If you encounter issues, try launching Visual Studio _before_ running your application, and then selecting that running instance from the dialog that pops up when the script engine executes `stop`.

Good luck!

**Comment by NickJWilliams** [comment]
That's great, thank you for your help :-)
