### ISSUE TITLE
Nothing

### ISSUE THREAD

**Issue by NickJWilliams** [Microsoft/ClearScript#106]
Hello,

I am using the VB Script engine and am trying to pass Nothing (Null) to one of the functions in an exposed host object. However it appears as Nothing is undefined?

m_scriptEngine.script.nothing = {[undefined]}

How to resolve this?

Many Thanks
Nick

**Comment by ClearScriptLib** [comment]
Hi Nick,

That's correct. ClearScript marshals `nothing` and `empty` into [`Undefined`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Undefined.htm) values, whereas VBScript's `null` shows up as `null` on the managed side.

If passing `null` isn't an option for your script code, you could add an overload of your host function that has an `Undefined` parameter. More details on your scenario could help us suggest other options as well.

Good luck!

**Comment by NickJWilliams** [comment]
Hi,

Thanks for getting back to me. I've already worked round it, but wanted to check that I wasn't missing something. As you state, VBScript supports 'Nothing'. 

Thanks again. :)
Nick

**Comment by ClearScriptLib** [comment]
No problem at all! Please reopen this issue if you have more questions on this topic.

**Comment by NickJWilliams** [comment]
Hi,

I have a Host method that returns nothing in some instances and a COM object in others. I would like to trap for the value returned to check if it is valid. With EnableNullResultWrapping set to false, the VB script throws an error 'Object Required'. With EnableNullResultWrapping set to true, the function succeeds but I am unable to check whether the value is null or not. 
e.g.

Set obj = MyHostObject.GetCOMObject()

If IsNull(obj) then
     msgbox "Is Null"
Else
     msgbox "Is Not Null"
End If

IsNull never seems to return true, even thought obj is nothing.

BTW I have also added a Host object instance.

scriptEngine.AddHostObject("host", HostItemFlags.GlobalMembers, New HostFunctions())

Any help would be appreciated.

Thanks
Nick

**Comment by ClearScriptLib** [comment]
Hi @Nick,

You can make one of two changes to get the desired behavior:
1. Disable null result wrapping and use use `obj = ` instead of `set obj = `. If the method returns `null`, you can test for it using VBScript's [`IsNull`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/zbchw6hz(v%3dvs.84)) function.
2. Enable null result wrapping and continue using `set obj = `. If the method returns `null`, you can test for it using ClearScript's [`isNull`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_isNull.htm) function. Your test above fails because you're still using VBScript's built-in `IsNull` function. Try `host.isNull` instead.

Good luck!

**Comment by NickJWilliams** [comment]
Thanks for the reply.
So it is not necessary to use 'Set' in Clear script?
Is it possible to access the host object IsNull method without specifying the Host. prefix?

Thanks :-)

**Comment by ClearScriptLib** [comment]
>So it is not necessary to use 'Set' in Clear script?

It's [VBScript](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/t0aew7h6(v=vs.84)) that executes script code, not ClearScript.

The [`Set`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/4afksd44(v%3dvs.84)) statement requires an _object expression_, and while `nothing` satisfies that requirement, `null` and `empty` do not. Non-object expressions (strings, numbers, etc.) must use "normal" assignment (without `Set`).

Unfortunately things get murkier with .NET in the mix. As marshaled by ClearScript, most .NET objects can be used with _both_ normal and `Set` assignment, but fundamental values (strings, numbers, etc.) cannot, and neither can `null`. Therefore, a .NET method that returns an object instance or `null` can be clumsy to consume from VBScript.

To help resolve this we've added things like [`MarshalNullAsDispatch`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_WindowsScriptEngineFlags.htm) and [`EnableNullResultWrapping`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_EnableNullResultWrapping.htm), but they have their own issues.

>Is it possible to access the host object IsNull method without specifying the Host. prefix?

Apparently not, as VBScript doesn't seem to allow hosts to override its built-in [`IsNull`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/zbchw6hz(v%3dvs.84)) function.

Good luck!

**Comment by NickJWilliams** [comment]
Thanks for the detailed explanation :-)

**Comment by ClearScriptLib** [comment]
The next ClearScript release will allow .NET methods and properties to explicitly return the value `nothing` to script code. That should make it easier to create VBScript-friendly APIs.

**Comment by NickJWilliams** [comment]
That's great news. Would it also be possible to support the Nothing keyword in VBScript? At the moment Null appears to be the closest match. When can we expect the next release?

Thanks
Nick

**Comment by ClearScriptLib** [comment]
Hi Nick,

VBScript is supported in its entirety today, including the `nothing` keyword. The issue is what happens when `nothing` crosses the host-script boundary.

If script code passes `nothing` to a host method, the host sees it as `null`. Unfortunately there's no way to change that; it's a limitation of the .NET Framework.

On the other hand, it _is_ possible for the host to pass `nothing` to script code. Currently it does that by passing `null` in conjunction with special options such as null result wrapping and null-as-dispatch marshaling.

In ClearScript 5.5.6 you'll be able to use something like `return Nothing.Value` to pass `nothing` to script code unconditionally. The script code will then be able to use its native `is nothing` test.

ClearScript 5.5.6 should be out within several weeks.

Good luck!

**Comment by NickJWilliams** [comment]
Thanks, I have noticed that passing Null from script to a host method appears to work. Where as Nothing does not...

**Comment by ClearScriptLib** [comment]
[Version 5.5.6](https://github.com/Microsoft/ClearScript/releases/tag/5.5.6) includes the [`Nothing`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_Nothing.htm) class.

**Comment by NickJWilliams** [comment]
Brilliant, that's great news. Thank you :-)

**Comment by EtienneLaneville** [comment]
> If script code passes `nothing` to a host method, the host sees it as `null`. Unfortunately there's no way to change that; it's a limitation of the .NET Framework.

This is still the case with version 7.3.0 correct? I am getting the following exception, which is consistent with your statement:

> Invalid property assignment

This is something that is possible with the MSScriptControl though.

**Comment by ClearScriptLib** [comment]
Hello @EtienneLaneville,

>This is still the case with version 7.3.0 correct?

VBScript and .NET behave as before, but some clarification might be helpful. Here's how VBScript's special values are handled as they move from script code to the host application:

| VBScript code passes | ClearScript receives | Host application receives |
| :---: | :---: | :---: |
| `null` | [`DBNull.Value`](https://docs.microsoft.com/en-us/dotnet/api/system.dbnull.value) | `null` |
| `nothing` or `empty` | `null` | [`ScriptEngine.UndefinedImportValue`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_UndefinedImportValue.htm) |

>This is something that is possible with the MSScriptControl though.

Please clarify. What doesn't work as you expect with ClearScript?

Thanks!

**Comment by EtienneLaneville** [comment]
That table was very helpful. I have set `ScriptEngine.UndefinedImportValue` to `null` and things work as expected. Once again, thanks for the great help!
