### ISSUE TITLE
ClearScript and the XML Document Object Model

### ISSUE THREAD

**Issue by AdamSobieski** [Microsoft/ClearScript#107]
Greetings. Does anybody know of any projects which implement the W3C XML DOM in .NET for convenience with XML documents in scripting environments using ClearScript?

**Comment by ClearScriptLib** [comment]
Hi @AdamSobieski,

The .NET Framework provides extensive XML support in its `System.Xml` and `System.Xml.Linq` namespaces. A simple example:

``` C#
engine.AddHostType(typeof(XmlDocument));
engine.AddHostType(typeof(Console));
engine.Execute(@"
    var doc = new XmlDocument();
    var root = doc.CreateElement('Widget');
    root.SetAttribute('Length', '123');
    root.SetAttribute('Width', '456');
    doc.AppendChild(root);
    Console.WriteLine(doc.OuterXml);
");
```

Good luck!

**Comment by AdamSobieski** [comment]
Thank you for ClearScript which is simplifying and accelerating a few projects including some pertaining to new programming and markup languages which utilize JavaScript.

Thank you for the example showcasing how to include XML documents and functionality in scripting environments. For the specific project, I might wrap the `System.Xml` functionality with new classes to deliver aspects of the specific W3C XML DOM JavaScript API’s which Web developers are familiar with.

**Comment by ClearScriptLib** [comment]
Hi [@AdamSobieski,](url)

As far as we know, `System.Xml` supports the W3C XML DOM with only a small number of [minor differences](https://docs.microsoft.com/en-us/dotnet/api/system.xml#diff), so it should serve your purposes adequately, either wrapped or exposed directly.

Cheers!

**Comment by AdamSobieski** [comment]
Thanks for the hyperlink.

I should clarify. By "specific W3C XML DOM JavaScript API's", I meant to indicate text capitalization. I intended to indicate providing an API with `createElementNS` instead of the .NET text capitalization of `CreateElement`. As `System.XML` does support the W3C XML DOM, it should be doable to wrap `System.Xml` classes to provide API to the scripting environment with text strings like `createElementNS`.

**Comment by AdamSobieski** [comment]
Interestingly, it could be also possible to fork or to modify the open-source `System.Xml` assembly to add ClearScript annotations such as `[ScriptMember]`.

**Comment by ClearScriptLib** [comment]
That sounds like an interesting project! For best results we'd recommend wrapping or forking over using attributes to rename methods.

If you're incorporating existing JavaScript code that consumes the XML DOM, consider using native JavaScript objects to wrap `System.Xml`. Host objects, even with methods capitalized as required, don't behave like native objects in all respects.

Please reopen this issue if you have further questions on this topic.
