### ISSUE TITLE
JavaScript Iteration Protocols

### ISSUE THREAD

**Issue by AdamSobieski** [Microsoft/ClearScript#108]
I wonder about how to best implement the JavaScript iteration protocols in a .NET interface or class which is to be passed to the scripting environment such that script objects support the iteration protocols (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols)? Is there a best practice to achieve this?

**Comment by ClearScriptLib** [comment]
Hi @AdamSobieski,

Any .NET object that implements [`IEnumerable`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable) or [`IEnumerable<T>`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1) supports the JavaScript iteration protocol when exposed to script code. An example:

``` C#
engine.Script.days = new[] { DayOfWeek.Monday, DayOfWeek.Wednesday, DayOfWeek.Friday };
engine.Script.odds = Enumerable.Range(1, 10).Where(num => (num & 1) == 1);
engine.AddHostType(typeof(Console));
engine.Execute(@"
    for (var day of days) {
        Console.WriteLine(day);
    }
    for (var odd of odds) {
        Console.WriteLine(odd);
    }
");
```

Cheers!

**Comment by AdamSobieski** [comment]
That is convenient. Thank you.
