### ISSUE TITLE
Make ClearScript NuGet Package compatible with ASP.Net

### ISSUE THREAD

**Issue by JacobcarrellWork** [Microsoft/ClearScript#109]
The documentation is very confusing as to how to get ClearScript working with ASP.Net MVC. You need to add: 
```XML
<compilation>
      <assemblies>
        <remove assembly="ClearScriptV8-64" />
        <remove assembly="ClearScriptV8-32" />
      </assemblies>
    </compilation>
```
To Both the main application web.config and the views' web.config. This is unclear in the instructions. And frankly, Should be included in the readme some NuGet Packages provide when  they first get installed.

**Comment by upsilondynamics** [comment]
I am experiencing this issue, after deployment to Azure via Continuous deployment, works fine with local IIS express, but only after I run a post build script to move the DLLS into a folder called ClearScript.V8.  IF anyone has more insight into this let me know, 

Exception message: Could not load file or assembly 'ClearScriptV8-32.DLL' or one of its dependencies. The specified module could not be found.

**Comment by ClearScriptLib** [comment]
Hi @upsilondynamics,

Our understanding is that this has to do with the [Assembly Shadow Copy](https://docs.microsoft.com/en-us/dotnet/framework/app-domains/shadow-copy-assemblies) feature. For reasons possibly related to code verifiability, mixed-mode assemblies such as ClearScriptV8 cause ASP.NET applications to fail at startup.

These assemblies must therefore be excluded explicitly from startup processing. Have you tried modifying your web.config files as described above and in [Building, integrating, and deploying ClearScript](https://microsoft.github.io/ClearScript/Details/Build.html)?

Good luck!

**Comment by upsilondynamics** [comment]
Nice thanks for the reply (you guys really do reply quick on here, which is great!)

What I did is setup a post build script that moves the DLL's:

ClearScriptV8-32.dll
v8-ia32.dll
v8-x64.dll
ClearScriptV8-64.dll

Into bin\ClearScript.V8 and this seems to work locally, I haven't tried using the <remove assembly> tag in the web.config.  I am trying to setup a "post deployment" script right now in my Azure Devops to do the same with my Azure Webjob to see i it works, moving these files manually worked so I imagine I can accomplish the same in this script.

**Comment by ClearScriptLib** [comment]
Interesting. Does ClearScript still work when you move its V8 assemblies to that folder? If so, are you putting that folder on the executable path?

**Comment by upsilondynamics** [comment]
When the solution is built, those DLL's are being placed in the bin directory (being built from the Nuget package) which causes the issue. I also have copies of the 4 DLL's in the webroot of my website which I placed there and being set to always Copy on Build.

I think the presence of those files in the bin directory is what's causing the issue.  It does appear to work this way, do you know if IIS would use the DLL's in the ClearScript.V8 directory I create - or the webroot.

(Current state and it does work - I feel there is obvious redundancy)
-- wwwroot
      ClearScriptV8-32.dll
      v8-ia32.dll
      v8-x64.dll
      ClearScriptV8-64.dll

      --bin
         --ClearScript.V8
               ClearScriptV8-32.dll
               v8-ia32.dll
               v8-x64.dll
               ClearScriptV8-64.dll

Thanks

**Comment by ClearScriptLib** [comment]
Hi @upsilondynamics,

With this setup, ClearScript almost certainly loads those assemblies from the application root folder, especially if you aren't adding `ClearScript.V8` to the executable path.

By the way, with the `web.config` change, ClearScript should work with all those assemblies in `bin`.

Cheers!

**Comment by ClearScriptLib** [comment]
[Version 5.5.6](https://github.com/Microsoft/ClearScript/releases/tag/5.5.6) includes a NuGet [`readme.txt`](https://github.com/Microsoft/ClearScript/blob/master/NuGet/readme.txt) file that provides the required information.

Thanks for your suggestion!
