### ISSUE TITLE
Using DynamicObjects in script

### ISSUE THREAD

**Issue by vskh** [Microsoft/ClearScript#11]
I am using V8 script engine and trying to use System.Dynamic.DynamicObject with overridden TryGetMember and TryGetIndex in the script. I am adding it via engine.AddHostObject(). Although I see that GetMetaObject() is called twice - when object is added to engine and when it is accessed from script - this does not seem to work. The overridden methods of DynamicObject get never called when access is attempted from within script yielding [undefined] results. If I use created object from host code in C#, it works as expected.

At the same time, ExpandoObject does work. E.g. if I create object in the host, add some dynamic field to it and then pass it to engine, script can access dynamic field I've created. I guess, there is something about implementation that causes this discrepancy but I could not find what.

Maybe, you could advise?

Thanks!

**Comment by ClearScriptLib** [comment]
For its dynamic properties to be accessible from script code, your object must implement [`GetDynamicMemberNames`](https://msdn.microsoft.com/en-us/library/system.dynamic.dynamicobject.getdynamicmembernames(v=vs.110).aspx) in addition to `TryGetMember`.

**Comment by vskh** [comment]
Ok, thanks! Tried that and it actually started working for "dot" access (obj.field). How would I make it to recognize indexing? Is it translated into member access or do I have to implement some interface (e.g. IDictionary)?

**Comment by ClearScriptLib** [comment]
For your dynamic object to support indexing directly, it must expose its valid indexes as property names. That is, `GetDynamicMemberNames` would have to return a list of string-formatted indexes, and `TryGetMember` would then have to work with those strings.

A simpler solution might be for your object to have a named property that returns an array, list, or other object that implements [`IList`](https://msdn.microsoft.com/en-us/library/system.collections.ilist(v=vs.110).aspx) or [`IList<T>`](https://msdn.microsoft.com/en-us/library/5y536ey6(v=vs.110).aspx), which would then automatically support indexing.

**Comment by vskh** [comment]
Thank you for prompt and quick answers, it works just like you explained!

I guess, it would be useful to add this somehow into the list of examples, just like with ExpandoObject.
