### ISSUE TITLE
ClearScript, V8 and WebAssembly

### ISSUE THREAD

**Issue by AdamSobieski** [Microsoft/ClearScript#110]
I would like to ask about ClearScript and [WebAssembly](https://developer.mozilla.org/en-US/docs/WebAssembly) for the [V8 JavaScript engine](https://v8.dev).

**Comment by ClearScriptLib** [comment]
Hi @AdamSobieski,

ClearScript neither supports nor disables V8's intrinsic WebAssembly capabilities.

All built-in WebAssembly-related JavaScript APIs should be available in `V8ScriptEngine`, and ClearScript supports fast data transfer to array buffers and typed arrays.

That said, we haven't done any WebAssembly testing with ClearScript.

Good luck!

**Comment by AdamSobieski** [comment]
That is excellent that `WebAssembly` and related APIs are available in `V8ScriptEngine` JavaScript environments. I hope that the feature can be supported in future versions of ClearScript. Thanks again.

**Comment by ClearScriptLib** [comment]
Hi @AdamSobieski,

We've now done a basic test with a "Hello, World!" C++ program compiled with [Emscripten](https://emscripten.org/) for the "shell" execution environment. It worked!

The only infrastructure we needed to provide was a `read` function for loading the compiled binary (`hello-world.wasm`), and a skeletal [`console`](https://nodejs.org/api/console.html) object to make [`printf`](https://en.cppreference.com/w/cpp/io/c/fprintf) work. With those things in place we able to execute the generated JavaScript code (`hello-world.js`) without any problems.

The exercise exposed a couple of ClearScript issues related to JavaScript [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), so thank you!

Good luck!

**Comment by cyraid** [comment]
> Hi @AdamSobieski,
> 
> We've now done a basic test with a "Hello, World!" C++ program compiled with [Emscripten](https://emscripten.org/) for the "shell" execution environment. It worked!
> 
> The only infrastructure we needed to provide was a `read` function for loading the compiled binary (`hello-world.wasm`), and a skeletal [`console`](https://nodejs.org/api/console.html) object to make [`printf`](https://en.cppreference.com/w/cpp/io/c/fprintf) work. With those things in place we able to execute the generated JavaScript code (`hello-world.js`) without any problems.
> 
> The exercise exposed a couple of ClearScript issues related to JavaScript [promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise), so thank you!
> 
> Good luck!

I know this may be years later, but is that read function exposed so we can provide WASM?

**Comment by ClearScriptLib** [comment]
Hi @cyraid,

ClearScript's source code includes a [WebAssembly test](https://github.com/microsoft/ClearScript/blob/6106c3043f05d51955a579fff6cfb1bccd0f3cfc/ClearScriptTest/V8ScriptEngineTest.cs#L4353) – a simple `printf("Hello, world!")` application.

Note that the [`HelloWorld.js`](https://github.com/microsoft/ClearScript/blob/master/ClearScriptTest/JavaScript/WebAssembly/HelloWorld.js) and [`HelloWorld.wasm`](https://github.com/microsoft/ClearScript/blob/master/ClearScriptTest/JavaScript/WebAssembly/HelloWorld.wasm) files were generated a while back, so the test code may not work with files generated by newer versions of [Emscripten](https://emscripten.org/).

Good luck!

**Comment by cyraid** [comment]
> Hi @cyraid,
> 
> ClearScript's source code includes a [WebAssembly test](https://github.com/microsoft/ClearScript/blob/6106c3043f05d51955a579fff6cfb1bccd0f3cfc/ClearScriptTest/V8ScriptEngineTest.cs#L4353) – a simple `printf("Hello, world!")` application.
> 
> Note that the [`HelloWorld.js`](https://github.com/microsoft/ClearScript/blob/master/ClearScriptTest/JavaScript/WebAssembly/HelloWorld.js) and [`HelloWorld.wasm`](https://github.com/microsoft/ClearScript/blob/master/ClearScriptTest/JavaScript/WebAssembly/HelloWorld.wasm) files were generated a while back, so the test code may not work with files generated by newer versions of [Emscripten](https://emscripten.org/).
> 
> Good luck!

You guys are quick to reply, and provide friendly great responses. Nice team you got there!
