### ISSUE TITLE
Public method overriden in internal class: call from JS error

### ISSUE THREAD

**Issue by ezolotko** [microsoft/ClearScript#112]
The code below produces Microsoft.ClearScript.ScriptEngineException: 'TypeError: myobj.MyMethod() is not a function', while the MyMethod method is public and is defined in a public class.

```
    public abstract class MyBase
    {
        public abstract void MyMethod();
    }
    internal class MyDerived : MyBase
    {
        public override void MyMethod()
        {
            Console.WriteLine("MyMethod");
        }
    }

    var engine = new V8ScriptEngine();
    var myobj = new MyDerived();

    myobj.MyMethod();

    engine.AddHostObject("myobj", myobj);

    // Microsoft.ClearScript.ScriptEngineException: 'TypeError: myobj.MyMethod() is not a function'
    engine.Execute("myobj.MyMethod();");
```
If I change `internal class MyDerived` to `public`, the method is called as expected. Here is a project that reproduces the problem:
[ClearScriptTypeError.zip](https://github.com/microsoft/ClearScript/files/3162831/ClearScriptTypeError.zip)
It also includes the WpfTest() method, which reproduces what seems to be the same problem, but with a real-world class from WPF (System.Windows.Media.VisualDrawingContext). This is how we encountered this issue in the first place.

**Comment by ClearScriptLib** [comment]
Hi @ezolotko,

This looks like a bug. Here's a workaround. Instead of this:

``` C#
engine.AddHostObject("myobj", myobj);
```

do this:

``` C#
engine.AddRestrictedHostObject<MyBase>("myobj", myobj);
```

Thank you!

**Comment by ezolotko** [comment]
@ClearScriptLib Thank you for your reply.

We are experiencing this issue in a scenario like this:
```
            var engine = new V8ScriptEngine();
            engine.Execute("function f(o) { o.MyMethod(); }");
            engine.Invoke("f", new MyDerived());
```
As I understand, the workaround with `AddRestrictedHostObject` is not applicable here. Do you have any advice on this scenario?
Thank you.

**Comment by ClearScriptLib** [comment]
Hi @ezolotko,

You can do this:

``` C#
var host = engine.Script.host = new HostFunctions();
engine.Invoke("f", host.cast<MyBase>(new MyDerived()));
```

Cheers!

**Comment by ezolotko** [comment]
@ClearScriptLib the workaround works, thank you very much!

**Comment by ClearScriptLib** [comment]
@ezolotko Thanks for reporting this issue. The next release will include a fix as well as an easier way to pass a type-bound ("restricted") object to script code.

**Comment by ClearScriptLib** [comment]
[ClearScript 5.6](https://github.com/microsoft/ClearScript/releases/tag/5.6.0) includes a fix for this issue.
