### ISSUE TITLE
V8 enable modules

### ISSUE THREAD

**Issue by fasihrana** [microsoft/ClearScript#114]
Is there a way to enable "import &lt;module&gt;.js;" statements in a V8 Runtime?

I couldn't find any examples and makes me think I'd have to parse the script file myself first to enable this.

As on [StackOverflow](https://stackoverflow.com/questions/56150187/c-net-clearsscript-v8-enable-modules).

**Comment by ClearScriptLib** [comment]
Hi @fasihrana,

ClearScript currently doesn't support ES6 modules. We're evaluating adding support for both ES6 and Node.js-style modules in an upcoming release.

Thanks!

**Comment by ClearScriptLib** [comment]
[ClearScript 5.6](https://github.com/microsoft/ClearScript/releases/tag/5.6.0) includes basic support for modules.

**Comment by Ariohor** [comment]
> [ClearScript 5.6](https://github.com/microsoft/ClearScript/releases/tag/5.6.0) includes basic support for modules.

Can you please show an example how to enable import/export in ClearScript? We try to use modules but allways return one error "Unexpected identifier" in code

`import ScriptClass1 from "ScriptClass1.js";`

**Comment by ClearScriptLib** [comment]
Hi @Ariohor,

Take a look at the test method [here](https://github.com/microsoft/ClearScript/blob/3f4e25e75c8d0564bea1484d0eb18134763aba09/ClearScriptTest/V8ModuleTest.cs#L50).

Good luck!

**Comment by Ariohor** [comment]
> Привет @Ariohor ,
> 
> Посмотрите на метод испытаний [здесь](https://github.com/microsoft/ClearScript/blob/3f4e25e75c8d0564bea1484d0eb18134763aba09/ClearScriptTest/V8ModuleTest.cs#L50) .
> 
> Удачи!

Thank you very much!

**Comment by karimi** [comment]
I have a follow up question on this,
What's the best way to import modules installed using NPM in visual studio? I have a package.json file that installs the dependencies in a node_modules folder.

**Comment by ClearScriptLib** [comment]
Hi @karimi,

You can use [`DocumentSettings.SearchPath`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_DocumentSettings_SearchPath.htm) to specify your module locations.

Please let us know if you need additional information.

Good luck!

**Comment by karimi** [comment]
Thanks, that's what I was looking for. I also had to have a build event that copies the node_modules to my build folder.

**Comment by pp2110** [comment]
I have a question, 
I have this C# code 
public JsonResult CreatePPT(string JSONToPass, string VisualInfo) {

    var jsonObject = JsonConvert.DeserializeObject<JSONModel>(JSONToPass);
    using (var engine = new V8ScriptEngine())
    {
        // Load the JavaScript script from a file
        var script = System.IO.File.ReadAllText("C:\\Users\\PrathmeshHanamantPaw\\Downloads\\GlobalReportFramework\\GlobalReportFramework - Copy\\GlobalReportFramework\\createPPT.js");

        // Set the values of connectionString, containerName, and outputPath in the JavaScript context
        var connectionString = Common.Constants.blobConnectionString;
        var containerName = jsonObject.Guid;
        var outputPath = Common.Constants.sessionFolder + Common.Constants.updatedPPTFileNamePath + jsonObject.Guid;

        engine.Script.connectionString = connectionString;
        engine.Script.containerName = containerName;
        engine.Script.outputPath = outputPath;
        // Execute the JavaScript code
        engine.Execute(script);

        engine.Script.createPresentation();
    }
    return null;
}

the JS script doesn't run returns an Error : "require is not defined"

NOTE: I have used require to use installed npm packages

**Comment by ClearScriptLib** [comment]
Hi @pp2110,

The `require` function is available only within [CommonJS](https://wiki.commonjs.org/wiki/CommonJS) modules. You can use ClearScript to execute a CommonJS module as follows:

``` C#
var info = new DocumentInfo { Category = ModuleCategory.CommonJS };
engine.Execute(info, script);
```

Note however that ClearScript provides a bare JavaScript environment containing only the JavaScript [built-ins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects) It does not implement the Web or Node.js APIs.
