### ISSUE TITLE
How to invoke a method that implicit cast string, such as XElment.Elements(XName name)

### ISSUE THREAD

**Issue by dwanboweb** [microsoft/ClearScript#115]
Firstly,I try to use Linq xml in my Script,such as:
`var XDocument=clr.System.Xml.Linq.XDocument
var doc = XDocument.Load(xmlPath);
var root = doc.Root;
var patients = root.Elements('patient');`
And it makes error.It seems that 'string' cannot be implicit  to the 'XName'.
So I have to write as
`var patients = root.Elements(Lib.GetXName('patient'));`
`public XName GetXName(string name)
        {
            return (XName)name;
        }`
Is there any more elegant way?As 'XName' is used frequently.
Thank you very much

**Comment by ClearScriptLib** [comment]
Hi @dwanboweb,

Currently ClearScript doesn't support implicit conversion operators for method arguments. Specifically, the call binds to the correct method, but ClearScript's invocation code can't perform the required conversion. We'll add that capability in the next release.

What you're doing is exactly the workaround we'd recommend. You could make the conversion syntax slightly simpler by providing a wrapper function or extending the String prototype, but that's really a matter of preference.

Thanks for reporting this!

**Comment by ClearScriptLib** [comment]
[ClearScript 5.6](https://github.com/microsoft/ClearScript/releases/tag/5.6.0) adds support for implicit conversion operators for host method arguments.

**Comment by dwanboweb** [comment]
wow ,I just need this!
