### ISSUE TITLE
Changing the default script name

### ISSUE THREAD

**Issue by alimtolman** [microsoft/ClearScript#116]
Not possible to change the script name "Script Document".
I've used constructor ```V8ScriptEngine(string name)``` but name isn't changed.

**Comment by ClearScriptLib** [comment]
Hi @alimtolman,

See the [`Execute`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ScriptEngine_Execute.htm) and [`Evaluate`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ScriptEngine_Evaluate.htm) method documentation. There are overloads that allow you to specify the script's name or URI. We recommend the newer ones that use the [`DocumentInfo`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_DocumentInfo.htm) structure.

Good luck!

**Comment by alimtolman** [comment]
Ok. Thank you! I’ll check it.

**Comment by alimtolman** [comment]
@ClearScriptLib I've looked at ```Execute``` method and tried to use ```DocumentInfo``` and pass ```string documentName``` but I'm not able to set the ```<anonymous>``` as default script document name cuz of error that name contains invalid characters. Is there any other way to do it?

**Comment by ClearScriptLib** [comment]
@alimtolman For historical reasons you can't use angle brackets or other non-path characters, but you can use braces or angle brackets.
