### ISSUE TITLE
How do I deploy a 64-bit ClearScriptV8 assemblies globally (at the machine level)?

### ISSUE THREAD

**Issue by Taritsyn** [microsoft/ClearScript#117]
Hello!

Is it possible to globally deploy the following assemblies: `ClearScript.dll`, `ClearScriptV8-64.dll`, `v8-base-x64.dll` and `v8-x64.dll`? I.e. I need to understand what assemblies should be registered in the GAC, and which copied to to the `C:\Windows\System32` directory.

**Comment by ClearScriptLib** [comment]
Hi Andrey,

Unfortunately ClearScript doesn't currently support global deployment.

In theory the official ClearScript* assemblies are GAC-able, but the v8* assemblies are native and loaded manually via an algorithm that assumes app-level deployment.

We'll look into adding support for machine-level deployment in the future.

Thanks!

**Comment by Taritsyn** [comment]
Thanks for information! As I understand it, we cannot deploy native assemblies globally due to [this logic](https://github.com/microsoft/ClearScript/blob/66e0ed19239825cdee08f5bf37702e96d7bee2a1/ClearScript/V8/V8Proxy.cs#L60-L152).

**Comment by ClearScriptLib** [comment]
[ClearScript 5.6](https://github.com/microsoft/ClearScript/releases/tag/5.6.0) supports machine-level deployment. It doesn't provide an installer, so you'll have to use `gacutil` and `copy` at the command line. Section VI of [this document](https://microsoft.github.io/ClearScript/Details/Build.html) contains more information.

**Comment by Taritsyn** [comment]
Thank you!
