### ISSUE TITLE
Included scripts

### ISSUE THREAD

**Issue by tu-lehong** [microsoft/ClearScript#122]
How do I add included scripts? I would like to have some common scripts that are referenced by the main script.

**Comment by ClearScriptLib** [comment]
Hi @tu-lehong,

Please clarify. How do you envision referencing one script from another? What kind of syntax would you like to use for including a script?

If you're talking about using a module system such as [CommonJS](http://www.commonjs.org/specs/modules/1.0/), you'll have to implement that yourself, although eventually we'd like to support both CommonJS and standard [JavaScript modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules).

Thanks!

**Comment by tu-lehong** [comment]
Hi @Clear
