### ISSUE TITLE
Script cannot call public method of a host object whose type is not public.

### ISSUE THREAD

**Issue by tu-lehong** [microsoft/ClearScript#124]
If the type of a host object is not public, an exception is thrown when script calls a public method of that host object. The object is exposed, so script should be able to access its public members. Below is the code.

```
using Microsoft.ClearScript.V8;
using System;

namespace ClearScriptDemo
{
    class Person
    {
        public string GetName()
        {
            return "John Doe";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var engine = new V8ScriptEngine())
            {
                // expose a host type
                engine.AddHostType("Console", typeof(Console));
                engine.Execute("Console.WriteLine('{0} is an interesting number.', Math.PI)");

                // expose a host object
                engine.AddHostObject("person", new Person());
                engine.Execute("Console.WriteLine(person.GetName())");

                Console.ReadKey();
            }
        }
    }
}
```

Exception:
An unhandled exception of type 'Microsoft.ClearScript.ScriptEngineException' occurred in ClearScriptV8-32.dll

Additional information: TypeError: person.GetName is not a function

**Comment by ClearScriptLib** [comment]
Hi @tu-lehong,

>The object is exposed, so script should be able to access its public members.

A script can access members that are _visible_ to it. In this case, the object's type is _not_ visible, so the script can only access visible members of any visible base types, which in this case includes only the public members of `System.Object`.

To grant your script the ability to access everything visible to `Program`, you can use ClearScript's [`AccessContext`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_AccessContext.htm) property:

``` C#
// expose a host object
engine.AccessContext = typeof(Program);
engine.AddHostObject("person", new Person());
engine.Execute("Console.WriteLine(person.GetName())");
```

Cheers!

**Comment by tu-lehong** [comment]
Thank you!

**Comment by karimi** [comment]
Does this work with Interfaces? I have an object `ctx` that implements `IGraphicContext` interface, inside my script I would like to invoke a method of this object.

```namespace Draft
{
    public class Engine
    {
        private V8ScriptEngine engine;

        public Engine()
        {
            engine = new V8ScriptEngine();
            engine.AccessContext = typeof(IGraphicContext);
        }

        public void plot(IGraphicContext ctx, string definition)
        {
            engine.Execute(Properties.Resources.draftjs);
            engine.AddHostType(typeof(Console));
            engine.AddHostObject("ctx", ctx);
            engine.Execute(@"
                Object.getOwnPropertyNames(ctx).map( x => Console.WriteLine(x));
                ctx.LineTo(100,200)
                ");
        }

    }

    public interface IGraphicContext
    {
        void MoveTo(float x, float y);
        void LineTo(float x, float y);
    }
}```

But I get an error: 
Microsoft.ClearScript.ScriptEngineException: 'TypeError: ctx.LineTo is not a function'

**Comment by ClearScriptLib** [comment]
Hi @karimi,

Does `ctx` implement `IGraphicContext` [explicitly](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)?

Thanks!

**Comment by karimi** [comment]
Yes @ClearScriptLib 
Here's the implementation of that interface:
```c#
    class formGraphicContext : IGraphicContext
    {
        private Graphics ctx;
        private Pen pen;
        private Tuple<float, float> currentPos;

        public formGraphicContext(PaintEventArgs e, Pen p)
        {
            ctx = e.Graphics;
            pen = p;
            currentPos = new Tuple<float, float>(0, 0);
    }
        public void LineTo(float x, float y)
        {
            ctx.DrawLine(pen, currentPos.Item1, currentPos.Item2, x, y);
            MoveTo(x, y);
        }

        public void MoveTo(float x, float y)
        {
            currentPos = new Tuple<float, float>(x, y);
        }
    }
```

**Comment by ClearScriptLib** [comment]
Hi @karimi,

The `formGraphicContext` class isn't public, so its non-inherited members are invisible to script code by default. You can use [`AccessContext`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_AccessContext.htm) as shown above to expand the script engine's access.

Good luck!
