### ISSUE TITLE
Is there any way to add a script function to a host type?

### ISSUE THREAD

**Issue by tu-lehong** [microsoft/ClearScript#125]
Is it possible to add a script function to a host type? The below code throws an exception when I try to add function _greet_ to type _Person_. A host type apparently has no prototype?

```
using Microsoft.ClearScript.V8;
using System;

namespace ClearScriptDemo
{
    class Person
    {
        public string GetName()
        {
            return "John Doe";
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            using (var engine = new V8ScriptEngine())
            {
                // expose a host type
                engine.AddHostType("Console", typeof(Console));
                engine.Execute("Console.WriteLine('{0} is an interesting number.', Math.PI)");

                // expose a host object
                engine.AccessContext = typeof(Program);
                engine.AddHostObject("person", new Person());
                engine.Execute("Console.WriteLine(person.GetName())");

                // add script function to host type
                engine.Execute("person.prototype.greet = function() { Console.WriteLine(\"Hello, World!\"); }");

                Console.ReadKey();
            }
        }
    }
}
```

Exception:
An unhandled exception of type 'Microsoft.ClearScript.ScriptEngineException' occurred in ClearScriptV8-64.dll

Additional information: TypeError: Cannot set property 'greet' of undefined

**Comment by ClearScriptLib** [comment]
Hi @tu-lehong,

Neither host objects nor host types have a `prototype` property (unless the corresponding .NET object or type exposes such a property). However, there are many ways to extend such objects in JavaScript.

One way is to add a link to the object's prototype chain:

``` JavaScript
function extendHostObject(hostObject) {
    let proto = {};
    proto._proto = proto;
    Object.setPrototypeOf(proto, Object.getPrototypeOf(hostObject));
    Object.setPrototypeOf(hostObject, proto);
}
extendHostObject(person);
person._proto.greet = function() {
    Console.WriteLine('Hello, World!');
}
person.greet();
```

A more flexible solution is to wrap the object in a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy). That way you can add extensions and even override existing host properties.

Good luck!

**Comment by tu-lehong** [comment]
Thank you!

**Comment by simontom** [comment]
Well, it won't work for Host types nowadays, will it?

**Comment by ClearScriptLib** [comment]
Hi @simontom,

>Well, it won't work for Host types nowadays, will it?

The extension technique described above should work for host types as well as objects.

Good luck!

**Comment by simontom** [comment]
Well, code with an  example is for object but types cannot be modified, can they?
I tried this (or maybe just something really similar to this _proto extension) but it threw an Ex saying that it cannot be modified.
I think this one
"Uncaught TypeError: Immutable prototype object '#<Object>' cannot have their prototype set"
Will try again when I have a little time.

Thank you so far

**Comment by ClearScriptLib** [comment]
Hi @simontom,

>"Uncaught TypeError: Immutable prototype object '#' cannot have their prototype set"

Ouch, you're absolutely correct! Some host resources (types, delegates, and possibly others) are realized on the JavaScript side as _immutable prototype exotic objects_ (see [here](https://262.ecma-international.org/7.0/#sec-immutable-prototype-exotic-objects)).

That's a hack. Those objects don't actually require immutable prototypes. It's just a rarely used attribute that ClearScript overloads for a specific unrelated purpose.

We've created Issue #330 to track the fix for this. In the meantime, [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) might provide an alternative.

Sorry about this inconvenience!

**Comment by simontom** [comment]
Thanks a lot

**Comment by AudriusButkevicius** [comment]
Proxy solution, nor does the wrapping solution really work well when roundtripping.

Namely, it's hard (maybe impossible?) for my C# to return something that has picked up the previous `MyType.prototype.__defineGetter_` calls that happened in the script. Even if there is, I'd have to do the wrapping on every return value.

Also, if my C# function exported as a global expects a `MyType` arguments, I don't think I can call it from js with a proxy object and expect it to work?

Are there any solutions to that?

In my specific scenario, js does not instantiate new instances of MyType, just adds extra getters/functions on the ones it receives from functions/globals exported from C#.
