### ISSUE TITLE
NuGet package for ClearScript.NoV8

### ISSUE THREAD

**Issue by skacurt** [microsoft/ClearScript#128]
The only NuGet package currently available includes V8, which is redundant for those who intend to use Windows scripting engines only.

Can you also provide a ClearScript.NoV8 NuGet package?

**Comment by ClearScriptLib** [comment]
[ClearScript 7.0](https://github.com/microsoft/ClearScript/releases/tag/7.0.0) offers separate component packages. [Microsoft.ClearScript.Windows](https://www.nuget.org/packages/Microsoft.ClearScript.Windows/) provides JScript/VBScript support.
