### ISSUE TITLE
Is the project still undergoing active development?

### ISSUE THREAD

**Issue by andrea-s** [Microsoft/ClearScript#13]
Dear ClearScript team,

I hope I don't sound entitled writing this (the library is absolutely excellent and a pleasure to use!), but I'm a bit worried to see that the last commit on this repository happened in May. Are you still planning to actively develop ClearScript in the future?

**Comment by ClearScriptLib** [comment]
Hi @andrea-s,

We apologize for the apparent slowdown in development activity. For a long time now ClearScript has been a side project (and therefore a low priority) for a very small group within the MS Office organization.

Over the last year or so we've seen a decrease in the number of bug reports and feature requests, both internally and externally. That probably has to do with a relatively mature code base, combined with growing developer interest in cross-platform .NET technologies, which ClearScript doesn't support.

Given that trend, we're down to a handful of potential enhancements for ClearScript, all of which are non-trivial. Here's the list we're looking at, in order of decreasing priority:

1. Support for newer V8 versions.
1. Support for Chakra / ChakraCore.
1. Support for .NET Core / .NET Standard.

Please understand that, as ClearScript is a side project, we don't have time estimates for any of these enhancements. To be honest, progress is likely to be slow, and one major work item at a time. We do plan to respond more quickly to any new bug reports and minor feature requests.

Thanks!

**Comment by andrea-s** [comment]
Of course, that's very understandable. Thanks for taking the time to answer!

**Comment by dennisdahlchristensen** [comment]
I am mostly interested in updates to newer versions for V8 more than anything else.
If Clearscript can not keep being updated, then I am fairly sad to say that I will have to use another framework to run my JS code with serverside.

**Comment by ClearScriptLib** [comment]
@dennisdahlchristensen Supporting newer V8 versions is our top priority for ClearScript. Internally we have it working with V8 6.1 (the latest stable release), but its debugging support needs a non-trivial update to support the new [V8 Inspector](https://github.com/v8/v8/wiki/Debugging-over-the-V8-Inspector-API) protocol, as recent V8 releases have dropped support for the original protocol.

**Comment by dennisdahlchristensen** [comment]
@ClearScriptLib Great news!! I very much look forward to being able to upgrade to 6.1. That is a huge jump from 5.5.
Keep up the good work!!

**Comment by ClearScriptLib** [comment]
Issue #9 tracks .NET Standard support, and we've added Issue #15 to track the Chakra enhancement.
