### ISSUE TITLE
Sign an Assembly with a Strong Name

### ISSUE THREAD

**Issue by AtlantisDe** [microsoft/ClearScript#130]
### Sign an Assembly with a Strong Name
- pls..........sign...... thanks very much
```c#
[assembly: InternalsVisibleTo("ClearScriptV8-32")]
[assembly: InternalsVisibleTo("ClearScriptV8-64")]
[assembly: InternalsVisibleTo("ClearScriptTest")]

```

**Comment by ClearScriptLib** [comment]
Hello @AtlantisDe,

The assemblies in the [official NuGet package](https://www.nuget.org/packages/Microsoft.ClearScript) have strong names. If you're building ClearScript yourself, Section IV of [this document](https://microsoft.github.io/ClearScript/Details/Build.html) outlines the procedure for enabling strong-named assemblies.

Good luck!

**Comment by AtlantisDe** [comment]
hello @ClearScriptLib 

i am sure...the official Nuget package ...not have  strong names
