### ISSUE TITLE
Preserve script array when serialized

### ISSUE THREAD

**Issue by MestreKarin** [microsoft/ClearScript#131]
I'm facing two issues with javascript arrays. The first one is the array is being serialized as object (using Newtonsoft.Json).

### JS Code
```
function main() {
    let obj = {
        name: "Hello World"
    }
	
    return [obj]
}
```

### C# Code

```
using (var engine = new V8ScriptEngine()) {
    engine.execute(jsCode);
	
    Newtonsoft.Json.JsonConvert.Serialize(engine.Script.main());
}
```

### Output
```
{
    "0": {
        "name": "Hello World"
    }
}
```

**Expected:**
```
[
   { "name": "Hello World" }
]
```
I need to serialize it correctly, since I'm gonna store the result in mongodb. I don't need to access the data on c# side, my (c#) function just grab the data and save in mongodb.

Array Loop
--
The other issue is, I can't use  `for (let x in y)`. However, a workaround I found is to use `forEach`.

```
let arr = ['hello', 'world'];

for (let s in arr) {
    Console.WriteLine(s);
}

// Output:
// 0
// 1
// 0
// 1
// ... bunch of 0's and 1's

arr.forEach(s => {
    Console.WriteLine(s);
});

// Output:
// hello
// world
```

**Comment by ClearScriptLib** [comment]
Hi @MestreKarin,

ClearScript doesn't convert script arrays to .NET arrays, as it favors providing full access to script objects over automatic conversion.

If you must use Json.NET to serialize the result, you can use a method like this one:

``` C#
private static object ConvertArray(object arg) {
    if (arg is ScriptObject) {
        dynamic scriptObject = arg;
        if (scriptObject.constructor.name == "Array") {
            int length = Convert.ToInt32(scriptObject.length);
            var array = new object[length];
            for (var index = 0; index < length; ++index) {
                array[index] = scriptObject[index];
            }
            return array;
        }
    }
    return arg;
}
```

And then:

``` C#
Console.WriteLine(JsonConvert.SerializeObject(ConvertArray(engine.Script.main())));
```

On the other hand, if the result never includes .NET objects, you'll get better performance from JavaScript's [JSON.stringify](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify), especially for large arrays:

``` C#
Console.WriteLine(engine.Script.JSON.stringify(engine.Script.main()));
```

As for your second question, aside from the call to `Console.WriteLine`, ClearScript is not involved in the processing of your JavaScript samples. The behavior of the [`for...in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in) statement, when applied to a script object, is not under ClearScript's control. Consider using [`for...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of) instead.

Good luck!

**Comment by MestreKarin** [comment]
My bad, I tought that we could use `for...in` with arrays.

For serializing, I will use the `JSON.stringify` and deserialize in c# and then save to database.

Thank you.
