### ISSUE TITLE
WebActivator incompatibility due to native DLLs

### ISSUE THREAD

**Issue by drumboog** [microsoft/ClearScript#133]
This is related to https://github.com/Microsoft/ClearScript/issues/75

I received similar errors and after troubleshooting for several days, I found that it was the result of adding a reference to the WebActivatorEx NuGet package.  WebActivatorEx iterates over all available assemblies, which caused the same issue described in the link above.  I wanted to make you aware in case others have this issue or you feel it should be added to ClearScript's NuGet documentation.

The fix was to add a regular expression to the appSettings section so WebActivator would not scan the ClearScript assemblies.  Something like this:

```
<configuration>
  <appSettings>
    <add key="webactivator:excludedFilesExpression" value="(ClearScriptV8-64.dll)|(ClearScriptV8-32.dll)" />
  </appSettings>
</configuration>
```

**Comment by ClearScriptLib** [comment]
Thanks for reporting this, @drumboog!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if it is still relevant. ClearScript has undergone many changes in packaging on order to support the new .NET runtimes and multiple platforms. Thank you!
