### ISSUE TITLE
VBScriptEngine with message queues and multi threaded environment

### ISSUE THREAD

**Issue by sturdy60** [microsoft/ClearScript#134]
First of all thank you so much for this project. I am trying to use this for a solution in which I am consuming messages from a message queue using masstransit service bus consumers. The number of messages read from the queue can change depending on the number of processors. So for my example, 8 messages are read from the queue at a time on a server spawing 8 threads. 

My VBScriptEngine code is pretty simple. The consumer code basically does this..

               using (var engine = new VBScriptEngine())
                {
                    engine.AddHostObject("a", obj1);
                    engine.AddHostObject("b", obj2);
                    engine.AddHostObject("c", obj3);
                    engine.Execute(scriptText);
                    engine.Invoke("StartProcessing");
                }

This works well and I am able to get my results from the VB script processing. However, in a performance test where I threw a huge bunch of messages into the queue, (around 3000 messages) about 10 of them failed with an exception message "**Not enough storage is available to process this command**"

The event log shows this is happening during a finalize call and I don't understand why. I have the code wrapped in a using statement and I see the ScriptEngine base class implements IDisposable. Here's the event log message

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at Microsoft.ClearScript.Windows.WindowsScriptEngine.Dispose(Boolean)
   at Microsoft.ClearScript.ScriptEngine.Finalize()

Fault bucket , type 0
Event Name: CLR20r3
Response: Not available
Cab Id: 0

Problem signature:
P1: MyTestProj.exe
P2: 8.5.1.0
P3: 5d715d65
P4: ClearScript
P5: 5.6.0.0
P6: 5d41cad2
P7: 4a6
P8: 0
P9: System.NullReferenceException
P10: 

I would appreciate any help in resolving this as I am stumped by it.

**Comment by sturdy60** [comment]
Another comment - I can run my queues up to about 50 minutes to be able to reproduce this error. In my log files where I capture more exception details, I have seen this.

   System.ComponentModel.Win32Exception (0x80004005): Not enough storage is available to process this command
   at MS.Win32.UnsafeNativeMethods.CreateWindowEx(Int32 dwExStyle, String lpszClassName, String lpszWindowName, Int32 style, Int32 x, Int32 y, Int32 width, Int32 height, HandleRef hWndParent, HandleRef hMenu, HandleRef hInst, Object pvParam)
   at MS.Win32.HwndWrapper..ctor(Int32 classStyle, Int32 style, Int32 exStyle, Int32 x, Int32 y, Int32 width, Int32 height, String name, IntPtr parent, HwndWrapperHook[] hooks)
   at System.Windows.Threading.Dispatcher..ctor()
   at System.Windows.Threading.Dispatcher.get_CurrentDispatcher()
   at Microsoft.ClearScript.Windows.WindowsScriptEngine..ctor(String progID, String name, String fileNameExtensions, WindowsScriptEngineFlags flags)
   at Microsoft.ClearScript.Windows.VBScriptEngine..ctor(String progID, String name, String fileNameExtensions, WindowsScriptEngineFlags flags)
   at Microsoft.ClearScript.Windows.VBScriptEngine..ctor(String name)

**Comment by ClearScriptLib** [comment]
Hi @sturdy60,

Unfortunately the 0x80004005 result code is unhelpful, as it's just `E_FAIL`, an unspecified error. Would it be possible to log the exception's [`NativeErrorCode`](https://docs.microsoft.com/en-us/dotnet/api/system.componentmodel.win32exception.nativeerrorcode) property?

Thanks!

**Comment by sturdy60** [comment]
Got that code changed. I will run it again and get it to you in an hour or less

**Comment by sturdy60** [comment]
It's an 8. 

ERROR_NOT_ENOUGH_MEMORY

8 (0x8)

Not enough storage is available to process this command.

**Comment by ClearScriptLib** [comment]
Hi @sturdy60,

To comply with the threading requirements of the underlying Windows Script engine, ClearScript associates each managed instance with a [dispatcher](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher), a thread-level object whose implementation is apparently based on a classic Win32 window.

The stack indicates that you're instantiating `VBScriptEngine` on a thread with no existing dispatcher, so a new one was being set up on the thread when window creation failed. The error code usually means that there were too many windows or other UI resources attached to the current desktop.

Does your application do anything obvious that might lead to this situation? For example, are you using VBScript on a very large number of threads?

Thanks!

**Comment by sturdy60** [comment]
Thank you! That made me look a little harder in the code. Two layers above in the stack, where we pull from the message queue into the consumer using masstransit, we have about 8-12 threads working at a time. Each of those threads was creating a new task for each item in the message and those weren't getting disposed. I was focused on the script engine because the event log was around it. Properly disposing the other objects took care of this issue. You can close this issue and thanks for your time!
