### ISSUE TITLE
stack trace on deployment machine missing

### ISSUE THREAD

**Issue by flat-eric147** [microsoft/ClearScript#137]
Hi,
we use ClearScript in our wpf application (as Javascript and VBScript flavour). 
On instantiation we use the WindowsScriptEngineFlags.EnableDebugging flag and the stack trace is perfectly fine when running on a development machine where VS.NET is installed. So from the 
 ScriptEngineException instance we use ErrorDetails to get the line number and colum of where a problem occured. 
When we install our application on a "naked" win7 or win10 box, we get the exception but no stack trace. We are pretty sure it is because there is no debugger installed on the target machine (?). We tried to install Visual Studio Code but no luck. So the question is, what is the minimal requirement to make the stack trace work on any target machine? 

Any hint appreciated!

**Comment by ClearScriptLib** [comment]
Hi @flat-eric147,

Windows Script debugging features require the Process Debug Manager component (PDM.DLL). Unfortunately the number of products that include this component has been shrinking lately. As far as we know, it's now installed only with [Office](https://products.office.com/en-us/home), [Visual Studio](https://visualstudio.microsoft.com/), and [Remote Tools for Visual Studio](https://visualstudio.microsoft.com/downloads/#remote-tools-for-visual-studio-2019).

Good luck!

**Comment by flat-eric147** [comment]
Hi! 
Your hint was brilliant :) I actually copied the pdm.dll off the internet explorer folder and regsrv32'd it, and there was my stack trace (on a win7 box)! The following page helped me as well (while feeding google), I guess they have similar issues:
https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z000000P8gpSAC

Thank you for your quick reply!
