### ISSUE TITLE
Cannot access Javascript Object from delegated Method

### ISSUE THREAD

**Issue by themightylc** [microsoft/ClearScript#138]
I am not sure if this is an issue with Javascript or ClearScript (or my limited understanding of both of those), but I am sure the ClearScript Wizards can enlighten me once again.

So I have an Interface IDateSelectionHandler to handle Date selections from a calender control.
I have implemented a Stub-Class to instantiate such a handler with delegates like so (pardon my VB affinity):

```
Public Class DateSelectionHandler
    Implements IDateSelectionHandler

    Public Delegate Function SelectDateDelegate(d As Date, token As Object) As Boolean
    Public Delegate Function SelectDateRangeDelegate(r As DateRange, token As Object) As Boolean

    Private _SelectedDate As SelectDateDelegate
    Private _SelectedRange As SelectDateRangeDelegate

    Public Sub New(selectedDate As SelectDateDelegate, selectedRange As SelectDateRangeDelegate)
        _SelectedDate = selectedDate
        _SelectedRange = selectedRange
    End Sub

    Public Function Selected(selectedDate As Date, token As Object) As Boolean Implements IDateSelectionHandler.Selected
        Return _SelectedDate(selectedDate, token)
    End Function

    Public Function Selected(dateRange As DateRange, token As Object) As Boolean Implements IDateSelectionHandler.Selected
        Return _SelectedRange(dateRange, token)
    End Function
End Class

```

In my ClearScript Script I generate such an "instant" handler like so:

```
class MyClass {

	_DateHandler = null;

	constructor() {
		this.Test="FooBar";
	}
	
	OnDateSelected(selectedDate,mouseModifier) {
        return (this.Test=="FooBar");
	}
	
	get DateHandler() {
		if (this._DateHandler==null) {
			var DateHandlerType=clr.imagiro.Common.Utilities.DateSelectionHandler;
			var x = new DateHandlerType.SelectDateDelegate(this.OnDateSelected);
			var y = new DateHandlerType.SelectDateRangeDelegate(function(x,y) {throw "range selection not implemented";});
			this._DateHandler = new DateHandlerType(x,y);
		}
		return this._DateHandler;
    }
    
}
```

The .NET-JavaScript communication works perfectly, **BUT** i cannot access the "MyClass" instance in the OnDateSelected Method.
In this line:

return (**this**.Test=="FooBar");

this is always nothing/undefined.

What am I doing wrong here? Is this even possible without passing the MyClass Object to the delegate? Thank you very much!

**Comment by ClearScriptLib** [comment]
Hi @themightylc,

A simple way to get the desired behavior is to bind `OnDateSelected` to your `MyClass` instance when constructing the delegate:

``` JavaScript
var x = new DateHandlerType.SelectDateDelegate(this.OnDateSelected.bind(this));
```

Good luck!

**Comment by themightylc** [comment]
Clear, concise, perfect. 
Thank you for taking the time to help me get the max out of this awesome, awesome library.
And I actually feel smart now, because even though i know next-to-nothing about javascript on that level, I knew at least that there **must** have been a solution that simple ;)

Sincerely, thank you.
