### ISSUE TITLE
Update documentation for V8 Debugging

### ISSUE THREAD

**Issue by Muchaszewski** [Microsoft/ClearScript#14]
Because Google Chrome Developer Tools for Java in Eclipse is no longer supported. Can you provide new instructions on how to connect to the debugger using a dedicated tool for V8 like Chrome "chrome://inspect" or another such tool that is still supported?

**Comment by ClearScriptLib** [comment]
Documentation updated. Please see Section V [here](https://microsoft.github.io/ClearScript/Details/Build.html).
