### ISSUE TITLE
DateTime parameter

### ISSUE THREAD

**Issue by fvi1234** [microsoft/ClearScript#141]
Hello, thanks for this project, apart from MSScriptControl (where I can't get callbacks to work) it seems to be the only currently maintained way left to run VBScript from C# (correct?). I can't use Core thought because it does not include Microsoft.ClearScript.Windows which has the VBScriptEngine, so I have a Framework based project.

I've tested and everything seems to work execpt an issue passing a DateTime parameter. It does not seem to get converted into a (VBS) Date object, but has the type 'Object' in VBS. I know a workaround would be to convert to string and then back to date again (but would need to change a lot of existing scripts). But this is unexpected and wonder if this is a bug, especially since a conversion from (VBS) Date to (C#) *does* seem to be going on.

Is it a bug in ClearScript? Is it undefined behaviour? Am I doing something wrong? (impossible right?)

This is code from my test case including remarks:

    private static void TestDateTimeParameter(VBScriptEngine engine)
    {
        var scriptText = @"
            Public Sub TestDateTimeParameter(myDateParam)

                Rem outputs 'False'
                StandardOutput.Echo CStr(IsDate(myDateParam))

                Rem outputs 'Object'
                StandardOutput.Echo TypeName(myDateParam)

                Rem outputs 'True' and 'Date'
                myDateLocal = Now()
                StandardOutput.Echo CStr(IsDate(myDateLocal))
                StandardOutput.Echo TypeName(myDateLocal)

                Rem this would give a 'Type mismatch' error
                Rem foobar = CStr(myDateParam)
                Rem this also
                Rem foobar = CDate(myDateParam)

                Rem you can pass the object back to c#
                StandardOutput.EchoDate(myDateParam)
                StandardOutput.EchoDateObject(myDateParam)

                Rem there is conversion from a Date (VBS) -> DateTime (C#)
                StandardOutput.EchoDate(myDateLocal)

                Rem but there seems no conversion going from DateTime (C#) -> Date (VBS)
            End Sub";
        try
        {
            engine.AddHostObject("StandardOutput", new StandardOutput());

            engine.Execute(scriptText);

            engine.Invoke("TestDateTimeParameter", DateTime.Now);
        }
        catch (Exception e)
        {
            Console.WriteLine(e.ToString());
        }
    }

    public class StandardOutput
    {
        public void Echo(string value)
        {
            Console.WriteLine(value);
        }

        public void EchoDate(DateTime date)
        {
            Console.WriteLine(date.ToString("yyyy/MM/dd HH:mm:ss"));
        }

        public void EchoDateObject(object obj)
        {
            if (obj is DateTime)
                EchoDate((DateTime)obj);
        }
    }

edit: completely screwed up the formatting, corrected

**Comment by ClearScriptLib** [comment]
Hi @fvi1234,

ClearScript generally prefers full access over automatic conversion. That is, it aims to expose to script code the full capabilities of .NET data types, and vice versa.

On the other hand, some data types (numbers, strings, etc.) are so fundamental that forcing manual conversion would have made ClearScript difficult to use.

Timestamps are a bit of a gray area. They're quite fundamental, but their representation varies to the extent that automatic conversion can mean data loss. Nevertheless, we've received a number of requests for automatic conversion from V8 users, so we added it as a V8-only option.

For VBScript's `Date`, the automatic conversion to `DateTime` is provided by the .NET runtime and is not under ClearScript's control. There's currently no automatic conversion going the other way, but we'll add it as an option in the next ClearScript release.

In the meantime, you can use .NET's [`ToOADate`](https://docs.microsoft.com/en-us/dotnet/api/system.datetime.tooadate) in conjunction with VBScript's [`CDate`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/2dt118h2(v=vs.84)) to perform the conversion manually.

Good luck!

**Comment by fvi1234** [comment]
Hi,
thanks for the explanation, makes sense. ToOADate would indeed provide a workaround, but I would need to change all the existing VBScripts (which are stored in customer's databases)

> There's currently no automatic conversion going the other way, but we'll add it as an option in the next ClearScript release.
That would be very helpful, thanks very much.

Thanks

**Comment by ClearScriptLib** [comment]
[ClearScript 6.0](https://github.com/microsoft/ClearScript/releases/tag/6.0.0) added [`WindowsScriptEngineFlags.MarshalDateTimeAsDate`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_WindowsScriptEngineFlags.htm) to resolve this issue.
