### ISSUE TITLE
Building V8 version

### ISSUE THREAD

**Issue by ravware** [microsoft/ClearScript#142]
Following the Build Instructions in the word doc file , and running the V8Update.cmd I ran into a few things.

1. I needed to open and save out the V8Update into US-ASCII and Change to Windows CRLF or the script would not find the right section. 

2. Running the Script it dies out with below message.

Build mode: Release
V8 revision: Tested (7.6.303.28)
Creating build directory ...
Downloading Depot Tools ...
Expanding Depot Tools ...
Downloading V8 and dependencies ...
The system cannot find the path specified.
*** THE PREVIOUS STEP FAILED ***

And tracing the code I see it is dying about here:

:SyncClient
echo Downloading V8 and dependencies ...
call gclient config https://chromium.googlesource.com/v8/v8 >config.log
if errorlevel 1 goto Error
call gclient sync -r %v8rev% >sync.log
if errorlevel 1 goto Error
:SyncClientDone

Config Log has
Downloading CIPD client for windows-386 from https://chrome-infra-packages.appspot.com/client?platform=windows-386&version=git_revision:2a121dde003a3079db0fdf58195b52cbf486f6ba...

Could someone tell me if they saw this before

**Comment by ClearScriptLib** [comment]
Hi @ravware,

Unfortunately we can't reproduce your issues. That is, the build instructions and V8Update.cmd work on every machine we've tried.

For the first issue, the instructions do state that Git must be configured for `core.autocrlf` mode, although we're not sure what you mean by "find the right section".

As for the V8Update.cmd issue, could you post your config.log and sync.log files?

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions on this topic.
