### ISSUE TITLE
How to throw exception when get a non-exists property in ExpandoObject

### ISSUE THREAD

**Issue by arthurshayne** [microsoft/ClearScript#144]
See the code below:
```
        public static void Main(string[] args)
        {
            using (V8ScriptEngine engine = new V8ScriptEngine())
            {
                dynamic data = new ExpandoObject();                
                
                engine.AddRestrictedHostObject("doc", data);

                object result = engine.Evaluate("doc.aaa");


                Console.WriteLine(result.GetType());
            }

            Console.ReadLine();
        }
```

Now we can get `Microsoft.ClearScript.Undefined` in output window. Is it possible to throw an exception say "The aaa is not defined in doc." ?

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @arthurshayne 

Returning `undefined` for a nonexistent property is standard JavaScript behavior, and ClearScript can't always override it, particularly with JScript.

However, if you're using V8, one way to override most behaviors is by wrapping a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) around your object:

```C#
dynamic data = new ExpandoObject();
engine.Script.doc = ((dynamic)engine.Evaluate(@"(function (target) {
    return new Proxy(target, {
        get: function (target, prop) {
            if (Reflect.has(target, prop)) {
                return Reflect.get(target, prop);
            }
            throw new Error('Property not found');
        }
    });
})"))(data);
```

Good luck!

**Comment by arthurshayne** [comment]
> Hi @arthurshayne
> 
> Returning `undefined` for a nonexistent property is standard JavaScript behavior, and ClearScript can't always override it, particularly with JScript.
> 
> However, if you're using V8, one way to override most behaviors is by wrapping a [proxy](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) around your object:
> 
> ```cs
> dynamic data = new ExpandoObject();
> engine.Script.doc = ((dynamic)engine.Evaluate(@"(function (target) {
>     return new Proxy(target, {
>         get: function (target, prop) {
>             if (Reflect.has(target, prop)) {
>                 return Reflect.get(target, prop);
>             }
>             throw new Error('Property not found');
>         }
>     });
> })"))(data);
> ```
> 
> Good luck!

That works for me! Great Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions about this topic. Thanks!
