### ISSUE TITLE
Add support for the JavaScript Internationalization API

### ISSUE THREAD

**Issue by balsamiqLuca** [microsoft/ClearScript#150]
Hi,
I see that the JavaScript localeCompare() function gives different results between Chrome browser and the V8 included in ClearScript. 
It also seems to ignore the options in ClearScript.

Example:
JS code executed from ClearScript:

```
var t1 = 'a'.localeCompare('A', 'en', { "caseFirst": "upper"});
var t2 = 'a'.localeCompare('A', 'en', { "caseFirst": "lower"});
```

they both give 32 as result in ClearScript. 
Whilst in Chrome I get 1 and -1.

Is this a know issue?
Thanks
Luca

**Comment by ClearScriptLib** [comment]
Hi @balsamiqLuca,

ClearScript's bundled V8 build has always excluded internationalization support. Originally we felt that most users wouldn't need it, so we chose to avoid a dependency on the hefty [ICU](http://site.icu-project.org/home) library.

That was several years ago, and you're the first to ask about JavaScript internationalization support. While we can't commit to it at this time, we'll keep this issue open as a potential enhancement.

In the meantime, have you considered doing your own ClearScript/V8 build? It should be trivial to modify V8Update.cmd to enable internalization support. Just search for `v8_enable_i18n_support` in that file. We haven't tried it, so no guarantees :)

Good luck!

**Comment by balsamiqLuca** [comment]
Thanks!

**Comment by ArgonAlex** [comment]
Would also like to express our interest in this. We've been using the [intl polyfill](https://www.npmjs.com/package/intl) for the past few years, which is not ideal because it's not maintained any more.

**Comment by magnusottosson** [comment]
It would be nice to have support for Intl since its required when trying to server side render scripts that dependens on Intl. The workaround by using the no longer maintained intl.js package as @ArgonAlex suggests works but is not ideal...

**Comment by ClearScriptLib** [comment]
Thanks @magnusottosson.

We'll enable the internationalization API in the next release. Unfortunately the API becomes fully functional only when a relatively large data file ([ICU Data](https://unicode-org.github.io/icu/userguide/icudata.html)) is deployed along with the application; we'll try to streamline that as much as possible.

Good luck!

**Comment by ClearScriptLib** [comment]
We've posted [ClearScript 7.1](https://github.com/microsoft/ClearScript/releases/tag/7.1.0).

**Comment by thurfir** [comment]
Hi, would it be possible to get some documentation about how to enable the Internationalization API for the V8 engine? The "ICU Data" link is dead.

**Comment by ClearScriptLib** [comment]
Hi @thurfir,

Thanks; we've fixed the link.

The JavaScript Internationalization API is enabled in the last few ClearScript releases. Full support requires the ICU Data file, which is provided in [this NuGet package](https://www.nuget.org/packages/Microsoft.ClearScript.V8.ICUData/). Use one of ClearScript's [composite packages](https://github.com/microsoft/ClearScript#composite-packages) to deploy everything you need for your platform, including the ICU data file.

Please let us know if you encounter any problems.

Thanks!
