### ISSUE TITLE
Add an option to expose static members on class instances

### ISSUE THREAD

**Issue by stefano77it** [microsoft/ClearScript#152]
Trying to read from JavaScript a const exposed from an host object returns `undefined` and the variable used to read the const is of type `Microsoft.ClearScript.Undefined`

Is this the expected behavior?

Sample code follows

    using System;
    using Microsoft.ClearScript.V8;

    public class Program
    {
        public static void Main()
        {
            var engine = new V8ScriptEngine();
            engine.AddHostObject("hostobj", new ClassWithConst());
            engine.Execute("value = hostobj.ConstValue;");
            Console.WriteLine(engine.Script.value);
            Console.WriteLine(engine.Script.value.GetType());

            // output:
            // undefined
            // Microsoft.ClearScript.Undefined
        }
    }

    public class ClassWithConst
    {
        public const string ConstValue = "value";
    }

**Comment by ClearScriptLib** [comment]
Hi @stefano77it,

Constant fields are implicitly [`static`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/static), so you must access them through the type rather than an instance:

``` C#
engine.AddHostType(typeof(ClassWithConst));
engine.Execute("value = ClassWithConst.ConstValue;");
```

Good luck!

**Comment by stefano77it** [comment]
With Jint constant fields are accessible from the instance (as is with C#). For ClearScript I resolved wrapping them in properties.
Thanks for the prompt reply and for your excellent library!

**Comment by ClearScriptLib** [comment]
Hi @stefano77it,

>With Jint constant fields are accessible from the instance (as is with C#).

ClearScript aims to give script code C#-like access to .NET objects, so we had to double-check this. The C# compiler does **not** make constant fields accessible through instances. For example:

``` C#
// C#
var obj = new ClassWithConst();
var value = obj.ConstValue;
```

Compiling this code produces "error [CS0176](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0176): Member 'ClassWithConst.ConstValue' cannot be accessed with an instance reference; qualify it with a type name instead".

We could probably add an option to expose static members on instances; do you think that would be generally useful?

Thanks!

**Comment by stefano77it** [comment]
> Compiling this code produces "error CS0176:

You are right, obviously.

> We could probably add an option to expose static members on instances; do you think that would be generally useful?

for my experience it's useful. I'm developing an application with scriptable logic and I've tried other languages before choosing JavaScript.

the second best was Lua (via NLua) and also with this library const are accessible via instances.

I'll post below a sample code to show how Lua works and the logic of my context object (the same I use with JavaScript): a master object, with all methods, const, properties exposed from the host for the scripts.

hope this clear my point of view and will incentive you to expose static members on instances (scripting languages should be more easy to use than C#, not having an IDE that alerts you when to use the type name or the instance)

[dotnetfiddle](https://dotnetfiddle.net/QPN6y2)

    using System;
    using NLua;
                        
    public class Program
    {
        public static void Main()
        {
            Console.WriteLine("Hello World");
            var State = new Lua();
            var context = new ScriptingContext();
            State["context"] = context;
            State.DoString(@"
    context.Utils:Log(context.Const.ConstA)  -- print 'ciao'
    ");
        }
    }

    public class ScriptingContext
    {
        public Utils Utils {get; private set;}
        public ConstClass Const {get;private set;}
        
        public ScriptingContext()
        {
            Utils = new Utils();
            Const = new ConstClass();
        }
    }

    public class Utils
    {
        public void Log(string msg)
        {
            Console.WriteLine(msg);
        }
    }

    public class ConstClass
    {
        public const string ConstA = "ciao";
        public const string ConstB = "hi";
    }

**Comment by ClearScriptLib** [comment]
Hi @stefano77it,

Thanks for posting the sample. We'll evaluate this feature for a future release.

In the meantime, would it not be possible to use `readonly` fields instead of `const`? Such fields are instance members and behave as you expect in both C# and ClearScript.

Cheers!

**Comment by stefano77it** [comment]
Hi, I used in fact `readonly` fields instead of `const` , duplicating the `const` definition that I need to have to use them inside a switch.

Hope to see this feature implemented in future release! 

And thanks again!

**Comment by ClearScriptLib** [comment]
[`Version 6.0.1`](https://github.com/microsoft/ClearScript/releases/tag/6.0.1) adds [`ScriptEngine.ExposeHostObjectStaticMembers`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_ExposeHostObjectStaticMembers.htm).
