### ISSUE TITLE
Support for MacOS and Linux

### ISSUE THREAD

**Issue by woigl** [microsoft/ClearScript#153]
I've just tried the ClearScipt on my MacOS with .NET Core 3.1 and found out after receiving the following exception, that only Windows OS is currently supported.

Exception:
`Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libkernel32, 1): image not found`

Are there any plans to add support for MacOS and/or Linux in the near future?

**Comment by ClearScriptLib** [comment]
Hi @woigl,

ClearScript uses [mixed assemblies](https://docs.microsoft.com/en-us/cpp/dotnet/mixed-native-and-managed-assemblies) to bridge .NET with V8. Unfortunately such assemblies are supported only on Windows.

It would be possible to reimplement ClearScript's V8 interface without mixed assemblies, but that would be a large project.

Of course, if support for mixed assemblies ever came to non-Windows platforms, or if relevant code conversion tools became available, then we'd definitely look into it. To that end we're monitoring [this .NET Core issue](https://github.com/dotnet/coreclr/issues/659).

Cheers!

**Comment by woigl** [comment]
Hi @ClearScriptLib,

thanks for the clarification.
