### ISSUE TITLE
Add an option to pass undefined as null instead of ClearScript.Undefined

### ISSUE THREAD

**Issue by stefano77it** [microsoft/ClearScript#154]
I'm writing a project that uses JavaScript to personalize the business logic.

As a fallback to ClearScript for non-windows platforms I support also Jint (until ClearScript will support other platforms, then I won't have to work with 2 engines anymore).

Doing some tests on null I stumbled upon the conversion of undefined parameters in `ClearScript.Undefined`.

I understand that there are valid reasons to convert undefined to an object `ClearScript.Undefined` but I like much more the Jint approach to convert all to null, that is also more compatible between engines.

Then I propose a new switch to be able to convert all to null instead of `ClearScript.Undefined`.

I've prepared a [fiddle](https://dotnetfiddle.net/O3YMvz) to show a working test case (with the other engine).

Thanks for what you could do about my proposal.

**Comment by ClearScriptLib** [comment]
[`Version 6.0.1`](https://github.com/microsoft/ClearScript/releases/tag/6.0.1) adds [`ScriptEngine.UndefinedImportValue`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_UndefinedImportValue.htm) and makes [`Undefined.Value`](https://microsoft.github.io/ClearScript/Reference/html/F_Microsoft_ClearScript_Undefined_Value.htm) public.
