### ISSUE TITLE
Script object: documentation improvement and request

### ISSUE THREAD

**Issue by stefano77it** [microsoft/ClearScript#157]
Hi,
I was experimenting with the 'script' object, and I found there is possible to call a JavaScript function from a string, using the syntax

    ClearScriptEngine.Script["functionName"]

Then, I thought it was possible to pass an indefinite number of arguments to the function, and I wrote this C# method

    public void JsRun(string function, params object[] arguments)
    {
        ClearScriptEngine.Script[function](arguments);  // execute the function passing arguments
    }
    
Unfortunately this doesn't work, because ClearScript the exact parameter type and this syntax is not allowed.

Then, I'm asking to:
1. add to the documentation the `ClearScriptEngine.Script["functionName"]` that I found nowhere
2. take in consideration to add the possibility to call functions with the syntax `ClearScriptEngine.Script[function](arguments);`

**Comment by ClearScriptLib** [comment]
Hi @stefano77it,

>Unfortunately this doesn't work, because ClearScript the exact parameter type and this syntax is not allowed.

That's correct. Without metadata to describe script function signatures, ClearScript has no way to guess whether to pass `arguments` as is or spread it out into multiple arguments.

>add the possibility to call functions with the syntax `ClearScriptEngine.Script[function](arguments)`;

There are already a couple of ways to do this:

``` C#
ClearScriptEngine.AddHostType(typeof(Console));
ClearScriptEngine.Execute(@"
    function foo(a, b, c) {
        Console.WriteLine('{0} {1} {2}', a, b, c);
    }
");

var arguments = new object[] { 123, 456.789, "qux" };

// technique #1
ClearScriptEngine.Invoke("foo", arguments);

// technique #2
var foo = (ScriptObject)ClearScriptEngine.Script.foo; // or ["foo"]
foo.Invoke(false, arguments);
```

Good luck!

**Comment by stefano77it** [comment]
The `Invoke` method is useful, I didn't see it (and I think that mentioning those techniques in the documentation would be immensely useful for new users of this wonderful library).

About ClearScript that has no way to guess whether to pass arguments as is or spread it out into multiple arguments, you could add an optional `bool` parameter to `Invoke` to split arguments or to pass as is.

Alternatively, I can write some code to split the arguments and _manually_ calling the JavaScript function with a number of different calls as done with [Action<T1, ..., T16>](https://docs.microsoft.com/en-us/dotnet/api/system.action-16) .

**Comment by ClearScriptLib** [comment]
Hi @stefano77it,

>The `Invoke` method is useful, I didn't see it

It's in the API documentation [here](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Invoke.htm).

>you could add an optional `bool` parameter to `Invoke` to split arguments or to pass as is

That's not necessary. `Invoke` is a .NET method that takes a [`params`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/params) argument array. The ambiguity applies only when invoking script functions directly.

Cheers!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or recommendations. Thank you!
