### ISSUE TITLE
scripts run with 'discard' option set to true are shown as [temp] during debug with Visual Studio Code

### ISSUE THREAD

**Issue by stefano77it** [microsoft/ClearScript#158]
trying to debug some scripts, I found that scripts run with [Evaluate](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Evaluate_2.htm) or [Execute ](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Execute_2.htm) `discard` option set to `true `always pollute the `<node internals>` section of Visual Studio Code while debugging.

the only difference between discarded and not discarded scripts is that discarded scripts has "[temp]" add to them.

follows an image with the `<node internals>` section of Visual Studio Code

![image](https://user-images.githubusercontent.com/8860389/73017251-c0562200-3e1f-11ea-9a11-33636602b7cf.png)

**Comment by ClearScriptLib** [comment]
HI @stefano77it,

This behavior is by design, going back to a time when ClearScript only supported Windows script engines. Back then `discard` had more of an effect, as temporary scripts would disappear from the debugger user interface after execution.

V8 and modern debuggers don't honor `discard`, but the "[temp]" suffix remains. Is that a serious issue for you?

Thanks!

**Comment by stefano77it** [comment]
It's not a serious issue, because using [Invoke](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Invoke.htm) the `<node internals>` section of Visual Studio Code is not polluted with the calls to functions (that in my case are hundreds).

However, I think you should update the API documentation of [Evaluate](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Evaluate_2.htm) and [Execute](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Execute_2.htm) because both contain the phrase

> **Discarding this document removes it from view** but has no effect on the script engine

which is no longer aligned to V8 and modern debuggers.

**Comment by ClearScriptLib** [comment]
Documentation updated in [Version 6.0.1](https://github.com/microsoft/ClearScript/releases/tag/6.0.1).
