### ISSUE TITLE
Debugging notes + Debugging of JavaScript from a C# executable without Visual Studio

### ISSUE THREAD

**Issue by stefano77it** [microsoft/ClearScript#159]
I don't know if you mind editing the debugging notes, but also if you close this issue without any addition to the documentation I post this message to leave a trace and help someone that may find not immediately clear how to debug JavaScript scripts with Visual Studio and Visual Studio code.

The essential piece of documentation/code I found that resolved all my debug issues was the issue #24 .

Before reading it was really difficult for me understand how debug worked and how to attach the debugger: sometimes it worked, many times not, I had to rewind code hoping to having it work with little luck.

Then, I found that with the only option `V8ScriptEngineFlags.EnableDebugging` enabled and the following code/instruction taken from the issue #24, everything was smooth, every time!

    // 0) setup Visual Studio Code as wrote here https://microsoft.github.io/ClearScript/Details/Build.html
    // 1) start the V8 engine with V8ScriptEngineFlags.EnableDebugging option
    // 2) Set a breakpoint at var timeout = 0; and launch the program from Visual Studio in Debug mode.
    // 3) When the breakpoint is hit, connect VSCode (Debug | Start Debugging).
    // 4) Resume the program immediately in Visual Studio.
    // At this point VSCode connects and stops at "debugger;" command. All scripts are loaded and accessible.
    var timeout = 0;
    while (timeout < 200)
    {
        Thread.Sleep(5);
        timeout += 1;
    }

PS and excuse me for all the issues opened today......

**Comment by ClearScriptLib** [comment]
Thanks, @stefano77it.

By the way, you can use `V8ScriptEngineFlags.AwaitDebuggerAndPauseOnStart` to have the script engine wait for a debugger connection before executing the first line of script code. When the script debugger connects, the engine will then immediately break into it.

Cheers!

**Comment by stefano77it** [comment]
Sure, it's possible and works it well, without the `while` loop and the breakpoint.

If you don't mind adding a note to [VII. Debugging with ClearScript and V8](https://microsoft.github.io/ClearScript/Details/Build.html) could be useful to highlight that `V8ScriptEngineFlags.AwaitDebuggerAndPauseOnStart` must be used with `V8ScriptEngineFlags.EnableDebugging` and that the breakpoint inside the Javascript code - if there are many files involved - could be added inserting a `debugger;` line.

**Comment by stefano77it** [comment]
After your suggestion to use `V8ScriptEngineFlags.AwaitDebuggerAndPauseOnStart` I was able to debug JavaScript from a C# executable, using only Visual Studio Code and the exe.

Now it seems an obvious thing, but when I first read the documentation about this library I didn't understand it was possible, and surely this is another big plus of ClearScript that I haven't found in other libraries.

I think that this functionality too should be highlighted in the debug document.

**Comment by ClearScriptLib** [comment]
Documentation updated in [Version 6.0.1](https://github.com/microsoft/ClearScript/releases/tag/6.0.1).
