### ISSUE TITLE
Better stack trace on JavaScript exceptions

### ISSUE THREAD

**Issue by Muchaszewski** [Microsoft/ClearScript#16]
Currently, when JavaScript throws an exception for almost any reason it throws exceptions like this:
```
No overload for method 'find' takes '2' arguments
   at V8Exception.ThrowScriptEngineException(V8Exception* ) in c:\clearscript-5.4.9\clearscript\v8\clearscriptv8\v8exception.cpp:line 81
   at Microsoft.ClearScript.V8.V8ContextProxyImpl.Execute(V8Script gcScript, Boolean evaluate) in c:\clearscript-5.4.9\clearscript\v8\clearscriptv8\v8contextproxyimpl.cpp:line 294
   at (...)
```

As you can see you don't know which object method find was executed and where it lacks overload. In  good enough scenario this should like this (This is how error looks cached by VSCode debugger):
```
Error: No overload for method 'find' takes '2' arguments
    at findOneTutorialData (Script Document:12085:47)
    at getLatestTutorialDataVersion (Script Document:12154:28)
    at Script Document:27:31
```

In the best case scenario, if the error is the object that is HostObject we would get which object V8 has tried to access and failed.

```
Error: No overload for method 'find' takes '2' arguments for host object '<namespace>.MongoCollection'
    at findOneTutorialData (Script Document:12085:47)
    at getLatestTutorialDataVersion (Script Document:12154:28)
    at Script Document:27:31
```

**Comment by Muchaszewski** [comment]
In addition because of the thrown exception method `Engine.GetStackTrace()` doesn't work as intended and results in null

**Comment by ClearScriptLib** [comment]
Hi @Muchaszewski,

The CLR can't record a script stack trace, but if the exception was thrown during script execution, you can usually find one in [`IScriptEngineException.ErrorDetails`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_IScriptEngineException_ErrorDetails.htm):

``` C#
try
{
    engine.Execute(someCode);
}
catch (Exception exception)
{
    var scriptException = exception as IScriptEngineException;
    if (scriptException != null)
    {
        Console.WriteLine(scriptException.ErrorDetails);
    }
}
```

**Comment by Muchaszewski** [comment]
This works great! Would be nice if this exception type would overwrite exception text entirely or add ErrorDetails as part of the exception stack that we can see currently.

**Comment by ClearScriptLib** [comment]
Not a bad idea! We'll take a look. Thanks!

**Comment by ClearScriptLib** [comment]
Added [`ToString()`](https://docs.microsoft.com/en-us/dotnet/api/system.object.tostring) overrides to exception classes in [Version 5.5.1](https://github.com/Microsoft/ClearScript/releases/tag/5.5.1).
