### ISSUE TITLE
Odd evaluate behaviour with anonymous objects in ClearScript 6.0.0

### ISSUE THREAD

**Issue by JohnLudlow** [microsoft/ClearScript#164]
I am investigating upgrading to ClearScript 6.0.0 from 5.5.3 for module support, and one of my unit tests is failing

```csharp
        [TestMethod]
        public void ScriptingHostManaged_SetVariableObject_EvaluateJsonStringify_ReturnsStringValue()
        {
            using (var engine = new V8ScriptEngine())
            {

                engine.AddHostType(typeof(JsonConvert));
                engine.AddHostObject("ExtendedHostTypes", new HostTypeCollection("Newtonsoft.Json"));

                engine.Evaluate(
@"
                (function () {
                    let js = JSON.stringify;
                    let clr = JsonConvert.SerializeObject;
            
                    JSON.stringify = (v, r, s) => js(v, r, s) || clr(v);            
                })()
            "
);
                engine.Script.variable = new { message = "hello", recipient = "world" };
                var result = engine.Evaluate("JSON.stringify(variable)");
                Assert.AreEqual("{\"message\":\"hello\",\"recipient\":\"world\"}", result);

            }
        }
```

Using 5.5.3 gives this string as the result:
`{"message":"hello","recipient":"world"}`

Using 6.0.0 gives this string as the result:
`{"<message>i__Field":"hello","<recipient>i__Field":"world","message":"hello","recipient":"world"}`

Notes:

* Nothing else has changed. Newtonsoft.Json was v11.0.2 in both of these test runs.
* The use of JsonConvert to back JSON.stringify in this way was discussed in #94

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

It looks like `JSON.stringify` has changed in the newer V8 version that comes with ClearScript 6. It used to choke on host objects and return a falsy result, but now it serializes them (poorly).

A revised approach might be to avoid passing host objects through `JSON.stringify` altogether:

``` C#
engine.Execute(
    @"
    (function () {
        let js = JSON.stringify;
        let clr = JsonConvert.SerializeObject;
        let isClr = v => v.toString() === '[object HostObject]';
        JSON.stringify = (v, r, s) => isClr(v) ? clr(v) : js(v, r, s);
    })()
");

engine.Script.variable = new { message = "hello", recipient = "world" };
var result = engine.Evaluate("JSON.stringify(variable)");
Assert.AreEqual("{\"message\":\"hello\",\"recipient\":\"world\"}", result);
```

Good luck!

**Comment by JohnLudlow** [comment]
Yeah that helps.

Thanks

**Comment by JohnLudlow** [comment]
@ClearScriptLib do you want me to close this issue?

**Comment by ClearScriptLib** [comment]
We'll close it, but please feel free to reopen this issue if you have additional questions or concerns about this topic. Thanks!
