### ISSUE TITLE
ES6 support question

### ISSUE THREAD

**Issue by drearyrainDeng** [microsoft/ClearScript#167]
Do ClearScript will support ES6 standard? any plan?

**Comment by ClearScriptLib** [comment]
Hi @drearyrainDeng,

For JavaScript, ClearScript supports [JScript](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/hbxc2t98(v=vs.84)) and [V8](https://v8.dev/). JScript supports ES3 and select features from subsequent standards. V8 supports ES7 and beyond.

Thanks!

**Comment by drearyrainDeng** [comment]
that is great,thanks

**Comment by r4nc1d** [comment]
@ClearScriptLib above you mentioned that " V8 supports ES7 and beyond." when i try to run the following code.

 engine.Evaluate(@"async function process1(data) {
                                return { xValue: 'asdasd' };
                            }");

var toReturn = engine.Script.process1(data);

I get the following error "**no further information on this object could be discovered**"

If i remove the async then it works fine, but having said that async is an ES7 feature
