### ISSUE TITLE
import node.js modules

### ISSUE THREAD

**Issue by flat-eric147** [microsoft/ClearScript#168]
Hello beloved CearScript team!

I am currently experimenting to use node.js modules in my ClearScript scripts :) so I installed node.js on my local machine and tried more or less this demo code here (which works fine from node.js):

const http = require( "http");

const hostname = '127.0.0.1';
const port = 3000;

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello, World!\n');
});

When I try this snipped in ClearScript it fails in the "require" statement throwing these errors:

error in script Error: Could not load file or assembly 'http' or one of its dependencies. The system cannot find the file specified.
error in script Exception has been thrown by the target of an invocation.
error in script Could not load file or assembly 'http' or one of its dependencies. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
error in script Could not load file or assembly 'http' or one of its dependencies. The system cannot find the file specified.
Error: Could not load file or assembly 'http' or one of its dependencies. The system cannot find the file specified.
    at CommonJS-createModule [internal]:14:36 ->                             return hostRequire(moduleId);

So it seems ClearScript can't locate that module. 
Any clues what I'm doing wrong?

I execute the script like this:

engine.Execute(new DocumentInfo { Category = ModuleCategory.CommonJS }, model.Script);

engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging | 
                                                V8ScriptEngineFlags.EnableRemoteDebugging | 
                                                V8ScriptEngineFlags.EnableDynamicModuleImports, 9222);
engine.DocumentSettings.AccessFlags = DocumentAccessFlags.EnableAllLoading;

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @flat-eric147,

While ClearScript now supports both JavaScript and CommonJS modules, it doesn't provide any script APIs beyond the standard JavaScript built-ins.

You might be able to use [`DocumentSettings.SearchPath`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_DocumentSettings_SearchPath.htm) to help ClearScript _locate_ Node.js modules on your machine, but most of those modules are unlikely to work, as they're ultimately dependent on Node.js intrinsics that ClearScript doesn't implement.

On the other hand, it should certainly be possible to use ClearScript as the foundation for a Node.js-compatible JavaScript platform. That would be an interesting project!

Good luck!

**Comment by flat-eric147** [comment]
Thank you, shortly after posting this I found the SearchPath as well, I have tried to put all possible paths - but no glory. Are there any "powerful" standard modules I can include that will work in ClearScript?

**Comment by ClearScriptLib** [comment]
>I have tried to put all possible paths - but no glory.

Are the modules loaded at least? Or does ClearScript still fail to find them (or their dependencies)? Keep in mind that ClearScript supports only search paths and has no knowledge of npm or package.json.

>Are there any "powerful" standard modules I can include that will work in ClearScript?

That's unlikely, although some could probably be made to work with a few simplified system modules such as "console", "process", etc.

**Comment by flat-eric147** [comment]
> > I have tried to put all possible paths - but no glory.
> 
> Are the modules loaded at least? Or does ClearScript still fail to find them (or their dependencies)? Keep in mind that ClearScript supports only simple search paths and has no knowledge of npm or package.json.

I get the very same error message, although I have added the system path and a bunch of other paths into the SearchPath. So no worries, probably as you said, intrinsics in node.js that ClearScript doesn't implement.

**Comment by stefano77it** [comment]
> On the other hand, it should certainly be possible to use ClearScript as the foundation for a Node.js-compatible JavaScript platform. That would be an interesting project!

Hi,
I'm developing a project that uses ClearScript (and another engine as backup) to run JavaScript code and working with other JavaScript external libraries (as the Node.js library [@hapi/formula](https://www.npmjs.com/package/@hapi/formula) etc).

Then, inspired by your comment, I published today a project with all the code of the JavaScript functionality on https://github.com/stefano77it/CSharpJavaScriptRunner, MIT licensed as ClearScript.

Highlights:
* starting from [some barebone code](https://github.com/musikele/require-example/) that mimic the functionality of require/CommonJs and his [explanation](https://michelenasti.com/2018/10/02/let-s-write-a-simple-version-of-the-require-function.html) I adapted it for this project ([myrequire.js](https://github.com/stefano77it/CSharpJavaScriptRunner/blob/master/Scripting.JsScripts.v1/lib/myrequire.js))
* implemented optional use of [Base64 encoded zip files](https://github.com/stefano77it/CSharpJavaScriptRunner/blob/master/Scripting.Js.v1/Utils/InMemoryScript/InMemoryScript.cs) to store an entire folder of Js files and libraries in [a single C# string](https://github.com/stefano77it/CSharpJavaScriptRunner/blob/master/Scripting.Tests/InMemoryFiles%20(Zip)%20%2B%20RealFs%20tests/ClearScript%20ES6/ES6_scripts_to_zip_plus_to_encode_in_Base64.cs). [Working tests and assets](https://github.com/stefano77it/CSharpJavaScriptRunner/tree/master/Scripting.Tests/InMemoryFiles%20(Zip)%20%2B%20RealFs%20tests) provided.
* built a virtual filesystem (using simply a dictionary inside the [scripting context](https://github.com/stefano77it/CSharpJavaScriptRunner/blob/master/Scripting.Js.v1/ScriptingContext/ScriptingContext.cs)) to intercept requests of files stored in memory
* wrote a simple [JavaScript filesystem API layer](https://github.com/stefano77it/CSharpJavaScriptRunner/blob/master/Scripting.JsScripts.v1/lib/myfs.ts) that calls Node.js and C# methods to be able to read/write a file without worrying if the script is executed in memory or against a real fs, from ClearScript or Node. For security purposes the C# code doesn't allow any  writing in the real filesystem above the `scriptsPath`

When possible I used TypeScript, to allow debug/static typing.

PS ClearScript is really a powerful library, and is a pleasure to work with it.

**Comment by ClearScriptLib** [comment]
@stefano77it Very nice! Thanks for sharing, and thanks for the kind words!
