### ISSUE TITLE
Debugging with ClearScript and V8

### ISSUE THREAD

**Issue by kevinkoenig** [Microsoft/ClearScript#17]
I was wondering how one would go about using ClearScript with the v8 engine and attaching to it using chrome devtools.  I cant seem to get that to work.  Can someone point me in the right direction.  I specifically don't want to use vscode if possible, but I will if I need to.  The key need for me is to debug remotely.

Thanks in advance

**Comment by ClearScriptLib** [comment]
Hi @kevinkoenig,

ClearScript currently supports only the legacy V8 debugging protocol, whereas Chrome DevTools uses the new Inspector protocol.

An Inspector implementation is our top priority, as it's holding up support for V8 6.x. We're hoping to post a new release with Inspector support soon.

Thanks!

**Comment by kevinkoenig** [comment]
Thank you.  I look forward to seeing that update.  I just switched to this library from a direct embedding of chakra.  So much easier.  I did finally get the vscode debugging to work.

**Comment by kevinkoenig** [comment]
I had one more question related to debugging using vscode.  I have everything working now, and my scripting engine is almost implemented.  I can use vscode to debug my script code when it is running on the same machine as the server.  

My ultimate goal is to enable remote debugging of script that is running in an ASP.NET server application.  That is why I switched from local embed of chakra to v8 using ClearScript.

As I said I can debug script on local machine.  If I try to connect from a remote machine by adding the "address" attribute to the launch.json, it does not connect.  

Also if I run vscode on the same machine as the web application, but add an "address" attribute and set it to the server's IP address (not loopback) it does not work.

I am definitely not an expert on the code base but if I look at V8DebugAgent it seems to bind to the loopback address.  in the constructor.  Is this the issue or is there something else that I might not be aware of.  

Thanks in advance for your help.

**Comment by ClearScriptLib** [comment]
Hi @kevinkoenig,

To be honest, we haven't tested remote debugging, but you've probably identified the issue. If you're building ClearScript yourself, try modifying [`V8DebugAgent`](https://github.com/Microsoft/ClearScript/blob/f4cd26809adeadb241f1476cf220e8ad7dd0b0b1/ClearScript/V8/V8DebugAgent.cs#L48) to use [`IPAddress.Any`](https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.any?view=netframework-4.7.1) or a specific address. We've done a quick test, and it appears to work.

We'll try to provide support for remote debugging in our upcoming Inspector implementation. As Inspector uses [WebSocket](https://en.wikipedia.org/wiki/WebSocket), it's likely that you'll have to use [netsh http add urlacl](https://msdn.microsoft.com/en-us/library/windows/desktop/cc307223(v=vs.85).aspx) to enable ClearScript's Inspector listener (unless your application runs under an administrator account).

Good luck!

**Comment by kevinkoenig** [comment]
Thanks for the quick reply.  I am building ClearScript myself and I will make the change and let you know what happens.  

when the WebSocket implementation is available I will configure the server with the uracl access. 

Thanks again for the rapid reply

**Comment by kevinkoenig** [comment]
I have been running for a while with remote debugging and haven't found any issues.

**Comment by ClearScriptLib** [comment]
We've posted [ClearScript 5.5](https://github.com/Microsoft/ClearScript/releases/tag/5.5.0). This release adds support for local and remote debugging via Inspector, enabling the use of Chrome DevTools and other JavaScript debuggers.
