### ISSUE TITLE
Centos 7.5 Issue:Unhandled exception. System.DllNotFoundException:

### ISSUE THREAD

**Issue by wurangbo** [microsoft/ClearScript#172]
Hi guys,
 when I run my app on centos7.5.  .netcore3.1, I got error as below. how can I fix it ?
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'kernel32' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libkernel32: cannot open shared object file: No such file or directory
   at Microsoft.ClearScript.Util.NativeMethods.LoadLibraryW(String path)

**Comment by Taritsyn** [comment]
This library only works under Windows.

**Comment by ClearScriptLib** [comment]
Thanks, Andrey!

@wurangbo Please reopen this issue if you have additional questions. Cheers!
