### ISSUE TITLE
ExtendedHostFunctions should have a releaseComObj function to go alongside newComObj

### ISSUE THREAD

**Issue by JohnLudlow** [microsoft/ClearScript#179]
The [`ExtendedHostFunctions.newComObj`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ExtendedHostFunctions_newComObj.htm) method creates objects that aren't necessarily cleaned up.

We've worked around this by adding a `releaseComObj` method which looks like this:

```csharp
    public class ExtendedHostFunctions : Microsoft.ClearScript.ExtendedHostFunctions
    {
        void releaseComObj(object o) { if (Marshal.IsComObject(o)) Marshal.ReleaseComObject(o); }
    }
```

ExtendedHostFunctions should probably havethis out of the box.

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

We'd prefer _not_ to add such a method, for the following reasons:

1. COM interop is designed to work with managed garbage collection, making explicit release unnecessary in most cases.
1. ClearScript aims to make it easy to expose .NET APIs to script code. We therefore consider it an _anti-pattern_ to simply wrap public .NET methods and re-expose them through ClearScript's API. A simple `engine.AddHostType(typeof(Marshal))` makes the methods you're looking for available.

Having said that, we acknowledge that COM explicit release may be desirable for reasons other than cleanup, and that exposing large classes like `Marshal` may be problematic. Can you say more about your particular scenario?

Thanks!

**Comment by JohnLudlow** [comment]
Hi @ClearScriptLib,

This is in relation to #170, where we found (while implementing a story to import data from Excel into our application using JavaScript) that failing to correctly clean up created objects caused lingering Excel processes.

Our temporary workaround was this:

```javascript
function Release(object) {
    let Marshal = ExtendedHostFunctions.type("System.Runtime.InteropServices.Marshal");
    Marshal.ReleaseComObject(object);
    object = null;
}
```

This worked fine, but the better option was to create a pair for `newComObject` which effectively did the above. This was better because in this scenario, creation and destruction are naturally paired activities.

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

Since you're exposing `ExtendedHostFunctions`, you already have all you need. There's no need to expose additional managed resources.

Your temporary solution is suboptimal because it doesn't cache the `Marshal` host type and doesn't provide a symmetric API, but you can easily fix both issues with something like this:

``` JavaScript
class Com {
    static #Marshal = ExtendedHostFunctions.type('System.Runtime.InteropServices.Marshal');
    static newObj() {
        return ExtendedHostFunctions.newComObj(...arguments);
    }
    static releaseObj(obj) {
        return Com.#Marshal.ReleaseComObject(obj);
    }
}
```

and then:

``` JavaScript
let fso = Com.newObj('Scripting.FileSystemObject');
for (let drive of fso.Drives) {
    System.Console.WriteLine(drive.Path);
}
Com.releaseObj(fso);
```

Cheers!

**Comment by JohnLudlow** [comment]
That's effectively what we did as a workaround

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

Because `ExtendedHostFunctions` already facilitates script access to `Marshal.ReleaseComObject`, we see no compelling reason to provide `ExtendedHostFunctions.releaseComObject`.

Please reactivate this issue if you have additional comments or concerns.

Thanks!
