### ISSUE TITLE
Provide a more flexible and performant alternative to GetDynamicMemberNames

### ISSUE THREAD

**Issue by Frolov-Nikita** [microsoft/ClearScript#180]
It wil be usefull.

**Comment by ClearScriptLib** [comment]
Hi @Frolov-Nikita,

ClearScript already supports a number of ways to access dynamic object members from script code. Do you have a specific scenario or pattern in mind?

Thanks!

**Comment by Frolov-Nikita** [comment]
Sorry for the inaccurate description.
I would like to use the dynamic properties of the "Params" object in the script as properties, but when I try to access "Params.Density", it returns undefined.
Maybe I'm missing something?
Here is the scenario:
```C#
using System;
using System.Dynamic;
using System.Collections.Generic;
using Microsoft.ClearScript.V8;

namespace ConsoleApp1
{
    public class Param
    {
        public object Value { get; set; }
        public string Units { get; set; }
    }

    public class DynamicDictionary : DynamicObject
    {
        Dictionary<string, Param> dictionary
            = new Dictionary<string, Param>();

        public int Count => dictionary.Count;

        public override bool TryGetMember(GetMemberBinder binder, out object result)
        {
            string name = binder.Name.ToLower();
            var success = dictionary.TryGetValue(name, out Param innerResult);
            result = innerResult;
            return success;
        }

        public override bool TrySetMember(SetMemberBinder binder, object value)
        {
            dictionary[binder.Name.ToLower()] = (Param)value;
            return true;
        }

        public void Add(string key, Param param)
        {
            dictionary.Add(key.ToLower(), param);
        }

        public object Get(string key)
        {
            return dictionary[key.ToLower()].Value;
        }

        public void Set(string key, object value)
        {
            dictionary[key.ToLower()].Value = value;
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            dynamic processParams = new DynamicDictionary();

            processParams.Add("Pressure", new Param());
            processParams.Add("Level",  new Param() { Value = 2 });
            processParams.Add("Density", new Param() { Value = 0.81 });

            var engine = new V8ScriptEngine();
            engine.AddHostObject("Params", processParams);

            var code = engine.Compile(@"

                //Params.Pressure.Value = Params.Density.Value * Params.Level.Value * 0.98 // <== this line doesn't work
                //TypeError: Cannot read property 'Value' of undefined

                // Next code works fine
                let level = Params.Get('Level')
                let density = Params.Get('Density')
                let pressure = 0.98 * level * density
                Params.Set('Pressure', pressure)
            ");

            engine.Execute(code);

            Console.WriteLine($"Tank pressure is {processParams.Pressure.Value}");
            Console.ReadLine();
        }
    }
}
```

**Comment by ClearScriptLib** [comment]
Hi @Frolov-Nikita,

There are a couple of issues here.

First, dynamic property access currently requires a working implementation of [`GetDynamicMemberNames`](https://docs.microsoft.com/en-us/dotnet/api/system.dynamic.dynamicobject.getdynamicmembernames). For example:

``` C#
public override IEnumerable<string> GetDynamicMemberNames() => dictionary.Keys;
```

This would be sufficient in most cases. Unfortunately, ClearScript's current implementation would interfere with your attempt to make dynamic property access _case-insensitive_. That is, given the above `GetDynamicMemberNames` override, `Params.pressure` would work, but not `Params.Pressure`.

It might be possible to relax the `GetDynamicMemberNames` requirement, at least for V8. We'll take a closer look.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @Frolov-Nikita,

Unfortunately, `GetDynamicMemberNames`, or something like it, is unavoidable.

In V8, method invocation is a two-step process: retrieve a function-valued property and then invoke the result. This is fundamentally incompatible with the one-step `TryInvokeMember`. To provide a reasonable value in the first step, ClearScript must determine if a dynamic member with the specified name exists, and `GetDynamicMemberNames` is the only way to do that.

Windows script engines, on the other hand, enumerate a host object's members upfront, and if the script requests an unenumerated member, the host gets no chance to fulfill the request. `GetDynamicMemberNames` is the only way to enumerate dynamic members.

We'll look into adding an alternative to `GetDynamicMemberNames` - one that would perform better and give hosts the flexibility to implement case-insensitive member access.

Thanks again!

**Comment by Frolov-Nikita** [comment]
Many thanks for the help.
Case-insensitive is not important to me. In my opinion, it is even a little harmful :)

**Comment by ClearScriptLib** [comment]
[Versionk 6.0.2](https://github.com/microsoft/ClearScript/releases/tag/6.0.2) adds [`DynamicHostObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_DynamicHostObject.htm).
