### ISSUE TITLE
Implementation of ExecuteAsync

### ISSUE THREAD

**Issue by Ellested** [microsoft/ClearScript#182]
If you are running the engine execute from a single threaded context, it is not possible to invoke async/await CLR methods from the script, without blocking. Would it be possible to make a native async implementation of the Execute method aka. ExecuteAsync?

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

Can you clarify how `ExecuteAsync` would be different from `Execute`? The  `async` and `await` keywords cannot be used in JavaScript's global context.

Thanks!

**Comment by Ellested** [comment]
ExecuteAsync would be a native async implementation of Execute, where you return a Task. 
Calling into the CLR from the engine scripts should be done by using the async/await patterns.
Like:
```
public async Task ExecuteStuff() 
{
     await ExecuteAsync(@" var x = asyncMethodThatLivesInClr().Wait(); ");
}
```
When you hit Wait() inside the script, the thread should be handed back to the async state machine that await's the ExecuteAsync method.

If you only have a single thread available, and called the above with a synchronous Execute method, the thread will deadlock, as it cannot continue processing tasks, while also awaiting.

In many cases this problem can be solved with await Task.Run(), as it will normally allow another thread to participate, but in a single threaded synchronization context, that's not possible.

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

>Calling into the CLR from the engine scripts should be done by using the async/await patterns.

ClearScript can't change how V8 executes JavaScript code. Unless you're in an [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function) and use the [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) operator, V8 will not pause execution and unwind the thread. 

If you wish to invoke an asynchronous CLR method from synchronous script code without waiting, you'll have to use [`ContinueWith`](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task.continuewith).

On the other hand, if you _are_ in a JavaScript async function and wish to invoke an asynchronous CLR method, you can convert the returned task into a promise and use JavaScript's `await`:

``` C#
engine.AddHostType(typeof(Task));
engine.AddHostType(typeof(Console));
engine.AddHostType(typeof(JavaScriptExtensions));
engine.Execute(@"
    (async function() {
        await Task.Delay(5000).ToPromise();
        Console.WriteLine('Finished waiting.');
    })();
");
```

Please send us your thoughts.

Thanks!

**Comment by Ellested** [comment]
This is what I'm trying to achieve:
```
void Main()
{
	using (var engine = new V8ScriptEngine())
	{
		engine.AddHostType(typeof(Task));
		engine.AddHostType(typeof(Console));
		engine.AddHostType(typeof(JavaScriptExtensions));
		engine.Execute(@"
    		(async function() {
		        await GetInt().ToPromise();
		        Console.WriteLine('Finished waiting.');
    		})();
		");
		Console.ReadLine();
	}
}

public async Task<int> GetInt() {
	await Task.Delay(1000);
	return 10;
} 
```
But it's not working for me - should it?

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

You're not exposing `GetInt` to the script engine. Try something like this:

``` C#
public static void Main() {
    using (var engine = new V8ScriptEngine()) {
        engine.AddHostType(typeof(Task));
        engine.AddHostType(typeof(Console));
        engine.AddHostType(typeof(JavaScriptExtensions));
        engine.Script.GetInt = new Func<Task<int>>(GetInt);
        engine.Execute(@"
            (async function() {
                let result = await GetInt().ToPromise();
                Console.WriteLine('Finished waiting; result = {0}', result);
            })();
        ");
        Console.ReadLine();
    }
}
public static async Task<int> GetInt() {
    await Task.Delay(1000);
    return 10;
}
```

This seems to work as expected.

Good luck!

**Comment by Ellested** [comment]
Sorry, I forgot to mention that I also need to wait for the execution to finish - as you would normally do with the await keyword, if the execute and evaluate was async.

Something along this:
```
public static void Main() {
    using (var engine = new V8ScriptEngine())
    {
        engine.AddHostType(typeof(Task));
        engine.AddHostType(typeof(Console));
        engine.AddHostType(typeof(JavaScriptExtensions));
        engine.Script.GetInt = new Func<Task<int>>(GetInt);
        engine.Execute(@"
            let Test = {
                getValue: async function() {
                    let result = await GetInt().ToPromise();
                    Console.WriteLine('Finished waiting; result = {0}', result);
                    return result;
                }
            }
        ");

        var x = engine.Evaluate(@"Test.getValue();");
        Console.WriteLine($"X is {x}");
        Console.ReadLine();
   }
}

public static async Task<int> GetInt()
{
    await Task.Delay(1000);
    return 10;
}
```

Not sure this makes sense, but thanks for trying to point me in the right direction.

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

`Test.getValue` returns a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). As with most script objects, ClearScript lets you use promises directly from managed code, but it might make sense to create a convenient helper. For example:

``` C#
public static class PromiseHelpers {
    public static Task<object> ToTask(this object promise) {
        var source = new TaskCompletionSource<object>();
        Action<object> onResolved = result => source.SetResult(result);
        Action<dynamic> onRejected = error => source.SetException(new Exception(error.toString()));
        ((dynamic)promise).then(onResolved, onRejected);
        return source.Task;
    }
}
```

With this simple class in place, you can use `await` on both sides:

``` C#
public static void Main() {
    RunTestAsync().Wait();
}
public static async Task RunTestAsync() {
    using (var engine = new V8ScriptEngine()) {
        engine.AddHostType(typeof(JavaScriptExtensions));
        engine.Script.GetInt = new Func<Task<int>>(GetInt);
        engine.Execute(@"
            let Test = {
                getValue: async function() {
                    return await GetInt().ToPromise();
                }
            }
        ");
        var result = await engine.Evaluate("Test.getValue();").ToTask();
        Console.WriteLine("result is {0}", result);
    }
}
```

Please let us know if this works for you. Thanks!

**Comment by Ellested** [comment]
What can I say other than WOW :-)
Exactly what I needed to understand how it works, thanks a lot.

Excuse me, now that I have an experts attention - is there any way to put resource constraints on the engine, such as CPU and RAM usage, so you can ensure that scripts are not going into infinite loops, or allocating all the RAM on the host - taking everything down with it?

**Comment by ClearScriptLib** [comment]
>Exactly what I needed to understand how it works, thanks a lot.

No problem at all. We've decided to add a slightly improved version of `ToTask` to the ClearScript API in the next release, so thank you!

>is there any way to put resource constraints on the engine, such as CPU and RAM usage

There are some things you can do, but, unfortunately, V8's design currently prevents bulletproof sandboxing. Please see our reply [here](https://github.com/microsoft/ClearScript/issues/101#issuecomment-625428406).

**Comment by ClearScriptLib** [comment]
[Version 6.0.2](https://github.com/microsoft/ClearScript/releases/tag/6.0.2) adds [`JavaScriptExceptions.ToTask`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_JavaScript_JavaScriptExtensions_ToTask.htm).

**Comment by gjvdkamp** [comment]
This JavaScriptExtensions class is pretty amazing stuff thanks!

**Comment by gjvdkamp** [comment]
How do I return a rejected promise from a faulted C# Task? I can catch the Exception in C#, but what should I return from the `async Task<string>` so that V8 understands this is a rejected promise? 

I use the flags to create the engine and just  call the `async Task<string>` straight form js (which blows my mind): 
`var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDateTimeConversion | V8ScriptEngineFlags.EnableValueTaskPromiseConversion);`
