### ISSUE TITLE
Disconnect from host events on engine dispose

### ISSUE THREAD

**Issue by uranoxyd** [microsoft/ClearScript#183]
I facing some issues when using host events from script code.
If i dispose the engine object/script, all event handlers from the script stay attached to the host events. So when the host event gets invoked a ``ObjectDisposedException`` occurs.

I know that i could disconnect the events script-side before disposing the engine, but i would like to see the engine cleaning up after itself though :). 

Am i missing something and there is a way to do this? If not, i would suggest this as a feature request/improvement.

**Comment by ClearScriptLib** [comment]
Hi @uranoxyd,

Are you referring to event connections established via [`EventSource<T>.connect`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_EventSource_1_connect.htm)?

Thanks!

**Comment by uranoxyd** [comment]
I think yes, i mean host events handled in script, like mentioned in the FAQtorial (16) ``hostEvent.connect(handler)``

**Comment by ClearScriptLib** [comment]
Thanks @uranoxyd. We believe this is a worthwhile enhancement and will implement it in the next ClearScript release.

**Comment by uranoxyd** [comment]
Thanks, glad to hear

**Comment by ClearScriptLib** [comment]
Fixed in [Version 6.0.2](https://github.com/microsoft/ClearScript/releases/tag/6.0.2).
