### ISSUE TITLE
I had the exact same issue as #142

### ISSUE THREAD

**Issue by Ellested** [microsoft/ClearScript#185]
I've spend more time on getting this thing to build, than my upcoming PR - I'm almost giving up.

Could you possibly include the V8 binaries and .dbg files for ease of use?

I also have problems with loading the .net framework test project. It could not import the project, as it wasn't found to be compatible?
I don't see why, and the error message points me to Microsoft page with nothing on the issue - any ideas?

I'm using VS2019 latest, and all SDK stuff etc. is in place as described in the docs.

**Comment by Ellested** [comment]
Got so far now:
![image](https://user-images.githubusercontent.com/7518147/82118500-23c1e200-9778-11ea-879f-23261728ef9a.png)

But it actually works fine:
![image](https://user-images.githubusercontent.com/7518147/82118541-5e2b7f00-9778-11ea-97e8-f43c90b506d5.png)

**Comment by Ellested** [comment]
![image](https://user-images.githubusercontent.com/7518147/82120643-e8c7aa80-9787-11ea-80a9-82af7bba5162.png)

Back to square one...

**Comment by Ellested** [comment]
Cleaning up environment path, fixed the above issue. As the error says, it's too long.

However, it just starts failing later on with the same problems. Seems like the build is using a lot of path concatenations, which end ups in errors if you don't start from a clean installed windows :-)

Maybe it's better to start the build with getting the directories you need, and filter the rest out - then the script can concatenate what is needed and hereby make sure it's working on all machines. Last step could restore the original path variable.

Anyway, it's stupid that we have to deal with limitations on command line length - someone at Microsoft should increase the buffers :-)

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

We've seen environment-related issues on some machines recently as well. Unfortunately we haven't found a robust solution.

In some cases we've been able to work around the problems by moving the ClearScript directory to a drive root. We've also found that using `setlocal`/`endlocal` to isolate the environment separately for the 32-bit and 64-bit builds helps in some cases. That change will be in the next release.

On the other hand we're not aware of any issues with the Visual Studio project files. If you get your V8 build working, let us know if your Visual Studio issues persist.

You can get ClearScript binaries on [nuget.org](https://www.nuget.org/packages/Microsoft.ClearScript). We're working on a way to also publish the PDBs, but unfortunately we have no ETA for that.

Good luck!

**Comment by Ellested** [comment]
![image](https://user-images.githubusercontent.com/7518147/82122407-d0f62380-9793-11ea-96c6-9f288e00b356.png)
I'm back to this issue again. I've backed up my env variables (with "Rapid Environment Editor", is anyone needs to do that), and have only a few folders left. I've also substituted drive Y for C:\Users\KE\Source\Git\ClearScript
The only thing left is that I get a warning that python is version 3, what version is known to work?

**Comment by ClearScriptLib** [comment]
Hi @Ellested,

We also see the Python v3 warning, but the build succeeds, so that's probably not the problem.

Our only recommendation would be to open a new Visual Studio command prompt, trim your path, and try again with ClearScript at the drive root. That works for us on all the machines we've tested.

If it still fails for you, we'd love to see a full log, if you can capture it.

Good luck!

**Comment by Ellested** [comment]
HA - it finally worked :-)
setlocal/endlocal did the trick
Thanks - and it builds on a substituted drive too

Now the test project...

**Comment by Ellested** [comment]
![image](https://user-images.githubusercontent.com/7518147/82123312-ff2a3200-9798-11ea-8f84-94b9bec2e5ac.png)

The link is just a standard landing page with some pointers. I'll see if I can find  out what it is, but apparently I don't have the required application type.

**Comment by Ellested** [comment]
Why are you using C#5.0 - I mean it's pretty old now - from 2012?
Are there any hidden constraints, as I believe all version of .net framework supports 7.3 at least.

**Comment by ClearScriptLib** [comment]
>Why are you using C#5.0 - I mean it's pretty old now - from 2012?

The project does go back that far. We put in the restriction to retain source compatibility with Visual Studio 2012, and it's just been inertia since then. C# 5 is also still the current Ecma and ISO standard.

**Comment by ClearScriptLib** [comment]
[Version 6.0.2](https://github.com/microsoft/ClearScript/releases/tag/6.0.2) isolates the environment in V8Update during 32-bit and 64-bit V8 builds. Please open a new issue if you encounter additional problems building V8.
