### ISSUE TITLE
Import V8 Module Cache? Refresh?

### ISSUE THREAD

**Issue by egooner** [microsoft/ClearScript#187]
I have been looking at the V8 Import capabilities and managed to get it working as below
Top Level File level1.js
<pre>
import HelloWorld  from 'modules/level2.js'
HelloWorld()
</pre>
Module file level2.js
<pre>
export default function HelloWorld() {
    console.log("Hello World How Are you today!!")
}
</pre>

My program is an automation tool that uses ClearScript at the backend. Therefore the scripts get executed multiple times at user discretion. During coding of the scripts if I make changes to the Module level2.js whilst the parent program is still running (but the scripts have finished) the original level2.js is executed instead of the updated code. If I stop and restart the parent program then the correct level2.js is executed.

This sounds like some sort of engine cache? Is this the case? Can I flush this somehow or tell engine not to cache the imported modules?

**Comment by egooner** [comment]
I just found this in some of your [Test Code](https://github.com/microsoft/ClearScript/blob/master/ClearScriptTest/ClearScriptTest.cs) which seems to have resolved this. 
<pre>
                DocumentLoader.Default.DiscardCachedDocuments();
                GC.Collect();
                GC.WaitForPendingFinalizers();
</pre>

**Comment by ClearScriptLib** [comment]
Hi @egooner,

The `DiscardCachedDocuments` call should be sufficient.

Please reopen this issue if you have additional questions or concerns.

Thanks!

**Comment by egooner** [comment]
Thanks - been working through this and found the same. :)
