### ISSUE TITLE
Question regarding V8ScriptEngine and multi-threads

### ISSUE THREAD

**Issue by KevinEady** [microsoft/ClearScript#189]
In https://github.com/microsoft/ClearScript/issues/12#issuecomment-328289190, it is mentioned:

> If you're using a single instance of `V8ScriptEngine`, you can execute JavaScript code on any thread, but not on multiple threads simultaneously.
>
> Your example launches a JavaScript task on a worker thread, but waits for it on the current thread. This is a deadlock because the worker thread can't start running JavaScript code until the current thread stops doing so.

I'm having trouble identifying _what_ is incorrect behavior, because I see two different situations here that can be wrong:
1. Executing code from multiple threads simultaneously, _or_
2. Having secondary thread await on code execution, while primary thread is executing code that never completes (a deadlock, _obviously_ wrong)

For example, say I have `engine.Script.foo` that exposes some function. What will happen in the scenario where primary thread calls `engine.Script.foo()`, and before this call completes, a secondary thread also executes into the script? Will the secondary thread's call ...
1. ... throw an Exception saying "engine is busy"
2. ... wait for the primary thread's call to finish, _then_ execute the secondary thread's call?

I suppose the difference between the two being: do I have to build my own "execute script code" dispatcher (in case of point #<span/>1) or does ClearScript have this support built-in (in case of point #<span/>2) and it is up to the developer to ensure deadlocks don't happen?

Thanks, Kevin

**Comment by ClearScriptLib** [comment]
Hi Kevin,

>For example, say I have engine.Script.foo that exposes some function. What will happen in the scenario where primary thread calls engine.Script.foo(), and before this call completes, a secondary thread also executes into the script? Will the secondary thread's call ...
>1. ... throw an Exception saying "engine is busy"
>2. ... wait for the primary thread's call to finish, then execute the secondary thread's call?

The answer is 2. Each `V8ScriptEngine` instance has a private mutex that it locks while executing script code.

Actually, the mutex belongs to the underlying V8 _runtime_, but you can ignore that if you aren't using shared runtimes.

Good luck!

**Comment by KevinEady** [comment]
Perfect! Thanks!
