### ISSUE TITLE
Missing exception call stack on some machines

### ISSUE THREAD

**Issue by Nir1812** [microsoft/ClearScript#190]
When getting an error during script execution, I usually get the full call-stack for the script functions, starting from the error line and going all the way to the first called function.
But there are some machines that do not give that information, and the call stack and other exception related information is missing.

I have found that when installing the Visual Studio Remote Debugger module, this issue is resolved and exceptions from those machines is again with all the needed info.

I guess it has something to do with one of the DLLs that is installed during the Remote Tools setup, but I really wish to know which one, so I will be able to pre-install it on the end users' machines.

**Comment by ClearScriptLib** [comment]
@Nir1812, are you using a Windows script engine (JScript/VBScript)?

**Comment by Nir1812** [comment]
Windows VBScript

**Comment by Nir1812** [comment]
I have found that installing this package:
https://download.visualstudio.microsoft.com/download/pr/bf2169fa-dee7-4d3f-8c6c-135b16f76519/1c9bc0529613fecf64cfa6d35c0cf96d3fa48fe2a8da82ab4cb89a7dc3a6c280/scriptdebugging_x64.msi

Solves the problem... Is there a possibility to tell ClearScript to use a local version of the needed DLL? I really do not wish to require administrative rights to install this update...

**Comment by ClearScriptLib** [comment]
Hi @Nir1812,

Thanks for researching and posting your solution!

>Is there a possibility to tell ClearScript to use a local version of the needed DLL?

ClearScript accesses the Windows debugging infrastructure indirectly via COM interfaces and registered classes. You could try preloading the relevant DLLs, or possibly using [DLL/COM Redirection](https://docs.microsoft.com/en-us/windows/win32/sbscs/dll-com-redirection-on-windows), but we've never tried it and we don't know whether system debugging components would function correctly when loaded in this manner. Sorry!

If you do decide to give it a try, please post your results!

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you additional thoughts on this topic. Thanks!
