### ISSUE TITLE
Setting to Ignore Missing Methods / Properties?

### ISSUE THREAD

**Issue by ooikengsiang** [microsoft/ClearScript#191]
I try to search around but cannot find any answer.
Is there any setting I can use to ignore mkssing methods / properties when executing JavaScript that accessing .NET object passed using AddHostObject?
Expecting to skip that line and continue execute the next line inside JavaScript.
Or is there any other way I can work around this to achieve the same result?
Thank you.

**Comment by ClearScriptLib** [comment]
Hi @ooikengsiang,

First, you'll have to define your desired behavior precisely, as "skip that line" can be ambiguous. For example, should the following code invoke `doSomething` or `doSomethingElse`? 

``` JavaScript
// JavaScript
if (!obj.MethodThatDoesNotExist()) {
    doSomething();
} else {
    doSomethingElse();
}
```

Please tell us exactly how you'd like invocation of nonexistent members to behave.

Thanks!

**Comment by ooikengsiang** [comment]
Thanks for the reply.
You have a good point, I never really think too hard about this.
I probably expect it to return a default value / null if something happen.
Thanks.

**Comment by ClearScriptLib** [comment]
Hi @ooikengsiang,

If you're using V8, you can wrap an object with a [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) and override any of its behaviors. Beyond that, it's difficult to make recommendations without knowing your exact requirements.

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts on this topic. Thanks!
