### ISSUE TITLE
[NuGet] referenced project doesn't have output files

### ISSUE THREAD

**Issue by cilerler** [microsoft/ClearScript#192]
I have a .NetFramework4.8 project with **PackageReference** setup *(let's call it **MyLibrary**)* that uses ClearScript NuGet package. And that project becomes another NuGet package where you may find the NuSpec file below.

I created another .NetFramework4.8 console app *(let's say **MyService**)* and installed **MyLibrary** as NuGet package. When I build the app, it doesn't copy the files in here https://github.com/microsoft/ClearScript/blob/ee1a5e3ad53594b732479b2e9855b2cc6c7b81f2/NuGet/files/build/net45/Microsoft.ClearScript.targets#L4-L34

***Side note;** if I add the ClearScript library as a top-level library into the project, it copies.  So it seems like a NuGet issue. However, I wanted to point it in case you may have an idea of what can be done not to need to install it as top-level on the MyService.*

## NuSpec file

```xml
<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://schemas.microsoft.com/packaging/2013/05/nuspec.xsd">
  <metadata>
    <id>LibraryId</id>
    <version>1.0.0</version>
    <authors>Developer</authors>
    <owners>Company</owners>
    <requireLicenseAcceptance>false</requireLicenseAcceptance>
    <description>Package Description</description>
    <repository type="git" url="https://github.com/cilerler/fake.git" />
    <dependencies>
      <group targetFramework=".NETFramework4.8">
        <dependency id="Microsoft.ClearScript" version="6.0.2" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Logging.Abstractions" version="3.1.5" exclude="Build,Analyzers" />
        <dependency id="Microsoft.Extensions.Primitives" version="3.1.5" exclude="Build,Analyzers" />
        <dependency id="Microsoft.NETCore.Platforms" version="3.1.1" exclude="Build,Analyzers" />
        <dependency id="NETStandard.Library" version="2.0.3" exclude="Build,Analyzers" />
        <dependency id="Newtonsoft.Json" version="12.0.3" exclude="Build,Analyzers" />
        <dependency id="System.Buffers" version="4.5.1" exclude="Build,Analyzers" />
        <dependency id="System.ComponentModel" version="4.3.0" exclude="Build,Analyzers" />
        <dependency id="System.Memory" version="4.5.4" exclude="Build,Analyzers" />
        <dependency id="System.Numerics.Vectors" version="4.5.0" exclude="Build,Analyzers" />
      </group>
    </dependencies>
    <frameworkAssemblies>
      <frameworkAssembly assemblyName="Microsoft.CSharp" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="mscorlib" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Core" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Data.DataSetExtensions" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Data" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Net.Http" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Numerics" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Xml" targetFramework=".NETFramework4.8" />
      <frameworkAssembly assemblyName="System.Xml.Linq" targetFramework=".NETFramework4.8" />
    </frameworkAssemblies>
    <contentFiles>
      <files include="any/net48/MyFile.txt" buildAction="Content" />
    </contentFiles>
  </metadata>
</package>
```

**Comment by ClearScriptLib** [comment]
Hi @cilerler,

Unfortunately we aren't aware of a better or more correct way to ensure that ClearScript's auxiliary assemblies are copied to the output directory.

BTW, have you tried including the Build tag with your ClearScript dependency? For example:

``` XML
<dependency id="Microsoft.ClearScript" version="6.0.2" include="Build" exclude="Analyzers" />
```

Good luck!

**Comment by cilerler** [comment]
Thank you for the quick response as usual.
Unfortunately, I have no control over NuSpec file, any idea what should I write below to get that output? *(it generates it via NuGet.Build.Tasks.Pack)*

```
    <PackageReference Include="Microsoft.ClearScript">
      <Version>6.0.2</Version>
    </PackageReference>
```

**Comment by ClearScriptLib** [comment]
Perhaps something like this:

``` XML
<PackageReference Include="Microsoft.ClearScript" Version="6.0.2">
    <PrivateAssets>contentFiles;analyzers</PrivateAssets>
</PackageReference>
```

This removes Build from the list of private assets, which _should_ cause it to flow to parent projects, unless the asset defaults have changed since the [documentation](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) was written.

Cheers!

**Comment by cilerler** [comment]
Thank you very much!

![bitmoji](https://sdk.bitmoji.com/render/panel/ed5c9c0f-c444-4b15-b96b-a66885184e6a-1d989a62-ae8a-48a8-b04f-0f575358153a-v1.png?transparent=1&palette=1&width=246)
