### ISSUE TITLE
How can I implement call, bind & apply methods on hostDelegate

### ISSUE THREAD

**Issue by mithrey** [microsoft/ClearScript#195]
Hello. I have some C# functions that return the C# List. The list is mimicking javaScript array with all its methods. 

```
// C# code
public class myclass{
   public JSList<int> func => new JSList<int>(1)
}

public class JSList<T> : List<T>
{
   public int push(params dynamic[] elements)
   { 
      // do somethin;
   }
}

```

Also, I have JS function that tries to execute push method with apply(). I cannot modify JS code, but I can append some functions. Is there any way i can implement call, bind & apply methods? 

```
//JS Code
let myclass = new myclass();
let someObject = myclass.func();
someObject.push.apply([1,2,3], [4,5,6])
```

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @mithrey,

A couple of questions:
- In your JavaScript code above, should that be `myclass.func.push.apply([1,2,3], [4,5,6])`? Please clarify what `myclass` is on the JavaScript side.
- The first argument to [`apply`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply) is the `this` object, for which you're passing `[1,2,3]`. Does that mean that you expect your `push` function to work on normal JavaScript arrays as well as C# lists?

Thanks!

**Comment by mithrey** [comment]
- `myclass` is C# class(line 2). I'm using `AddHostType` on C# side.  ps: i've modified JS code.
- This is just simplified example. In my case `push` works on C# hostObjects as well as on JS objects. But i need it to work with `apply`, `bind`, `call` methods.
Thank you!

**Comment by mithrey** [comment]
It worked for me! Such a simple solution. Thank you again!
