### ISSUE TITLE
Cannot load V8 interface assembly, An attempt was made to load a program with an incorrect format. (0x8007000B)

### ISSUE THREAD

**Issue by martysupple** [microsoft/ClearScript#197]
It looks like there have been other bugs associated to the ClearScript V8 Native library load. The particular issue I ran into is when using ASP.Net Core 3.1 hosted in IIS on premise Windows. By default the least priv app pool ldentity (say IIS AppPool\DefaultAppPool) will not have "File Create" permissions on the AppDomain.CurrentDomain.BaseDirectory folder. When the V8 Proxy tries to extract the ijwhost.dll into this folder it fails with access denied, but the poor exception handling returns the error above; which is VERY misleading. At a minimum I would recommend catching the access denied on file create of IJWhost.dll or better yet just bundle this dll for .Net Core projects (if possible). My workaround was to just bundle the ijwhost.dll with my deployment.

**Comment by ClearScriptLib** [comment]
Hi @martysupple,

Thanks for reporting this.

ClearScript uses `CurrentDomain.BaseDirectory` only if it can't write to the local app data folder. That was added to support the default app pool identity on Azure, where we've tested this path successfully. If the default app pool identity can't write to either folder on IIS, a special case may be necessary. We'll take a look.

As for ijwhost.dll, ClearScript has always tried to support simple deployment with all its files in the same folder. Unfortunately we can't put the 32-bit and 64-bit versions of ijwhost.dll in the same folder, as both must have that exact name. The current solution is clumsy, but it works in most cases. Hopefully we can find a better one in the future.

Thanks again!

**Comment by ClearScriptLib** [comment]
Hi @martysupple,

>As for ijwhost.dll, ClearScript has always tried to support simple deployment with all its files in the same folder. Unfortunately we can't put the 32-bit and 64-bit versions of ijwhost.dll in the same folder, as both must have that exact name. The current solution is clumsy, but it works in most cases. Hopefully we can find a better one in the future.

Our next release will eliminate ijwhost.dll altogether. Thanks again for reporting this issue!

**Comment by ClearScriptLib** [comment]
[ClearScript 7.0 RC](https://github.com/microsoft/ClearScript/releases/tag/7.0.0-rc) eliminates ijwhost.dll. Please reopen this issue if you encounter additional problems.
