### ISSUE TITLE
heads up VS Code

### ISSUE THREAD

**Issue by flat-eric147** [microsoft/ClearScript#199]
Hi, some recent update in Visual Studio Code now requires to add

"debug.javascript.usePreview": false

to the setting.json to make remote debugging work properly. Perhaps something to add in 
https://microsoft.github.io/ClearScript/Details/Build.html

**Comment by ClearScriptLib** [comment]
Thanks @flat-eric147, we'll take a look.

**Comment by ClearScriptLib** [comment]
[ClearScript 7.0 RC](https://github.com/microsoft/ClearScript/releases/tag/7.0.0-rc) mentions this issue in the debugging documentation. Thanks again!
