### ISSUE TITLE
NuGet has outdated version of ClearScript.V8

### ISSUE THREAD

**Issue by Muchaszewski** [Microsoft/ClearScript#20]
Can you update version of ClearScript.V8 on NuGet platform? Current latest avaviable is 5.4.9

**Comment by Taritsyn** [comment]
@Muchaszewski [ClearScript.V8](https://www.nuget.org/packages/ClearScript.V8/) is an unofficial package. There is no official package from Microsoft yet. Everybody builds the assemblies from the source code.

There is even a [discussion on this topic](https://github.com/Microsoft/ClearScript/issues/5).

**Comment by Muchaszewski** [comment]
Ok thanks. Would be nice to have one though.
