### ISSUE TITLE
ES7 and above javascript support question

### ISSUE THREAD

**Issue by r4nc1d** [microsoft/ClearScript#200]
@ClearScriptLib above you mentioned that " [V8 supports ES7 and beyond.](https://github.com/microsoft/ClearScript/issues/167)" when i try to run the following code.

```
 engine.Evaluate(@"async function process1(data) {
                                return { xValue: 'asdasd' };
                            }");

var toReturn = engine.Script.process1(data);
```
I get the following error "no further information on this object could be discovered"

If i remove the async then it works fine, but having said that async is an ES7 feature

**Comment by ClearScriptLib** [comment]
Hi @r4nc1d,

We can't reproduce this issue with the code you provided above, having tried several dissimilar argument types for `data`.

Did you leave something out?

Thanks!

**Comment by r4nc1d** [comment]
The data parameter needed really, if i take it out it does not make a difference.
I created a small example of exactly what i am doing with the error below.

```
using (var engine1 = new V8ScriptEngine())
{
	engine1.Evaluate(@"async function process1() {
					return { xValue: 'asdasd' };
				}");

	var toReturn = engine1.Script.process1();
        var value = toReturn.xValue; // added this line after i have taken the screenshot. but its just to show how i would try and retrieve the value
}
```

![image](https://user-images.githubusercontent.com/5917232/90645655-85419300-e236-11ea-8295-bf00b560c8eb.png)

**Comment by ClearScriptLib** [comment]
It looks like the code executed successfully, but the debugger couldn't fully inspect the resulting script object. That's probably just fine. Does the debugger let you continue?

**Comment by r4nc1d** [comment]
It did complete yes...but if you actually look at the result from the script it should have returned the object.
Do you agree var value = toReturn.xValue; should have returned **asdasd**

![image](https://user-images.githubusercontent.com/5917232/90661727-cee6a980-e247-11ea-866a-e1e8b9e0caf5.png)

If you run my exact script does it work for you?

**Comment by ClearScriptLib** [comment]
Hi @r4nc1d,

>Do you agree var value = toReturn.xValue; should have returned **asdasd**

Because `process1` is an [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), it returns a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise). To retrieve the async return value, you must use a method such as [`then`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then). Here's how you might do it from C#:

``` C#
var ev = new ManualResetEvent(false);
toReturn.then(new Action<dynamic>(value => {
    Console.WriteLine(value.xValue);
    ev.Set();
}));
ev.WaitOne();
```

In async context you could also [convert](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_JavaScript_JavaScriptExtensions_ToTask.htm) the promise into a .NET [task](https://docs.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) and use `await`.

Good luck!

**Comment by r4nc1d** [comment]
Great stuff the above works!! if i want to convert it to the .NET task will it look like the below

```
 using(var engine1 = new V8ScriptEngine()) {

   engine1.AddHostType(typeof(JavaScriptExtensions));
   engine1.Evaluate(@"async function process1() { return { xValue: 'asdasd'};}");

   var toReturn = await engine1.Script.process1().ToTask();
   Console.WriteLine(toReturn xValue);
 }
```

**Comment by ClearScriptLib** [comment]
A couple of minor tweaks:
- You don't have to expose `JavaScriptExtensions` since you're only using it in managed code.
- You need to declare `toReturn` as `dynamic` to enable script property retrieval via the dot operator.

Here's the working code:

``` C#
using (var engine1 = new V8ScriptEngine()) {
    engine1.Evaluate(@"async function process1() { return { xValue: 'asdasd'};}");
    dynamic toReturn = await engine1.Evaluate("process1();").ToTask();
    Console.WriteLine(toReturn.xValue);
}
```

Cheers!

**Comment by r4nc1d** [comment]
This is exactly what i wanted, thanks
