### ISSUE TITLE
How to validate dynamic result

### ISSUE THREAD

**Issue by r4nc1d** [microsoft/ClearScript#201]
How can i validate the dynamic object result.

```
dynamic result = await this.engine.Evaluate("process(" + data + ");").ToTask();
return new ExportResult
{
     type = result.type,
     output = result.output,
     options = result.options
};

```

So if i want to validate that the options object has the property **filename** i have to-do the following check

```
if (this.options.Equals(Microsoft.ClearScript.Undefined.Value) || this.options.filename.Equals(Microsoft.ClearScript.Undefined.Value) || string.IsNullOrEmpty(this.options.filename))
            {
                ......
            }
```

Is this the correct way of checking? 

I am using `Microsoft.ClearScript.Undefined.Value` to check if the object us undefined if i just use s`tring.IsNullOrEmpty`
the whole condition falls over.

The reason i am asking is because the option object can have multiple properties and i cant think that i will have to evaluate all of the properties like this.

**Comment by ClearScriptLib** [comment]
Hi @r4nc1d,

>Is this the correct way of checking?

It should work, although `if (result.foo is Undefined) {...}` might be a bit more readable.

Also, if performance is a concern, try to minimize your use of the `dynamic` infrastructure. One way is to use the [`ScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptObject.htm) class to interact with script objects:

``` C#
var result = engine.Evaluate(someCode);
if (result is ScriptObject scriptObject) {
    if (scriptObject.PropertyNames.Contains("foo")) {
        Console.WriteLine(scriptObject.GetProperty("foo"));
    }
}
```

Good luck!

**Comment by r4nc1d** [comment]
Thanks this will work for me. 👍
