### ISSUE TITLE
Solution cannot be compiled:

### ISSUE THREAD

**Issue by SamOxigen** [microsoft/ClearScript#203]
Number of dll files are missing from ...\ClearScript\V8\V8\lib\ folder

**Comment by ClearScriptLib** [comment]
Hi @SamOxigen,

Most likely you're trying to build the full ClearScript solution without first having run the V8Update script to download and build V8. Please see Section III in [this document](https://microsoft.github.io/ClearScript/Details/Build.html) for complete build instructions.

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you encounter additional issues building ClearScript. Thanks!
