### ISSUE TITLE
[Feature Request] win-arm64 support

### ISSUE THREAD

**Issue by Tlaster** [microsoft/ClearScript#206]
I can get tested v8 arm64 compiled by adding arm64 target in V8Update.cmd without any problem, but I've not tested it yet, maybe it can support win-arm64 without any modification?
I can create a PR if needed.

**Comment by ClearScriptLib** [comment]
Hi @Tlaster,

Are you looking for native support for Surface Pro X?

Thanks!

**Comment by Tlaster** [comment]
Yes, I'm trying to get ClearScriptV8 compiled with arm64 target.

**Comment by ClearScriptLib** [comment]
The next ClearScript release will have win-arm64 support.

**Comment by deandob** [comment]
Hi, any ETA on linux arm64?

**Comment by ClearScriptLib** [comment]
The next release will have linux-arm64 support as well. It should be out later this month. We’re just waiting for V8 8.8 to stabilize.

**Comment by ClearScriptLib** [comment]
We've posted [ClearScript 7.1](https://github.com/microsoft/ClearScript/releases/tag/7.1.0).
