### ISSUE TITLE
[Question] V8 version

### ISSUE THREAD

**Issue by andreespirela** [microsoft/ClearScript#212]
Hello, I'd like to know what version of V8 is being used by ClearScript.

**Comment by ClearScriptLib** [comment]
Hi @andreespirela,

Have a look at the [Releases](https://github.com/microsoft/ClearScript/releases) page. At the bottom of the notes for each release there's a "Tested with V8 x.y.z.w" line that specifies the V8 version. If there's no such line, the release uses the same version as the previous release.

Good luck!
