### ISSUE TITLE
Manipulating script-defined classes

### ISSUE THREAD

**Issue by Longwelwind** [microsoft/ClearScript#214]
Hi,

I've been fiddling with this awesome library and have been able to quickly setup user-scripting in my software. Though, one of the thing that I've failed to achieve is to instantiate and manipulate script-defined classes. Basically, what I'd like to do is this:

```csharp
var engine = new V8ScriptEngine();
var scriptDefinedClass = engine.Evaluate(new DocumentInfo { Category = ModuleCategory.Standard}, @"
  export default class Test {
    foo() {
      return 'bar';
    }
  }
")

var scriptDefinedClassInstance = scriptDefinedClass.Instantiate();
Console.WriteLine(scriptDefinedClassInstance.foo());
```

Is it possible to achieve the same flow that I've described? Or are there limitations that prevents me from doing that?

Thanks in advance!

**Comment by ClearScriptLib** [comment]
Hi @Longwelwind,

A standard module's exports are only accessible via [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import). However, like any script document, a module can return a _result_ when its top-level code is executed.

In your case, the module's only top-level code is an [`export`](https://developer.mozilla.org/en-US/docs/web/javascript/reference/statements/export) statement, which returns no result, so the value assigned to `scriptDefinedClass` is [`undefined`](https://developer.mozilla.org/en-US/docs/Glossary/undefined). To return a different result, simply evaluate the desired expression at the end of your module's top-level code:

``` C#
var scriptDefinedClass = engine.Evaluate(new DocumentInfo { Category = ModuleCategory.Standard}, @"
    export default class Test {
        foo() {
            return 'bar';
        }
    }
    Test;
");
```

This doesn't interfere with the module's exports. Note that, if the module is developed externally and you don't wish to modify it, you can use another module to import whatever you need and return it as shown above.

Once your C# variable is holding a JavaScript class, you can instantiate it as follows:

``` C#
dynamic scriptDefinedClassInstance = ((ScriptObject)scriptDefinedClass).Invoke(asConstructor: true);
Console.WriteLine(scriptDefinedClassInstance.foo());
```

Good luck!

**Comment by Longwelwind** [comment]
Makes sense, thanks a lot!
