### ISSUE TITLE
Exit vbscript halfway?

### ISSUE THREAD

**Issue by bmaster001** [microsoft/ClearScript#218]
I'm creating a tool that we can use to make/queue/run all kinds of maintenance-style scripts. Using ClearScript we could make those scripts in VBScript, which is pretty cool. But sometimes if a specific condition exists halfway a script, it's necessary to exit. In 'normal' vbscript you can use something like "Wscript.Quit", but this does not work in ClearScript. Is there another way to accomplish this? I know that we could use if-then statements to check if the rest of the code should be executed, but sometimes a simple "exit" is just way easier... Thanks!

**Comment by ClearScriptLib** [comment]
Hi @bmaster001,

You can use an exception for this purpose. Here's a sample extension class that provides an `ExecuteWithQuit` method:

``` C#
public static class ScriptEngineExtensions {
    public static bool ExecuteWithQuit(this ScriptEngine engine, string code) {
        engine.Script.Quit = new Action(() => throw new QuitException());
        try {
            engine.Execute(code);
            return true;
        }
        catch (ScriptEngineException exception) {
            if (exception.GetBaseException() is QuitException)
                return false;
            throw;
        }
        finally {
            engine.Script.Quit = Undefined.Value;
        }
    }
    private class QuitException : Exception { }
}
```

And here's how you might use it:

``` C#
engine.AddHostType(typeof(Console));
engine.ExecuteWithQuit(@"
    Console.WriteLine(""This should be printed."")
    Quit()
    Console.WriteLine(""This should not be printed."")
");
```

Good luck!

**Comment by bmaster001** [comment]
That works perfectly, thanks a lot for the example!
