### ISSUE TITLE
Question SQL

### ISSUE THREAD

**Issue by flat-eric147** [microsoft/ClearScript#222]
Hi! I am a bit lost on what can be done through this line (using V8 engine!):

engine.AddHostObject("xHost", new ExtendedHostFunctions());

What .net types can I instantiate with this? Just system types? When I use 
xHost.type('System.Collections.Generic.List") or xHost.type('System.DayOfWeek') it works just fine, but when I want to do more complex things, like open a sql connection using
xHost.type('System.Data.SqlClient')
I get "Could not find a specific type or generic type definition for 'System.Data.SqlClient'".
So what are the limitations in the use of ExtendedHostFunctions. Is there a way to make those things available in ClearScript without explicitly adding them with AddHostType ?

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @flat-eric147,

>What .net types can I instantiate with this? Just system types?

The [`ExtendedHostFunctions.type(String, Object[])`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ExtendedHostFunctions_type.htm) method is based on [`Type.GetType(String)`](https://docs.microsoft.com/en-us/dotnet/api/system.type.gettype?view=net-5.0#System_Type_GetType_System_String_), but because it's limited to namespace-qualified type names, it can only import types from core libraries such as **mscorlib** or **System.Private.CoreLib**.

>Is there a way to make those things available in ClearScript without explicitly adding them with AddHostType ?

The host can expose any algorithm to the script engine, including algorithms for importing types. Here's a trivial example:

``` C#
engine.Script.getType = new Func<string, object>(name => {
    switch (name) {
        case "System.Data.SqlClient.SqlConnection":
            return typeof(SqlConnection).ToHostType();
        // ...
    }
    return null;
});

engine.Execute(@"
    var SqlConnection = getType('System.Data.SqlClient.SqlConnection');
    var connection = new SqlConnection();
    // ...
");
```

Of course, if you really wish to give scripts the ability to import arbitrary types by name, a simple `switch` statement is probably impractical, but hopefully it gives you an idea of what's possible.

Good luck!

**Comment by flat-eric147** [comment]
Brilliant hint! So I added to your sample an assembly parameter, a potential user can lookup type and assembly and with that, use getType(sting  assembly, string type). 

The JavaScript code could look like:

   var connetionString;
   var SqlConnection = getType('System.Data.SqlClient', 'System.Data.SqlClient.SqlConnection');
   connetionString = "Data Source=WIN-50GP30FGO75;Initial Catalog=Demodb;User ID=sa;Password=demol23";
   cnn = new SqlConnection(connetionString);
   cnn.Open();
   MessageBox.Show("Connection Open  !");
   cnn.Close();

(sample taken and adapted from https://www.guru99.com/c-sharp-access-database.html)

I just wonder if the respective assembly/dll needs to be somehow linked to the application or if it's sufficient to be present on the target system. If no explicit linking is necessary, this means we have almost the same power as VBScript's "CreateObject" (?)

Thanks for your valuable input!

**Comment by ClearScriptLib** [comment]
Hi @flat-eric147,

>So I added to your sample an assembly parameter, a potential user can lookup type and assembly and with that, use getType(sting assembly, string type).

ClearScript provides [`ExtendedHostFunctions.type(String, String, Object[])`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ExtendedHostFunctions_type_1.htm), which takes an assembly name. This method also supports generic types.

>I just wonder if the respective assembly/dll needs to be somehow linked to the application or if it's sufficient to be present on the target system.

That depends. If the assembly isn't already in memory, the CLR must be able to locate it on the local system, so unless it's installed as part of the CLR, it must be deployed with your application.

Note that the set of preinstalled assemblies, the assembly names, and the rules by which assemblies are located depend on the CLR you're using. For example, `SqlConnection` is in the **System.Data** assembly preinstalled with .NET Framework, but the same class on .NET Core is in **System.Data.SqlClient** and must be pulled in via a package reference.

Cheers!

**Comment by flat-eric147** [comment]
Thank you very much, it's clear to me now.
