### ISSUE TITLE
Usage of VBScriptEnginee

### ISSUE THREAD

**Issue by Narasimhara** [microsoft/ClearScript#225]
Hi All,

Could you please let me know how to use VBSctiptEnginee and it is throwing error MsgBox is not defined as well. Could you please let me know examples for using it

**Comment by ClearScriptLib** [comment]
Hello @Narasimhara,

Here's a simple example of `VBScriptEngine` usage:

``` C#
using (var engine = new VBScriptEngine()) {
    engine.AddHostType(typeof(Console));
    engine.Execute("Console.WriteLine(\"Hello, world!\")");
}
```

For `MsgBox` to work, you need to provide an implementation of [`IHostWindow`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_IHostWindow.htm). Here's a minimal example:

``` C#
internal class MyHostWindow : IHostWindow {
    public IntPtr OwnerHandle => IntPtr.Zero;
    public void EnableModeless(bool enable) {}
}
```

And then:

``` C#
using (var engine = new VBScriptEngine { HostWindow = new MyHostWindow() }) {
    Console.WriteLine(engine.Evaluate("MsgBox(\"Are you OK?\", vbQuestion + vbYesNo, \"Hello, world!\") = vbYes"));
}
```

Good luck!

**Comment by Narasimhara** [comment]
Thanks so much ..

**Comment by Narasimhara** [comment]
I have one more doubt ..in old VBScript we have dao databases concepts in the VBScript File.

with the new code can we initialize Dao engine. Any possibility of doing that?

**Comment by ClearScriptLib** [comment]
>with the new code can we initialize Dao engine. Any possibility of doing that?

You can use VBScript's [`CreateObject`](https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/dcw63t7z(v=vs.84)) function to instantiate any installed ActiveX class. Here's a simple example:

``` C#
using (var engine = new VBScriptEngine()) {
    engine.AddHostType(typeof(Console));
    engine.Execute(@"
        set dbe = CreateObject(""DAO.DBEngine.120"")
        Console.WriteLine(dbe.Version)
    ");
}
```

Cheers!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or concerns. Thank you!
