### ISSUE TITLE
Launch on the ARM platform

### ISSUE THREAD

**Issue by dalekseev-monokot** [microsoft/ClearScript#230]
Hello Team,

Is it possible to use the library on a 32-bit ARM platform? If so, where can I get the necessary native dependencies?

Thanks.

**Comment by ClearScriptLib** [comment]
@dalekseev-monokot You're asking about Linux, right?

**Comment by dalekseev-monokot** [comment]
@ClearScriptLib Yes, that's right. Trying to figure out if I can use your library on a 32-bit Raspbian OS.

**Comment by ClearScriptLib** [comment]
@dalekseev-monokot Barring any unexpected issues, we'll include 32-bit Linux ARM support in the next ClearScript release, which should coincide with the stable release of V8 8.9 in a few weeks.

**Comment by ClearScriptLib** [comment]
[Version 7.1.1](https://github.com/microsoft/ClearScript/releases/tag/7.1.1) includes support for Linux on 32-bit ARM hardware.
