### ISSUE TITLE
Cannot load V8 interface assembly v8-zlib-x64.dll

### ISSUE THREAD

**Issue by jack-weakley** [microsoft/ClearScript#232]
I am updating my teams' projects that reference the deprecated nuget package ClearScript.V8 version [5.4.3](https://www.nuget.org/packages/ClearScript.V8/5.4.3) to the signed composite package version [6.0.2](https://www.nuget.org/packages/Microsoft.ClearScript/6.0.2). I am unable to use the V8 component package as my team is running an outdated nuget version.

When trying to build, I am given the following error message across 4 of the 15 projects being built that reference ClearScript:

```
Attempt: [2], 60 of 548 tests failed.
Microsoft.Online.Monitor.Common.UnitTest.Utilities.MetricsComposerTests.MetricsComposer_ScalingFactor
Test method Microsoft.Online.Monitor.Common.UnitTest.Utilities.MetricsComposerTests.MetricsComposer_ScalingFactor threw exception: 
System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Cannot load V8 interface assembly. Load failure information for v8-zlib-x64.dll:
d:\dbs\sh\acem\0223_104742\cmd\o\qtest2\TestResults\Deploy_CBA-0223_104742 2021-02-23 10_53_59\Out\v8-zlib-x64.dll: The specified module could not be found
C:\windows\system32\v8-zlib-x64.dll: The specified module could not be found
    at Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary(String baseFileName)
   at Microsoft.ClearScript.V8.V8Proxy.LoadAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.GetAssembly()
   at Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)
   at Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)
```

For context, I updated about 15 projects, and only 4 are failing, all with the above error message. These projects rely on corext to import nuget packages using a nuget feed. The ClearScript package is referenced in the csproj files as follows:

Old:

```
  <Reference Include="ClearScript">
      <SpecificVersion>False</SpecificVersion>
      **<HintPath>$(PkgClearScript_V8)\lib\net40\ClearScript.dll</HintPath>**
  </Reference>

...

  <ItemGroup>
    <Robocopy Include="$(PkgClearScript_V8)\tools\native\x86">
      <DestinationFolder>$(TargetDir)</DestinationFolder>
      <VerifyExists>True</VerifyExists>
      <IsRecursive>False</IsRecursive>
    </Robocopy>
    <Robocopy Include="$(PkgClearScript_V8)\tools\native\amd64">
      <DestinationFolder>$(TargetDir)</DestinationFolder>
      <VerifyExists>True</VerifyExists>
      <IsRecursive>True</IsRecursive>
    </Robocopy>
  </ItemGroup>
```

New:

```
<Reference Include="ClearScript">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>$(PkgMicrosoft_ClearScript)\lib\net45\ClearScript.dll</HintPath>
</Reference>

...

  <ItemGroup>
    <Robocopy Include="$(PkgMicrosoft_ClearScript)\v8">
      <DestinationFolder>$(TargetDir)</DestinationFolder>
      <VerifyExists>True</VerifyExists>
      <IsRecursive>False</IsRecursive>
    </Robocopy>
    <Robocopy Include="$(PkgMicrosoft_ClearScript)\v8\net45">
      <DestinationFolder>$(TargetDir)</DestinationFolder>
      <VerifyExists>True</VerifyExists>
      <IsRecursive>True</IsRecursive>
    </Robocopy>
    <Robocopy Include="$(PkgMicrosoft_ClearScript)\lib\net45">
      <DestinationFolder>$(TargetDir)</DestinationFolder>
      <VerifyExists>True</VerifyExists>
      <IsRecursive>True</IsRecursive>
    </Robocopy>
  </ItemGroup>
```

The way the various projects reference clearscript is identical so it is unclear why it is failing for some and not for others.

Am I incorrectly referencing the composite package, or is there any packages that I am missing to allow the builds to complete successfully?

**Comment by ClearScriptLib** [comment]
Hi @jack-weakley,

>When trying to build, I am given the following error message across 4 of the 15 projects being built that reference ClearScript:

Just to be clear, you're seeing these errors during the build? Not during a test run? Or do your tests run as part of your build?

>The ClearScript package is referenced in the csproj files as follows:

Hmm; it looks like you've aligned your Robocopy elements with the newer ClearScript package layout, so your issue isn't immediately obvious. The error message lists the location from which ClearScript attempted to load the assembly (in this case it's d:\dbs\sh\acem\0223_104742\cmd\o\qtest2\TestResults\Deploy_CBA-0223_104742 2021-02-23 10_53_59\Out\v8-zlib-x64.dll). Can you check whether the assembly exists at that location?

Thanks!

**Comment by jack-weakley** [comment]
Hi, I have solved the above issue (issue with our test configurations) - but am no experiencing a very similar issue but with the v8-x64.dll

I am receiving the following error message:

EvaluateCombination exception: Microsoft.Online.Monitor.Common.Exceptions.MonitorServiceException: customMonitorExecution ---> System.TypeLoadException: Cannot load V8 interface assembly. Load failure information for v8-x64.dll:
C:\WFRoot\Monitor.1\Fabric\work\Applications\MonitorActorApp_App106\MonitorActor.Code.2021.302.1736.0-e35f3a91b53\v8-x64.dll: The specified module could not be found
D:\Windows\system32\v8-x64.dll: The specified module could not be found

I have verified that the v8-x64.dll is present at C:\WFRoot\Monitor.1\Fabric\work\Applications\MonitorActorApp_App106\MonitorActor.Code.2021.302.1736.0-e35f3a91b53\

**Comment by ClearScriptLib** [comment]
Hi @jack-weakley,

Is the new issue occurring on a machine without Visual Studio – e.g., a deployment server?

Thanks!

**Comment by jack-weakley** [comment]
yes

**Comment by ClearScriptLib** [comment]
@jack-weakley Please make sure you have the latest Visual C++ redistributables installed on the target machine:

- https://aka.ms/vs/16/release/vc_redist.x86.exe
- https://aka.ms/vs/16/release/vc_redist.x64.exe

Cheers!

**Comment by jack-weakley** [comment]
This was the answer
