### ISSUE TITLE
[V8] Catching import errors

### ISSUE THREAD

**Issue by PaulFreund** [microsoft/ClearScript#233]
First let me start by thanking you for this library and the extensive support you provide here.

I started porting a library that uses ESM and while it seems to work in general I was not able to find a way to catch loading errors. Currently I am using Procmon to find resolution failures but I would like to catch this in my code.

I currently use this loader code:

```C#
                engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging | V8ScriptEngineFlags.EnableDynamicModuleImports, 9222);
                engine.AddHostType("Console", typeof(Console));
                engine.DocumentSettings.SearchPath += (location + "\\src\\;");
                engine.DocumentSettings.AccessFlags = DocumentAccessFlags.EnableAllLoading;

                engine.Evaluate(@"
                     globalThis.console = {
                         log: function(msg) {
                             Console.WriteLine('{0}', msg);
                         },
                         err: function(msg) {
                             Console.WriteLine('{0}', msg);
                         }
                     };

                     try {
                         import('atum.mjs');
                     }
                     catch(err) {
                         console.log('[JS][Ex] ' + err);
                     }
                 ");
            }
            catch (Exception ex) {
                System.Console.WriteLine("Script exception: " + ex.ToString());
            }
```

And while it seems to work in general I don't get an error if a file in the import chain is not found. Did I miss anything?

**Comment by ClearScriptLib** [comment]
Hi @PaulFreund,

[Dynamic imports](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) are asynchronous, so errors are reported via the [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) rejection mechanism:

``` JavaScript
import('atum.mjs').then(
    result => console.log('[JS] import succeeded ' + result),
    err => console.log('[JS][Ex] ' + err)
);
```

You can however use `try`/`catch` in an asynchronous context:

``` JavaScript
async function doImport(name) {
    try {
        result = await import(name);
    }
    catch (err) {
        console.log('[JS][Ex] ' + err);
    }
}
```

Good luck!

**Comment by PaulFreund** [comment]
Thank you very much, I tried something similar but it didn't work:

```js
async function loader() {
    await import('./main.mjs');
}

try {
    loader();
}
catch(err) {
    console.log('[JS][Ex] ' + err);
}
```

which didn't work. I expected this to have the same outcome but seems I was wrong for the first async function
