### ISSUE TITLE
MSBuild does not deploy native ClearScriptV8.win-x86.dll 

### ISSUE THREAD

**Issue by pretzelfisch** [microsoft/ClearScript#236]
When we add ClearScript 7.1 via nuget to our asp web api project.  A visual studio build for our developer moves all files correctly to the bin directory.  However our build serer using msbuild is missing 
ClearScriptV8.ICU.dat
ClearScriptV8.win-x64.dll
ClearScriptV8.win-x86.dll 
from the bin directory.  The nuget restore works but the dlls do not copy into our project.

**Comment by ClearScriptLib** [comment]
Hi @pretzelfisch,

Can you tell us anything about your build server setup and/or share a minimal repro case?

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you can provide more information. Thanks!
