### ISSUE TITLE
setTimeout not found error

### ISSUE THREAD

**Issue by PeterViau** [microsoft/ClearScript#238]
I use a WPF TextBox to run Javascript code with Clearscript, however there are some javascript features I can't get to work like a call to setTimeout gives me "setTimeout is not defined"

what Addhosttype and addhostobject do I need to add to allow settimeout to work?

**Comment by ClearScriptLib** [comment]
Hello @PeterViau,

The [`setTimeout`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout) method isn't a JavaScript feature; it's part of the Web API framework provided by web browsers. However, implementing `setTimeout` with ClearScript is relatively simple. See issue #205 for an example.

Good luck!

**Comment by PeterViau** [comment]
That works, thanks!

Is it possible to reference Web API framework ?

**Comment by ClearScriptLib** [comment]
>Is it possible to reference Web API framework ?

ClearScript aims to make it easy to consume any .NET or JavaScript API, but as you can see, the [Web API set](https://developer.mozilla.org/en-US/docs/Web/API) is very large and constantly evolving, so full implementations are few in number and cumbersome to use outside the browser.

Some available implementations:
- [jsdom](https://github.com/jsdom/jsdom) – an implementation written in pure JavaScript. This is designed for Node.js, so integrating it into a ClearScript application may not be trivial.
- [CEFSharp](https://cefsharp.github.io/) – A .NET version of [Chromium Embedded Framework](https://bitbucket.org/chromiumembedded/cef/src/master/) that should be fairly complete, but we haven't experimented with it.

Cheers!

**Comment by PeterViau** [comment]
Thanks, I'll have a look at CEFSharp
