### ISSUE TITLE
Syntax-check a script without executing it?

### ISSUE THREAD

**Issue by bmaster001** [microsoft/ClearScript#244]
I use the VBScriptEngine to execute some nightly maintenance-scripts. Some scripts are somewhat difficult to run during the day for testing-purposes (like rebooting a server for example). Sometimes I make small changes to such a script, and cannot test it. But when I make stupid syntax errors (like forgetting a quote or a bracket), the script fails during the nightly-run. 

So, is there a way to parse a script without really running it (basically do a syntax-check) ?

EDIT: I found a workaround using the "quit" command I added a while ago (see https://github.com/microsoft/ClearScript/issues/218): it's possible to syntax check if you add the "quit" command before the first script-line and then execute it. However, I have the feeling that there must be a better way to syntax-check a script :-)

**Comment by ClearScriptLib** [comment]
Hi @bmaster001,

Unfortunately we are not aware of any way to check VBScript code for syntax errors without executing it. The Windows Script API doesn't seem to expose that capability.

Sorry!

**Comment by bmaster001** [comment]
Ok thanks, I'll have to keep using my workaround then!
