### ISSUE TITLE
Support ValueTask<T> and Promise marshalling

### ISSUE THREAD

**Issue by phosphene47** [microsoft/ClearScript#248]
It would be convenient if ClearScript could automatically marshal `ValueTask<T>` types to `Promise` and back when `V8ScriptEngineFlags.EnableTaskPromiseConversion` flag is set.

At the moment, methods that return `ValueTask<T>` can be awaited like this in JavaScript:

```js
await stream.ReadAsync(memory).AsTask();
```

(Or so I *think*, though I haven't tested it yet.)

It should theoretically work because `AsTask()` returns a regular `Task<T>` which ClearScript should recognize and marshal to promise.

With this proposal, ClearScript might also be able to apply performance optimizations by unwrapping directly into `Promise.resolve(ValueTask<T>.Result)` when the task synchronously completes, skipping `AsTask()` wrapping altogether.

**Comment by ClearScriptLib** [comment]
Hi @phosphene47,

That's a very interesting proposal. If we understand correctly, it would work as follows (pseudocode):

```
if valueTask has completed
    convert valueTask directly to a resolved or rejected promise
else
    convert valueTask.AsTask() to a promise as before
```

Is that correct? Also:

1. How does your proposal affect the reverse (promise-to-task) conversion?
2. How should the non-generic ValueTask behave?

Thanks!

**Comment by phosphene47** [comment]
Yes, that pseudocode looks correct.

> How should the non-generic ValueTask behave?

Non-generic `ValueTask` results should be treated as undefined. It should follow the same behavior as non-generic `Task`s.

> How does your proposal affect the reverse (promise-to-task) conversion?

Here is a little more detailed pseudocode I came up with.

When JS calls host async method:

1. Library invokes said method and receives return value `v`
2. Switch on `v`
   1. `Task` or `Task<T>`, return a promise wrapping `v`
   2. `ValueTask` or `ValueTask<T>`, switch
      1. `IsCompleted`, return `Promise.resolve` with `v.Result`
      2. `IsCanceled` or `IsFaulted`, return `Promise.reject` with `v.Exception`
      3. otherwise, return a promise wrapping `v.AsTask()`

In other words, both types of tasks are marshaled to `Promise` as a result, but it is possible for ClearScript to apply an optimization for `ValueTask<T>` because they may completely synchronously and resolve the result immediately. This allows ClearScript to skip layer of indirection that comes with wrapping `Task<T>` to `Promise`, instead directly returning an already resolved or rejected promise instance.

The performance increase is probably trivial, but the idea seems simple enough.

On the other hand, when host calls JS async func:

1. Library invokes said func and receives return value `v`
2. Switch on `v`
   1. `Promise`, return a regular task wrapping `v`

Tasks returned from an async JS function will always be `Task<T>`, because there is no information to distinguish `Task<T>` and `ValueTask<T>` solely from a `Promise` instance.

To sum up:

- `Task`, `ValueTask` => `Promise` resolving undefined
- `Task<T>`, `ValueTask<T>` => `Promise` resolving `T`
- `Promise` resolving undefined => `Task`
- `Promise` resolving `T` => `Task<T>`

Do you think this is feasible? Please correct me if anything above seems wrong!

**Comment by ClearScriptLib** [comment]
Hello @phosphene47,

The host-to-script conversion should be possible as described above, and we'll look into it for the next release. However:

>* `Promise` resolving `undefined` => `Task`
>* `Promise` resolving `T` => Task<T>

JavaScript promises are all of the same "type", so ClearScript converts them all to `Task<object>`. It might be possible to leverage `ValueTask<object>` in this direction, but it would be of questionable benefit, since the host would have to detect the type, or provide overloads, to deal with both types.

Cheers!

**Comment by ClearScriptLib** [comment]
[Version 7.1.2](https://github.com/microsoft/ClearScript/releases/tag/7.1.2) adds optional `ValueTask` conversion. Thanks for suggesting it!
