### ISSUE TITLE
Studio Code Debugging with UNC-Paths 

### ISSUE THREAD

**Issue by OuterHeaven07** [microsoft/ClearScript#249]
Hi, 

I am writing an application in C# that communicates and remotely controls a 3D CAD software. 

Now I currently ran into a problem by debugging a JS script, because apparently the breakpoints in the Studio Code Debugger does not work with UNC paths. 

example: 

```
> engine = new V8ScriptEngine("JS_NX_ScriptingHost", 8ScriptEngineFlags.EnableDebugging, 9222);
> engine.DocumentSettings.AccessFlags = DocumentAccessFlags.EnableFileLoading;

// all breakpoints are skipped in Studio Code
engine.ExecuteDocument(@"\\demchtcvs707n.gplm.com\iecad\CAD\application\scripts\MAIN.js);

// this works fine since I have connected 
// the server : \\demchtcvs707n.gplm.com\iecad\CAD
// as a network drive P
engine.ExecuteDocument(@"P:\application\scripts\MAIN.js");
```
The launch.json is set according to the default 
![image](https://user-images.githubusercontent.com/82034502/113710853-83a0de80-96e4-11eb-8d49-bf162f9dee45.png)

In both cases the debugger is active, only when executing a UNC path all breakpoints are skipped

![image](https://user-images.githubusercontent.com/82034502/113711179-ec885680-96e4-11eb-9d3b-3221d3e54996.png)

I am currently using ClearScript V7.1.0

Thank You 

Cheers Gregor

**Comment by ClearScriptLib** [comment]
Hi @OuterHeaven07,

We've confirmed that VSCode doesn't reactivate breakpoints in scripts loaded via URL or UNC path. Unfortunately this behavior isn't under ClearScript's control. We'll follow up internally with the VSCode team.

In the meantime, if this issue makes it difficult for you to debug your script, consider temporarily specifying [`V8ScriptEngineFlags.AwaitDebuggerAndPauseOnStart`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngineFlags.htm) to break into the debugger before any script code is executed. Another option might be to use Chrome's DevTools debugger, as it appears to behave as you expect.

Good luck!

**Comment by OuterHeaven07** [comment]
Hi @ClearScriptLib, 

thank you for the information. Basically, I'm getting ahead for now. 
Maybe the function will be added by VSCode team. 
Thanks
