### ISSUE TITLE
Cannot execute Javascript Callback inside of a Host Type

### ISSUE THREAD

**Issue by FeliaDev** [microsoft/ClearScript#256]
Buenas,

I'm trying to execute a Javascript Callback but it never execute and also the execution keeps eternally and never continue.
I've the following code:
```csharp
public class MyHostType 
{
     private dynamic JSCallback;
     public MyHostType(dynamic jscall){
            JSCallback = jscall
     }
     public string Execute(){
          JSCallback("A Test");
          return "A Test";
     }
}
```
In JS code I create an instance of "MyHostType", passing as an argument the callback, but when the "Execute" method is called the execution of the program stuck on JSCallback and never continues.

There's something I doing wrong or is a not possible way to execute JS Callbacks?

Gracias y Saludos.

**Comment by ClearScriptLib** [comment]
Hi @FeliaDev,

ClearScript does support calling JavaScript functions directly from the host. For example, we tested the following code with your class and encountered no issues:

``` C#
engine.AddHostType(typeof(Console));
var jscall = engine.Evaluate("(function (arg) { Console.WriteLine(arg); })");
new MyHostType(jscall).Execute();
```

>when the "Execute" method is called the execution of the program stuck on JSCallback and never continues

Is it possible that you're calling `Execute` while the script engine is busy on another thread? That would explain the hang.

Thanks!

**Comment by FeliaDev** [comment]
You save my life!!!. Graciela amego.
"script engine is busy on another thread" <- That was the problem. 
I'm using a while loop inside my JS code and the thread busy for that. The solution was change that while loop to another thread inside the HostType. 
Thank you!.
