### ISSUE TITLE
JavaScript Async Iteration Protocols from IAsyncEnumerable<T>

### ISSUE THREAD

**Issue by tangkhaiphuong-colpal** [microsoft/ClearScript#259]
Are there any way to marshal IAsyncEnumerable<T> to Symbol.asyncIterator in JavaScript. Does ClearScript support marshal automatically.

See: (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator)? Is there a best practice to achieve this?

**Comment by ClearScriptLib** [comment]
Hi @tangkhaiphuong-colpal,

Unfortunately ClearScript does not yet support JavaScript's async iteration protocol, so you'll have to interact with the `IAsyncEnumerable` interface directly in script code.

Suppose you have a class like this:

``` C#
public static class Thing {
    public static async IAsyncEnumerable<string> GetItems() {
        await Task.Delay(100);
        yield return "foo";
        await Task.Delay(100);
        yield return "bar";
        await Task.Delay(100);
        yield return "baz";
    }
}
```

You can use a JavaScript async generator to convert the `IAsyncEnumerable` to an object suitable for `for await...of` consumption. ClearScript's support for task-promise interop simplifies this considerably (requires ClearScript 7.1.2):

``` C#
using (var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableTaskPromiseConversion | V8ScriptEngineFlags.EnableValueTaskPromiseConversion)) {
    engine.AddHostType(typeof(Thing));
    engine.AddHostType(typeof(Console));
    engine.Script.Done = new ManualResetEvent(false);
    engine.Execute(@"
        async function* toAsyncIterable(enumerable) {
            const enumerator = enumerable.GetAsyncEnumerator();
            while (await enumerator.MoveNextAsync()) {
                yield enumerator.Current;
            }
        }
        (async function test() {
            for await (const item of toAsyncIterable(Thing.GetItems())) {
                Console.WriteLine(item);
            }
            Done.Set();
        })();
    ");
    engine.Script.Done.WaitOne();
}
```

We should be able to provide transparent `IAsyncEnumerable` support in an upcoming release.

Thanks!

**Comment by ClearScriptLib** [comment]
[Version 7.1.3](https://github.com/microsoft/ClearScript/releases/tag/7.1.3) supports async enumeration/iteration interop.
