### ISSUE TITLE
Provide ClearScript binaries

### ISSUE THREAD

**Issue by Bizarrus** [Microsoft/ClearScript#26]
Please!

**Comment by Markipelago** [comment]
Title really should be "new provide V8 assemblies" or something of the like.  That's what I've been trying to do to use this release, and it isn't going well.  Not with MinGW, not with Cygwin.  It's been rough :/

**Comment by ClearScriptLib** [comment]
@Markipelago How are you building V8? Have you tried the procedure outline [here](https://microsoft.github.io/ClearScript/Details/Build.html)? It requires neither of those environments.

**Comment by SimonCropp** [comment]
While not ideal, you could extract the binaries from here https://www.nuget.org/packages/ClearScript.V8/

**Comment by sgwong** [comment]
I just build the V8 and ClearScript following the instruction on Windows 10 with VS2017 community edition. It works fine and I was able to build the V8 binary and clearscript except the V8 build show git rebase error message which I have no idea but it seems to be succeed at the end. I suggest to close this issue.

**Comment by Bizarrus** [comment]
But when you can build successfull, why you don't provide the binarys here? Add Attachements. You suggest to close that, but i'm not.

**Comment by ClearScriptLib** [comment]
We've posted an official [NuGet package](https://www.nuget.org/packages/Microsoft.ClearScript/) for Version 5.5.3.

**Comment by SimonCropp** [comment]
Just closing the loop here. I have deprecated https://www.nuget.org/packages/ClearScript.V8/ and am pointing people to use https://www.nuget.org/packages/Microsoft.ClearScript/ instead.
