### ISSUE TITLE
debugging and code editing

### ISSUE THREAD

**Issue by flat-eric147** [microsoft/ClearScript#260]
I frequently use the Visual Studio Code remote debugging functionality in conjunction with ClearScript's V8 engine, which works great! I just wonder what it would take to also be able to modify the code inside Visual Studio Code on the fly? It would be so handy as you get autocompletion, syntax highlighting etc and all that for free. BTW, on the application side I use AvalonEdit for editing/writing the code. I don't know if the websocket debugging protocol even allows to send over the modified code, so just asking :-p

**Comment by ClearScriptLib** [comment]
Hi @flat-eric147,

For V8 debugging, the host (ClearScript in this case) is only responsible for sending and receiving messages to and from the debugger. It is not – and as far as we know, it cannot be – involved in any other way.

We just did some script debugging in ClearScript using Chrome DevTools (in Microsoft Edge 😉) and were able to edit scripts on the fly without problems. In fact, the modified scripts persisted even after we detached the debugger.

Could your issue be specific to Visual Studio Code? Could you give DevTools a try?

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts or findings. Thank you!

**Comment by flat-eric147** [comment]
Hello and thank you for your reply! I am not quite sure how you achieved that. I connected to my host through the DevTools (tried both chrome and edge), set a breakpoint and modified the code in DevTools, but as expected the new code is not executed. When the debugger hits the breakpoint again, a different tab opens with the original code. Any specific settings I forgot? I'm also not sure how the eventually modified code can be read back into my host application. The ScriptEngine class dos not appear to have getter methods to retrieve the code in execution.

**Comment by flat-eric147** [comment]
Hello and thank you for your reply! I am not quite sure how you achieved that. I connected to my host through the DevTools (tried both chrome and edge), set a breakpoint and modified the code in DevTools, but as expected the new code is not executed. When the debugger hits the breakpoint again, a different tab opens with the original code. Any specific settings I forgot? I'm also not sure how the eventually modified code can be read back into my host application. The ScriptEngine class dos not appear to have getter methods to retrieve the code in execution.
