### ISSUE TITLE
How to cache imported modules from remote sites

### ISSUE THREAD

**Issue by faramos** [microsoft/ClearScript#264]
I´m using a common module across different engine instances by adding it using:

`engine.DocumentSettings.AddSystemDocument()`

Into the common system document lines, I have some imports from https://unpkg.com/

Like:

`import myPkg from 'https://unpkg.com/my-pkg@0.3.0/dist/my-pkg.esm.js';`

Everything works fine, but I did notice that the engine dumps the package every time an engine is used, with a significant performance penalty.

Is it possible to keep these files in cache?

Thanks in advance.

**Comment by ClearScriptLib** [comment]
Hi @faramos!

ClearScript's default document loader maintains a cache – essentially a [`Uri`](https://docs.microsoft.com/en-us/dotnet/api/system.uri)-to-[`Document`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Document.htm) dictionary – that holds raw document content across engine instances.

Therefore, unless we're missing something, you probably don't need to use `AddSystemDocument`. Simply enable document downloads via [`DocumentAccessFlags.EnableWebLoading`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_DocumentAccessFlags.htm).

However, ClearScript has no _persistent_ document cache; that is, it doesn't have one that holds document content across process lifetimes. Is that what you're looking for?

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or thoughts on this topic. Thank you!
