### ISSUE TITLE
Multi-threaded callbacks not working

### ISSUE THREAD

**Issue by jduncalf** [Microsoft/ClearScript#27]
Hi all, have tried to use V8 javascript and Clearscript 5.4.10 to script TPL System.Threading.Tasks.Parallel.ForEach() however the calls never complete and seem blocked within the engine.

Any ideas?

**Comment by ClearScriptLib** [comment]
Hi @jduncalf,

A V8 runtime cannot execute JavaScript code on multiple threads simultaneously. Although `Parallel.ForEach` invokes callbacks concurrently, each callback must wait for the script engine to free up. But since the script engine is running `Parallel.ForEach`, which returns only when all callbacks have terminated, you get deadlock.

The only way to run JavaScript code on multiple threads simultaneously is to use multiple V8 runtimes. Here's an example that uses `Parallel.ForEach`:

``` C#
using (var master = new V8ScriptEngine())
{
    var lib = new HostTypeCollection("mscorlib", "System.Core");
    master.AddHostObject("lib", HostItemFlags.GlobalMembers, lib);

    var workers = new V8ScriptEngine[Environment.ProcessorCount];
    for (var i = 0; i < workers.Length; ++i) {
        workers[i] = new V8ScriptEngine();
        workers[i].AddHostObject("lib", HostItemFlags.GlobalMembers, lib);
        workers[i].Execute(@"
            function body(item) {
                System.Console.WriteLine(item);
            }
        ");
    }

    Action<int, ParallelLoopState, long> dispatch = (item, state, index) => {
        workers[index % workers.Length].Script.body(item);
    };

    master.Script.dispatch = dispatch;
    master.Execute(@"
        var items = System.Linq.Enumerable.Range(0, 100);
        System.Threading.Tasks.Parallel.ForEach(items, dispatch);
    ");

    Array.ForEach(workers, worker => worker.Dispose());
}
```

Good luck!

**Comment by jduncalf** [comment]
Excellent answer, thanks very much.

Late last night I had moved the actual System.Threading.Tasks.Parallel.ForEach() call to a C#/.Net thread by invoking a helper function exposed by my wrapper app which executed the call on a worker thread, so that the deadlock is avoided, even though it was difficult to code a solution that allowed me to determine that the ForEach had completed without causing further deadlocks. And I now understand that I wasn't achieving true concurrency anyway.

I'll continue working with your solution plus i'll try the VB ClearScript engine to see if I get concurrency there.

Thanks again for your assistance.

**Comment by ClearScriptLib** [comment]
@jduncalf It seems like you're working on an interesting project! Please let us know if you encounter additional issues.

Note however that the classic Windows script engines (VBScript and JScript) are even less concurrency-friendly than V8. They have _thread affinity_; that is, each instance can only run script code on the thread that created it.

That makes these script engines difficult to use in a thread-pooled environment. Not only must you create multiple worker instances as in the example above, but you must also manage a dedicated thread for each instance, and marshal each invocation from the thread pool to the appropriate thread. The [`Dispatcher`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_Windows_WindowsScriptEngine_Dispatcher.htm) object can assist with that.

Thanks!

**Comment by jduncalf** [comment]
Hi, I was just about to leave a comment to say i've just tried the parallel ForEach with VB and discovered the thread affinity deadlocks. Think i'll continue working with the multiple javascript V8 engine instance example you posted.

Thanks again for your assistance.
