### ISSUE TITLE
Update Nuget to 5.5 please!!

### ISSUE THREAD

**Issue by joaodotneto** [Microsoft/ClearScript#28]
Please guys, i want to use the 5.5 in my projects but i use Nuget to keep updated.
Thanks in advance!

**Comment by ClearScriptLib** [comment]
@joaodotneto We don't provide ClearScript binaries (see Issue #26). In the meantime, consider contacting the owners of the NuGet package you're using.

**Comment by joaodotneto** [comment]
oh my, i believe you are the owners.
Thanks for the extreme fast answer!
