### ISSUE TITLE
Provide custom serializer for objects from Host?

### ISSUE THREAD

**Issue by makotech222** [microsoft/ClearScript#283]
Hi I am new to Clearscript. I'm using the V8 engine to run some code from a js file in my c# environment. I have a tricky situation with the following pseudocode:

c#:
```
class MyObject{
    [javascriptVar("value")]
    public int Value {get;set;} = 5;
}
class Host{
    public MyObject Get(){ 
        return new MyObject() // Need to serialize properties different, using javascriptVar attribute as property name.
    }
}
_v8.AddHostObject("host", new Host())
```

JS:

```
    let a = host.Get()
    console.log(a.value) // Undefined, needs to be a.Value
```

Essentially, my JS expects an instance of MyObject with properties matching the 'javascriptVar' attribute, rather than the actual C# property name(Basically, needs camel case rather than pascal case). In my current setup, I can't modify the JS code to accommodate this; I have to provide it properly from the C# side.

My initial question is, can I provide a customer Serializer for Clearscript (preferable use System.Text.Json) to serialize the object with the proper property names? Or is there some other way to provide the object? I can obviously make a copy of the MyObject class with property names in camel case, which would technically work, but I really want to avoid that if possible, since my C# depends on the PascalCase property names.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @makotech222,

>My initial question is, can I provide a customer Serializer for Clearscript (preferable use System.Text.Json) to serialize the object with the proper property names?

A clarification might be helpful here. When you expose a host object via `AddHostObject` or some other means, the object you provide is _marshaled_ to the script environment, not serialized. That is, the script code receives a proxy that allows it to access the original .NET object, not a JSON copy of it.

If a JSON copy of your object is what you want, you can use any .NET-based JSON serializer; e.g., [Json.NET](https://www.newtonsoft.com/json).

If on the other hand you wish to provide access to the original host object but with one or more members renamed, you can do that with ClearScript's [`ScriptMemberAttribute`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptMemberAttribute.htm). Here's an example:

``` C#
public class MyObject {
    [ScriptMember("value")]
    public int Value { get; set; } = 5;
}
```

And then:

``` C#
engine.AddHostObject("myObj", new MyObject());
Console.WriteLine(engine.Evaluate("myObj.value"));
```

Please let us know if you have additional questions.

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you additional questions or comments on this topic. Thank you!
