### ISSUE TITLE
How to debug JScriptEngine / VBScriptEngine?

### ISSUE THREAD

**Issue by joaodotneto** [Microsoft/ClearScript#29]
I found docs only for V8, ok. But how to debug JScriptEngine and VBScriptEngine?

Thanks in advance.

**Comment by ClearScriptLib** [comment]
Hi @joaodotneto,

You can use Visual Studio to debug script code running in Windows script engines.

First, enable debugging by passing [`WindowsScriptEngineFlags.EnableDebugging`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_WindowsScriptEngineFlags.htm) to the `JScriptEngine` or `VBScriptEngine` constructor.

Once your program is running, use the procedure outlined [here](https://msdn.microsoft.com/en-us/library/bb385613.aspx) to attach Visual Studio's script debugger. You'll then see your script documents in Solution Explorer. You can open them, set breakpoints, etc.

Good luck!

**Comment by joaodotneto** [comment]
Man, thanks a lot for this!
Extremely fast again!
