### ISSUE TITLE
Is there a more efficient way to transfer data into the Javascript context besides JSON?

### ISSUE THREAD

**Issue by cchapin89** [microsoft/ClearScript#292]
I believe a similar question has been asked before, but I am trying to transfer a large multi-dimensional array of doubles from my host context into the V8 JavaScript context. So far I have found that the only somewhat reasonable solution is to convert the entire thing into a JSON string and then JSON.parse it in JavaScript. This solution is still extremely slow compared to a solution where we use the V8 C++ API's to construct the arrays. 

I have considered using the ITypedArray interface to construct the arrays, but even that I have found to be slower than JSON. Also, since I have an array of arrays, the ITypedArray interface won't help as I'll still need to cross the JS/.NET boundary many times to construct the array of arrays. 

Does ClearScript expose any way to quickly construct native V8 objects or is this a technical limitation of using this component? 

Thanks, any suggestions are appreciated.

**Comment by cchapin89** [comment]
I'm doing some tests where I write the entire multi dimensional array into a single Float64Array and use the ITypedArray interface to pass to the JS context, then split it up into individual arrays on the JS side. This might be the best approach.

**Comment by ClearScriptLib** [comment]
Hi @cchapin89,

>I'm doing some tests where I write the entire multi dimensional array into a single Float64Array and use the ITypedArray interface to pass to the JS context, then split it up into individual arrays on the JS side. This might be the best approach.

Yes, that would be our recommendation – copy the multidimensional array into a flat `double[]`, then use [`ITypedArray<double>.Write`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_JavaScript_ITypedArray_1_Write.htm) to blast the data into a JavaScript array.

Note also that you can do the "splitting" on the script side without copying data – by using the [`Float64Array` constructor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array/Float64Array) that lets the array be a view onto a portion of the flat array's memory buffer.

Thanks, and good luck!
