### ISSUE TITLE
EnableTopLevelAwait with Modules doesn't throw Exceptions on error in script.

### ISSUE THREAD

**Issue by midnightnoon** [microsoft/ClearScript#293]
There doesn't seem to be a way to get an Exception thrown for the missing "zzz" function while EnableTopLevelAwait is enabled.

```
V8Settings.EnableTopLevelAwait = true;
V8ScriptEngine v8 = new V8ScriptEngine();
DocumentInfo di = new DocumentInfo();
di.Category = ModuleCategory.Standard;
v8.Execute(di, "zzz()");
```

Tested on 7.1.6 and 7.1.7.

**Comment by ClearScriptLib** [comment]
Hi @midnightnoon,

When Top-Level Await is enabled, code at the outermost scope of a JavaScript module behaves as an [async function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function), reporting errors via the [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) rejection mechanism.

Here's one way to catch such an error in C#:

``` C#
try {
    v8.Evaluate(di, "zzz()").ToTask().Wait();
}
catch (Exception exception) {
    Console.WriteLine(exception.GetBaseException().Message); // prints "ReferenceError: zzz is not defined"
}
```

Good luck!

**Comment by midnightnoon** [comment]
Thank you, that works.

As a side note, what's the best documentation resource for ClearScript?  The [reference website](https://microsoft.github.io/ClearScript/Reference/html/R_Project_Reference.htm)  only has terse descriptions of what things do but no general guides as to what they are or how to use them.   It appears the only way to learn what each setting does is to go through the source code. For example, there is no good source for what these are or how they are used: AccessContext, ExtensionMethods, SystemDocuments?

Instead of answers to the specific items listed above, I just want to make sure I'm not missing out on some better documentation somewhere.  If all that is available at the moment is the sparse reference site and the examples that don't provide any help beyond "hello world" then I guess I'll continue methodically going through each class, method, and property in the source code to figure this whole project out.

Thanks in advance!

**Comment by ClearScriptLib** [comment]
Hi @midnightnoon,

>As a side note, what's the best documentation resource for ClearScript?

We provide a [tutorial](https://microsoft.github.io/ClearScript/Tutorial/FAQtorial.html), [sample code](https://microsoft.github.io/ClearScript/Examples/Examples.html), and [API reference](https://microsoft.github.io/ClearScript/Reference/html/R_Project_Reference.htm). The tutorial is relatively old but still covers the basics, though it predates some major facilities such as document loading and module support. You can also search, browse, or augment our [Issues](https://github.com/microsoft/ClearScript/issues) and [Discussions](https://github.com/microsoft/ClearScript/discussions) areas if you have specific questions, to which we try to respond quickly, and often with example code.

>The [reference website](https://microsoft.github.io/ClearScript/Reference/html/R_Project_Reference.htm) only has terse descriptions of what things do but no general guides as to what they are or how to use them.

If and when you have a chance, please let us know what specific improvements you'd like to see in our documentation. We've tried to make it clear and unambiguous, but yes, many of its descriptions are brief. Early in the project we included code samples for most API elements, but we haven't kept that up as the project expanded and the API grew. Things are more stable now, so documentation is something to which we might be able to allocate more resources in the near future.

>It appears the only way to learn what each setting does is to go through the source code.

Yes, when all else fails, the source code is the ultimate reference. We believe however that the combination of a tutorial and an API reference _can_ be good enough for most applications. Please let us know how to improve ours.

Thank you!
