### ISSUE TITLE
Expectations to expose the V8 snapshot API?

### ISSUE THREAD

**Issue by andrea-s** [Microsoft/ClearScript#3]
Hello! I hope this is the right plage to open discussions related to the library - same as we did on CodePlex. I apologize in advance if it's not the right place.

As of 5.4.9 you guys have been using the V8 snapshot functionality to improve engine start-up times. Do you have any plans to expose the same functionality to the .NET layer, thus allowing users to build their own snapshotted versions of engines and do the same?

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @andrea-s,

We don't have plans to expose V8 snapshot capabilities via the ClearScript API.

For one thing, for this feature to be truly useful in ClearScript, it would need the ability to snapshot arbitrary managed objects and types, and that isn't possible as far as we know.

Also, as ClearScript aims to support multiple script engines, our goal has always been to keep engine-specific APIs to a minimum.

For accelerating the re-execution of common script code, consider using V8 code caching (see [here](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_Compile_2.htm) and [here](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_Compile_1.htm)).

Thank you!
