### ISSUE TITLE
Is there an option to timeout `AwaitDebuggerAndPauseOnStart`?

### ISSUE THREAD

**Issue by KurtGokhan** [microsoft/ClearScript#309]
Users can accidentally turn on `AwaitDebuggerAndPauseOnStart` and if they are unable to open a debugger, it will block the process forever. Is there a way to stop awaiting if no debugger has connected after a certain timeout? Alternatively, is there a way to stop awaiting manually from another thread?

**Comment by ClearScriptLib** [comment]
[ClearScript 7.2](https://github.com/microsoft/ClearScript/releases/tag/7.2.0) added [`V8ScriptEngine.CancelAwaitDebugger`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_V8_V8ScriptEngine_CancelAwaitDebugger.htm).
