### ISSUE TITLE
Add special handling for shared array buffers and views

### ISSUE THREAD

**Issue by ClearScriptLib** [microsoft/ClearScript#317]
Hi @nextfool,

As you point out, `SharedArrayBuffer` is a standard JavaScript built-in, and V8 has supported it for a while now.

However, ClearScript currently provides no _special treatment_ for `SharedArrayBuffer` objects. That is, a `SharedArrayBuffer` is a script object like any other. You can pass it to the host, invoke its members from .NET, etc. The host can pass it to another script engine, but as with any foreign script object, the result is a doubly-marshaled reference – a proxy to a proxy – that goes through the host for all member access.

Exposing foreign script objects isn't something we recommend. In addition to overhead, deadlock becomes a point of concern, as each script engine has its own internal mutex. Furthermore, proxying a `SharedArrayBuffer` in this manner is particularly pointless, as you couldn't use the resulting reference to construct a `TypedArray` or `DataView`.

>If there is any way which allows me to get the "value of the pointer", so I can pass this "pointer" to the code in a worker

No. A `SharedArrayBuffer`'s backing store isn't accessible from JavaScript or C#, nor is there any way to construct a new `SharedArrayBuffer` on top of an existing backing store. That can only be done via V8's native C++ embedding API.

To support your scenario, ClearScript needs an enhancement whereby exposing a foreign `SharedArrayBuffer` has the expected behavior – both engines get local script objects that share a backing store. This should also work for shared `TypedArray` and `DataView` objects, as that would agree with Chromium behavior.

Thank you very much for making us aware of this issue!

_Originally posted by @ClearScriptLib in https://github.com/microsoft/ClearScript/discussions/316#discussioncomment-1620249_

**Comment by nextfool** [comment]
Hi @ClearScriptLib ,

Thanks for the support. I suppose this new "foreign SharedArrayBuffer" will also support all those builtin  "atomics" operations?

**Comment by ClearScriptLib** [comment]
Hi @nextfool,

>I suppose this new "foreign SharedArrayBuffer" will also support all those builtin "atomics" operations?

It'll be a standard `SharedArrayBuffer` with all its normal functionality. We'll just be changing the way ClearScript marshals these objects from one script engine to another.

Cheers!

**Comment by ClearScriptLib** [comment]
[ClearScript 7.2](https://github.com/microsoft/ClearScript/releases/tag/7.2.0) added this enhancement.
