### ISSUE TITLE
Implementing a custom module loader

### ISSUE THREAD

**Issue by andreespirela** [microsoft/ClearScript#319]
How can I implement a custom module loader ?

**Comment by nextfool** [comment]
Hi @andreespirela ,

You can create a subclass of "DocumentLoader", inside the subclass, you can override the "LoadDocumentAsync" method. Then you can pass your own "LoadCallback" as well as "ContextCallback" so that you have the full control of how the new loaded module behavies. 

Chears.

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions on this topic. Thanks!
