### ISSUE TITLE
After update to 5.5.0 "v8-base-ia32.dll" cannot be loaded.

### ISSUE THREAD

**Issue by HSyr** [Microsoft/ClearScript#32]
I got the following exception after I update my projects ClearScript.V8 version 5.5.0.

`Cannot load V8 interface assembly. Load failure information for v8-base-ia32.dll`

When I return back to the version 5.4.9 the applications run fine.

**Comment by ClearScriptLib** [comment]
Hi @HSyr,

The `v8-base-ia32.dll` and `v8-base-x64.dll` assemblies are new in ClearScript 5.5 and must be deployed with your application. This is mentioned in the [release notes](https://github.com/Microsoft/ClearScript/releases/tag/5.5.0) and the [build/deployment guide](https://microsoft.github.io/ClearScript/Details/Build.html).

If you're using a NuGet package and believe that it's missing these assemblies, consider contacting the package owners.

Good luck!

**Comment by HSyr** [comment]
Yes, I am using NuGet package. I will try to contact the owner.
