### ISSUE TITLE
V8 stringify the result of Evaluate(code)

### ISSUE THREAD

**Issue by gjvdkamp** [microsoft/ClearScript#329]
Hi, 

When I Evaluate code I get back an object, but that does not have a name itself. If there any way to stringify the result of Evaluate from within the V8 engine? 

Right now I use 
```
object res = engine.Evaluate(code);
var jt = JToken.FromObject(res);
```

But this has the issue that undefined values in res get replaced with empty objects {} in jt everywhere. Also wrapping the object in a JObject would create a lot of round trips between the host and the script engine for large reply objects. 

So I have two reasons to want to get that values out as a string, and I would also like to keep Evaluate to have the user code behave like a query expression instead of statements. 

I tried 
`var s = res.ToString();`
But that only returns "Microsoft.ClearScript.V8.V8ScriptItem"

Any ideas?

**Comment by gjvdkamp** [comment]
Never mind figured it out already: 
`var s = engine.Script.JSON.stringify(res);`

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or comments on this topic. Thank you!
