### ISSUE TITLE
Some host resources are proxied to V8 as immutable prototype exotics

### ISSUE THREAD

**Issue by ClearScriptLib** [microsoft/ClearScript#330]
That includes host types, delegates, and possibly others. ClearScript hijacks the rarely used immutable prototype attribute for use as a directive to its patched implementation of the `typeof` operator.

**Comment by simontom** [comment]
Might be interesting to have an Attribute to make (custom) host immutable if needed

**Comment by ClearScriptLib** [comment]
Hi @simontom,

>Might be interesting to have an Attribute to make (custom) host immutable if needed

V8 provides no API for toggling the immutability of an object's prototype. An immutable prototype exotic object can only be created from a special _object template_ – a V8-specific API concept.

It's certainly doable, but we'd have to add significant new engine-specific APIs – something we usually avoid unless the use case is particularly compelling.

Cheers!

**Comment by ClearScriptLib** [comment]
[Version 7.2.1](https://github.com/microsoft/ClearScript/releases/tag/7.2.1) eliminated host proxies implemented as immutable prototype exotics.
