### ISSUE TITLE
Any demo code on how to communicate through Inspector Protocol? 

### ISSUE THREAD

**Issue by gjvdkamp** [microsoft/ClearScript#332]
Hi, 

Does anyone know of some example code on how to interact with the V8 engine through the Inspector Prototcol? I would like be able to get a dump of variables to help write and debug code. Right now I look at the engine.Script global object, but to see variables that way I need to declare them as var which becomes messy pretty quickly. 

For now I'd like to get out let and const variables from the Script object. 

I'd tried looking through issues here and the VS Source but couldn't find anything I could port to Clearscipt/ C# does anyone here have something to get me started? 

Thanks, GJ

**Comment by ClearScriptLib** [comment]
Hi @gjvdkamp,

Why not use a debugger such as Visual Studio Code or Chrome/Edge DevTools? Both support the Inspector protocol.

Thanks!

**Comment by gjvdkamp** [comment]
I'll look into that, but if possible I'd like to put that into the app itself.. You haven't come across any code that does this?

**Comment by ClearScriptLib** [comment]
>I'll look into that, but if possible I'd like to put that into the app itself.. You haven't come across any code that does this?

Unfortunately, no, but Chromium and Visual Studio Code are both open-source projects, so their code could be helpful.

Good luck!

**Comment by gjvdkamp** [comment]
Ok will look into it.
