### ISSUE TITLE
"Icu Error" in string.localCompare in 7.1.7

### ISSUE THREAD

**Issue by balsamiqLuca** [microsoft/ClearScript#334]
Hi,
we updated ClearScript in our application (netCore 3.1) from from 6.0.2 to 7.1.7 and some of our customers started having this crash: 
`RangeError: Internal error. Icu error` 
in a localCompare() between two strings:
`string1.localCompare(string2)`

I see that the file _ClearScriptV8.ICU.dat_ is deployed along with the ClearScript dlls, although we did not reference the _Microsoft.ClearScript.V8.ICUData_ nuget package directly.

Is this a known issue? Would updating to 7.2.0 fix the problem?

Thanks

**Comment by ClearScriptLib** [comment]
Hi @balsamiqLuca,

Support for the JavaScript Internationalization API was added in ClearScript 7.1. Before that it's unlikely that the `localeCompare` method worked correctly.

We cannot reproduce any issue with `localeCompare` when the .dat file is deployed with the application. We see that exact `RangeError` when it isn't.

Please verify that the .dat file is there. If it is, and you can reproduce the problem, please let us know what strings (and other arguments, if applicable) are triggering the crash (if you can share them, of course).

Thanks!

**Comment by balsamiqLuca** [comment]
Hi, thanks for the reply!
I see that if I remove the .dat file I have that same error too.
So maybe these customers for some reason don't have it in their installation folder...
I think we can close the issue until I have some more info.
Thanks

**Comment by balsamiqLuca** [comment]
Despite the fact that the `ClearScriptV8.ICU.dat` file was present we were having lots of crashes from lots of customers with different languages.

**Comment by ClearScriptLib** [comment]
Hi @balsamiqLuca,

Sorry to hear that. Please reopen this issue if you find a way to reproduce the problem.

Thanks!
