### ISSUE TITLE
Support for .NET 6? 

### ISSUE THREAD

**Issue by dalibor-florian** [microsoft/ClearScript#341]
Hi, is there any plan for official support of .NET 6.0?
In README of your project you mentioned only these versions of .net ( .NET 5.0, .NET Core 3.1, .NET Framework 4.5, and .NET Standard 2.1.). 
Is there any problem with retargeting to .NET 6?

**Comment by ClearScriptLib** [comment]
Hi @dalibor-florian,

ClearScript does support .NET 6.0. It doesn't _target_ .NET 6.0 because it doesn't use any 6.0-specific platform features.

Thanks!

**Comment by dalibor-florian** [comment]
Thanks for response.  Would it be possible to change it in readme?
Currently there is info 'Support for .NET 5.0', i found it a bit confusing if you are saying that ClearScript supports also .NET 6.0.

**Comment by ClearScriptLib** [comment]
Hi @dalibor-florian,

We've changed the text to: _Support for .NET 5.0+, .NET Framework 4.5+, .NET Core 3.1, and .NET Standard 2.1._

Thank you!
