### ISSUE TITLE
.NET local tool that using the ClearScript.V8 library quietly crashes on macOS 12.1

### ISSUE THREAD

**Issue by Taritsyn** [microsoft/ClearScript#343]
Hello!

Initially, [this error](https://github.com/Taritsyn/DartSassHost/issues/4) was discovered by [Sergey Zwezdin](https://github.com/sergeyzwezdin). By many characteristics, this error is very similar to [another issue](https://github.com/microsoft/ClearScript/issues/318) registered in this repository.

This error occurs in macOS 12.1 not only on ARM64 processors, but also on x64 processor architecture. In the case of x64 processor architecture, this error occurs only if the [.NET 6.0.101 SDK](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/sdk-6.0.101-macos-x64-installer) was installed cleanly (without additional runtimes and other SDKs).

In order for you to reproduce this error, I created a [sample project](https://github.com/Taritsyn/ClearScriptV8Tester.DotNetTool) on GitHub. In macOS's terminal, you need to perform the following steps:

 * Clone a repository.
   * `mkdir TemporaryProjects && cd TemporaryProjects`
   * `git clone https://github.com/Taritsyn/ClearScriptV8Tester.DotNetTool`
 * Build a NuGet package.
   * `cd ClearScriptV8Tester.DotNetTool`
   * `dotnet pack`
 * Install and run a tool locally.
   * `cd ..`
   * `mkdir TestDotNetTool && cd TestDotNetTool`
   * `dotnet new tool-manifest`
   * `dotnet tool install ClearScriptV8Tester.DotNetTool --add-source ../ClearScriptV8Tester.DotNetTool/nupkg`
   * `dotnet tool run clearscript-v8-tester`
 
If the .NET 6.0.101 SDK is installed cleanly, then a quiet crash will occur during script execution:

![before-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149979495-6a9dfdb4-7678-4ebd-b09d-a6c726d0fddc.png)

If you install the [.NET 5.0.13 Runtime](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-5.0.13-macos-x64-installer) and then run a local tool, this error will no longer occur:

![after-dotnet-runtime-5 0 13-osx-x64-installation-marked](https://user-images.githubusercontent.com/251859/149980164-72d8e6a5-1599-464b-ac73-2e465cefaa72.png)

**Comment by ClearScriptLib** [comment]
Hi Andrey,

Yes, this is the same issue. Oddly, the tool works when run as a normal application (`dotnet run`). This would appear to be an issue in the .NET runtime. We'll investigate internally.

Thanks!

**Comment by Taritsyn** [comment]
Hello!

After updating the ClearScript library to version 7.2.2, the error began to appear more clearly:

![clearscript-v8-error-original-marked](https://user-images.githubusercontent.com/251859/152948416-604bc1e3-c5c4-4d0c-88f0-790b145cac61.png)

```
<--- Last few GCs --->


<--- JS stacktrace --->


#
# Fatal javascript OOM in GC during deserialization
#
```

**Comment by Taritsyn** [comment]
Nothing has changed in the system and using the ClearScript library version 7.2.1 gives the old result.

**Comment by ClearScriptLib** [comment]
Hi Andrey,

>Nothing has changed in the system and using the ClearScript library version 7.2.1 gives the old result.

We're seeing exactly the same results with 7.2.1 and 7.2.2. We had been using an older version of .NET 6, so we just updated to the latest and repeated your procedure several times, but there was no change:

```
csl@Sebulba tool % dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.1
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
csl@Sebulba tool % dotnet tool run clearscript-v8-tester
Start script execution...
csl@Sebulba tool %
```

BTW, here's the modified .csproj file we used:

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>clearscript-v8-tester</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.osx-arm64" Version="7.2.2" />
  </ItemGroup>

</Project>
```

Any idea what could be different in our setups?

**Comment by Taritsyn** [comment]
I testing this application on the x64 version of operating system. Unfortunately, I don't have the opportunity to test on ARM64.

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional information or observations related to this topic. Thank you!
