### ISSUE TITLE
Add several host types with specific name

### ISSUE THREAD

**Issue by GH-07** [microsoft/ClearScript#344]
Hi, 

this might be a stupid question but anyway ;)
 
Is it possible to add several types to one item name? 

```csharp
//c#

engine = new V8ScriptEngine("ScriptingHost", flags, 9222);

List<Type> types = new List<Type>();
types.Add(typeof(MyClass1));
types.Add(typeof(MyClass2));
types.Add(typeof(MyClass3));

// engine.AddHostType("SuperType", types.ToArray()); // thats what i am looking for 
```

So that i can use several class types "packed" in one type name 

```js
//js
SuperType.Methode1(); //static method from MyClass1
SuperType.Methode2(); //static method from MyClass2
SuperType.Methode3(); //static method from MyClass3

```

I found this method in the API reference but i think this is not what i need 

```csharp
ScriptEngine.AddHostType Method (String, String,Type[])
```

Thank You

**Comment by ClearScriptLib** [comment]
Hi @GH-07,

For a simple case with unambiguous behavior, what you need should be easy to set up with a tiny bit of code.

Suppose you have two static classes that you'd like to expose under one name:

``` C#
public static class FirstType {
    public static void Foo() => Console.WriteLine("Foo called");
    public static void Bar() => Console.WriteLine("Bar called");
}
public static class SecondType {
    public static void Baz() => Console.WriteLine("Baz called");
    public static void Qux() => Console.WriteLine("Qux called");
}
```

The standard [`Object.assign`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) method could be all you need:

``` C#
engine.Script.SuperType = engine.Script.Object.assign(
    engine.Evaluate("({})"),
    typeof(FirstType).ToHostType(engine),
    typeof(SecondType).ToHostType(engine)
);
```

And now you can do this:

``` C#
engine.Execute(@"
    SuperType.Foo();
    SuperType.Bar();
    SuperType.Baz();
    SuperType.Qux();
");
```

Of course, that's just one way to do it, but hopefully it gives you an idea.

Good luck!

**Comment by GH-07** [comment]
Hi @ClearScriptLib, 

that is exactly what I was looking for. 

Thank You ;)
