### ISSUE TITLE
IAsyncEnumerator is not disposed after iteration

### ISSUE THREAD

**Issue by jakubneubauer** [microsoft/ClearScript#348]
Hello,
I'm using this feature: https://github.com/microsoft/ClearScript/issues/259

My IAsyncEnumerator needs some backing resources during iteration and I need to free them after the iteration ends.
If the iteration is not interrupted, I am able to do it inside moveNextAsync because I can recognize the last item.

But there is no way how to implement it when iteration is terminated prematurely (either with exception or with "break"). The IAsyncEnumerator extends IAsyncDisposable which is perfect candidate to do the cleanup, but this is actually and unfortunately never called.

It would be nice (and needed) to call the DisposeAsync after the iteration finishes.

Unit test attached
[ClearScriptAsyncEnumeratorMissingDisposeTest.txt](https://github.com/microsoft/ClearScript/files/7958205/ClearScriptAsyncEnumeratorMissingDisposeTest.txt)
.

**Comment by ClearScriptLib** [comment]
Hi @jakubneubauer,

This is a bug, and it affects non-async enumerators as well. Thanks for reporting it!

Cheers!

**Comment by ClearScriptLib** [comment]
Fixed in [Version 7.2.2](https://github.com/microsoft/ClearScript/releases/tag/7.2.2).
