### ISSUE TITLE
Direct access to ArrayBuffer bytes from .net side?

### ISSUE THREAD

**Issue by jakerdy** [microsoft/ClearScript#349]
Hi!
I am currently working on project where we have array buffers with pretty big sizes, like 512mb+. 
Most of the data processing happens on JS side. But some times we need to get data from JS side, and upload it to the gpu via OpenGL apis, like glTexImage2d. Api of IArrayBuffer doesn't let us access actual JS buffer, it allows only copy data from JS runtime, which is suboptimal, in terms of speed and convenience. 
Is there any (maybe hacky) way, to get actual IntPtr to internal V8 buffer? 
It will be used only in callback from JS side, data immediatly copied to gpu, so no sharing issues because of buffer moved in memory shouldn't occur.
Or maybe you cold suggest other solution which could help us avoid copy before upload OpenGL Call?

**Comment by jakerdy** [comment]
It would be great if api like ```InvokeWithArrayBufferOrViewData(Action<IntPtr>)```, will be available.

**Comment by ClearScriptLib** [comment]
Hi @jakerdy,

>I am currently working on project where we have array buffers with pretty big sizes, like 512mb+. Most of the data processing happens on JS side.

Wow! It's impressive that V8 provides the performance to handle that much data in JavaScript.

>Is there any (maybe hacky) way, to get actual IntPtr to internal V8 buffer?

Unfortunately, no.

>It would be great if api like `InvokeWithArrayBufferOrViewData(Action<IntPtr>)`, will be available.

We'll provide such an API in the next release.

Thank you!

**Comment by ClearScriptLib** [comment]
[Version 7.2.2](https://github.com/microsoft/ClearScript/releases/tag/7.2.2) added [`IArrayBuffer.InvokeWithDirectAccess`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_JavaScript_IArrayBuffer_InvokeWithDirectAccess.htm) and [`IArrayBufferView.InvokeWithDirectAccess`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_JavaScript_IArrayBufferView_InvokeWithDirectAccess.htm).
