### ISSUE TITLE
ERROR:Cannot load V8 interface assembly. Load failure information for v8-ia32.dll: 

### ISSUE THREAD

**Issue by yuzd** [Microsoft/ClearScript#35]
System.TypeLoadException

Cannot load V8 interface assembly. Load failure information for v8-ia32.dll: **D:\App\cb\hangfire_pro\v8-ia32.dll**: 找不到指定的模块。
![image](https://user-images.githubusercontent.com/16083659/34510131-257926c0-f08c-11e7-845d-d204093f3d8b.png)

System.TypeLoadException: Cannot load V8 interface assembly. Load failure information for v8-ia32.dll:
D:\App\cb\hangfire_pro\v8-ia32.dll: 找不到指定的模块。
   在 Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary()
   在 Microsoft.ClearScript.V8.V8Proxy.LoadAssembly()
   在 Microsoft.ClearScript.V8.V8Proxy.GetAssembly()
   在 Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type)
   在 Microsoft.ClearScript.V8.V8Proxy.CreateImpl[T](Object[] args)
   在 Microsoft.ClearScript.V8.V8IsolateProxy.Create(String name, V8RuntimeConstraints constraints, Boolean enableDebugging, Int32 debugPort)
   在 Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort)
   在 Microsoft.ClearScript.V8.V8Runtime..ctor(V8RuntimeConstraints constraints)
   在 JavaScript.Manager.RuntimeManager..ctor(IManagerSettings settings)
   在 Hangfire.Job.Common.TabrisUtil.Excute(JobItem item, String jobName, PerformContext context)

**Comment by ClearScriptLib** [comment]
@TehWardy Does your Visual Studio installation include the **Desktop development with C++** workload?

**Comment by ClearScriptLib** [comment]
@antibarbie What version of Visual Studio are you using?

**Comment by antibarbie** [comment]
We are using Visual 2017 15.8.x  (we deploy with C++ runtimes v141). The symptoms are present on developper machines (Windows 8.1 - Windows 10). 

We deliver other versions of our software with Clearscript 5.4.6 and Visual 2013. Works perfectly.

**Comment by ClearScriptLib** [comment]
@antibarbie We aren't aware of any recent changes to the way ClearScript loads its V8 modules. Please verify that at least one of the listed paths contains **ALL** of the following:

- ClearScriptV8-64.dll
- v8-base-x64.dll
- v8-x64.dll

**Comment by antibarbie** [comment]
The last path is the web site path : `C:\inetpub\wwwroot\webapplication4\bin\`

It contains all of the files (the files I thought that would be required) : 
```
ClearScript.dll (version 5.5.4 - microsoft signed with timestamp  november 20th)
ClearScriptV8-64.dll (version 5.5.4 - microsoft signed with timestamp  november 20th)
v8-x64.dll (microsoft 3rd party signed with timestamp  november 20th)
v8-base-x64.dll (microsoft 3rd party signed with timestamp  november 20th)
```
That is the only path that contains all the DLL, and it probably explains why the last error is different. It is not "FILE not found", but "MODULE not found".  Why module not found ? I don't know yet.

Maybe it is not a regression but an incompatibility with .NET 4.7.2

I must admit that such a problem is hard to spot when the unit tests would have a hard time mixing all the DLLs like in the shadow assembly copy : on our side we don't know if this is due to jumping from .NET 4.51 to .NET 4.7.2 or jumping from clearscript 5.4.6 to 5.5.2+. Our unit tests pass, because they are not affected by the "shadow assembly" mode.

nb: I will be interested in seeing how you will unit test that bug once it is fixed.

**Comment by antibarbie** [comment]
I will try to create a repro. Thanks for your time.

**Comment by antibarbie** [comment]
@clearscript In fact, I could not spot a change in clearscript code, and also we saw the problem with one of our Visual 2013 build, at a client's site. So I guess my first impressions were completely wrong.

It looks more like a platform problem, or maybe it depends on Windows 10 versions. Or IIS versions.  

I will still try to investigate & create a repro when I have time.

**Comment by TehWardy** [comment]
Seems good here ... needs VS (any version from 2013 seems fine here) tested on windows 7 up to windows 10) ... install the c++ redist / c++ workload for VS2017 and it should be fine. 
Older VS versions can be a bit twitchy though ... highly recommend to peeps that they use VS 2017, there's basically no reason not to.

**Comment by alarya** [comment]
I fixed this by installing Visual C++ redistributable on the server where I was deploying.

For links to the download, see [https://microsoft.github.io/ClearScript/Details/Build.html](link)
Section V -> #4

**Comment by shirishayellu** [comment]
Could you please give the  correct link. I am have the same issue on Server.
