### ISSUE TITLE
Adding better exception handling in VBScript

### ISSUE THREAD

**Issue by Nir1812** [microsoft/ClearScript#350]
Is there any plans on adding a better exception handling for VBScript?
The 'on error resume next' method is an old approach.
A better one will be to implement "try....catch.... finally" blocks.

**Comment by ClearScriptLib** [comment]
Hi @Nir1812

>Is there any plans on adding a better exception handling for VBScript?

We aren't aware of any upcoming enhancements to VBScript. That script engine appears to be in maintenance mode.

>The 'on error resume next' method is an old approach.
A better one will be to implement "try....catch.... finally" blocks.

Enhancing script languages and script engines is outside the scope of the ClearScript project. You can use [`HostFunctions.tryCatch`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_tryCatch.htm) with VBScript's [`GetRef`](https://docs.microsoft.com/en-us/previous-versions//ekabbe10(v=vs.85)), but it's not exactly a convenient solution.

Sorry!

**Comment by ClearScriptLib** [comment]
Please feel free to reopen this issue if you have additional questions on this topic. Thank you!
