### ISSUE TITLE
Is there a way to control networking in ClearScript

### ISSUE THREAD

**Issue by sr229** [microsoft/ClearScript#351]
Our use case requires that we want to control how the V8 engine interacts with the host's network, is there a way to do this in ClearScript?

**Comment by ClearScriptLib** [comment]
Hi @sr229,

>Our use case requires that we want to control how the V8 engine interacts with the host's network, is there a way to do this in ClearScript?

To our knowledge, V8 doesn't interact directly with the network. ClearScript implements simple network I/O for things like module loading and debugger interaction. Can you say more about what you're looking for?

Thanks!

**Comment by sr229** [comment]
> Hi @sr229,
> 
> > Our use case requires that we want to control how the V8 engine interacts with the host's network, is there a way to do this in ClearScript?
> 
> To our knowledge, V8 doesn't interact directly with the network. ClearScript implements simple network I/O for things like module loading and debugger interaction. Can you say more about what you're looking for?
> 
> Thanks!

We're looking into restricting networking like HTTP calls and websockets, and have C# throw an error if they try to use `fetch` or use any kind of API call that requires outbound internet connectivity.

**Comment by ClearScriptLib** [comment]
>We're looking into restricting networking like HTTP calls and websockets, and have C# throw an error if they try to use fetch or use any kind of API call that requires outbound internet connectivity.

By default, V8 and ClearScript provide a bare [standard JavaScript environment](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects), which includes no I/O APIs whatsoever – no networking, no file access, no logging, etc.

All such facilities must be provided by the host explicitly. ClearScript aims to make that easy by allowing hosts to use .NET objects and types for this purpose.

APIs such as `fetch` are part of the [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API) provided by browsers.

**Comment by sr229** [comment]
Thank you so much, this solves some of our critical issues lately. 💖

**Comment by ClearScriptLib** [comment]
Please feel free to reopen this issue if you have additional questions on this topic. Thank you!
