### ISSUE TITLE
What is the purpsoe of `V8ScriptEngine.Compile`?

### ISSUE THREAD

**Issue by LeNitrous** [microsoft/ClearScript#353]
[In documentation](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8ScriptEngine_Compile.htm), it says that it returns:
> A compiled script that can be executed multiple times without recompilation.

However in tests it says that it is a no-op:
https://github.com/microsoft/ClearScript/blob/8b5b794ff4366e23dc72b4966f3ada72afa17416/ClearScriptTest/V8ModuleTest.cs#L437-L438

What does [`V8ScriptEngine.Compile`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8ScriptEngine_Compile.htm) actually do?

**Comment by ClearScriptLib** [comment]
Hello @LeNitrous,

>What does [V8ScriptEngine.Compile](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8ScriptEngine_Compile.htm) actually do?

That's a good question. The V8 API doesn't make it very clear. However, in V8, compilation is always the first step of script execution, and it's apparently expensive enough for V8 to expose it as a separate API, enabling script re-execution without recompilation. The best way to describe compilation might be that it converts script code into a form that's ready for execution.

>However in tests it says that it is a no-op:

In ClearScript, a `V8Script` instance can represent one of two different V8-level concepts: a compiled script or a compiled [module](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). Scripts can be re-executed, but modules cannot. That is, V8's own API for executing a compiled module does nothing if the module has already been executed.

Please let us know if you have additional questions or comments on this topic.

Thanks!

**Comment by LeNitrous** [comment]
Thanks for the clear response. As far as I understand your reply, modules can be compiled ahead of time for later execution and this quirk is unique to V8 only. If that is correct then there is no other questions to follow.
