### ISSUE TITLE
Intermittent crash on 32-bit Windows during V8 background work

### ISSUE THREAD

**Issue by EinmalIM** [microsoft/ClearScript#354]
We use the V8 ClearScript engine (currently 7.2.1) to execute js code and hand in host objects implemented in C#.

We face seldom crashes which result in the stack trace I show at the end of this post.

With some debugging we think that our way to add host objects might cause a problem, that the .Net garbage collection might remove objects which are still used in the V8 engine. Some pseudo code:

--- sample code ---
V8ScriptEngine engine = runtime.CreateScriptEngine("ScriptEngine", flags, debugPort);
engine.AddHostObject("someHost", new OurHostObject());
engine.Evaluate(...);
---

Notice that we do not reference the object created with new OurHostObject() in our code at any later point.
Debugging into the v8 shows that the host objects are stored:

  private readonly ConditionalWeakTable<object, List<WeakReference>> hostObjectHostItemCache;

So it seems that .Net runtime does not know that the host object should be kept alive.

Could our seldom crashes be caused because of the WeakReference List?

We currently added code to keep our host objects in a List of our own, to make sure the objects are referenced and are kept alive. No crashes in the last 3 days.

Shouldn't the V8 engine keep "full" references to the host objects?
Is there a reason to keep only weak refs?

Regards
Sven

--- call stack from crash ---

Managed Exception = System.AccessViolationException:Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
CallStack - Managed Exception
========================================================
     Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative+Impl_Windows_X86.NativeCallback_Invoke(Handle)
     Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative+Impl_Windows_X86.Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative.NativeCallback_Invoke(Handle)
     Microsoft.ClearScript.V8.SplitProxy.NativeCallbackImpl.<Invoke>b__4_0(Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative)
     Microsoft.ClearScript.V8.SplitProxy.V8SplitProxyNative.InvokeNoThrow(System.Action`1<Microsoft.ClearScript.V8.SplitProxy.IV8SplitProxyNative>)
     Microsoft.ClearScript.V8.SplitProxy.NativeCallbackImpl.Invoke()
     Microsoft.ClearScript.Util.MiscHelpers.Try(System.Action)
     Microsoft.ClearScript.Util.MiscHelpers+<>c__DisplayClass33_0.<QueueNativeCallback>b__0(System.Object)
     System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
     System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
     System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     System.Threading.ThreadPoolWorkQueue.Dispatch()
     System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by EinmalIM** [comment]
Hi,

a minimal sample is a little problematic.: Our V8Engine setup code is always the same. It can be triggered in parallel in an Azure App Service through http events. Most of the time the exact same scripts execute successfully but every now and then we see our App Service crash.

So we think the crashes could be triggered if the garbage collection kicks in while a script is executed in engine.Evaluate and our host objects are removed too early. Then a host object might be called which has already been freed.

We saw crashes once or twice a day - correlating to morning times, when our customers start using the system, which generates events which result in script executions. Since we added our own list of host objects to keep them referenced there have been no crashes - still a bit early to tell, if that is due to the code change or less actions from our customers.

Nevertheless I will try to create a simple multi threaded console app to execute multiple scripts in parallel with host objects not referenced in our code. If I get a repro with such a test I will share the code - bit busy currently, so it could take a week or two...

**Comment by ClearScriptLib** [comment]
>Nevertheless I will try to create a simple multi threaded console app to execute multiple scripts in parallel with host objects not referenced in our code. If I get a repro with such a test I will share the code - bit busy currently, so it could take a week or two...

Sounds good, thank you.

By the way, it looks like you're running your service in 32-bit mode. Is there a particular reason for that? Just curious...

**Comment by EinmalIM** [comment]
Our App Service is deployed in 32-bit mode. We had no reason for 64-bit up to now. Our App Service plan is configured with 7GB RAM and we use the App Service and a Web Job - so two 32-bit processes with each up to 2GB of user mode memory and the remaining 3GB for the OS.

Do you see advantages when using 64-bit ClearScript host processes? Advantages, except the obvious that we could handle larger objects in ClearScript - any other improvements in performance or robustness?

**Comment by ClearScriptLib** [comment]
>Do you see advantages when using 64-bit ClearScript host processes? Advantages, except the obvious that we could handle larger objects in ClearScript - any other improvements in performance or robustness?

We don't have anything specific in mind. It's just that V8 is optimized to an unusual extent to favor speed over memory efficiency. For example, each V8 runtime reserves large blocks of address space, a practice that can be problematic in a 32-bit process, especially if you use multiple runtimes.

**Comment by ClearScriptLib** [comment]
Hi again,

Thank you for your efforts.

Interestingly, the crash stack above is very similar to one that another user reported last year. That report triggered a lengthy investigation and even a conversation with .NET runtime developers. The result was a very subtle change that went into ClearScript 7.1.4, and the user verified the fix. Is it at all possible that you observed the issue on an earlier version of ClearScript?

In any case, since the crash seems to be elusive, please consider [enabling crash dumps](https://docs.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) for your application. Use the Full dump type if possible. If you're comfortable sharing a crash dump, we'll be happy to take a look.

Cheers!

**Comment by EinmalIM** [comment]
Yes, we enabled crash monitoring on the App Service which crashed regularily.

I will ask internally if I can share the dump. We have 5 dmp files between 550 and 870MB - maybe we can arrange to share the 550MB one. Thanks for the offer!

We use version 7.2.0.

**Comment by EinmalIM** [comment]
Could you give us an upload location for the dump or an email address to send you a private download link?

**Comment by ClearScriptLib** [comment]
Please send a link to ClearScript@microsoft.com. Thank you!

**Comment by EinmalIM** [comment]
On its way. Thank you!

**Comment by ClearScriptLib** [comment]
Hi Sven,

Thank you very much for providing the crash dump! It was immensely helpful.

The root cause appears to be a V8 bug. We've reported it [here](https://bugs.chromium.org/p/v8/issues/detail?id=12653).

The problem appears to be related to _Fast TLS_ – an internal V8 performance tweak that can apparently fail when V8 performs background work – something it does to accelerate housekeeping activities. As long as the V8 bug remains unfixed, future ClearScript releases will disable Fast TLS and provide a way to disable all V8 background work globally.

In the meantime, unfortunately, there's no workaround. However, Fast TLS on Windows appears to be limited to 32-bit V8 builds, so switching to a 64-bit host process might eliminate the issue.

Thanks again!

**Comment by EinmalIM** [comment]
Thank you for your analysis! That was fast :-)

I switched a test environments App Service to 64 bit and see how our tests behave with the platform change.

Any idea when the next version of ClearScript with disabled Fast TLS / background work could be available?

**Comment by EinmalIM** [comment]
Great support!

Our internal tests with our .Net code in 64-bit App Services showed no problems so far. Plan to switch to x64 on the App Service which "crashes most reliable" on the coming weekend.

Thank you :-)

**Comment by ClearScriptLib** [comment]
>Plan to switch to x64 on the App Service which "crashes most reliable" on the coming weekend.

Excellent! Please let us know how it goes.

**Comment by ClearScriptLib** [comment]
`Version 7.2.3` disabled Fast TLS and added [`V8ScriptEngineFlags.DisableBackgroundWork`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8GlobalFlags.htm).

**Comment by EinmalIM** [comment]
Quick update: no v8 crash the last 9 days, since we switched the App Service to 64-bit.
