### ISSUE TITLE
Just want to say thank you

### ISSUE THREAD

**Issue by sep2** [microsoft/ClearScript#357]
Thank you for this project!

I just want to share that I have successfully integrated a crdt library `y.js` into .net with clearscript!

Have to polyfill console.log and setTimout friends, and know how to convert data/callback to/from .net/js efficiently did take a bit time, but it was as easy as searching the issues list and always find an answer.

**Comment by ClearScriptLib** [comment]
Thanks @sep2! Please feel free to ask questions or report any issues that you encounter.
