### ISSUE TITLE
DOMParser is undefined

### ISSUE THREAD

**Issue by dearshivaramallva** [Microsoft/ClearScript#36]
I want to parse a XML, apply xpath and grab some data. Do we have any xml parser support in clearscript or any other alternative method?

```
using Microsoft.ClearScript;
using Microsoft.ClearScript.V8;
using Microsoft.ClearScript.JavaScript;
V8ScriptEngine _v8Engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging);
            _v8Engine.Execute(@"
                var text, parser, xmlDoc;
                text = '<bookstore><book><title>Everyday Italian</title><author>Giada De Laurentiis</author><year>2005</year></book></bookstore>';
                parser = new DOMParser();
                xmlDoc = parser.parseFromString(text, 'text/xml');
            ");
```
```
Error:
Microsoft.ClearScript.ScriptEngineException: 'ReferenceError: DOMParser is not defined
```

I'm using clearscript under c#.

**Comment by ClearScriptLib** [comment]
Hi @dearshivaramallva,

`DOMParser` is part of the [Web APIs](https://developer.mozilla.org/en-US/docs/Web/API) provided by Web browsers. It isn't part of the JavaScript standard.

On the other hand, .NET includes rich XML functionality, and one of ClearScript's goals is to make it easy for script code to access .NET facilities.

Here's a simple example that uses [`XmlDocument`](https://msdn.microsoft.com/en-us/library/system.xml.xmldocument.aspx):

``` C#
// using System;
// using System.Xml;
_v8Engine.AddHostType(typeof(XmlDocument));
_v8Engine.AddHostType(typeof(Console));
_v8Engine.Execute(@"
    var text, xmlDoc;
    text = '<bookstore><book><title>Everyday Italian</title><author>Giada De Laurentiis</author><year>2005</year></book></bookstore>';
    xmlDoc = new XmlDocument();
    xmlDoc.LoadXml(text);
    Console.WriteLine(xmlDoc.ChildNodes.Count);
");
```

Good luck!

**Comment by dearshivaramallva** [comment]
Thank you for your email :)

Basically, I've to provide a JS based config file to my client and which then will give full access to XML handling like accessing node-text, attr value, loop nodes, xpath etc. In c#, I will pass the live XML to JS and get the response from JS for further c# handlings.

```
var doc = new XmlDocument();
doc.LoadXml('<article><title id="1">foo</title><author><lastname>name1</lastname></author><author><lastname>name2</lastname></author></article>');

node = doc.SelectSingleNode("//title");
console.log(node.InnerText);  // This works
console.log(node.Attributes["id"].Value); // TypeError: Cannot read property 'Value' of undefined

nodeList = doc.SelectNodes("//author");
console.log(nodeList[0]["lastname"].InnerText); // TypeError: Cannot read property 'lastname' of undefined

nodeList = doc.SelectNodes("//author");
var len = nodeList.Count; // This works: we get count length 2
var str = '';
for (i = 0; i < len; i++) {
    str += i + ":" + nodeList[i]["lastname"].InnerText;   // Throws undefined error
}
console.log(str);
```
The error are marked in JS comments (above). So, basically I couldn't get full control on the XML handling. Would appreciate your answers if you can tell how to access attr value, loop through childnodes, get node-text, etc.

Thanks in advance.

**Comment by ClearScriptLib** [comment]
Hi @dearshivaramallva,

Your code tries to use JavaScript bracket syntax to access .NET indexers (e.g., `nodeList[0]["lastname"]`). That's the part that doesn't work as you expect.

The problem is that brackets in JavaScript are just an alternate way to access properties, whereas .NET indexers can operate on arbitrary data sets. Also, .NET indexers can be overloaded and accept multiple parameters. For these reasons ClearScript can't always make .NET indexers accessible via JavaScript brackets.

Note that .NET indexers are actually properties with parameters. These properties have names (such as `Item` or `ItemOf`) that C# hides under the covers. You can see these names in the .NET documentation (see [here](https://msdn.microsoft.com/en-us/library/0ftsfa87.aspx) for an example).

ClearScript supports the following generic JavaScript syntax for accessing such properties:

``` JavaScript
// JavaScript
value = obj.Item.get(index1, index2 ...); // obj.Item(index1, index2 ...) also works
obj.Item.set(index1, index2 ..., value);
```

Here's a modified version of your JavaScript code that should work:

``` JavaScript
var doc = new XmlDocument();
doc.LoadXml('<article><title id="1">foo</title><author><lastname>name1</lastname></author><author><lastname>name2</lastname></author></article>');

node = doc.SelectSingleNode("//title");
console.log(node.InnerText);  // This works
console.log(node.Attributes.ItemOf("id").Value);

nodeList = doc.SelectNodes("//author");
console.log(nodeList.Item(0).Item("lastname").InnerText);

nodeList = doc.SelectNodes("//author");
var len = nodeList.Count;
var str = '';
for (i = 0; i < len; i++) {
    str += i + ":" + nodeList.Item(i).Item("lastname").InnerText + ' ';
}
console.log(str);
```

Cheers!

**Comment by dearshivaramallva** [comment]
Yes, it works. Thank you for your valuable time and detailed explanation.

**Comment by jameson75** [comment]
This helped me a lot. Thanks.
