### ISSUE TITLE
Making member access case-insensitive

### ISSUE THREAD

**Issue by kpko** [microsoft/ClearScript#363]
Hi,

I'm thinking about moving from Jint to ClearScript in my project, but I have a bit of source code that I want to make compatible with ClearScript. I'm using a range of user provided host objects which follow the default C# naming conventions, so methods and properties are written in PascalCase. Is there a method to make the members accessible via camelCase without having to put a ScriptMemberAttribute on every member in my entire system? 

Is there a way to either ignore casing when accessing host objects or make host object members camelCased when getting marshalled automatically?

Thanks for the magnificent work on ClearScript! :)

**Comment by ClearScriptLib** [comment]
Hi @kpko,

Thanks for your kind words! 😊

>Is there a method to make the members accessible via camelCase without having to put a ScriptMemberAttribute on every member in my entire system? [...] Is there a way to either ignore casing when accessing host objects or make host object members camelCased when getting marshalled automatically?

Unfortunately, no. We believe that case-insensitive member binding is _doable_, with the obvious caveat that it introduces potential ambiguity. The tricky case is method binding, for which ClearScript uses the always-case-sensitive C# compiler rather than reflection. Still, since renaming is possible via `ScriptMemberAttribute`, case-insensitive binding should also be possible, although it would probably affect binding performance.

We'll take a closer look at this for a future release.

Thanks!

**Comment by kpko** [comment]
Hi, 

thanks for the quick investigation, this sounds great!

Regarding the performance penalty: Would it be better for performance if one could choose to always use camelCased members instead of PascalCased? This would not necessarily mean that the binding needs to be case insensitive and would remove the ambiguity. This would be fine for my case, where I need to annotate every Property with a ScriptMember("camelCasedPropertyName") attribute, especially for .NET library classes.

**Comment by ClearScriptLib** [comment]
hi @kpko,

>Would it be better for performance if one could choose to always use camelCased members instead of PascalCased?

Please clarify. Suppose script code issues a camel-cased method call such as `hostObj.fooBar()`. Are you suggesting that, instead of binding case-insensitively, ClearScript would convert "fooBar" into "FooBar" and bind normally (that is, _with_ case sensitivity)?

Thanks!

**Comment by kpko** [comment]
My main concern is not about script code but about code that got mapped from .NET objects. Suppose we have a C# class that I add as a host object:

```csharp
public class Person
{
  public string FirstName { get; set; } = string.Empty;
  public string FormatHelloMessage() => $"Hello, my name is {FirstName}!";
}
...
engine.AddHostObject("person", new Person());
```

I would like to be able to access "FirstName" by using firstName or FormatHelloMessage by using formatHelloMessage() (my users are used to writing "js"-like camel case). This could be achieved by using case-insensitive bindings, but also by specifying how a "clr member" is named in v8. I could achieve what I want by using [ScriptMember]-attributes, but this only works for classes that I created. I could not access `person.ToString()` by using `toString()` or other members further down the object graph.

**Comment by ClearScriptLib** [comment]
Hi @kpko,

>I could achieve what I want by using [ScriptMember]-attributes, but this only works for classes that I created.

We've long considered it a deficiency that hosts can't apply such attributes to platform or external resources. To resolve that issue as well as yours, we're planning to make the following changes in the next release:

1. Funnel all attribute access through a central location.
2. Provide a way for hosts to override the attribute retrieval process.

This scheme will allow hosts to provide "virtual" ClearScript attributes for any resource, all in one place. For example, to expose all type members as camel case, you might do something like this:

``` C#
class CamelCaseHook : CustomAttributeHook {
    public override T[] GetCustomAttributes<T>(ICustomAttributeProvider resource, bool inherit) {
        if (typeof(T) == typeof(ScriptMemberAttribute) && resource is MemberInfo member) {
            var name = char.ToLowerInvariant(member.Name[0]) + member.Name.Substring(1);
            return new[] { new ScriptMemberAttribute(name) } as T[];
        }
        return base.GetCustomAttributes<T>(resource, inherit);
    }
}
```

And then:

``` C#
HostSettings.CustomAttributeHook = new CamelCaseHook();
engine.AddHostType("console", typeof(Console));
engine.Execute("console.writeLine('foo')");
```

We'll be adding this feature in addition to optional case-insensitive member binding.

Thanks again!

**Comment by ClearScriptLib** [comment]
[Version 7.2.4](https://github.com/microsoft/ClearScript/releases/tag/7.2.4) added [`V8ScriptEngineFlags.UseCaseInsensitiveMemberBinding`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngineFlags.htm).
