### ISSUE TITLE
Trouble with update from 7.2.0 to 7.2.1 :(

### ISSUE THREAD

**Issue by MF91WorkPS** [microsoft/ClearScript#366]
Hi,

I am currently trying to update our code to use the latest hotfix instead of version 7.2.0. We are running all scripts as tasks because we need to e. g. log information in fixed time intervalls to a monitoring system without the user needing to write code. We are using the following method to create the task: 

```csharp
        private static Task<object> CreateScriptTask(
            JavaScriptExecutionContext javaScriptExecutionContext,
            V8ScriptEngine engine)
        {
            return Task.Run(
                () => engine
                        .Evaluate(
                            new DocumentInfo(javaScriptExecutionContext.ScriptName)
                            {
                                Category = ModuleCategory.Standard
                            },
                            javaScriptExecutionContext.ScriptCode
                        )
                        .ToTask()
            );
        }
```

It is similar to the code in this [post](https://github.com/microsoft/ClearScript/issues/182). The code works fine with version 7.2.0. After the update to version 7.2.1 the method Microsoft.ClearScript.JavaScript.JavaScriptExtensions.ToTask(Object promise) throws an ArgumentException: "The object is not a V8 promise.". I have been unable to fix the issue. Am I missing something? Can you help? Thank you in advance!

**Comment by ClearScriptLib** [comment]
Hi @MF91WorkPS,

Can you give us an idea about what the JavaScript module code looks like?

Thanks!

**Comment by MF91WorkPS** [comment]
Thank you for your answer. Sorry, somehow I did not consider that the script content might be important. I created a test. You should be able reproduce the behaviour with the code below. I tested with the versions 7.2.0 and 7.2.4. Still on .NET Framework 4.7.2, but we are working on it. The test case with the async function works in 7.2.0 but not for 7.2.4. This is how almost all our scripts look like (minus all the imported modules and logic). The test case without the async function does not work in 7.2.0 or 7.2.4. We have probably thousands of scripts running every day. I am surprise nobody ever tried running such a script. Is this why you asked how the script looks like? Is there a better way to implement CreateScriptTask(...)?

```csharp
        [DataTestMethod]
        [DynamicData(nameof(GetTestScripts), DynamicDataSourceType.Method)]
        public void TestIfThrowsException(
            string scriptName,
            string scriptCode)
        {
            using (V8Runtime runtime = new V8Runtime("V8RuntimeTest"))
            {
                using (V8ScriptEngine engine = new V8ScriptEngine("V8ScriptEngineTest"))
                {
                    var scriptExecutionTask = CreateScriptTask(scriptName, scriptCode, engine);

                    var scriptExecutionIsComplete = false;

                    while (!scriptExecutionIsComplete)
                    {
                        scriptExecutionIsComplete = scriptExecutionTask.Wait(100);

                        if (!scriptExecutionIsComplete)
                        {
                            //do stuff
                        }
                    }

                    if (scriptExecutionTask.IsCompleted)
                    {
                        object o = scriptExecutionTask.Result;
                    }
                    else if (scriptExecutionTask.Exception != null)
                    {
                        throw scriptExecutionTask.Exception;
                    }

                }
            }
        }

        private static IEnumerable<object[]> GetTestScripts()
        {
            //works with 7.2.0, but not with 7.2.1 -> usually basic structure of our integration tests/scripts
            yield return new object[] { "test1.js", "test(); async function test() { }" };
            //works neither with 7.2.0 nor 7.2.1
            yield return new object[] { "test2.js", "let test = 'somevalue';" };
        }

        private static Task<object> CreateScriptTask(
            string scriptName,
            string scriptCode,
            V8ScriptEngine engine)
        {
            return Task.Run(
                () => engine
                        .Evaluate(
                            new DocumentInfo(scriptName)
                            {
                                Category = ModuleCategory.Standard
                            },
                            scriptCode
                        )
                        .ToTask()
            );
        }
```

**Comment by ClearScriptLib** [comment]
Hi @MF91WorkPS,

Your code calls [`ToTask`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_JavaScript_JavaScriptExtensions_ToTask.htm) on the evaluation result of a module. `ToTask` requires a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) argument.

There are two cases in which a module's evaluation result is a promise:
- The module is _asynchronous_ – that is, it uses [`await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await) or [`for await...of`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) – or imports an asynchronous module.
- The module is _synchronous_ but explicitly returns an _unfulfilled_ promise.

In your test code above, both modules are synchronous. The first one (`test1.js`) returns a _fulfilled_ promise – the return value from the `test` call, so the evaluation result is the fulfillment value (`undefined`). The second one returns nothing – the `let` statement has no value, so the evaluation result is again `undefined`.

The behavior in 7.2.0 appears to have been a bug that is now fixed. Please let us know if you have additional questions.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi again,

While our answer above was technically correct, we'd like to provide some more practical information.

>I am surprise nobody ever tried running such a script.

The wrinkle here is that you're relying on module evaluation results. This is a bit unusual, as modules normally use imports and exports to exchange code and data. Module evaluation results, being accessible only to the host, are defined by the script engine implementation, and V8 has some unfortunate history here.

As far as we can tell, the JavaScript standard doesn't say much about module evaluation results, and the V8 team doesn't seem very concerned about making them useful or reliable.

In fact, when they permanently enabled [Top-Level Await](https://github.com/tc39/proposal-top-level-await), the V8 team changed module evaluation results for all modules, completely breaking hosts that relied on the immediate results of synchronous module evaluation. Although we've tried to [work around](https://microsoft.github.io/ClearScript/2022/02/04/top-level-await.html) this change and retain host compatibility, it almost certainly has something to do with the difference you're seeing between ClearScript 7.2.0 and 7.2.1.

>Is there a better way to implement CreateScriptTask(...)?

The simplest solution depends on the kinds of scripts you need to run. Based on your comments and code above, we assume that your scripts are all standard JavaScript modules.

The main consideration is whether your modules are synchronous or asynchronous. If you're running both kinds of modules, the simplest solution might be something like this:

``` C#
private static Task<object> CreateScriptTask(string scriptName, string scriptCode, V8ScriptEngine engine) {
    return Task.Run(() => {
        var info = new DocumentInfo(scriptName) { Category = ModuleCategory.Standard };
        var result = engine.Evaluate(info, scriptCode);
        try {
            return result.ToTask();
        }
        catch (ArgumentException) {
            return Task.FromResult(result);
        }
    });
}
```

You might also consider using [`V8ScriptEngineFlags.EnableTaskPromiseConversion`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngineFlags.htm). That would allow you to avoid the exception:

``` C#
private static Task<object> CreateScriptTask2(string scriptName, string scriptCode, V8ScriptEngine engine) {
    return Task.Run(() => {
        var info = new DocumentInfo(scriptName) { Category = ModuleCategory.Standard };
        var result = engine.Evaluate(info, scriptCode);
        return result as Task<object> ?? Task.FromResult(result);
    });
}
```

Good luck!

**Comment by MF91WorkPS** [comment]
Hi @ClearScriptLib, 

thank you. Officially, we only support standard modules with at least one async function. In the future I would like to support a boarder range of script/module types. Top-Level Awaits have already been requested.  At the moment I am testing the following version of CreateScriptTask(...):

```csharp
    public class ScriptTaskCreator : IScriptTaskCreator
    {
        private const string PROPERTYNAME_IS_PROMISE = "IsPromise";

        public Task<object> CreateScriptTask(
            string scriptName,
            string scriptCode,
            V8ScriptEngine engine)
        {
            object evaluationResult = engine.Evaluate(
                new DocumentInfo(scriptName)
                {
                    Category = ModuleCategory.Standard
                },
                scriptCode);

            //Engine.Evaluate will return Microsoft.ClearScript.Undefined, e. g. if:
            //- The script contains no function: let test = 'test';
            //- The script contains an async function without the user returning a value: test(); async function test() { }
            if (evaluationResult is Undefined)
                return Task.FromResult<object>(Undefined.Value);

            var evaluationResultType = evaluationResult.GetType();
            var isPromiseProperty = evaluationResultType.GetProperty(PROPERTYNAME_IS_PROMISE);

            //The promise property is not there if there is no asynchronous function, e. g. if:
            //- The script returns a string: test(); function test() {return "test";}
            //- The script returns a string: test(); function test() {return true;}
            if (isPromiseProperty == null)
                return Task.FromResult(evaluationResult);

            var isPromisePropertyValue = isPromiseProperty.GetValue(evaluationResult);

            if (!(isPromisePropertyValue is bool))
                throw new ApplicationException($"The property {PROPERTYNAME_IS_PROMISE} is not of the expected type Boolean.");

            var isPromise = (bool)isPromisePropertyValue;

            //If IsPromise is true, it is safe to call ToTask(), e. g. if:
            //- Top level await: await test(); async function test() { } 
            if (isPromise)
                return evaluationResult.ToTask();

            //If IsPromise property is present but false, e. g. if:
            //- Any await is performed within a function, but it is not a top level await. See integration tests e. g. 'GetSitesInRootViaGraph'
            //- Promise.resolve(promise) is called on a function in a function. See integration tests e. g. 'GetListByTitle'
            return Task.FromResult(evaluationResult);
        }
    }
```

The implementation works with 7.2.4 for all our integration tests. I am utilizing the property 'IsPromise' to check if I can call ToTask(). Is the property intended to be used like that? Do you know the check reliable?

Thanks!
