### ISSUE TITLE
How to handle exceeded heap size in async code?

### ISSUE THREAD

**Issue by dalibor-florian** [microsoft/ClearScript#369]
Hello,
i am trying to handle case when script exceeds memory limit.

For synchronous version of script it works like charm, when allocation meets the limit engine throws ScriptEngineException with expected message.

```
         [Test]
        public void MemoryLimitInSyncCode() 
        {
            using var engine = new V8ScriptEngine();
            engine.MaxRuntimeHeapSize = new UIntPtr(5 * 1024 * 1024);

            //throws Microsoft.ClearScript.ScriptEngineException: The V8 runtime has exceeded its memory limit
            Assert.Throws<ScriptEngineException>(() =>
                engine.Execute(
                    @"(function () {
                        let x = {};

                        for (let i = 0; i < 10 * 1024 * 1024; i++) {
                            x = {next: x};
                        }
                    })();")
            );
        }
```

In case of async code i can't figure out how to find out if the memory has been exceeded.
I would expect that the behaviour would be the same. 
When i tried it, i end up with stucked script execution. 

```
        [Test]
        public void MemoryLimitInAsyncCode()
        {
            using var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableTaskPromiseConversion);
            engine.MaxRuntimeHeapSize = new UIntPtr(5 * 1024 * 1024);
            engine.AddHostType(typeof(Task));

           var xxx =  Assert.ThrowsAsync<ScriptEngineException>(async () =>
                await (Task)engine.Evaluate(
                    @"(async function () {
                        let x = {};

                        for (let i = 0; i < 10 * 1024 * 1024; i++) {
                            if ((i % 20000) === 0) await Task.Delay(5);
                            x = {next: x};
                        }
                    })();")
            );
        }
```

Am i missing something? Is there some way how to handle this kind of errors?

tested on 
 - ClearScript 7.2.3
 - .net 6.0.202

**Comment by ClearScriptLib** [comment]
Hi @dalibor-florian,

Unfortunately, the heap size monitoring code is relatively old and predates much of V8 and ClearScript's async support. The problem in this case is that, when ClearScript detects that the heap size limit has been exceeded, it terminates script execution.

Script termination, while generally the best way to avoid a V8 crash, is catastrophic for async code, which relies on post-error processing for promise rejection and such.

To fix this, ClearScript will have to throw a script exception instead of terminating script execution. That'll be a breaking change, so we'll have to make the new behavior optional.

Thanks for reporting this!

**Comment by dalibor-florian** [comment]
Thanks for explanation.
For now, i am using workaround.
I create a task with each engine. Task periodically checks if the script has not exceeded the MaxRuntimeHeapSize and if so, I am finishing the script.
But it would be nice to have this feature within the engine itself.

**Comment by ClearScriptLib** [comment]
[Version 7.2.5](https://github.com/microsoft/ClearScript/releases/tag/7.2.5) added [`V8ScriptEngine.RuntimeHeapSizeViolationPolicy`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8ScriptEngine_RuntimeHeapSizeViolationPolicy.htm). See [here](https://github.com/microsoft/ClearScript/blob/70a9c6fb52c87fe89b420ce6fc935f760118cf2c/ClearScriptTest/V8ScriptEngineTest.cs#L3689) for the relevant test code. Thanks again!
