### ISSUE TITLE
Garbage collection stops once app receives SIGTERM signal

### ISSUE THREAD

**Issue by vbystricky21** [microsoft/ClearScript#371]
Hi,
Once our ASP.NET core app receives SIGTERM (used in Kubernetes as the standard way to initiate graceful shutdown), it stops freeing memory.
This issue seems to be connected to [370](https://github.com/microsoft/ClearScript/issues/370), but it is not the same as we tested versions where  [370](https://github.com/microsoft/ClearScript/issues/370) did not manifest itself, but this issue did.  Adding option [V8GlobalFlags.DisableBackgroundWork](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8GlobalFlags.htm) helped, but it is more workaround than a permanent solution.

Repro:
run this code 
```
using Microsoft.ClearScript.JavaScript;
using Microsoft.ClearScript.V8;

AppDomain.CurrentDomain.ProcessExit += (_, _) =>
{
    Console.WriteLine("Received SIGTERM");
    Console.ReadLine();
};

const int Size = 4096;
byte[] Bytes = CreateBytes();

V8Settings.GlobalFlags = V8GlobalFlags.DisableBackgroundWork;
using (var engine = new V8ScriptEngine())
{
    dynamic uint8ArrayFactoryFunc = engine.Evaluate(@"
            (function (length) {
                return new Uint8Array(length);
            })
            .valueOf();
        ");

    ITypedArray<byte> Alloc(long byteCount) => uint8ArrayFactoryFunc(byteCount);

    while (true)
    {
        var typedArray = Alloc(Size);
        typedArray.Write(Bytes, 0, Size, 0);
        engine.CollectGarbage(true);
    }
}

static byte[] CreateBytes()
{
    var bytes = new byte[Size];
    Array.Fill(bytes, (byte)42);
    return bytes;
}
```
send process SIGTERM e.g. via kill -s SIGTERM <pid>
and watch memory usage

**Comment by vbystricky21** [comment]
I was wrong  [V8GlobalFlags.DisableBackgroundWork](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8GlobalFlags.htm) it actually doesn't help.

**Comment by vbystricky21** [comment]
When you remove engine.CollectGarbage(true); from the previous code sample issue becomes much more visible

**Comment by ClearScriptLib** [comment]
Hello @vbystricky21,

This issue is unrelated to #370, and at first glance it seems unrelated to ClearScript – or even .NET, as the affected component appears to be V8 only – but we'll take a closer look.

In the meantime, we're curious: Is this issue preventing you from implementing graceful shutdown for your application?

Thanks!

**Comment by vbystricky21** [comment]
In Kubernetes, there is a workaround for this kind of issue. We can use a preStop hook mechanism that will block SIGTERM and enable us to re-implement a graceful shutdown. But this will force us to alter our current logic significantly.

**Comment by ClearScriptLib** [comment]
>But this will force us to alter our current logic significantly.

Would you mind elaborating on that? In what way does a memory leak – especially one that only occurs _after_ SIGTERM – complicate or interfere with graceful shutdown?

We modified your sample app above with support for graceful shutdown triggered by the `ProcessExit` event and found that it works just fine with the apparent leak. We tested it on Linux and used `kill` to send SIGTERM.

**Comment by vbystricky21** [comment]
We wait for the script to complete during a graceful shutdown. We don't cancel or stop anything. And in this case memory leak causes our app to crash.

**Comment by ClearScriptLib** [comment]
Hi @vbystricky21,

We can reproduce this issue in a console application that doesn't use ClearScript. The .NET runtime itself appears unable to finalize objects while the `ProcessExit` event handler is blocked. Here's the code:

``` C#
using System;
using System.Diagnostics;
using System.Threading;
namespace Test {
    internal class Foo {
        private readonly byte[] bytes = new byte[16 * 1024 * 1024];
        ~Foo() {
            Console.WriteLine("finalizing Foo");
        }
    }
    internal static class Program {
        public static void Main() {
            AppDomain.CurrentDomain.ProcessExit += (_, _) => {
                Console.WriteLine("Received SIGTERM");
                Console.ReadLine();
            };
            while (true) {
                new Foo();
                GC.Collect();
                using var process = Process.GetCurrentProcess();
                Console.WriteLine("{0:#,#} {1}", process.PrivateMemorySize64, process.Id);
                Thread.Sleep(200);
            }
        }
    }
}
```

Once you use `kill` to send this application SIGTERM, it stops printing "finalizing Foo", and its memory usage starts increasing rapidly. Therefore it would appear that this issue is not related to ClearScript.

Thanks!

**Comment by vbystricky21** [comment]
Thank you for your effort!  It seems to be unrelated to ClearScript. I will close this issue for now and continue to investigate it independently.

**Comment by simontom** [comment]
You can see [here](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/finalizers#example)

![image](https://user-images.githubusercontent.com/1636523/166525019-b464314c-e2f9-4291-8bd6-1222a6688645.png)
