### ISSUE TITLE
Host methods with void return type should return undefined

### ISSUE THREAD

**Issue by KurtGokhan** [microsoft/ClearScript#372]
If a host method has `void` return type, an object typed `Microsoft.ClearScript.VoidResult` will be returned when the method is called from script side. For example:

```csharp
// C# side

public void MyMethod() { }

// Javascript side

var result = myClass.MyMethod();
var isUndefined = result === undefined; // false
var isNullish = result == null; // false

```

As discussed in issue #298, `toFunction` can be used or the function can be wrapped to basically customize this behavior. But I am questioning if there is any use case where returning `VoidResult` to script side is useful. 

Maybe it can return `undefined` or `Microsoft.ClearScript.Undefined` (I don't know if those two would be the same thing). Or there could be a configuration for this like `VoidExportValue`, like how there is a configuration for `UndefinedImportValue` (which is a life-saver for me tbh).

**Comment by ClearScriptLib** [comment]
Hi @KurtGokhan,

Sounds reasonable and straightforward. `ScriptEngine.VoidResultValue` incoming!

Thanks!

**Comment by ClearScriptLib** [comment]
[Version 7.2.5](https://github.com/microsoft/ClearScript/releases/tag/7.2.5) added [`ScriptEngine.VoidResultValue`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_VoidResultValue.htm). Thanks!
