### ISSUE TITLE
Why not export the Array class like ScriptArray, or give a flag to point the ScriptObject is Array?

### ISSUE THREAD

**Issue by feiyin0719** [microsoft/ClearScript#374]
When I get the object from JavaScript, I just get the ScriptObject, but it is too inconvenient to convert it , Can you export some other object like Array or Dictionary to help converting

**Comment by ClearScriptLib** [comment]
Hi @feiyin0719,

>I just get the ScriptObject, but it is too inconvenient to convert it

With some exceptions, ClearScript favors giving the host full access to script objects over conversion. The problem with conversion is that it's both costly and lossy.

Also, if you're using V8, arrays implement [`IList`](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ilist), so there's no need to convert them:

``` C#
var jsArray = (IList)engine.Evaluate("[1,2,3,4,5]");
foreach (var item in jsArray) {
    Console.WriteLine(item);
}
```

Good luck!

**Comment by ClearScriptLib** [comment]
Feel free to reopen this issue if you have additional questions on this topic. Thanks!
