### ISSUE TITLE
IPropertyBag not support JSON.stringify in V8

### ISSUE THREAD

**Issue by feiyin0719** [microsoft/ClearScript#376]
I want to pass a C# object to JS, when I used IPropertyBag, I found that when I use JSON.stringify in JS, it will return "{}" json string, how should I assign a C# object to JS?

**Comment by ClearScriptLib** [comment]
Hi @feiyin0719,

Please clarify. Do you need to use the C# object on the JavaScript side, or do you just need its JSON representation? Or both?

Thanks!

**Comment by feiyin0719** [comment]
I need both

**Comment by feiyin0719** [comment]
I need to use C# object use in JavaScript side , and can use  JSON.stringify to serialization the c# object in JavaScript side

**Comment by feiyin0719** [comment]
ok, I will try it, thanks

**Comment by feiyin0719** [comment]
yes, This solves the problem, but can we provide a way to make c# objects work like javascript objects? For example, the JSI(JavaScript interface) in React Native. I have tried to provide an object implement the getPropertyNames, hasOwnProperty method, but it cannot work. I think this can make the communication between c# and javascript more convenient

**Comment by ClearScriptLib** [comment]
Hi @feiyin0719,

>This solves the problem, but can we provide a way to make c# objects work like javascript objects in JS? For example, the JSI(JavaScript interface) in React Native.

One of ClearScript's main goals is to allow script code to access .NET objects and types _without_ special coding. There's no need to implement `getPropertyNames` – or any such method – when you can simply do this:

``` C#
// use a .NET object in script code
engine.AddHostObject("myObj", new MyClass());
engine.Execute("myObj.MyMethod()");

// use a .NET type in script code
engine.AddHostType(typeof(MyClass));
engine.Execute(@"
    const myObj = new MyClass();
    myObj.MyMethod();
");
```

.NET and JavaScript have radically different type systems, so .NET objects can't always behave _exactly_ like script objects. but ClearScript tries to provide convenient access. If the result isn't sufficiently "JavaScript-like", you can always hide ClearScript's .NET objects within pure JavaScript wrappers:

``` C#
dynamic setup = engine.Evaluate(@"(function (myClrObject) {
    globalThis.MyJsObject = {
        myMethod: () => myClrObject.MyMethod()
    }
})");
setup(new MyClass());
engine.Execute("MyJsObject.myMethod()");
```

This approach should yield much better performance than handling low-level JavaScript operations in .NET.

Cheers!

**Comment by feiyin0719** [comment]
ok, I got it, but if I want to use some js lib,It will be a little more cumbersome to deal with

**Comment by ClearScriptLib** [comment]
Hello @feiyin0719,

>if I want to use some js lib,It will be a little more cumbersome to deal with

Unfortunately, it seems like most JavaScript libraries out there assume either a web browser or Node.js environment, requiring modifications to work correctly in a bare JavaScript setting.

Our hope is that, by providing easy access to .NET objects from script code, and vice versa, ClearScript enables you to construct whatever script API you require with the least amount of work.

The ability to serialize host objects via `JSON.stringify` is a frequent request, so we'll keep this issue open and look into improving support for that in a future release. If you encounter other specific obstacles, please create a new issue and let us know.

Thanks!
