### ISSUE TITLE
how to show  js log

### ISSUE THREAD

**Issue by heartacker** [microsoft/ClearScript#377]
hi, how can we show the js log  to the command windows via `console.log('hello world');`

**Comment by heartacker** [comment]
I have try the **ClearScriptConsole** project and it is the result

![image](https://user-images.githubusercontent.com/1876302/167802854-f48fd67a-1539-4fe5-887e-aed4116bafad.png)

**Comment by ClearScriptLib** [comment]
Hi @heartacker,

The [`console`](https://developer.mozilla.org/en-US/docs/Web/API/console) object is part of the large [Web API](https://developer.mozilla.org/en-US/docs/Web/API) that's provided by browsers. As you can see [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects), it isn't part of the standard JavaScript library.

Surprisingly, as you've discovered, V8 _does_ provide a `console` object – and this is the first V8 extension to the JavaScript standard that we've encountered – but it doesn't work as you'd expect.

You can use the standard .NET [`Console`](https://docs.microsoft.com/en-us/dotnet/api/system.console) class to implement `console`. Here's a simple example:

``` C#
engine.AddHostType(typeof(Console));
engine.Execute(@"
    console = {
        log: value => Console.WriteLine(value),
        warn: value => Console.WriteLine('WARNING: {0}', value),
        error: value => Console.WriteLine('ERROR: {0}', value)
    };
");
```

Good luck!

**Comment by ClearScriptLib** [comment]
Feel free to reopen this issue if you have additional questions on this topic. Thanks!
