### ISSUE TITLE
Bypass AllowReflection=false

### ISSUE THREAD

**Issue by dalibor-florian** [microsoft/ClearScript#382]
Hi, during penetration testing of our solution we found a way how to bypass AllowReflection settings.
In following example you can find basic example how to do it.

```

    public class ThrowingClass
    {
	    public void Throw()
        {
            throw new Exception();
        }
    }
        
    [Test]
    public void AccessToAssembly()
    {
        using var engine = new V8ScriptEngine();
        engine.AllowReflection = false;
        engine.AddHostType(typeof(ThrowingClass));
        
        engine.Evaluate(
            @"(function () {
                let throwingClass = new ThrowingClass();
                try {
                    throwingClass.Throw();
                } catch(e) {                
                    var assembly = e.hostException.TargetSite.GetParameters()[0].ParameterType.Assembly;
                    //load anything from assembly
                }
            })();"
        );
    }

```

Would it be possible to forbid passing of Type instances from .NET to JS?
I believe that there can be other way how to access types and this might be bullet proof solution.

Tested on ClearScript 7.2.5.

**Comment by Bobris** [comment]
Another posibility to fix this could be to make exposing hostException optional, we would gladly disable this feature.

**Comment by ClearScriptLib** [comment]
Hi @dalibor-florian,

Thank you for reporting this! We'll add `Exception.TargetSite` to the list of properties affected by `AllowReflection`. Please let us know if you find additional holes.

>Would it be possible to forbid passing of Type instances from .NET to JS?

We'd prefer not to do that. `System.Type` is an abstract class, and we've encountered a surprising number of custom derivations, some of which are barely related to standard reflection.

Thanks again!

**Comment by ClearScriptLib** [comment]
Hi @Bobris,

>Another posibility to fix this could be to make exposing hostException optional, we would gladly disable this feature.

We added `hostException` after several users requested it. If the feature is undesirable in your scenario, please let us know why.

Thanks!

**Comment by ClearScriptLib** [comment]
Hi @Bobris,

>We want to be very cautious what to exposed to JS, first security wise, but second compatibility wise - think of it if we ever wanted to exchange ClearScript by another implementation we would need to emulate all this functionality or we cloud break customer scripts.

Interesting. Normally we'd point out that ClearScript starts with a blank slate – an environment containing only the standard JavaScript built-in objects – and lets you expose as much or as little as you want.

However, exceptions are different in that there's little control over their behavior at the host-script boundary. You could hide `hostException` by wrapping your host API within script objects, but that could get very tedious.

We'll provide a way to suppress `hostException` in the next release. Thanks for suggesting it!

**Comment by dalibor-florian** [comment]
Hi @ClearScriptLib , when do yout think a version with bugfix could come out?

**Comment by ClearScriptLib** [comment]
[ClearScript 7.3](https://github.com/microsoft/ClearScript/releases/tag/7.3.0) addressed both issues discussed above.
