### ISSUE TITLE
VS Code debugger crashes with exit code 0 on .NET 6 / MacOS / arm64

### ISSUE THREAD

**Issue by NuclearFishin** [microsoft/ClearScript#385]
I've uncovered an issue whereby attempting to step-over the ClearScript engine execution via the VS Code debugger will crash the debugger with exit code 0, and no further error information. The scame code runs without issue when executed via `dotnet run`.

I've created minimal reproduction console app, available here.

https://github.com/NuclearFishin/DebugFailDemo

I suspect this might be a .NET Core MacOS (and Linux) specific issue, based on similar bug reports I've found reporting debugger crashes in VS Code:

https://github.com/OmniSharp/omnisharp-vscode/issues/3655

https://github.com/dotnet/runtime/issues/12739

In my case, this issue occurred on MacOS Monterey 12.4, running .NET Core 6 for MacOS/arm64 (ie Mac M1 chip).

This repo contains a minimal console app that executes the ClearScript engine
over a JS file that renders a `<div>` via React. 

The console app excutes without issue when executed via `dotnet run`:

```
% dotnet run
Hello, World!
<div>Hello world</div>
Finished. Press enter
```

Likewise the script also runs without issue when invoking directly via node:

```
% node --version
v16.14.0
% node webpack-output.js 
<div>Hello world</div>
```

However, when attaching the VS Code debugger, and attempting to step-over line
15 in `DemoConsoleApp/Program.cs`, namely

```csharp
engine.ExecuteDocument(@"webpack-output.js");
```

...the app terminates with the following output in the debug console:

```
The program '[22971] DemoConsoleApp.dll' has exited with code 0 (0x0).
```

It's also worth noting that just running via the debugger with no breakpoints will also fail on the same line.

There is no other information output via the debug console, so I cannot
determine how to fix this issue. Hope you can help! Happy to provide any further information required!

## System Info

Operating system: 

```
Macos Monterey 12.4 (21F79)
```

CPU:

```
Apple M1 Pro
```

VS Code version:
```
Version: 1.67.2 (Universal)
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:57.384Z
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0
```

.NET Core version:
```
% dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  12.4
 OS Platform: Darwin
 RID:         osx.12-arm64
 Base Path:   /usr/local/share/dotnet/sdk/6.0.201/

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  6.0.201 [/usr/local/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.3 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by ClearScriptLib** [comment]
Hi @NuclearFishin,

This issue is related to Apple Silicon code security.

V8 uses JIT compilation. For macOS to permit that on arm64, the parent application must include certain entitlements in its signature, and apparently VS Code, like many other applications, doesn't.

We're aware of two ways to get around this issue:

1. It seems that macOS bypasses JIT enforcement if the errant module carries an ad-hoc linker signature. Presumably that's intended to facilitate local testing, but that's unclear. In any case, see [here](https://github.com/microsoft/ClearScript/issues/318#issuecomment-966831720) for the relevant instructions.

2. You can use [`V8Settings.GlobalFlags`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8Settings_GlobalFlags.htm) to turn off JIT compilation.

Please let us know if these workarounds do not resolve the issue for you.

Thanks!

**Comment by NuclearFishin** [comment]
Thanks very much @ClearScriptLib!

I can conifrm that option 2 fixed the issue for me in my example repo:

```csharp
V8Settings.GlobalFlags |= V8GlobalFlags.DisableJITCompilation;
```

This is a suitable workaround for me, so I'm happy for this issue to be closed.

It might be a good idea to put this in the [FAQtorial](https://microsoft.github.io/ClearScript/Tutorial/FAQtorial.html), as other MacOS users might get tripped up on this one. I'd be happy to help with this in return for investigating my issue :)

Thanks again!

**Comment by ClearScriptLib** [comment]
Thanks, @NuclearFishin!

We'll document this aspect of using ClearScript on Apple Silicon in a blog post – once we understand exactly how macOS JIT security works. At the moment, all we have is a workaround that we discovered by trial and error – one that _shouldn't_ work according to all the Apple documentation we've been able to find 🤣

Please feel free to reopen this issue if you encounter additional unexplained crashes on Apple Silicon.
