### ISSUE TITLE
"Object doesn't support this property or method" with VBScriptEngine

### ISSUE THREAD

**Issue by EtienneLaneville** [microsoft/ClearScript#386]
I've been troubleshooting a Type Mismatch exception when trying to use object properties that are enums with VBScript. In trying to reproduce this, I started with the following enum and class (from another ticket):

```
public enum Kingdom { Plant, Animal };
public class Being
{
    public String Name { get; set; } = "Being";
    public Kingdom Kingdom { get; set; }
}
```
Then, I created a VBScriptEngine instance to check if I can access the Being.Kingdom property:

```
using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
{

    host.HostWindow = new HostWindow();

    Being cat = new Being();
    cat.Name = "Felix";
    cat.Kingdom = Kingdom.Animal;

    host.AddHostType(typeof(Kingdom));
    host.AddHostObject("cat", cat);

    host.Execute("MsgBox \"Test\"");
    host.Execute("MsgBox cat.Name");
    host.Execute("MsgBox cat.Kingdom");
    host.Execute("MsgBox cat.Kingdom = Kingdom.Animal");

}
```

The first Execute (MsgBox \"Test\" but the next one (MsgBox cat.Name) throws an exception:
_Object doesn't support this property or method: cat.Kingdom_

For reference, this is the HostWindow class used:
```
class HostWindow : Microsoft.ClearScript.Windows.IHostWindow
{
    public IntPtr OwnerHandle
    {
        get { return IntPtr.Zero; }
    }

    public void EnableModeless(bool enable)
    {
        return;
    }
}
```

_Originally posted by @EtienneLaneville in https://github.com/microsoft/ClearScript/issues/156#issuecomment-1154541414_

**Comment by ClearScriptLib** [comment]
Hi @EtienneLaneville,

We tested your sample code and observed the following:

- `MsgBox "Test"` works as expected, showing "Test".

- `MsgBox cat.Name` works as expected, showing "Felix".

- `MsgBox cat.Kingdom` fails with a "Type mismatch" error. That's because ClearScript exposes .NET enums as _objects_, and VBScript can't convert objects to strings. `MsgBox cat.Kingdom.ToString()` works as expected, showing "Animal".

- `MsgBox cat.Kingdom = Kingdom.Animal` fails with a "Type mismatch" error. That's because VBScript's equality operator doesn't work with objects. `MsgBox cat.Kingdom is Kingdom.Animal` works as expected, showing "True".

All of the observed behavior seems correct. Would you mind retesting? Are you still seeing "Object doesn't support this property or method" errors? Do the modifications above work for you?

Thanks!

**Comment by EtienneLaneville** [comment]
In Visual Studio 2022, I created two projects, one in C# and one in VB.NET (thinking there could be a difference) with the following:

- Packages Microsoft.ClearScript.Core (7.3.0) and Microsoft.ClearScript.Windows (7.3.0)
- Windows Forms project
- .NET 6

Both projects give me the same exception (Object doesn't support this property or method: cat.Kingdom). Here's the entire code I have been testing with:

C# Program.cs

```
namespace ClearScriptTesting
{
    internal static class Program
    {

        public enum Kingdom { Plant, Animal };
        public class Being
        {
            public String Name { get; set; } = "Being";
            public Kingdom Kingdom { get; set; }
        }

        class HostWindow : Microsoft.ClearScript.Windows.IHostWindow
        {
            public IntPtr OwnerHandle
            {
                get { return IntPtr.Zero; }
            }

            public void EnableModeless(bool enable)
            {
                return;
            }
        }

        /// <summary>
        ///  The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {

            // To customize application configuration such as set high DPI settings or default font,
            // see https://aka.ms/applicationconfiguration.
            ApplicationConfiguration.Initialize();


            using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
            {

                host.HostWindow = new HostWindow();

                Being cat = new Being();
                cat.Name = "Felix";
                cat.Kingdom = Kingdom.Animal;

                host.AddHostType(typeof(Being));
                host.AddHostType(typeof(Kingdom));
                host.AddHostObject("cat", cat);

                host.Execute("MsgBox \"Test\"");
                host.Execute("MsgBox cat is Nothing");
                host.Execute("MsgBox cat.Name");
                host.Execute("MsgBox cat.Kingdom");
                host.Execute("MsgBox cat.Kingdom = Kingdom.Animal");

            }

            Application.Run(new Form1());
        }

    }
}
```

VB.NET ApplicationEvents.vb:

```
Imports System.Runtime.InteropServices
Imports Microsoft.ClearScript.Windows
Imports Microsoft.VisualBasic.ApplicationServices

Namespace My

    Partial Friend Class MyApplication

        Public Enum Kingdom
            Plant
            Animal
        End Enum

        Public Class Being
            Public Property Name As String = "Being"
            Public Property Kingdom As Kingdom
        End Class

        Public Class HostWindow
            Implements Microsoft.ClearScript.Windows.IHostWindow

            Public ReadOnly Property OwnerHandle As IntPtr Implements IHostWindow.OwnerHandle
                Get
                    Return IntPtr.Zero
                End Get
            End Property

            Public Sub EnableModeless(enable As Boolean) Implements IHostWindow.EnableModeless
                Return
            End Sub

        End Class

        Private Sub MyApplication_Startup(sender As Object, e As StartupEventArgs) Handles Me.Startup

            Using host As New Microsoft.ClearScript.Windows.VBScriptEngine

                host.HostWindow = New HostWindow()

                Dim cat As Being = New Being()
                cat.Name = "Felix"
                cat.Kingdom = Kingdom.Animal

                host.AddHostType(GetType(Being))
                host.AddHostType(GetType(Kingdom))
                host.AddHostObject("cat", cat)

                host.Execute("MsgBox ""Test""")
                host.Execute("MsgBox cat is Nothing")
                host.Execute("MsgBox cat.Name = ""Jimbo""")
                host.Execute("MsgBox cat.Name")
                host.Execute("MsgBox cat.Kingdom")
                host.Execute("MsgBox cat.Kingdom = Kingdom.Animal")

            End Using

        End Sub

    End Class

End Namespace

```

Ultimately I have been trying to work around the difference in Enum properties compared to MSScriptControl. With MSScriptControl, enums seem to be handled as their Integer value and that's where my scripts have been causing Type Mismatch errors with ClearScript. Your answer has been helpful in understanding how Enums are handled so I will try to adjust my scripts but it sounds like having scripts compatible with both ClearScript and MSScriptControl is not going to be possible. My goal is to move away from MSScriptControl so backwards-compatibility is not a problem. 

I am going to close this ticket because you have answered my question but I wanted to provide the complete code that caused the exception in case someone else runs into the same issue.

**Comment by ClearScriptLib** [comment]
Hi @EtienneLaneville,

>With MSScriptControl, enums seem to be handled as their Integer value and that's where my scripts have been causing Type Mismatch errors with ClearScript.

That's correct. ClearScript doesn't convert enums to integers, because such conversion is _lossy_. One potential problem is that it could break method invocation. For example, consider the following .NET method:

``` C#
public void Foo(Kingdom arg) { ... }
```

If ClearScript converted enums to integers, a call such as `Foo(Kingdom.Animal)` would fail, because there's no implicit conversion from integer back to enum. Worse, if the method were overloaded, such a call could invoke the wrong overload:

``` C#
public void Foo(Kingdom arg) { ... }
public void Foo(SomeOtherEnum arg) { ... }
public void Foo(int arg) { ... }
```

>it sounds like having scripts compatible with both ClearScript and MSScriptControl is not going to be possible

Well, not exactly. You have control over what you expose to the script engine. If strongly typed enums are a problem in your scenario, you could expose a [facade](https://en.wikipedia.org/wiki/Facade_pattern) that uses integers instead.

Please feel free to reopen this issue if you have additional questions or thoughts about this topic.

Good luck!

**Comment by EtienneLaneville** [comment]
I ran into the "Object doesn't support this property or method: cat.Name" issue again as I was upgrading my scripts.

![image](https://user-images.githubusercontent.com/18358729/173661979-141cc6ca-1d54-4985-8b5e-a9274dcc1937.png)

In a separate .NET application I have a function that returns an object or Nothing. I am able to deal with the Nothing value using what was explained in issue #106. In that scenario I use another function to create the object:

`Set obj = CreateNewObject`

When I try accessing properties on that object in VBScript, I get the same problem where it doesn't recognize the object's properties. It seems like it doesn't recognize the object's type.

Here is some code that should replicate this problem:

```
public enum Kingdom { Plant, Animal };
public class Being
{
    public String Name { get; set; } = "Being";
    public Kingdom Kingdom { get; set; }

    public Being(string name) 
    { 
        this.Name = name;
    }

}
public class Creator
{
    public Being CreateBeing(string name)
    {
        return new Being(name);
    }
}
```
I've added a Creator class from which I want to create new objects and use them on the script side:

```
using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
{

    host.HostWindow = new HostWindow();

    Creator creator = new Creator();
    Being cat = new Being("Felix");
    cat.Kingdom = Kingdom.Animal;

    host.AddHostType(typeof(Creator));
    host.AddHostType(typeof(Being));
    host.AddHostType(typeof(Kingdom));

    host.AddHostObject("creator", creator);
    host.AddHostObject("cat", cat);

    host.Execute("MsgBox \"Test\"");
    host.Execute("MsgBox cat is Nothing");
    host.Execute("MsgBox creator.CreateBeing(\"Test\").Name");
    host.Execute("MsgBox cat.Name");
    host.Execute("MsgBox cat.Kingdom");
    host.Execute("MsgBox cat.Kingdom = Kingdom.Animal");

}
```
With this code I get essentially the same exception:
![image](https://user-images.githubusercontent.com/18358729/173665093-5368ead2-1afd-474c-9ad7-9fd17f4f6b83.png)

**Comment by ClearScriptLib** [comment]
Hello @EtienneLaneville,

>With this code I get essentially the same exception

That's because "creator" actually refers to the `Creator` host type, which has no static method `CreateBeing`.

Here's what's going on. Your setup code includes the following:

``` C#
host.AddHostType(typeof(Creator));
// other code
host.AddHostObject("creator", creator);
```

These lines create two host items: `Creator` referring to the type, and `creator` referring to the instance. However, VBScript is _case-insensitive,_ so the name "creator" ends up binding to the former rather than the latter, probably because it was created first.

The script code above doesn't actually use `Creator` the type, so you can delete the line that adds it to eliminate the exception.

Cheers!

**Comment by EtienneLaneville** [comment]
Thanks for your response. I've removed the line that add the Creator type to the engine but I am not getting any further, I get the same _Object doesn't support this property or method: creator.CreateBeing_ exception.

Here are the steps that I take, hopefully something here will stand out:

1. Start Visual Studio 2022.
2. Select Create New Project
3. Select Windows Forms App
4. Select .NET Framework 4.7.2
5. In Solution Explorer, right-click References, then select "Manage NuGet Packages..."
6. Browse for ClearScript
7. Install Microsoft.ClearScript (7.3.0)
8. In `Program.cs`, add the following in the `Program` class:
```
public class Being
{
    public String Name { get; set; } = "Being";

    public Being(string name)
    {
        this.Name = name;
    }

}

class HostWindow : Microsoft.ClearScript.Windows.IHostWindow
{
    public IntPtr OwnerHandle
    {
        get { return IntPtr.Zero; }
    }

    public void EnableModeless(bool enable)
    {
        return;
    }
}
```
9. Update `Main`:
```
static void Main()
{
    using (var host = new Microsoft.ClearScript.Windows.VBScriptEngine())
    {

        host.HostWindow = new HostWindow();

        Being cat = new Being("Felix");
        host.AddHostType(typeof(Being));

        host.AddHostObject("cat", cat);

        host.Execute("MsgBox \"Test\"");
        host.Execute("MsgBox cat.Name");

    }

}
```
10. When running the project, you should see a Test message box which confirms the VBScript engine is working and then an exception on the `host.Execute("MsgBox cat.Name");` line:

![image](https://user-images.githubusercontent.com/18358729/173694079-4ce66adc-16f7-4280-9890-123756b3c5ed.png)

**Comment by EtienneLaneville** [comment]
Figured out the problem: The code doesn't work when it is in the `internal static class Program` class. Using the following class, everything works as expected:

```
public class EngineTest
{

    private Microsoft.ClearScript.Windows.VBScriptEngine _host = new Microsoft.ClearScript.Windows.VBScriptEngine();

    public EngineTest()
    { 
        
        _host.HostWindow = new HostWindow();

    }

    public void Test()
    {

        Being cat = new Being("Felix");
        _host.AddHostType(typeof(Being));

        _host.AddHostObject("cat", cat);

        _host.Execute("MsgBox \"Test\"");
        _host.Execute("MsgBox cat.Name");
    }
    public class Being
    {
        public String Name { get; set; } = "Being";

        public Being(string name)
        {
            this.Name = name;
        }

    }

    class HostWindow : Microsoft.ClearScript.Windows.IHostWindow
    {
        public IntPtr OwnerHandle
        {
            get { return IntPtr.Zero; }
        }

        public void EnableModeless(bool enable)
        {
            return;
        }
    }
}
```

**Comment by ClearScriptLib** [comment]
>The code doesn't work when it is in the `internal static class Program` class.

Ah, yes. Member visibility enforcement is often the hidden cause of such issues. Thanks for posting the solution!
