### ISSUE TITLE
Cannot iterate arrays with non-public iterators

### ISSUE THREAD

**Issue by KurtGokhan** [microsoft/ClearScript#389]
I am having an error when trying to iterate arrays in script side. The error is `TypeError: a.Dispose is not a function` and it happens in `toIterator` of EngineInternals.

```cs
// Setup
public class MyClass : IEnumerable<string>
{
    public IEnumerator<string> GetEnumerator() => new MyIterator();
    IEnumerator IEnumerable.GetEnumerator() => new MyIterator();

    private class MyIterator : IEnumerator<string>
    {
        int i = -1;
        public string Current => i == 0 ? "item1" : "item2";
        object IEnumerator.Current => Current;
        public void Dispose() { }
        public bool MoveNext() => i++ < 1;
        public void Reset() => i = 0;
    }
}

// Test
var list = new MyClass();
Engine.Global.SetProperty("list", list);
Assert.AreEqual("item1,item2", Engine.ExecuteCommand("Array.from(list).join(',')"));
```

If `MyIterator` is public, the above test works.

This is a problem in Mono because Array iterator is implemented as internal as seen in the [source code] (https://github.com/mono/mono/blob/main/mcs/class/corlib/System/Array.cs#L237). This bug makes it not possible to call script functions from C#, because it uses arrays internally. It is possible to call them with a workaround such as converting array to List first.

I think the most comprehensive solution would be that even if a class is private, if it implements an interface, interface properties should be exposed. In this case `MyIterator` is private but it implements `IEnumerator` and its methods such as `MoveNext` should be exposed to script.

**Comment by KurtGokhan** [comment]
Just tested the code above inside ClearScript project. It works. I wonder why it does not work in Unity.

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts, questions, or information about this topic. Thank you!
