### ISSUE TITLE
Is there a way to capture the object thrown from the javascript?

### ISSUE THREAD

**Issue by liuhongbo** [Microsoft/ClearScript#39]
For example, we can write JavaScript like this:

```
var test = {
    a:'this is a demo',
    b: 100
};
throw test;
```
 

then in the c#/host side, we can catch the ScriptEngineException. However, The exception will look like this (Converted to Json string for easy to read):

```
{
   "ClassName":"Microsoft.ClearScript.ScriptEngineException",
   "Message":"[object Object]",
   "Data":{

   },
   "InnerException":null,
   "HelpURL":null,
   "StackTraceString":"   ...,
   "RemoteStackTraceString":null,
   "RemoteStackIndex":0,
   "ExceptionMethod":"8\nV8Exception.ThrowScriptEngineException\nClearScriptV8-32, Version=5.4.6.0, Culture=neutral, PublicKeyToken=935d0c957da47c73\nVoid V8Exception.ThrowScriptEngineException(V8Exception*)",
   "HResult":-2146233079,
   "Source":"ClearScriptV8-32",
   "WatsonBuckets":null,
   "ScriptEngineName":"b5ddbce9-b0ce-4fdd-8bce-c0bc3096af33:",
   "ScriptErrorDetails":"[object Object]\n    at 23b147c2-5bbc-4ea2-b366-5998dc365279 [temp]:12:1 -> throw test;\n    at 23b147c2-5bbc-4ea2-b366-5998dc365279 [temp]:14:6\n    at 23b147c2-5bbc-4ea2-b366-5998dc365279 [temp]:16:2",
   "IsFatal":false,
   "ExecutionStarted":true
}
```

Is there a way in the c#/host, the ScriptEngineException can have the value of the object thrown by the exception?  That can help the host side to process the exception.

**Comment by ClearScriptLib** [comment]
Hi @liuhongbo,

You can catch the object in JavaScript code and return it to the host.

Here's a sample extension method that runs arbitrary code and returns either its return value or any exception object thrown during execution:

``` C#
public static class ScriptEngineExtensions {
    public static object TryEvaluate(this ScriptEngine engine, string code) {
        object tryCatch = engine.Script.__tryCatch;
        if (tryCatch is Undefined) {
            tryCatch = engine.Evaluate(@"
                __tryCatch = function (code) {
                    try {
                        return { succeeded: true, returnValue: eval(code) };
                    }
                    catch (exception) {
                        return { succeeded: false, exception: exception };
                    }
                }
            ");
        }
        return ((dynamic)tryCatch)(code);
    }
}
```

And here's how you might use it:

``` C#
dynamic result = engine.TryEvaluate("Math.PI");
Console.WriteLine(result.succeeded); // True
Console.WriteLine(result.returnValue); // 3.14159265358979

result = engine.TryEvaluate("throw { foo: 123, bar: 456 }");
Console.WriteLine(result.succeeded); // False
Console.WriteLine(result.exception.foo); // 123
Console.WriteLine(result.exception.bar); // 456
```

Good luck!

**Comment by liuhongbo** [comment]
thanks for the example.  
That works if i have control of the script.  How about if I have no control of the script?  For example, I could write a c# program that will execute the script that user will write.  In this scenario,  it that possible the ClearScript can still capture the data object throwing in the js and wrapped in the c# exception?

**Comment by ClearScriptLib** [comment]
Hi @liuhongbo,

Actually, the `TryEvaluate` method internally handles exceptions and creates the result object, so you can pass any code into it.

However, we'll keep this issue open and look into the possibility of providing access to the script exception from the managed exception.

Thanks!

**Comment by ClearScriptLib** [comment]
[Version 5.5.2](https://github.com/Microsoft/ClearScript/releases/tag/5.5.2) includes the new property [`IScriptEngineException.ScriptException`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_IScriptEngineException_ScriptException.htm).
