### ISSUE TITLE
`InputBox`: cancel vs empty string

### ISSUE THREAD

**Issue by valinet** [microsoft/ClearScript#390]
Is there any way, for an `InputBox`, to differentiate between the user clicking the `Cancel` button and the user clicking `OK` and the text box being an empty string being?

As far as I can tell, as it currently stands, both actions produce the same object of type `Microsoft.ClearScript.Undefined`.

Sample code in C#:

```
var obj = engine.Evaluate("InputBox(\"Type here:\", \"" + dialog_title + "\", \"\")");
if (obj is Microsoft.ClearScript.Undefined)
{
    Console.WriteLine(":(");
}
```

I have the following code in C which correctly detects the user pressing Cancel vs pressing Ok with an empty text field:

```
VARIANT result;
VariantInit(&result);
pActiveScriptParse->lpVtbl->ParseScriptText(pActiveScriptParse, wszEvaluation2, NULL, NULL, NULL, 0, 0, SCRIPTTEXT_ISEXPRESSION, &result, &ei);
BOOL bWasCancelled = (result.vt == VT_EMPTY);
// else, the field's content was empty or not, it is stored in result.bstrVal
```

I don't know exactly how this thing is implemented here internally, but a differentiation has to be made between when the VARIANT returned by `ParseScriptText` is VT_EMPTY, or when it contains a BSTR string that is empty, aka "".

**Comment by ClearScriptLib** [comment]
Hi @valinet,

Well, that's an interesting find. ClearScript uses [`Marshal.GetObjectForNativeVariant`](https://docs.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.getobjectfornativevariant) to convert VBScript evaluation results to .NET values. Apparently that method returns `null` for a `VT_BSTR/NULL` variant.

As far as we can tell, that's a bug in .NET. According to [this article](https://docs.microsoft.com/en-us/archive/blogs/ericlippert/erics-complete-guide-to-bstr-semantics), a `NULL` `BSTR` must be treated as an empty string. In other words, unlike .NET's [`string`](https://docs.microsoft.com/en-us/dotnet/api/system.string), `BSTR` isn't semantically nullable, so a variant of type `VT_BSTR` should never be converted to `null`.

The good news is that `ScriptEngine.Evaluate` has full access to the result variant and could easily detect this case to work around the bug. We'll implement that in the next release.

The bad news is that .NET makes the same mistake when converting method arguments passed from script code. In theory ClearScript could work around that too, but it would be a lot more work and quite a bit of tricky low-level code.

Luckily, VBScript doesn't appear to use `VT_BSTR/NULL` variants very often. In fact, the `InputBox` return value is the only case of which we're currently aware. Also fortunate is that VBScript seems to normalize `VT_BSTR/NULL` to `VT_BSTR/""` when assigning variables. That enables the following temporary workaround:

``` C#
public static class VBScriptEngineExtensions {
    public static object Evaluate2(this VBScriptEngine engine, string code) {
        if (engine.Global.GetProperty("Eval2") is Undefined) {
            engine.Execute("Function Eval2(code) : result = Eval(code) : Eval2 = result : End Function");
        }
        return engine.Global.InvokeMethod("Eval2", code);
    }
}
```

And then:

``` C#
var obj = engine.Evaluate2("InputBox(\"Type here:\", \"" + dialog_title + "\", \"\")");
if (obj is Undefined)
{
    Console.WriteLine(":(");
}
```

Thanks for reporting this!

**Comment by ClearScriptLib** [comment]
[Version 7.3.1](https://github.com/microsoft/ClearScript/releases/edit/7.3.1) fixed the `InputBox` return value.
