### ISSUE TITLE
GetHeapInfo / GetRuntimeHeapInfo does not reflect usage in Uint8Array

### ISSUE THREAD

**Issue by ColonelBundy** [microsoft/ClearScript#391]
If I allocate any amount in a Uint8Array, that would not be visible in GetHeapInfo / GetRuntimeHeapInfo in any way. I assume this is only measurable in HeapSpaceStatistics? if that's the case, can we expose this function?

**Comment by ClearScriptLib** [comment]
Hi @ColonelBundy,

The V8 API that underlies `GetHeapInfo` et al has been updated and now returns an "external" memory size, which seems to include the total size of _private_ array buffers. We'll surface that in the next release.

Unfortunately, we're not aware of a way to retrieve the total size of _shared_ array buffers.

Thanks!

**Comment by ClearScriptLib** [comment]
[Version 7.3.1](https://github.com/microsoft/ClearScript/releases/tag/7.3.1) added [`V8RuntimeHeapInfo.TotalAvailableSize`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeHeapInfo_TotalAvailableSize.htm) and [`TotalExternalSize`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_V8_V8RuntimeHeapInfo_TotalExternalSize.htm).
