### ISSUE TITLE
.net 3.5 support?

### ISSUE THREAD

**Issue by grimmdev** [Microsoft/ClearScript#4]
I tried using .net 3.5 however seems to be quite a few functions don't exist, best way to get it working with 3.5 .net or is it even possible?

**Comment by ClearScriptLib** [comment]
@grimmdev, ClearScript depends heavily on the [Dynamic Language Runtime](https://msdn.microsoft.com/en-us/library/dd233052(v=vs.110).aspx) and the [C# Runtime Binder](https://msdn.microsoft.com/en-us/library/microsoft.csharp.runtimebinder(v=vs.110).aspx), both of which arrived in .NET 4.0.
