### ISSUE TITLE
Can you add Version 5.5.1.1 to Nuget?

### ISSUE THREAD

**Issue by postacik** [Microsoft/ClearScript#40]
The latest version on nuget repository is v5.5.0.1 which has issues with debugging V8 scripts.

https://www.nuget.org/packages/ClearScript.V8/

Can you please upload the latest version to Nuget?

**Comment by Taritsyn** [comment]
Hello, Ahmet!

See the [“Update Nuget to 5.5 please!!”](https://github.com/Microsoft/ClearScript/issues/28) discussion.

**Comment by postacik** [comment]
Understood. :)

I'll make the request to the owners of the Nuget package.
