### ISSUE TITLE
how to release parameters which pass to v8scriptitem

### ISSUE THREAD

**Issue by coader** [microsoft/ClearScript#405]
use host object as parameter to call v8scriptitem like this:
engine.Execute(....)
engine.Script.run(host1,host2)

if js not use those args, everything is ok, but if host1 is object and js call it's method:
const a=host1.get(...)

after executed, even call engine.dispose, but host1, host2 still in memory
and v8scriptengine also can't release

**Comment by ClearScriptLib** [comment]
Hi @coader,

A host object can only be released when it's no longer in use.

If you pass a host object to a script engine, the script engine retains its reference until:
1. No script references to the host object are reachable **AND** the script engine has performed garbage collection, **OR**
2. The script engine has been disposed.

Once the script engine has released its reference **AND** no managed references are reachable, the object can be released when the host performs garbage collection.

Here's a sample that demonstrates host object lifetime:

``` C#
WeakReference wr1 = null;
WeakReference wr2 = null;
new Action(() => {
    wr1 = new WeakReference(new object());
    wr2 = new WeakReference(new Random());
    using var engine = new V8ScriptEngine();
    engine.AddHostType(typeof(Console));
    engine.Execute(@"function run(host1, host2) {
        const a = host1;
        const b = host2;
        Console.WriteLine('Host1 is {0}', a);
        Console.WriteLine('Host2 is {0}', b);
    }");
    engine.Script.run(wr1.Target, wr2.Target);
})();
GC.Collect();
Console.WriteLine("Host1 is {0}", wr1.IsAlive ? "alive!" : "DEAD.");
Console.WriteLine("Host2 is {0}", wr2.IsAlive ? "alive!" : "DEAD.");
```

You can see this sample in action [here](https://dotnetfiddle.net/qvc6JK).

Good luck!

**Comment by coader** [comment]
const a=host1 is ok and not not hold this object
but if use:
`const a=host1.method()`
thus will hold host1 and engine also be holded

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/186556024-93346d26-bea2-4356-a381-50855ce4a00e.png)

V8ScriptEngine still in memory
![image](https://user-images.githubusercontent.com/3700498/186556069-aac34a7f-546a-468e-a099-07db02abe4d6.png)

if not run script, everything is ok

**Comment by coader** [comment]
I didn't pass any host object this time, but the v8scriptengine still in memory, can't be released
![image](https://user-images.githubusercontent.com/3700498/186556724-24d66bec-028e-494d-b408-53958ddaae52.png)

**Comment by coader** [comment]
` {
                using var engine = new V8ScriptEngine();
                engine.Execute("function run(){ }"); 
                engine.Script.run();  
                
                GC.Collect();
                GC.WaitForPendingFinalizers();
            }`

**Comment by ClearScriptLib** [comment]
Hi @coader,

In your sample above, `engine` is still reachable when you invoke `GC.Collect`. Even if you move that call outside the braces, there's no guarantee that the script engine will be released.

One way to force release is to use a lambda scope instead of braces:

``` C#
WeakReference wrEngine = null;
new Action(() => {
    using var engine = new V8ScriptEngine();
    wrEngine = new WeakReference(engine);
    engine.AddHostType(typeof(Console));
    engine.Execute(@"function run() {
        Console.WriteLine('The engine is running.');
    }"); 
    engine.Script.run();  
})();
GC.Collect();
Console.WriteLine("The engine is {0}", wrEngine.IsAlive ? "alive!" : "DEAD.");
```

We've added this sample as `Test2` in the [Fiddle](https://dotnetfiddle.net/qvc6JK).

Cheers!

**Comment by coader** [comment]
```csharp
                for (var i = 0; i < 10; i++)
                {
                    var host = new Test(i);
                }
                GC.Collect();
                GC.WaitForPendingFinalizers();
```

after that, still has last instance in memory,

about scriptengine, I call it in web controller, then call GC.Collect  and take memory snapshot
but v8scriptengine count is increment every time,

**Comment by coader** [comment]
```csharp
{
    public class HostType
    {
        public int Index { get; set; }
        public object Value = new();
        public HostType(int i)
        {
            Index = i;
        }
        public object get()
        {
            return this.Value;
        }

    }

            new Action(() => { 
                for (var i = 0; i < 10; i++)
                {
                    var host = new HostType(i); 
                    using var engine = new V8ScriptEngine();
                    engine.Execute("function run(a){ const x= a.get() }");
                    engine.Script.run(host);
                    engine.Dispose();
                }
                GC.Collect();
                GC.WaitForPendingFinalizers();
            })();
```

it seems ok, but why not release in my really code, the class of mine which hold the engine is also released, but V8ScriptEngine still alive

**Comment by coader** [comment]
![image](https://user-images.githubusercontent.com/3700498/186626564-36ec105f-4088-4e02-97e3-d90f3d769ad2.png)
 host object also referenced by it

**Comment by ClearScriptLib** [comment]
Hi @coader,

We've tried to reproduce your scenario, but object and engine cleanup is still working as it should. Here's the code:

``` C#
private static void Test3() {
    Console.WriteLine("*** TEST 3 ***");
    var hostObjectWeakRefs = new WeakReference[10];
    var scriptEngineWeakRefs = new WeakReference[10];
    Test3Worker(hostObjectWeakRefs, scriptEngineWeakRefs);
    GC.Collect();
    if (hostObjectWeakRefs.Any(wr => wr.IsAlive)) {
        Console.WriteLine("Some host objects are alive!");
    } else {
        Console.WriteLine("All host objects are DEAD.");
    }
    if (scriptEngineWeakRefs.Any(wr => wr.IsAlive)) {
        Console.WriteLine("Some script engines are alive!");
    } else {
        Console.WriteLine("All script engines are DEAD.");
    }
}
private static void Test3Worker(WeakReference[] hostObjectWeakRefs, WeakReference[] scriptEngineWeakRefs) {
    for (var i = 0; i < 10; i++) {
        var host = new HostType(i);
        hostObjectWeakRefs[i] = new WeakReference(host);
        using var engine = new V8ScriptEngine();
        scriptEngineWeakRefs[i] = new WeakReference(engine);
        engine.AddHostType(typeof(Console));
        engine.Execute(@"function run(a) {
            const x = a.get();
            Console.WriteLine('Processing iteration #{0} (a is {1}) (x is {2})', a.Index, a, x);
        }");
        engine.Script.run(host);
    }
}
public class HostType {
    public int Index { get; set; }
    public object Value = new();
    public HostType(int i) {
        Index = i;
    }
    public object get() {
        return this.Value;
    }
}
```

Please see `Test3` in the [Fiddle](https://dotnetfiddle.net/qvc6JK) and let us know if you don't think it captures your scenario adequately.

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional comments or questions about this topic. Thank you!
