### ISSUE TITLE
Best way to use V8ScriptEngine in Multi-threading program

### ISSUE THREAD

**Issue by GameHackerPM** [microsoft/ClearScript#408]
I have been looking over the other issues and questions here and there, but didn't get clear answer for that question! Like I have a program that does more than 100 tasks (Long Running) at the same, it takes a lot of time like it can take up to 30-40 seconds to get them finished, I have checked the performance issues with dotTrace and found the most processing time taken by ClearScript in general from different namespaces.

My current way using it: Creating new instance for each thread, it takes like about 17 instances of V8ScriptEngine with "using" keyword, each instance has a script that might have 1-5 loops, each loop can be 2-30 count of times for a simple math operations. I'm not sure if that is right way to use it or wrong, but I really need the best way to save time of processing! I need to reach like 10 seconds instead of 30-40 seconds.
When I go with 20 tasks only, I get it like 10 seconds or something, maybe less actually! but my Program is built to use more than 100 tasks at the same time. So I need solution for that if possible or the best way possible to use it correctly. 

Also I tried to create only 2 instances for each worker so I can use them and override the scripts I need to run, but that didn't help, maybe a bit not sure if it was really better or nothing. 

If you need more information about it, please ask me I would like to provide any information that make you figure what I really need for that.

Thanks for reading all of that.

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

We can't give you specific recommendations without knowing more about your requirements. Some questions:

- Are your tasks CPU-bound, or do they perform I/O?
- How much of your task code is script/managed/native/other?
- Does your script code interact frequently with the host?
- Do all tasks run the same script code?
- Do tasks reuse previously instantiated engines?
- Do tasks call `ScriptEngine` methods such as `Execute` or `Evaluate` multiple times?

Thanks!

**Comment by GameHackerPM** [comment]
Thank you for your reply..

Here are the answers for all your questions:

- Are your tasks CPU-bound, or do they perform I/O? **CPU-bound**
- How much of your task code is script/managed/native/other? **Native Javascript code**
- Does your script code interact frequently with the host? **Nope, It's just a native JS code with some simple math equations in loops.**
- Do all tasks run the same script code? **Nope, as each task has different math every call!**
- Do tasks reuse previously instantiated engines? **Nope, I use "Using" keyword and create new one every cycle!**
- Do tasks call ScriptEngine methods such as Execute or Evaluate multiple times? **Nope, just 1 time which is "Execute" then use the script itself.. Ex:** 
`using (var engine = new V8ScriptEngine())
{
     engine.Execute("function x(){bla bla bla..}");
     var result = engine.Script.x();
     engine.CollectGarbage(true);
}`

Waiting for any other explanation or questions to answer..!

Thanks again.

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

Thanks for answering our questions. It looks like your tasks consist of four phases:

1. Script engine instantiation.
2. Script execution, which installs a function in the script environment.
3. Script function invocation.
4. Garbage collection.

Right off the bat, consider ditching the garbage collection. It's a waste if the script engine is about to go away.

Next, consider combining steps 2 and 3 into a single "hop" across the host-script boundary. For Example:

``` C#
// engine.Execute("function x(){bla bla bla..}");
// var result = engine.Script.x().ToString();
var result = engine.Evaluate("(function(){bla bla bla..})()").ToString();
```

Beyond that, since your script code doesn't interact with the host, its performance is pretty much dictated by V8's implementation, and ClearScript has no way to accelerate it.

The only other thing worth mentioning is that V8 startup is fairly heavy. If the time you're spending within the `V8ScriptEngine` constructor is at all significant (relative to the script execution time), then you might consider reducing the instance count.

To that end, some applications manage a pool of reusable script engines. Our understanding is that running more than _n_ CPU-bound tasks concurrently, where _n_ is in the neighborhood of your CPU core count, won't improve overall performance, and could actually hamper it. It might therefore make sense to use a pool of ~_n_ reusable script engines.

Unfortunately that approach brings additional complications. The pool must be carefully managed to avoid concurrent access to any one script engine. Running a script could pollute the script environment and trip up subsequent scripts. And if your scripts allocate a lot of memory, it may be necessary to perform manual garbage collection from time to time.

Good luck!

**Comment by GameHackerPM** [comment]
I appreciate the effort you put on the post to give as much info that can help as possible! But seems I couldn't get any better performance from it. I tried what you said to try, but it didn't improve it, not even a little sadly! The only way it makes it better like when I split the tasks on two different process of the same program, like each process take 50 tasks that made it take only the half time (20-25 seconds), I just wanted to have the right solution or the best over it. 

Not sure what else I can do or work around it to get better. If you have any other advice that may help me, would be really appreciate it.

Thanks a lot for your time and your effort!

**Comment by ClearScriptLib** [comment]
>But seems I couldn't get any better performance from it.

That's unfortunate but unsurprising given that your scripts are pure, flat-out JavaScript and don't interact with the host.

There's definitely overhead associated with invoking the script engine, especially via the dynamic function call you were using originally, and there's overhead associated with garbage collection even if it's mostly a no-op, but all that overhead is apparently insignificant compared to the actual script execution in your case.

>The only way it makes it better like when I split the tasks on two different process of the same program

That's surprising. Threads are more lightweight than processes, so you should be able to achieve the same or better efficiency with a single process. Out of curiosity, can you describe your thread management? Specifically, are you using the thread pool, or creating threads manually? Are you somehow limiting the active thread count?

**Comment by GameHackerPM** [comment]
Thanks for still trying to help me out!

I don't do any thread management at all tbh! It's just like running tasks over and over also putting the max threads like 1000, I know that could be bad, but if you have a tip or a link that can be useful for me to manage it correctly as I need at least 100-200 tasks to be concurrently working at the same time and to be as fast as possible!

          ```
ThreadPool.SetMaxThreads(1000, 1000);
          var countOfNeededTasks = MaxTasks - TasksCount;
          for (int i = 0; i < countOfNeededTasks; i++)
          {
              try
              {
                  Task.Factory.StartNew(() => StartWorker(null), AllTasksCancellationToken,
                      TaskCreationOptions.LongRunning, TaskScheduler.Current);
                  TasksCount++;
              }
              catch { }
          }
```

Also is there a way to make V8ScriptEngine to load just lightweight as I don't need any of host usage or anything, just running a javascript code and that's it? Maybe that make it load faster and even perform faster? Something like a flag you may add to ClearScript for **Light** running? Would be great if we got such flag, if you got what I mean!

Thanks a lot for your time.

**Comment by ClearScriptLib** [comment]
Hi @GameHackerPM,

We set up a test with 1000 CPU-bound JavaScript tasks with no host interaction and tried several ways to execute them:

- `TaskFactroy.StartNew` vs. `Parallel.For`
- With vs. without thread pool expansion
- With vs. without a cancellation token
- ClearScript/V8 vs. a pure .NET JavaScript engine ([Jint](https://github.com/sebastienros/jint)).

Observations:

- `Parallel.For` was slower than `TaskFactroy.StartNew`. 
- As expected, thread pool expansion was ineffective, especially with `TaskCreationOptions.LongRunning`.
- The cancellation token _sometimes_ had significant negative performance impact, but results were inconclusive.
- V8 was much faster than Jint, although we've seen the opposite in tests with small scripts and chatty host interaction.

So. unfortunately, we don't have much to recommend in your case:

- Try getting rid of the cancellation token.
- Use System Monitor or a similar utility to see if script execution is causing your machine to swap.

Good luck!

**Comment by GameHackerPM** [comment]
Hi @ClearScriptLib,

Thanks for your reply and efforts. I really appreciate how you are trying to help me with this case! I will try to take your advice and try to move on it somehow with a way or another! But really thanks again for your support and help!

Much love! <3
