### ISSUE TITLE
How to AddHostType with a constructor

### ISSUE THREAD

**Issue by roa-nyx** [microsoft/ClearScript#409]
We are trying to create a class in .Net land, and have it be created and returned from Javascript land.

To do that we thought we could use `AddHostType(typeof(Poco))` and call `new Poco()` from Javascript to instantiate it.

Here is my example:

```
class Poco
{
	public bool Success { get; set; }
}
```

Before evaluating we register the type using one of the following:

```
//scriptEngine.AddHostType(typeof(Poco));
scriptEngine.AddHostType("Poco", typeof(Poco));
```

Finally we try to evaluate this script:

```
engine.Evaluate("new Poco();");
```

However this call results in this exception:

```
Microsoft.ClearScript.ScriptEngineException: 'Error: Type 'Poco' has no constructor that matches the specified arguments'
```

Are we missing something? We've tried to explicitly create a public constructor, but that didn't help. We didn't find anywhere in the documentation stating what the requirements of such a constructor might be.

Any assistance would be greatly appreciated.

**Comment by roa-nyx** [comment]
Amazing! Thanks for the fast response!

> ClearScript provides a number of ways to make non-public .NET resources accessible from script code

Are these ways documented somewhere? I'll give a quick google now that I know what the issue is.

**Comment by ClearScriptLib** [comment]
>Are these ways documented somewhere?

Yes, although not necessarily well 😅 

For example, there's [`HostItemFlags.PrivateAccess`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_HostItemFlags.htm) and [`ScriptEngine.AccessContext`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_AccessContext.htm).

Please reopen this issue if you have additional questions about this topic.

Good luck!
