### ISSUE TITLE
Using clearscript in c++

### ISSUE THREAD

**Issue by CrosRoad95** [microsoft/ClearScript#419]
Hello, i'm trying to use clearscript in c++ project, dll loads fine, but when i'm trying to createContext it throws exception somewhere inside clearscript
![image](https://user-images.githubusercontent.com/22455534/194100707-c4d66d6c-50ca-4f6a-8f48-5f27742424ba.png)
full source code: https://github.com/CrosRoad95/mtasa-blue/blob/21553ca6de25044a531d5d4429ceb435ab6c931a/Server/mods/deathmatch/logic/CJavascript.cpp

I seen clearscript first executes InitializeIcu, then isolateCreate, so i did it and crashes
"getVersion" working perfectly fine and i'm able to see version "7.3.4"

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

As you probably realize, we don't support the ClearScriptV8 native entry points, whose signatures are subject to change with each new ClearScript release. In fact, there were several "breaking" changes in recent releases.

However, if you share a crash dump, we might be able to give you a better idea about the cause of the crash.

Thanks!

**Comment by CrosRoad95** [comment]
https://drive.google.com/file/d/1-Ymnr95zctTd7ttKAa7YebNvNx0T8-iO/view?usp=sharing
i don't think this will work, exported using this option:
![image](https://user-images.githubusercontent.com/22455534/194109234-9e56285d-65a6-43e4-9b24-206e1595b32e.png)

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

Here's the crash stack:

```
V8Platform::EnsureInitialized::__l2::void <lambda>(void)::__l2::<lambda_675a7b198b023cb6a3f9e796ce6cce42>::operator()(void * * pMethodTable) Line 73
std::invoke(V8Platform::EnsureInitialized::__l2::void <lambda>(void)::__l2::<lambda_675a7b198b023cb6a3f9e796ce6cce42> &) Line 1558
std::_Invoker_ret<enum V8GlobalFlags>::_Call(V8Platform::EnsureInitialized::__l2::void <lambda>(void)::__l2::<lambda_675a7b198b023cb6a3f9e796ce6cce42> &) Line 670
std::_Func_impl_no_alloc<<lambda_675a7b198b023cb6a3f9e796ce6cce42>,enum V8GlobalFlags,void * *>::_Do_call(void * * && <_Args_0>) Line 831
std::_Func_class<enum V8GlobalFlags,void * *>::operator()(void * * <_Args_0>) Line 878
V8SplitProxyManaged::InvokeNoThrow(const std::function<enum V8GlobalFlags __cdecl(void * *)> &) Line 125
V8Platform::EnsureInitialized::__l2::<lambda>() Line 73
std::_Func_class<void>::operator()() Line 878
OnceFlag::Impl::CallOnce(const std::function<void __cdecl(void)> &) Line 103
OnceFlag::CallOnce(const std::function<void __cdecl(void)> & func) Line 130
V8Platform::EnsureInitialized() Line 69
V8IsolateImpl::V8IsolateImpl(const StdString & name, const v8::ResourceConstraints * pConstraints, const V8Isolate::Options & options) Line 512
V8Isolate::Create(const StdString &) Line 12
V8Isolate_Create(const StdString & name, int maxNewSpaceSize, int maxOldSpaceSize, double heapExpansionMultiplier, unsigned __int64 maxArrayBufferAllocation, V8Isolate::Flags flags, int debugPort) Line 719
```

Many ClearScriptV8 entry points – including `V8Isolate_Create` – need to call back into (what is normally) managed code. They do so by utilizing an array of several dozen function addresses placed into thread-local storage via a call to [`V8SplitProxyManaged_SetMethodTable`](https://github.com/microsoft/ClearScript/blob/fbbd2930e5e5fbfd1031ac5ddbb7a0599fd3f95e/ClearScriptV8/V8SplitProxyNative.cpp#L113). That's what you're missing.

Honestly, using ClearScriptV8 in this manner isn't something we'd recommend. Out of curiosity, why not use V8 directly? It has a public API that, while not simple, is at least more friendly to C++ hosts.

Cheers!

**Comment by CrosRoad95** [comment]
can't find precompiled v8 binaries that will work with 32/64bit linux and windows. As you can see the repository is for multiplayer game and we don't want to quadruple compilation time

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

>we don't want to quadruple compilation time

One possibility might be to build V8 once and reuse it in binary form for your builds. A package manager for native binaries – such as [Conan](https://conan.io/index.html) – might be useful for this purpose..

>if c++ api of clearscript v8 didn't change much over time its not problem to adapt, i don't think so you are rewriting it every update

You are, of course, welcome to give it a shot, and you're right – it shouldn't change very often. It's just that, because ClearScriptV8's interface is internal, we can't guarantee its long-term stability.

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions, comments, or findings related to this topic. Thanks!
