### ISSUE TITLE
Clearscript 5.5.1.1 and Chrome Developer Tools support

### ISSUE THREAD

**Issue by helloIAmPau** [Microsoft/ClearScript#42]
Hello all,
I've recently updated the ClearScript version from 5.5.0 to 5.5.1.1 and now I'm not able to debug my javascript code by using Chrome Developer Tools anymore. 
Every time I try to connect to an engine using the CDT, a WebSocket connection is established and then closed by chrome as soon as the first message is received.

From a brief analysis seems to be an issue connected to the new WebSocket implementation.

I can reproduce the issue with the following steps:

1) I create a minimal test console application:

```c#
using Microsoft.ClearScript.V8;
using System;

namespace Minimal
{
    class Program
    {
        static void Main(string[] args)
        {
            using (var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableDebugging | V8ScriptEngineFlags.EnableRemoteDebugging, 9876))
            {
                Console.WriteLine(engine.Evaluate("'Press enter to send debug command';"));
                Console.ReadKey();
                engine.Evaluate("debugger;");
            }
        }
    }
}
```

2) while the console application is waiting for a key, I open chrome at URL:
http://127.0.0.1:9876/json/list
3) then I use the devtoolsFrontendUrl to start debugging the engine

My solution, for now, is to downgrade ClearScript version.

Thanks

**Comment by ClearScriptLib** [comment]
Hi @helloIAmPau,

We've confirmed that manually entering the CDT front end URL into the Chrome address bar currently doesn't work. We're investigating.

In the meantime, you can configure chrome://inspect to monitor your host and port, and launch CDT from there. That works and is the recommended procedure for launching CDT with ClearScript 5.5.1 and later.

Thanks for reporting this!

**Comment by helloIAmPau** [comment]
Hello @ClearScriptLib,
thank you for your hint, but I cannot use the chrome automatic detection in my developing workflow, so I'll wait for updates.

Thank you

**Comment by helloIAmPau** [comment]
The issue is for me closed!

Thank you.

**Comment by ClearScriptLib** [comment]
Great to hear. Thanks!
