### ISSUE TITLE
How to compare ScriptObject with other ScriptObject?

### ISSUE THREAD

**Issue by CrosRoad95** [microsoft/ClearScript#422]
I just want to make subscribe/unsubscribe methods
so:
```js
const a = () => { } 

subscribe(a) // internally doing: subscribers.Add(scriptObject)
unsubscribe(a) // subscribers.Remove(scriptObject)
```
but comparer always return false

**Comment by ClearScriptLib** [comment]
HI @CrosRoad95,

It's often best to let the script engine deal with script objects. In this case, you can use JavaScript's [`Object.is`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is) method:

``` C#
private bool Equals(ScriptObject func1, ScriptObject func2) {
	return func1.Engine.Equals(func2.Engine) && func1.Engine.Script.Object.@is(func1, func2);
}
```

You can see this technique in action [here](https://dotnetfiddle.net/pNl76M).

Good luck!

**Comment by ClearScriptLib** [comment]
Hi again,

In the next ClearScript release, script objects will implement identity comparison.

Thanks!

**Comment by ClearScriptLib** [comment]
[Version 7.3.5](https://github.com/microsoft/ClearScript/releases/tag/7.3.5) added support for script object identity comparison.
