### ISSUE TITLE
Process cannot quit on Windows 7 with version > 7.3.2

### ISSUE THREAD

**Issue by ogo-adp** [microsoft/ClearScript#424]
Just build this simple console program (either with .NET 4.8 or .NET Core >= 5.0):
`static void Main()
{
    using (var engine = new V8ScriptEngine())
    {
    }
}`

The exe run forever on Windows 7 with version 7.3.3 or 7.3.4 but does quit normally with version <= 7.3.2. It does run normally on Windows 10 with all versions.

I did try win x64 only

Great library BTW :)

**Comment by ClearScriptLib** [comment]
Hi @ogo-adp,

Windows 7 is no longer a supported OS, but our curiosity led to a quick investigation. It looks like a certain V8 component is hitting a deadlock during process termination. Why it only happens on Windows 7 is a mystery, but barring anything unexpected, the next ClearScript release will include a fix.

Thanks for reporting this issue!

**Comment by ogo-adp** [comment]
Hi @ClearScriptLib and thanks for you quick response (and for the fix). 

I opened this issue knowing that Windows 7 is outdated, but maybe this V8 bug could also impact newer OSes in some (less obvious) cases.

**Comment by ClearScriptLib** [comment]
Fixed in Version [7.3.5](https://github.com/microsoft/ClearScript/releases/tag/7.3.5).
