### ISSUE TITLE
ScriptObject, how to know if this is an async function?

### ISSUE THREAD

**Issue by CrosRoad95** [microsoft/ClearScript#425]
as in title, how can i check if scriptobject is awaitable?
maybe i just care to much?

but if i make scriptObject non async and i'm using "ToAsync" to await it, it throws exception

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

>as in title

The title refers to determining whether an object is an async function. You can do something simple, like this:

``` C#
private static bool IsAsyncFunc(dynamic obj) => obj.constructor.name == "AsyncFunction";
```

That's a bit fragile, though. A more robust approach is to use [`instanceof`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof). Oddly, JavaScript doesn't expose [`AsyncFunction`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncFunction) as a global property, but it's easy to find:

``` C#
dynamic isAsyncFunc = engine.Evaluate("const ctor = (async() => {}).constructor; x => x instanceof ctor");
Console.WriteLine(isAsyncFunc(engine.Evaluate("async() => {}")));  // output: "True"
Console.WriteLine(isAsyncFunc(engine.Evaluate("() => {}")));       // output: "False"
```

>how can i check if scriptobject is awaitable?

That's a different question. Async functions aren't awaitable. They return promises, which _are_ awaitable, but only in async JavaScript code. However, you can await a promise in .NET code by converting it to a task:

``` C#
engine.AddHostType(typeof(Console));
engine.Execute("async function foo() { Console.WriteLine('Hello!'); }");
object promise = engine.Script.foo();
await promise.ToTask();
```

You can also use an engine flag to make this conversion automatic:

``` C#
using (var engine = new V8ScriptEngine(V8ScriptEngineFlags.EnableTaskPromiseConversion)) {
    engine.AddHostType(typeof(Console));
    engine.Execute("async function foo() { Console.WriteLine('Hello!'); }");
    await engine.Script.foo();
}
```

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions about this topic. Thank you!
