### ISSUE TITLE
AddHostObject, don't map inherited methods, properties

### ISSUE THREAD

**Issue by CrosRoad95** [microsoft/ClearScript#428]
so, i have some library that i want to expose to javascript
but i want to wrap it so i can clear stuff created by javascript and run it again
example
```csharp
class Foo{
  public DoSomething() { }
}

class FooScripting : Foo {
  public DoSomething2()
  {
    DoSomething()
  }
}
```

`_engine.AddHostObject(new Foo())` - simplified

```js
DoSomething() -- should not be mapped
DoSomething2() -- ok
```

**Comment by ClearScriptLib** [comment]
Hi @CrosRoad95,

You can do something like this:

``` C#
class Foo {
    public void DoSomething() {}
}
public class FooScripting {
    private readonly Foo _foo = new Foo();
    public void DoSomething2() => _foo.DoSomething();
}
```

Good luck!

**Comment by CrosRoad95** [comment]
yea, i want to avoid it

**Comment by ClearScriptLib** [comment]
>yea, i want to avoid it

In that case, you can do this:

``` C#
public class Foo {
    [NoScriptAccess] public void DoSomething() {}
}
public class FooScripting : Foo {
    public void DoSomething2() => DoSomething();
}
```

Cheers!

**Comment by CrosRoad95** [comment]
i might need something in reverse, attribute that tell to map this method, property

```csharp
public class Foo {
    public void DoSomething() {}
}
public class FooScripting : Foo {
  [ScriptAccess]
    public void DoSomething2() => DoSomething();
}
```

`_AddHostObject(new FooScripting(), HostFlags.ExplicitTagged)` smth like that, and it would map only these properties and methods i marked with attribute

**Comment by ClearScriptLib** [comment]
>i might need something opposite, attribute that tell to map this method, property

The closest capability that ClearScript provides is as follows:

``` C#
[NoDefaultScriptAccess] public class Foo {
    public void DoSomething() { Console.WriteLine("Boo!"); }
}
public class FooScripting : Foo {
    [ScriptMember] public void DoSomething2() => DoSomething();
}
```

[`NoDefaultScriptAccess`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_NoDefaultScriptAccessAttribute.htm) can be applied at the type or assembly level. It is an inherited attribute.

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or comments related to this topic. Thank you!
