### ISSUE TITLE
Performance issue with DataRow in 7.3.4

### ISSUE THREAD

**Issue by rouvian** [microsoft/ClearScript#433]
Here is a sample script which accesses a DataRow

``` JavaScript
var ds = server.ExecuteDataSet(context.connectionString, context.queryText, context);

var dt = ds.Tables(0);
var drs = dt.Rows;

for(var i = 0; i < drs.Count; i++) {
    var dr = drs(i);
    var value = dr(0);
    logger.LogMessage(MessageType.Information, value, "");
}
```

The line value = dr(0) cause OperationCanceledException which is caught internally. However, this causes a big performance issue in the loop. The issue is in TypeHelpers.cs in the source code of ClearScript:

``` C#
if (argIndex >= args.Length)
{
    if (!param.IsOptional && !param.HasDefaultValue)
    {
        throw new OperationCanceledException();
    }

    continue;
}
``` 

The same issue does not occur in 7.3.1.

**Comment by ClearScriptLib** [comment]
Hi @rouvian,

We've reproduced the performance regression and will address it in the next release.

By the way, the JavaScript syntax `obj(arg)` is rarely used for invoking managed indexers, but it requires fewer host calls than the more common `obj.Item(arg)` or `obj.Item.get(arg)`, so it's faster.

However, you could still do better by doing the indexing in managed code:

``` C#
engine.Script.getRow = new Func<DataRowCollection, int, DataRow>((drs, i) => drs[i]);
engine.Script.getCol = new Func<DataRow, int, object>((dr, i) => dr[i]);
```

And then, in JavaScript:

``` JavaScript
const drs = dt.Rows;
const count = drs.Count;
for (let i = 0; i < count; ++i) {
    const dr = getRow(drs, i);
    const value = getCol(dr, 0);
    // ...
}
```

The performance regression you discovered doesn't affect this technique, so it should yield a significant boost in all recent ClearScript versions.

Thanks for reporting this issue!

**Comment by ClearScriptLib** [comment]
[Version 7.3.5](https://github.com/microsoft/ClearScript/releases/tag/7.3.5) addressed the performance regression.
