### ISSUE TITLE
VBA Support

### ISSUE THREAD

**Issue by IrunguMunene** [microsoft/ClearScript#434]
Hi,

Does clear script support visual basic for appilications (VBA)? Can I execute a statement like follows?

`IIF([Total Price] - [Price] >= 15, 'Very Expensive', 
IIF([Total Price] - [Price] >= 10 AND [Total Price] - [Price] < 15, 'Expensive', 
IIF([Total Price] - [Price] >= 5 AND [Total Price] - [Price] < 10, 'Affordable',
IIF([Total Price] - [Price] >= 1 AND [Total Price] - [Price] < 5, 'Low Priced',
IIF([Total Price] - [Price] = 0, 'Tax Free', 'Other')))))`

**Comment by ClearScriptLib** [comment]
Hi @IrunguMunene,

No, ClearScript doesn't support VBA. The closest language it supports is [VBScript](https://learn.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/scripting-articles/t0aew7h6(v=vs.84)).

Sorry!

**Comment by IrunguMunene** [comment]
Thanks.
