### ISSUE TITLE
How to have a return type known only at runtime?

### ISSUE THREAD

**Issue by vbornand** [microsoft/ClearScript#437]
Hi,

I have a very specific use case, I want to return an object with a specific type only known on the runtime, and I don't want the javascript caller need to specify it.

I have currently the 2 methods:
```cs
[ScriptUsage]
public T GetDeviceByCode2<T>(string code) where T : class
{
    return this.GetDeviceByCode(code) as T;
}

[ScriptUsage]
public object GetDeviceByCode3(string code)
{ 
    return this.GetDeviceByCode(code) as ITelegramBot; //ITelegramBot is here hardcoded, but in real world, the type is not always the same and depends of the parameter value.
}
```
The first method works well, but I need to specify the type (T) in the javascript:
```js
var bot = house.getDeviceByCode2(ITelegramBot, "MyBot");
```
Only the methods defined on the `ITelegramBot` interface can be invoked from the javascript. It is the expected behavior.

With the second method, I don't need to specify the type in the javascript:
```js
var bot = house.getDeviceByCode3("MyBot");
```
But here all the methods of the runtime object are visible and can be called. And I would like to limit the methods callable.

How can I have receive the same object returned by the method  the method `getDeviceByCode2 ` in the method `getDeviceByCode3` ?

To complexify, the type `ITelegramBot` provides from a plugin, and I don't want the plugin have a reference on ClearScript, so I can't use the `ScriptAccess `attributes.

Thanks for your help.

**Comment by ClearScriptLib** [comment]
Hi @vbornand,

>How can I have receive the same object returned by the method `getDeviceByCode2`

ClearScript provides an extension method – [`ToRestrictedHostObject`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_Extensions_ToRestrictedHostObject.htm) – that may be of assistance. For example:

``` C#
[ScriptUsage]
public object GetDeviceByCode3(string code)
{ 
    return this.GetDeviceByCode(code).ToRestrictedHostObject<ITelegramBot>();
}
```

Please note that `ToRestrictedHostObject` returns a _host object_ – an instance of an internal ClearScript class intended to be passed or returned to script code. Such an object isn't useful to the host application.

>To complexify, the type `ITelegramBot` provides from a plugin, and I don't want the plugin have a reference on ClearScript, so I can't use the `ScriptAccess` attributes.

There's a way to "virtually" add ClearScript attributes to external resources. You can read about it [here](https://microsoft.github.io/ClearScript/2022/03/20/custom-attribute-loaders.html).

Good luck!

**Comment by vbornand** [comment]
Thanks @ClearScriptLib for your quick answer.

I successfully attended my goal using the `ToRestrictedHostObject` function. (Using reflection before to call it, because `ITelegramBot` is defined in a plugin and not known at the compile time by the app hosting the script engine.)

It's not clean code, but if it can help somebody:
```cs
[ScriptUsage]
public object GetDeviceByCode3(string code)
{
    var tBot = this.GetDeviceByCode(code);

    var telegramBotType = this.sharedTypes.First(t => t.Name.Contains("ITelegramBot"));

    //Dirty way to get the method
    var ext = typeof(Microsoft.ClearScript.Extensions)
             .GetMethods(BindingFlags.Static | BindingFlags.Public)
             .FirstOrDefault(m => m.Name == "ToRestrictedHostObject" && m.GetParameters().Length == 2);
    var r = ext.MakeGenericMethod(telegramBotType).Invoke(null, new object[] { tBot, jsEngine });

    return r;
}
```

If the method `ToRestrictedHostObject` provided an overload with the type as parameter (and not only available with genericity), it would be great. 

Thanks for the link about to add attributes on external resources. Maybe it is the best solution, and I can use pretty complex logic to know on which methods are script visible depending which interface the method implements. I think it would be a cleaner solution as the one with the `ToRestrictedHostObject`.

Thanks again

Valentin

**Comment by ClearScriptLib** [comment]
Hi Valentin,

>If the method `ToRestrictedHostObject` provided an overload with the type as parameter (and not only available with genericity), it would be great.

Good idea! We'll add that in the next release.

Thank you!

**Comment by ClearScriptLib** [comment]
[Version 7.3.5](https://github.com/microsoft/ClearScript/releases/tag/7.3.5) added a pair of [`ToRestrictedHostObject`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_Extensions_ToRestrictedHostObject.htm) overloads.
