### ISSUE TITLE
Don't expose System.Object public members to the script?

### ISSUE THREAD

**Issue by iotalambda** [microsoft/ClearScript#451]
How can we provide a host object to the engine in such a way, that `System.Object`'s public members (properties, methods) would not be exposed to the script?

For example, if we do
`engine.AddHostObject("console", new { log = new Action<string>(Console.WriteLine) });`
then the `console` object and its `console.log` property will have `GetHashCode` etc. exposed.

I tried using `PropertyBag` like
`engine.AddHostObject("console", new PropertyBag { ["log"] = new Action<string>(Console.WriteLine) });`
but still, the problem persists with `console.log`. Perhaps there's something `PropertyBag`-like for functions?

**Comment by ClearScriptLib** [comment]
Hi @iotalambda,

You can do something like this:

``` C#
dynamic setupConsole = engine.Evaluate("impl => console = { log: arg => impl.WriteLine(arg) }");
setupConsole(typeof(Console).ToHostType(engine));
```

This way `console.log` is a normal JavaScript function, and the underlying `System.Console` host type is inaccessible.

Good luck!

**Comment by iotalambda** [comment]
Hi @ClearScriptLib ,

Oh yes, this solves the problem elegantly :) Thanks!
