### ISSUE TITLE
Web Crypto API support?

### ISSUE THREAD

**Issue by thurfir** [microsoft/ClearScript#464]
Hi, is there a way to enable the crypto web apis https://developer.mozilla.org/en-US/docs/Web/API/Crypto in Microsoft ClearScript V8 ?

When I try to run this sample in the engine I get a `ReferenceError: crypto is not defined` exception:

```js
 const array = new Uint32Array(10);
crypto.getRandomValues(array);
```

Tested on _Microsoft.ClearScript.V8.Native.win-x64_  v7.3.5

**Comment by thurfir** [comment]
Thanks for your help, however I am looking to generate ids, and Math.random is not a cryptographically-secure PRNG https://gist.github.com/joepie91/7105003c3b26e65efcea63f3db82dfba .

I might have to move to nodeJS from this package as there don't seems to be a JS-only way to do this.

**Comment by ClearScriptLib** [comment]
Hi @thurfir,

>I am looking to generate ids, and Math.random is not a cryptographically-secure PRNG

The example above uses [`Random`](https://learn.microsoft.com/en-us/dotnet/api/system.random), which isn't cryptographically secure, but [`RandomNumberGenerator`](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator) _is_ cryptographically secure, to our knowledge:

``` C#
public sealed class Crypto {
    public unsafe ITypedArray getRandomValues(ITypedArray array) {
        var size = Convert.ToInt32(array.Size);
        array.InvokeWithDirectAccess(pBytes => {
            RandomNumberGenerator.Fill(new Span<byte>(pBytes.ToPointer(), size));
        });
        return array;
    }
}
```

Cheers!

**Comment by thurfir** [comment]
My bad! I should have been better at reading your sample, thanks a lot!
