### ISSUE TITLE
global use function for all module.

### ISSUE THREAD

**Issue by stone89son** [microsoft/ClearScript#468]
In client code.
```
function print(data) {
    Console.Info(data);
}
```
I want to use "print" function all module.
How to write function to use for all module.

**Comment by ClearScriptLib** [comment]
Hi @stone89son,

Any function you define at the top level of a normal (non-module) script will be visible to all modules. For example:

``` C#
engine.AddHostType(typeof(Console));
engine.Execute(@"
    function print(data) {
        Console.WriteLine(data);
    }                    
");
engine.Execute(new DocumentInfo { Category = ModuleCategory.Standard }, @"
    print(123);
");
```

Good luck!

**Comment by stone89son** [comment]
thank you!!!!!!!!!!!!!!!!!!!
