### ISSUE TITLE
message, stack members not found unless manually set

### ISSUE THREAD

**Issue by nloewen** [Microsoft/ClearScript#47]
I'm trying to pass JS Error objects to .NET functions. Accessing the message or stack members of this object results in the exception "Public member 'message' on type 'V8ScriptItem' not found."
If I pass a JS object that I created myself (`{message:"Error",stack:"trace"}`) I am able to access these members.
Further, passing in other objects such as `{x:1}` and attempting to access message or stack result in exceptions rather than returning Microsoft.ClearScript.Undefined.

**Comment by ClearScriptLib** [comment]
Hi @nloewen,

We ran the following C# test code in an attempt to confirm your report:

``` C#
engine.Script.dump = new Action<dynamic>(arg => {
    Console.WriteLine(arg.message);
    Console.WriteLine(arg.stack);
});

engine.Execute(@"
    dump(new Error('hello'));
    dump({x:1});
");
```

This code threw no exceptions and produced the expected output:

```
hello
Error: hello
    at Script Document:2:26
[undefined]
[undefined]
```

Are you doing something differently? Can you provide a minimal code sample that reproduces the issue?

Thanks!

**Comment by nloewen** [comment]
The following VB.net code produces the error

```
Imports Microsoft.ClearScript

Public Module Module1

    Sub Main()
        Dim engine = New V8.V8ScriptEngine()

        engine.Script.dump = Sub(arg As Object)
                                 Console.WriteLine(arg.message)
                                 Console.WriteLine(arg.stack)
                             End Sub

        engine.Execute("dump({message:'hello',stack:'trace'});" & _
                       "dump(new Error('world'));")
    End Sub

End Module
```

**Comment by ClearScriptLib** [comment]
Hi @nloewen,

We've confirmed your report. The key difference between the two cases is that the `message` and `stack` properties of JavaScript error objects are not enumerable.

VB.NET and C# behave very differently when dealing with dynamic objects, and VB.NET appears to have some quirks that _sometimes_ block access to non-enumerable JavaScript properties.

Would you mind trying something? If you reverse the order of the two calls to `dump`, does the test still fail?

Thanks!

**Comment by nloewen** [comment]
This works,
```
engine.Execute("dump(new Error('world'));" & _
               "dump({message:'hello',stack:'trace'});")
```
As does this
```
engine.Execute("dump(new Error('world'));" & _
               "dump({message:'hello',stack:'trace'});" & _
               "dump(new Error('world'));")
```

Thanks for looking into this issue!

**Comment by ClearScriptLib** [comment]
Fixed in [Version 5.5.2](https://github.com/Microsoft/ClearScript/releases/tag/5.5.2).

**Comment by nloewen** [comment]
I've found a case that isn't fixed in 5.5.2

```
engine.Execute("dump(new Error('test'));" & _
               "dump({message:'test'});")
```

**Comment by ClearScriptLib** [comment]
Version 5.5.3 will include a fix for this.

**Comment by ClearScriptLib** [comment]
[Version 5.5.3](https://github.com/Microsoft/ClearScript/releases/tag/5.5.3) has been posted.
