### ISSUE TITLE
Client code run completed event.

### ISSUE THREAD

**Issue by stone89son** [microsoft/ClearScript#474]
Hi everyone.
In V8ScriptEngine . on Host code (C#) how to do know Client code has completed excuted and include asynchronous task (http request, sleep, setTimeout)? 
thank for help me.

**Comment by ClearScriptLib** [comment]
Hi @stone89son,

As you mentioned, there are several ways for script code to be operating asynchronously, including via direct invocation of managed async methods, blocking calls, etc. – and any number of such operations can be in flight simultaneously.

Therefore, generally speaking, there are no shortcuts. The host and script engine must work together if synchronization is required. For example, the host can hand the script code an [event](https://learn.microsoft.com/en-us/dotnet/api/system.threading.manualreseteventslim) to set when it's done. Alternatively, the script code can give the host a [promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) or [task](https://learn.microsoft.com/en-us/dotnet/api/system.threading.tasks.task) that tracks the progress of the operation in question.

Good luck!

**Comment by stone89son** [comment]
thank you for reply. i clear.
