### ISSUE TITLE
Javascript code import C# assembly (dll,exe)

### ISSUE THREAD

**Issue by stone89son** [microsoft/ClearScript#477]
hi everyone.
If user can import C# assembly (dll,exe) from javascript code same node module, I think very useful.
in the case, Is there a way to that?

**Comment by ClearScriptLib** [comment]
Hi @stone89son,

You can't load .NET assemblies via `import` or `require`, but [`ExtendedHostFunctions.lib`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_ExtendedHostFunctions_lib.htm) provides something similar:

``` C#
engine.AddHostObject("host", new ExtendedHostFunctions());
engine.AddHostType(typeof(Console));
engine.Execute(@"
    const clr = host.lib('mscorlib', 'System', 'System.Core');
    let array = clr.System.Linq.Enumerable.Range(0, 5).ToArray();
    Console.WriteLine(Array.from(array).toString()); // output: 0,1,2,3,4
");
```

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts or questions about this topic. Thank you!
