### ISSUE TITLE
V8 Crash

### ISSUE THREAD

**Issue by TomasPospisil** [microsoft/ClearScript#478]
Hi @ClearScriptLib,

we ran into an issue during starting V8 Engine which caused crash of entire application. The issue was this:

> dotnet: /home/jerry/ClearScript/ClearScriptV8/V8IsolateImpl.cpp:1825: V8IsolateImpl::ExecutionScope *V8IsolateImpl::EnterExecutionScope(V8IsolateImpl::ExecutionScope *, size_t *): Assertion `m_spHeapWatchTimer.IsEmpty()' failed.

We never seen such crash in the application, so it must be "unique". Do you know what could have gone wrong from this little piece of code?

**Comment by ClearScriptLib** [comment]
Hi @TomasPospisil,

>Do you know what could have gone wrong from this little piece of code?

We're investigating that – as well as why assertion code was included in the official build 🤔

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @TomasPospisil,

Is the crash reproducible? Do you have a code sample you could share?

Thanks!

**Comment by TomasPospisil** [comment]
Hi @ClearScriptLib,

sorry for late reply. The crash is not reproducible at all, it was just an occasional crash. However it was run on ClearScript version 7.3.4

**Comment by ClearScriptLib** [comment]
[Version 7.3.7](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_JavaScript_JavaScriptObjectFlags.htm) fixes at least one cause of this crash. Please reopen this issue if you encounter it in ClearScript 7.3.7 or newer builds.
