### ISSUE TITLE
Fetch Local Variables value in VBScript implented using clearscript

### ISSUE THREAD

**Issue by jaskaran0001** [Microsoft/ClearScript#48]
I am implementing a debugger for Vbscript using Clearscript which is expected to display all the variables and their values upon hitting break point.

I am able to fetch all the variables using following code:

```
public static VBScriptEngine engine;
dynamic ome = engine.Evaluate("me"); 
foreach (var name in ome.GetDynamicMemberNames())
Console.WriteLine("{0}: {1}", name, ome[name]);
```
The challenge here i am facing is that i am not able to fetch the context specific variables: e.g. A break point is set inside a function then upon hitting the break-point the variable list gets empty as per the above code.

Is there a way to fetch the context specific variables also(the variables inside the function)

Consider the following code:

```
abc = 123

def = 1432
Call hello()

Function hello()

 jas=123

 [breakpoint]

 ja = 14

End Function
```

Here on hitting the breakpoint it should display jas = 123

**Comment by ClearScriptLib** [comment]
Hi @jaskaran0001,

To our knowledge, the only way to implement a fully functional debugger for Windows Script engines (JScript/VBScript) is via the Active Script Debugging API; have a look [here](https://docs.microsoft.com/en-us/scripting/winscript/active-script-debugging-overview) and [here](https://msdn.microsoft.com/en-us/library/bb984890.aspx) to get started.

Script debuggers such as Visual Studio can connect to ClearScript applications and display local variables at breakpoints, so what you're trying to do appears to be possible. However, although ClearScript establishes the connection between the script engine and the debugging framework, it is not involved thereafter and exposes no additional debugging API.

Good luck!
