### ISSUE TITLE
How to replace INodeServices

### ISSUE THREAD

**Issue by gogo1008** [microsoft/ClearScript#481]
//var crypto = require('crypto');
module.exports = {
    fn: function (callback, argJson, args) {
        let argParams= JSON.parse(argJson);
        callback(null /* error */, argParams);
    }
};

module.exports = function (callback, argJson, args) {
    let argParams = JSON.parse(argJson);
    callback(null, { "name": "demo", args: args});
};

**Comment by ClearScriptLib** [comment]
Hello @gogo1008,

Please clarify your question. What are you trying to do? What isn't working?

Thank you!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you can provide more information. Thank you!
