### ISSUE TITLE
How to call the local third-party js library

### ISSUE THREAD

**Issue by gogo1008** [microsoft/ClearScript#482]
1、For example, call dayjs. If the third-party library file has been checked for more than 1M, the following code is very difficult to use

 var result = "";
            using (var engine = new V8ScriptEngine())
            {
                var scirpt = await FileUtil.ReadFileAndContentByVirUrlAsync("~/AppNodeJs/Plugins/words/cnchar/cnchar.all.min.js");
                engine.Execute($"{scirpt}");
                result = engine.Script.cnchar.convert.simpleToTrad("content");
            }

**Comment by ClearScriptLib** [comment]
Hi @gogo1008,

We aren't clear on the problem you're having. Does the code above not work for you?

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you can provide more information about your issue. Thank you!
