### ISSUE TITLE
Create instance of V8ScriptEngine crashes on macOS x64 NET 7.0

### ISSUE THREAD

**Issue by dany28** [microsoft/ClearScript#489]
Reopen #343 

Packages
```XML
  <ItemGroup>
    <PackageReference Include="Microsoft.ClearScript.V8" Version="7.3.7" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.win-x64" Version="7.3.7" />
    <PackageReference Include="Microsoft.ClearScript.V8.Native.osx-x64" Version="7.3.7" />
  </ItemGroup>
```  

System: macOS Ventura 3.2.1
Processor: x64

Code:
```C#
var engine = new Microsoft.ClearScript.V8.V8ScriptEngine();
```

Runtime error:
```
12 == (*__error()).
```

Fix:
After installing net5.0 the problem disappears

**Comment by ClearScriptLib** [comment]
Hi @dany28,

This looks like a duplicate of Issue #483. Please see [here ](https://github.com/microsoft/ClearScript/issues/483#issuecomment-1419248600)for an explanation and workarounds.

Good luck!

**Comment by dany28** [comment]
Suggestion:
https://github.com/microsoft/ClearScript/issues/483#issuecomment-1419248600

works for me

Thanks.
