### ISSUE TITLE
How to clean up a V8ScriptEngine?

### ISSUE THREAD

**Issue by liuhongbo** [Microsoft/ClearScript#49]
Not sure my question makes much sense.
First,
```cs
 var Runtime = new V8Runtime(Guid.NewGuid().ToString());
 var Engine = Runtime.CreateScriptEngine(V8ScriptEngineFlags.DisableGlobalMembers);
```
Then, i will execute some script
```cs
Engine.Execute(script);
```

Then I want to clean up the Engine to make sure the executed script will not have any side affects on the next script execution.

I can 
```cs
Engine.CollectGarbage(true);
```
But i think that is NOT enough to make sure the Engine is clean.

I can also recreate the Enigne
```cs
Engine.Dispose();
Engine = Runtime.CreateScriptEngine(V8ScriptEngineFlags.DisableGlobalMembers);
```
But not sure the cost of recreating the Engine object.  Will it have poor performance?

Is there a better way?

Thanks,

**Comment by ClearScriptLib** [comment]
Hi @liuhongbo,

Creating a new engine is the only way to ensure a pristine environment for script execution:

``` C#
Engine.Dispose();
Runtime.CollectGarbage(true); // optional
Engine = Runtime.CreateScriptEngine( ... );
```

Good luck!

**Comment by liuhongbo** [comment]
good to know.  thanks!
