### ISSUE TITLE
btoa and atob not defined error

### ISSUE THREAD

**Issue by dehghani-mehdi** [microsoft/ClearScript#490]
I tried to run a script that uses `btoa` and `atob` methods, but I got `not defined error` for this two. I'm using `V8` on windows.

Here is my code:

```
using var engine = new V8ScriptEngine();
engine.Execute(JS CODE);
var result = engine.Script.METHOD(INPUT);
```

**Comment by ClearScriptLib** [comment]
Hi @dehghani-mehdi,

These functions are part of the [Web API](https://developer.mozilla.org/en-US/docs/Web/API), typically provided by web browsers, whereas ClearScript provides only the standard set of [JavaScript built-ins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects).

Thanks!

**Comment by dehghani-mehdi** [comment]
Thank you @ClearScriptLib 

Actually, after I posted this issue, I could resolve the issue by adding a custom implementation of these two methods to the main js code.
