### ISSUE TITLE
ScriptEngineException: SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jnilsson89** [microsoft/ClearScript#491]
I am working on a Worker Service project that includes the ClearScript NuGet package. ClearScript enables me to call JavaScript functions from my C# code without importing modules, which has been working great so far. However, I need to import a file in my JavaScript code using the "node-fetch" library in my .js file.

The line of code I have added is: import fetch from 'node-fetch'.

Unfortunately, when I run ExecuteDocument, the application crashes with the following error message: "ScriptEngineException: SyntaxError: Cannot use import statement outside a module."

Although I have read that using a JavaScript engine should be possible, I am still very new to this technology and have been unable to find a solution to get my code running. Thank you in advance for any assistance you can provide.

**Comment by ClearScriptLib** [comment]
Hi @jnilsson89,

>Unfortunately, when I run ExecuteDocument, the application crashes with the following error message: "ScriptEngineException: SyntaxError: Cannot use import statement outside a module."

The [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) declaration is valid only within a [_module_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). If you're using ClearScript's [`V8ScriptEngine`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngine.htm), you can execute a document as a JavaScript module as follows:

``` C#
// using Microsoft.ClearScript.JavaScript;
engine.ExecuteDocument(pathOrUrl, ModuleCategory.Standard);
```

Keep in mind however that node-fetch, like most npm packages, is likely to be dependent on the [Node.js API](https://nodejs.org/api/), whereas ClearScript provides only the standard [JavaScript built-ins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects), aiming to make it easy to use .NET to provide additional facilities.

Good luck!

**Comment by jnilsson89** [comment]
> Hi @jnilsson89,
> 
> > Unfortunately, when I run ExecuteDocument, the application crashes with the following error message: "ScriptEngineException: SyntaxError: Cannot use import statement outside a module."
> 
> The [`import`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) declaration is valid only within a [_module_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules). If you're using ClearScript's [`V8ScriptEngine`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_V8_V8ScriptEngine.htm), you can execute a document as a JavaScript module as follows:
> 
> ```cs
> // using Microsoft.ClearScript.JavaScript;
> engine.ExecuteDocument(pathOrUrl, ModuleCategory.Standard);
> ```
> 
> Keep in mind however that node-fetch, like most npm packages, is likely to be dependent on the [Node.js API](https://nodejs.org/api/), whereas ClearScript provides only the standard [JavaScript built-ins](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects), aiming to make it easy to use .NET to provide additional facilities.
> 
> Good luck!

Thank you so much for quick support!
