### ISSUE TITLE
AsyncIterable convert to IAsyncEnumerable 

### ISSUE THREAD

**Issue by jzapletal95** [microsoft/ClearScript#494]
Hi guys,
I am using ClearScript (v7.3.7) in my project.
Currently i'm struggling with transfer of AsyncIterable from V8 to C#.
You have implemented automatic marshalling in oposite way (AsyncEnumerable -> AsyncIterable) but i cannot find the way how to pass it.
Any ideas?

**Comment by ClearScriptLib** [comment]
Hi @jzapletal95,

You're right that, currently, JavaScript objects aren't _enumerable_, in either normal or asynchronous modes. There are exceptions – arrays implement [`IList`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.ilist), and soon most other JavaScript objects will implement [`IDictionary<string, object>`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.idictionary-2) – but there's no mapping of JavaScript's [iteration protocols](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) to [`IEnumerable`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ienumerable-1)/[`IAsyncEnumerable`](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.iasyncenumerable-1).

However, nothing stops you from building such support yourself. For example, you could define extension methods that convert script objects to enumerables. Here's a class that provides an example:

``` C#
public static class ScriptObjectExtensions {
    public static void Initialize(ScriptEngine engine)        {
        engine.Execute(@"
            Object.prototype.getIterator = function () { return this[Symbol.iterator]?.call(this); }
            Object.prototype.getAsyncIterator = function () { return this[Symbol.asyncIterator]?.call(this); }
        ");
    }
    public static IEnumerable<object> ToEnumerable(this ScriptObject iterable) {
        if (iterable.InvokeMethod("getIterator") is ScriptObject iterator) {
            while (iterator.InvokeMethod("next") is ScriptObject result && !result["done"].Equals(true)) {
                yield return result["value"];
            }
        }
    }
    public static async IAsyncEnumerable<object> ToAsyncEnumerable(this ScriptObject asyncIterable) {
        if (asyncIterable.InvokeMethod("getAsyncIterator") is ScriptObject asyncIterator) {
            while (await asyncIterator.InvokeMethod("next").ToTask() is ScriptObject result && !result["done"].Equals(true)) {
                yield return result["value"];
            }
        }
    }
}
```

And here's how you might use it:

``` C#
using var engine = new V8ScriptEngine();
ScriptObjectExtensions.Initialize(engine);
engine.Script.delay = new Func<int, object>(ms => Task.Delay(ms).ToPromise());
engine.Execute(@"
    async function* foo() {
        await delay(1000); yield 'This ';
        await delay(1000); yield 'is ';
        await delay(1000); yield 'not ';
        await delay(1000); yield 'a ';
        await delay(1000); yield 'drill!';
    }
");
var asyncIterable = (ScriptObject)engine.Script.foo();
await foreach (var text in asyncIterable.ToAsyncEnumerable()) {
    Console.Write(text);
}
Console.WriteLine();
```

Please let us know if you have additional thoughts or findings.

Thanks!

**Comment by ClearScriptLib** [comment]
[`ClearScript 7.4`](https://github.com/microsoft/ClearScript/releases/tag/7.4.0) added  [`JavaScriptExtensions.ToEnumerable`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_JavaScript_JavaScriptExtensions_ToEnumerable.htm) and [`ToAsyncEnumerable`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_JavaScript_JavaScriptExtensions_ToAsyncEnumerable.htm).

**Comment by jzapletal95** [comment]
Thank you for your advice and for releasing a new version. Everything works good.
