### ISSUE TITLE
out parameters with .NET arrays

### ISSUE THREAD

**Issue by OuterHeaven07** [microsoft/ClearScript#496]
Hi @ClearScriptLib  

I have a problem with the keyword **out** and .NET arrays. The array object itself does not seem to have an .out method implemented

here is a simple example 

``` javascript
//Script
var stringArray= host.newArr(System.String, 3)

method1(stringArray.out) // --> error: method1 got invalid arguments

```

``` c#
// c#
    public void method1(out string[] strArray) 
    { 
             // Initialize the array:
            strArray = new string[3] { "do", "some", "thing"};
    } 
```

Basically the **out** parameter works with single variables, but unfortunately I can't get it to work with arrays.

Thanks for the support

**Comment by ClearScriptLib** [comment]
Hi @OuterHeaven07,

`out` is a property of [_host variables_](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_newVar__1.htm). To call `method1`, you must first create a host variable of type `string[]`. You can use an initial dummy value to avoid having to provide an explicit type argument when invoking `newVar`:

``` C#
const initialDummyValue = host.newArr(System.String, 0);
const arrayVar = host.newVar(initialDummyValue);
method1(arrayVar.out);
System.Console.WriteLine(System.String.Join(', ', arrayVar));
```

Good luck!
