### ISSUE TITLE
Is Microsoft Visual Studio C++ 2015 Redistributable a dependency for ClearScript

### ISSUE THREAD

**Issue by enoladev** [Microsoft/ClearScript#50]
Today I have an issue with a production server of one of my clients. The actual error message was "Application popup: <actual service name> - System Error : The program can't start because MSVCP140.dll is missing from your computer. Try reinstalling the program to fix this problem. "

Problem occurs on instantiating V8 engine.

                using (var engine = new V8ScriptEngine())
                {...

After installing VS 2015 C++ redist, problem was solved.

First of all - why this is application popup. It blocks service until pressing "OK" on message box.
Second - on ClearScript install it's mentioned that the package has no dependencies. Actually it depends on VC C++ redist.

**Comment by Taritsyn** [comment]
Hello, Nikolay!

> Second - on ClearScript install it's mentioned that the package has no dependencies. Actually it depends on VC C++ redist.

The [ClearScript.V8](https://www.nuget.org/packages/ClearScript.V8/) package is unofficial. This has been [discussed many times](https://github.com/Microsoft/ClearScript/issues/5).

In [documentation](https://microsoft.github.io/ClearScript/Details/Build.html) clearly states:

>…
>4. Important: If Visual Studio is not installed on your deployment machine, you must install 32-bit and 64-bit Visual C++ Redistributable packages:
>
>    [Visual C++ Redistributable for Visual Studio 2015](https://www.microsoft.com/en-us/download/details.aspx?id=48145)
>    Visual C++ Redistributable for Visual Studio 2017 [[x64]](https://go.microsoft.com/fwlink/?LinkId=746572) [[x86]](https://go.microsoft.com/fwlink/?LinkId=746571)
>…

**Comment by ClearScriptLib** [comment]
Thanks for answering, Andrey!

**Comment by enoladev** [comment]
Dear Andrey,
Thank you for this qualification. Silly me, I had to read documentation.
It’s pity that ClearScript is unofficial. Actually it’s an excellent package and I enjoy it very much.
 
Best regards 
Nikolay

**Comment by Taritsyn** [comment]
Hello, Nikolay!

You can contact to author of the package ([Simon Cropp](https://github.com/SimonCropp)) and tell him your suggestions for improving the package.

I am not a member of the ClearScript project team :-) I'm just an experienced user of this library.
