### ISSUE TITLE
[VBScript] number of parameters

### ISSUE THREAD

**Issue by Tor012** [microsoft/ClearScript#502]
Hello,

is there a way in VBScriptEngine to check how many parameters a script method has?

```
Function MethodA(p1, p2, p3, p4)
	...
End Function

Function MethodB(p1, p2)
	...
End Function
```

**Comment by ClearScriptLib** [comment]
Hi @Tor012,

>is there a way in VBScriptEngine to check how many parameters a script method has?

Unfortunately, no. We are _not_ aware of a way to check the parameter count of a VBScript function. There seems to be no way to do it in script code, nor is the parameter count exposed via [`IReflect`](https://learn.microsoft.com/en-us/dotnet/api/system.reflection.ireflect).

Sorry!

**Comment by Tor012** [comment]
OK, too bad. Thank you.
