### ISSUE TITLE
How to execute/call objects via interop?

### ISSUE THREAD

**Issue by victoriaquasar** [microsoft/ClearScript#508]
Let's supposed I have an interop object, a result from the `engine.EvaluateScript(...)` method as an `object`. Now let's suppose that result is a JavaScript `Function`, I have that in C# now.

How can I:

- Execute the function in the engine using the `object` variable that I got?
- Or pass the object back to the engine then execute it as function?

For example, in Jint I can do:

```cs
var myFunction = engine.Evaluate(...);
engine.Call(myFunction, ...);
```

**Comment by ClearScriptLib** [comment]
Hi @victoriaquasar,

>Execute the function in the engine using the object variable that I got?

Script objects are instances of the [`ScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptObject.htm) class, which has methods such as [`InvokeAsFunction`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptObject_InvokeAsFunction.htm):

``` C#
engine.AddHostType(typeof(Console));
var func = (ScriptObject)engine.Evaluate("(function(x) { Console.WriteLine(x); })");
func.InvokeAsFunction("Hello, world!");
```

You can also use C#'s [`dynamic`](https://learn.microsoft.com/en-us/dotnet/csharp/advanced-topics/interop/using-type-dynamic) type:

``` C#
engine.AddHostType(typeof(Console));
dynamic func = engine.Evaluate("(function(x) { Console.WriteLine(x); })");
func("Hello, world!");
```

>Or pass the object back to the engine then execute it as function?

No problem at all:

``` C#
engine.Execute("function invoke(x) { x(...Array.from(arguments).slice(1)); }");
engine.Script.invoke(func, "Hello, world!");
```

Good luck!

**Comment by victoriaquasar** [comment]
Thanks!
