### ISSUE TITLE
Permission Denied For Msgbox

### ISSUE THREAD

**Issue by jaskaran0001** [Microsoft/ClearScript#51]
When we try to run the vbscript code with msgbox, Permission denied message is displayed.

Msgbox "Hello"

Below error shows up :

---------------------------

---------------------------
Permission denied: 'Msgbox'
---------------------------
OK   
---------------------------

**Comment by ClearScriptLib** [comment]
Hi @jaskaran0001,

For the `MsgBox` and `InputBox` functions to work, you must provide an implementation of [`IHostWindow`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_IHostWindow.htm). Here's a minimal example:

``` C#
internal class HostWindow : IHostWindow {
    public IntPtr OwnerHandle {
        get { return IntPtr.Zero; }
    }
    public void EnableModeless(bool enable) {
        throw new NotImplementedException();
    }
}
```

And then:

``` C#
engine.HostWindow = new HostWindow();
engine.Execute("result = MsgBox(\"Ready?\", vbQuestion + vbYesNo, \"Let's Go!\")");
```

Good luck!

**Comment by jaskaran0001** [comment]
Thanks for the reply, but i could not figure out where do this implementation.
It would be very kind of you , if you could elaborate more.

Thanks !

**Comment by ClearScriptLib** [comment]
Hi @jaskaran0001,

You need to set the engine's [`HostWindow`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_Windows_WindowsScriptEngine_HostWindow.htm) property to a non-null value. Once you've done that, VBScript's `MsgBox` and `InputBox` functions should work.

Here's a full sample program:

``` C#
using System;
using Microsoft.ClearScript.Windows;

namespace TestApp {
    internal class Window : IHostWindow {
        public IntPtr OwnerHandle {
            get { return IntPtr.Zero; }
        }
        public void EnableModeless(bool enable) {
            throw new NotImplementedException();
        }
    }
    public static class Program {
        public static void Main() {
            using (var engine = new VBScriptEngine()) {
                engine.HostWindow = new Window();
                engine.Evaluate("MsgBox(\"Ready?\", vbQuestion + vbYesNo, \"Let's Go!\")");
            }
        }
    }
}
```

Cheers!

**Comment by jaskaran0001** [comment]
Thanks ! It Worked!
