### ISSUE TITLE
Single cross-platform package?

### ISSUE THREAD

**Issue by jcoc611-microsoft** [microsoft/ClearScript#515]
Is there a single ClearScript V8 package we could include that automatically works on all supported platforms?

Our package reference looks like this:
```xml
<PackageReference Include="Microsoft.ClearScript;Microsoft.ClearScript.osx-x64;Microsoft.ClearScript.osx-arm64;Microsoft.ClearScript.linux-x64" />
```

We sometimes get customers using new platforms and have to spend a lot of time debugging why the program isn't working on their end. It would be helpful if we could reduce this down to a single cross-platform package.

**Comment by ClearScriptLib** [comment]
Hello @jcoc611-microsoft,

Can you say more about your customer scenario? For example, is ClearScript a dependency of a NuGet package that your team provides?

Thanks!

**Comment by jcoc611-microsoft** [comment]
In our setup, ClearScript is a dependency of a C# project included in a end-user desktop application

**Comment by ClearScriptLib** [comment]
> ClearScript is a dependency of a C# project included in a end-user desktop application.

Sorry, we aren't clear on the problem. Is it not possible for your application to depend on multiple packages?

**Comment by jcoc611-microsoft** [comment]
It is possible, we are just wondering if there could be a `Microsoft.ClearScript.All` package that imports all available platforms rather than having to list them out explicitly on our end

**Comment by ClearScriptLib** [comment]
>we are just wondering if there could be a `Microsoft.ClearScript.All` package that imports all available platforms

That should certainly be possible. Out of curiosity, how is your application packaged and distributed? Bundling all the native V8 assemblies could impact your package size significantly.

**Comment by jcoc611-microsoft** [comment]
Something like this
```
dotnet build --no-self-contained --runtime $(BuildRuntime)
```
Would passing an explicit runtime prune the packages auto-magically?

**Comment by ClearScriptLib** [comment]
>Would passing an explicit runtime prune the packages auto-magically?

A `dotnet build` probably fetches _all_ the dependencies. However, once your project is built, something like `dotnet publish` only bundles cross-platform files and those that apply to the specified target platform(s).

In any case, we'll take a closer look at this for a future release.

Thank you!

**Comment by ClearScriptLib** [comment]
The [![ClearScript.Core](https://img.shields.io/nuget/v/Microsoft.ClearScript.Complete?label=ClearScript.Complete&logo=data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHN2ZyB3aWR0aD0iNjguNjU5bW0iIGhlaWdodD0iNjMuMTYzbW0iIHZlcnNpb249IjEuMSIgdmlld0JveD0iMCAwIDY4LjY1OSA2My4xNjMiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeG1sbnM6Y2M9Imh0dHA6Ly9jcmVhdGl2ZWNvbW1vbnMub3JnL25zIyIgeG1sbnM6ZGM9Imh0dHA6Ly9wdXJsLm9yZy9kYy9lbGVtZW50cy8xLjEvIiB4bWxuczpyZGY9Imh0dHA6Ly93d3cudzMub3JnLzE5OTkvMDIvMjItcmRmLXN5bnRheC1ucyMiPgogPG1ldGFkYXRhPgogIDxyZGY6UkRGPgogICA8Y2M6V29yayByZGY6YWJvdXQ9IiI+CiAgICA8ZGM6Zm9ybWF0PmltYWdlL3N2Zyt4bWw8L2RjOmZvcm1hdD4KICAgIDxkYzp0eXBlIHJkZjpyZXNvdXJjZT0iaHR0cDovL3B1cmwub3JnL2RjL2RjbWl0eXBlL1N0aWxsSW1hZ2UiLz4KICAgIDxkYzp0aXRsZS8+CiAgIDwvY2M6V29yaz4KICA8L3JkZjpSREY+CiA8L21ldGFkYXRhPgogPGcgdHJhbnNmb3JtPSJ0cmFuc2xhdGUoLS4xNzM2MykiPgogIDxnIGZpbGw9IiNmZmYiIHN0cm9rZS13aWR0aD0iLjI2NDU4IiBhcmlhLWxhYmVsPSJDICAgIFMiPgogICA8cGF0aCBkPSJtMTguODc2LTIuNDQwMWUtN3EzLjYyMTUgMCA2Ljk5NDkgMS41ODc1IDEuNTg3NSAwLjc0NDE0IDIuMjA3NiAwLjc0NDE0IDAuNDQ2NDggMCAxLjQzODctMC4yMjMyNCAwLjMyMjQ2LTAuMDc0NDE0IDAuNzE5MzQtMC4wNzQ0MTQgMS4yODk4IDAgMi4yNTcyIDEuMTkwNiAyLjM4MTIgMi44NzczIDIuMzgxMiA3LjE0MzcgMCAzLjAwMTQtMi4wNTg4IDQuMzkwNC0xLjExNjIgMC43NDQxNC0yLjUwNTMgMC43NDQxNC0xLjI2NSAwLTIuMDU4OC0wLjU0NTd0LTEuNTM3OS0xLjkzNDhxLTEuMDY2Ni0xLjk1OTYtMS43MzYzLTIuODAyOS0wLjY2OTczLTAuODY4MTYtMS42MzcxLTEuNTYyNy0yLjQwNjEtMS42ODY3LTUuMDM1NC0xLjY4NjctMi41NTQ5IDAtNC4wNjggMS44NjA0LTEuNDg4MyAxLjgzNTUtMS40ODgzIDQuOTM2MSAwIDQuMjY2NCAyLjE1OCA3LjgxMzUgMi45MjcgNC43Mzc3IDguMzg0IDQuNzM3NyAyLjAwOTIgMCAzLjk2ODgtMC42Njk3MyAxLjk4NDQtMC42Njk3MyAzLjA3NTgtMS43MzYzIDAuOTQyNTgtMC44OTI5NyAxLjUzNzktMC44OTI5NyAwLjg2ODE2IDAgMS40ODgzIDAuODE4NTYgMC42MjAxMiAwLjc5Mzc1IDAuNjIwMTIgMS45MzQ4IDAgMS40Mzg3LTAuODY4MTYgMy4yMjQ2dC0yLjA4MzYgMi44MDI5cS0wLjUyMDkgMC40MjE2OC0yLjE1OCAwLjc0NDE0LTAuOTQyNTggMC4xNzM2My0yLjUwNTMgMC45MTc3Ny0zLjY3MTEgMS43NjExLTcuNjM5OCAxLjc2MTEtNC4xNDI0IDAtOC4yNi0xLjg2MDQtNC43ODczLTIuMTU4LTcuNTY1NC02LjYyMjktMi43Mjg1LTQuMzQwOC0yLjcyODUtOS4wNzg1IDAtNS41MDY2IDMuNDIzLTEwLjA0NiAyLjk3NjYtMy45NDM5IDcuNzYzOS02LjAyNzUgMy42NDYzLTEuNTg3NSA3LjUxNTgtMS41ODc1eiIvPgogICA8cGF0aCBkPSJtNTMuMDU3IDI3Ljk0cTIuNTU0OSAwIDYuNjk3MyAxLjI2NSAwLjQ5NjA5IDAuMTQ4ODMgMC43OTM3NSAwLjE0ODgzIDAuMjQ4MDUgMCAxLjQ4ODMtMC40NDY0OCAwLjM5Njg4LTAuMTQ4ODMgMC44NDMzNi0wLjE0ODgzIDEuNjYxOSAwIDMuNDk3NSAyLjYyOTMgMS44NjA0IDIuNjI5MyAxLjg2MDQgNS4wMTA1IDAgMS4zODkxLTAuODQzMzYgMi4zNTY0LTAuODE4NTYgMC45NDI1OC0yLjAwOTIgMC45NDI1OC0wLjk5MjE5IDAtMS42MTIzLTAuMzk2ODgtMC42MjAxMi0wLjM5Njg4LTIuNzI4NS0yLjM1NjQtMi45NzY2LTIuNzc4MS01Ljg1MzktMi43NzgxLTEuMzg5MSAwLTIuMjMyNCAwLjY2OTczLTAuODE4NTYgMC42Njk3My0wLjgxODU2IDEuNzYxMSAwIDIuMTU4IDMuNzk1MSAzLjI0OTQgNS4xMzQ2IDEuNTEzMSA2LjU3MzIgMi4yMDc2IDYuMzI1MiAzLjA3NTggNi4zMjUyIDkuMDUzNyAwIDUuMjgzNC00LjMxNiA4LjYzMi00LjQxNTIgMy40MjMtMTEuNTM0IDMuNDIzLTMuMTc1IDAtNi42OTczLTAuNzQ0MTQtMy41MjIzLTAuNzY4OTQtNS4wODUtMS43ODU5LTEuMTkwNi0wLjc5Mzc1LTIuMTU4LTMuNDQ3OS0wLjk0MjU4LTIuNjc4OS0wLjk0MjU4LTUuMjA5IDAtMS4yMTU0IDAuNDk2MDktMS44MzU1IDAuNjIwMTItMC43OTM3NSAxLjU2MjctMC43OTM3NSAwLjk0MjU4IDAgMS44MTA3IDAuOTY3MzggMC41MjA5IDAuNTQ1NyAyLjQ1NTcgMy40OTc1IDAuOTE3NzcgMS4zODkxIDIuOTAyMSAyLjMwNjggMi4wMDkyIDAuOTE3NzcgNC4xNDI0IDAuOTE3NzcgMS44MzU1IDAgMi45NzY2LTAuNjY5NzMgMS4xNDEtMC42OTQ1MyAxLjE0MS0xLjc2MTEgMC0wLjk5MjE5LTAuODkyOTctMS43MTE1dC0yLjkwMjEtMS4zMzk1cS0zLjU0NzEtMS4xMTYyLTUuNDA3NC0yLjAzNC0xLjg2MDQtMC45NDI1OC0zLjQ3MjctMi4zNTY0LTMuOTE5MS0zLjQ3MjctMy45MTkxLTcuODg3OSAwLTIuMTgyOCAxLjAxNy00LjI0MTYgMS4wMTctMi4wODM2IDIuODc3My0zLjU5NjcgNC4xNjcyLTMuNDk3NSAxMC4xNy0zLjQ5NzV6Ii8+CiAgPC9nPgogPC9nPgo8L3N2Zz4K&logoColor=white)](https://www.nuget.org/packages/Microsoft.ClearScript.Complete) NuGet package is now available.
