### ISSUE TITLE
How to delete functions(or Propertys) from script object 

### ISSUE THREAD

**Issue by OuterHeaven07** [microsoft/ClearScript#519]
Hi ClearScript Team,

I have a (maybe stupid) question how to remove functions from the script engine so that they are not found in the properties ?

Below I have attached an example of what I would expect:

I define a function in the JS and can delete it from the script engine via the `DeleteProperty`, so that this function is no longer callable.

Of course, you can also simply set the function to `undefined`, but then the function will still be in the `global property` list

```c#
using Microsoft.ClearScript.V8;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        private static void Main(string[] args)
        {
            Console.WriteLine("Start!");

            V8ScriptEngineFlags flags = V8ScriptEngineFlags.EnableDebugging | V8ScriptEngineFlags.EnableRemoteDebugging;
            using (var engine = new V8ScriptEngine("host", flags, 9222))
            {
                engine.AddHostType(typeof(Console));

                engine.Execute(@"function MyFunc(text) {Console.WriteLine(text);}");

                engine.Execute(@"
                MyFunc(' --> Hello JS')
                ");

                var delete = engine.Global.DeleteProperty("MyFunc()");
                Console.WriteLine("is deleted ?: " + delete);

                // i would expect, that the function "MyFunc" is not in the scripe engine anymore
                engine.Execute(@"
                MyFunc(' --> Why is this still callable ?')
                ");
            }
            Console.WriteLine("Finish!");
        }
    }
}
```
Thank You

**Comment by ClearScriptLib** [comment]
Hi @OuterHeaven07,

There are a couple of issues here. First, the name of your function doesn't include parentheses:

``` C#
var delete = engine.Global.DeleteProperty("MyFunc"); // not "MyFunc()"
```

If you make this change, the output indicates that your function couldn't be deleted:

```
is deleted ?: False
```

As for _why_ it couldn't be deleted, that's a bit more elusive. It has something to do with the way V8 handles the [global object](https://developer.mozilla.org/en-US/docs/Glossary/Global_object).

Apparently, top-level scripts don't have the same access to the global object as those that run within nested scopes. Specifically, it seems that the global object has top-level and nested _facades_ that don't behave identically in all cases.

Evidently, in V8, [`function` declarations](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/function) create normal properties in nested scopes but _non-configurable_ properties in the top-level scope. It's unclear why V8 has that particular quirk, but the JavaScript standard dictates that non-configurable properties cannot be deleted.

To work around this issue, you could set a global variable to a [`function` expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/function) instead:

``` C#
engine.Execute("MyFunc = function (text) {Console.WriteLine(text);}");
```

Another possibility is to use [`eval`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval) to execute the `function` declaration in a nested scope:

``` C#
engine.Script.eval("function MyFunc(text) {Console.WriteLine(text);}");
```

Good luck!

**Comment by OuterHeaven07** [comment]
Hi @ClearScriptLib, 

thank you for your support. I´ll give it a try
