### ISSUE TITLE
StackTrace Not Working 

### ISSUE THREAD

**Issue by jaskaran0001** [Microsoft/ClearScript#52]
Stack trace is not working .

I am using the following code to fetch stack trace:

`string trace = engine.GetStackTrace();
`

It always returns blank  value.

Any help would be higly apppreciated.

Regards

**Comment by ClearScriptLib** [comment]
Hi @jaskaran0001,

If you're using JScript or VBScript, [`GetStackTrace`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_Windows_WindowsScriptEngine_GetStackTrace.htm) always returns an empty string unless you pass [`WindowsScriptEngineFlags.EnableDebugging`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_WindowsScriptEngineFlags.htm) to the engine constructor. This is a limitation of Windows script engines.

Good luck!

**Comment by jaskaran0001** [comment]
i am using the following code to create vbscript engine.

` engine = new VBScriptEngine(WindowsScriptEngineFlags.EnableDebugging);`

It is still returning empty string for GetStackTrace. Is there anything else that i need to be careful about ?

**Comment by ClearScriptLib** [comment]
Hi @jaskaran0001,

A stack trace only exists when the engine is executing script code, so calling this method only makes sense in a host method invoked by script code.

Here's a complete sample program that demonstrates `GetStackTrace` usage:

``` C#
using System;
using Microsoft.ClearScript;
using Microsoft.ClearScript.Windows;
namespace Test {
    public class Host {
        public ScriptEngine Engine;
        public void DoSomething() {
            Console.WriteLine(Engine.GetStackTrace());
        }
    }
    internal static class Program {
        public static void Main() {
            using (var engine = new VBScriptEngine(WindowsScriptEngineFlags.EnableDebugging)) {
                engine.Script.host = new Host { Engine = engine };
                engine.Execute("host.DoSomething");
            }
        }
    }
}
```

Are you calling `GetStackTrace` in some other scenario?
