### ISSUE TITLE
Is there a way to toggle V8 engine into Debug state and await for debugger?

### ISSUE THREAD

**Issue by 3da** [microsoft/ClearScript#524]
I want to toggle V8 engine into Debug state not from start. I want to execute some scripts and then turn on Debug mode.

Is it possible?

**Comment by ClearScriptLib** [comment]
Hi @3da,

>I want to execute some scripts and then turn on Debug mode.

You can use [`DocumentFlags.AwaitDebuggerAndPause`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_DocumentFlags.htm). Here's an example:

``` C#
engine.AddHostType(typeof(Console));
engine.Execute("Console.WriteLine('This script runs immediately.')");
engine.Execute(
    new DocumentInfo { Flags = DocumentFlags.AwaitDebuggerAndPause },
    "Console.WriteLine('This script waits for a debugger connection.')"
);
```

However, that flag has some limitations. Please consult the [documentation page](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_DocumentFlags.htm).

Good luck!

**Comment by 3da** [comment]
Thanks, great!
