### ISSUE TITLE
 The type or namespace name 'ClearScript' does not exist in the namespace 'Microsoft'

### ISSUE THREAD

**Issue by eliashezron** [microsoft/ClearScript#527]
I keep getting this error when i try to build the program,
![Screenshot 2023-07-27 at 18 39 29](https://github.com/microsoft/ClearScript/assets/60871378/7e31e5ba-d100-454c-a51c-3705e18470df)

What could be the problem and how do I fix this?

**Comment by ClearScriptLib** [comment]
Hi @eliashezron,

>What could be the problem and how do I fix this?

How did you incorporate ClearScript into your project?

**Comment by eliashezron** [comment]
> 

As per the documentation example [here](https://microsoft.github.io/ClearScript/Examples/Examples.html)

I am basically re-running it on my console.

**Comment by ClearScriptLib** [comment]
>I am basically re-running it on my console.

Sorry, please clarify. In order to use ClearScript, you must add the appropriate ClearScript NuGet packages to your project. Have you done that?

Thanks!

**Comment by eliashezron** [comment]
> > I am basically re-running it on my console.
> 
> Sorry, please clarify. In order to use ClearScript, you must add the appropriate ClearScript NuGet packages to your project. Have you done that?
> 
> Thanks!

yes, Here is my file structure.

<img width="315" alt="Screenshot 2023-08-06 at 17 08 24" src="https://github.com/microsoft/ClearScript/assets/60871378/d098e45d-3475-438c-8f44-c914867792d5">

**Comment by ClearScriptLib** [comment]
Hi @eliashezron,

It appears that Issue #528 refers to the same program, so we'll continue there and close this one for now. Please feel free to reopen it if you believe there's a separate issue here.

Thanks!
