### ISSUE TITLE
System.TypeLoadException has been Thrown When running a ClearScript Engine

### ISSUE THREAD

**Issue by eliashezron** [microsoft/ClearScript#528]
I am failing to run a basic ClearScript Engine. 
I keep getting this error, What could be the problem

![Screenshot 2023-07-27 at 15 43 31](https://github.com/microsoft/ClearScript/assets/60871378/6547173c-b553-4572-ae84-12746271657b)

**Comment by ClearScriptLib** [comment]
Hii @eliashezron,

>I keep getting this error, What could be the problem

Please let us know how you integrated ClearScript into your project.

Also, it looks like you've resolved the compilation problem you reported in Issue #527. Is that correct?

Thanks!

**Comment by eliashezron** [comment]
> Hii @eliashezron,
> 
> > I keep getting this error, What could be the problem
> 
> Please let us know how you integrated ClearScript into your project.
> 
> Also, it looks like you've resolved the compilation problem you reported in Issue #527. Is that correct?
> 
> Thanks!

No, I didnt resolve issue#527, I just here using the debug UI, 

Also, I am basically running the example [here](https://microsoft.github.io/ClearScript/Examples/Examples.html)

The issue is basically at instantiating of the V8JS engine.

To replicate, 
I am using Vistual studio on MacBook M2 pro

here is the code
```
using Microsoft.ClearScript;
using Microsoft.ClearScript.JavaScript;
using Microsoft.ClearScript.V8;
namespace JsTest
{

    class Program
{
    static void Main(string[] args)
    {
        // create a script engine

        using (var engine = new V8ScriptEngine())
        {

            // expose a host type

            engine.AddHostType("Console", typeof(Console));

            engine.Execute("Console.WriteLine('{0} is an interesting number.', Math.PI)");
        }
     }
}
            
```

**Comment by ClearScriptLib** [comment]
>I am using Vistual studio on MacBook M2 pro

We need to understand how you're adding ClearScript to your project. Can you post your .csproj file?

Thanks!

**Comment by eliashezron** [comment]
> > I am using Vistual studio on MacBook M2 pro
> 
> We need to understand how you're adding ClearScript to your project. Can you post your .csproj file?
> 
> Thanks!

This is my file structure, I did install the dependencies using Nuget. 

<img width="315" alt="Screenshot 2023-08-06 at 17 08 24" src="https://github.com/microsoft/ClearScript/assets/60871378/3349a522-4035-45b8-a342-acc358091bff">

**Comment by ClearScriptLib** [comment]
Hi @eliashezron,

The `TypeLoadException` above indicates that your test app is running in x64 emulation (Rosetta). Please try adding the [Microsoft.ClearScript.osx-x64](https://www.nuget.org/packages/Microsoft.ClearScript.osx-x64) package.

Cheers!

**Comment by eliashezron** [comment]
> Hi @eliashezron,
> 
> The `TypeLoadException` above indicates that your test app is running in x64 emulation (Rosetta). Please try adding the [Microsoft.ClearScript.osx-x64](https://www.nuget.org/packages/Microsoft.ClearScript.osx-x64) package.
> 
> Cheers!

This solution worked for me, Thank you.
