### ISSUE TITLE
How to use ClearScript in VC++ project?

### ISSUE THREAD

**Issue by fangjialivico** [microsoft/ClearScript#544]
In my VC++ project,
we want to use ClearScript,  but I can't find any instructions about how to use ClearScript in VC++ project.

Could you give me an example?

**Comment by ClearScriptLib** [comment]
Hi @fangjialivico,

>I can't find any instructions about how to use ClearScript in VC++ project.

ClearScript is designed for [.NET](https://dotnet.microsoft.com/en-us/) applications and optimized specifically for C#. You can use it with [C++/CLI](https://learn.microsoft.com/en-us/cpp/dotnet/dotnet-programming-with-cpp-cli-visual-cpp), but native C++ applications are better off interfacing directly with [V8](https://v8.dev/), which exposes a C++ API.

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts about this topic. Thank you!
