### ISSUE TITLE
Whether ClearScript acts as a parser.

### ISSUE THREAD

**Issue by Rison-Hub** [microsoft/ClearScript#548]
Does ClearScript parse JavaScript code into ASTs (Abstract Syntax Trees), allowing you to traverse and analyze code structures more easily.
Example:
```
let IFstr_TYbox="A";
function Test1() {
	zp.Print(GlobalPara); }
}
function Test2() {
	zp.Print(GlobalPara); } function Test2() { zp.
}

function Main() {
	zp.Print(GlobalPara); } function Main() { zp.
}
Main().
```

I want to iterate through and extract all the function code

**Comment by ClearScriptLib** [comment]
Hi @Rison-Hub,

ClearScript uses [V8](https://v8.dev/) or [JScript](https://learn.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/x85xxsf4(v=vs.100)) to execute JavaScript code. Parsing is part of that, but neither ClearScript nor the script engines themselves expose JavaScript parsing services to the host.

You can use a library such as [Esprima](https://esprima.org/) to parse and inspect JavaScript code.

Good luck!

**Comment by Rison-Hub** [comment]
Oh, that's a shame. But thank you very much.
