### ISSUE TITLE
How to use Task and Task.Run in VBScript?

### ISSUE THREAD

**Issue by wangjinbiao1985** [microsoft/ClearScript#549]
I'm having problems.
The C# code is below:

`engine.AddHostType("CSTask", typeof(Task));`
`engine.AddHostType("CSAction", typeof(Action));`

The VBScript code is below:

`Function LoopOut1()`
 `  '............`
`End Function`

`Function LoopOut2()`
`   '............`
`End Function`

`Function LoopOut3()`
`   '............`
`End Function`

`CSTask.Run(host.del(CSAction,LoopOut1))`
`CSTask.Run(host.del(CSAction,LoopOut2))`
`CSTask.Run(host.del(CSAction,LoopOut3))`

But the final results are not executed as expected, they are executed sequentially.
LoopOut1 -> LoopOut2 -> LoopOut3

So, what is the correct way to use Task and Task.Run?

**Comment by wangjinbiao1985** [comment]
Thank you very much.

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions about this topic. Thank you!
