### ISSUE TITLE
Host function with a optional parameter

### ISSUE THREAD

**Issue by kevinkoenig** [Microsoft/ClearScript#55]
I am using ClearScript quite extensively to add scripting to my web application.  I want to create a Host function that takes an optional parameter like:

```
public class HostClass
{
        public bool hidden(bool hidden)
        {
            if (! (hidden is ClearScript.Undefined))
            {
            }
        }
}

```
how do I define the parameter so i can call it from the JavaScript
```
host.hidden();
```
if I don't pass the parameter it gives an error (which is expected based on the way that the API is defined).  Is there a way to configure the parameter to the hidden() API so it can accept a javascript value that may be undefined or a Boolean.

Thanks in Advance

**Comment by ClearScriptLib** [comment]
Hi @kevinkoenig,

ClearScript aims to make .NET APIs accessible to script code without modification, so any .NET technique to make a parameter optional should work with ClearScript.

For example, you could define a default argument:

``` C#
public bool hidden(bool hidden = false) {
    return hidden;
}
```

Or, if you needed to detect when no argument was provided, you could define an overload:

``` C#
public bool hidden() {
    return hidden(false);
}
public bool hidden(bool hidden) {
    return hidden;
}
```

Or even use a nullable parameter type:

``` C#
public bool hidden(bool? hidden = null) {
    return hidden ?? false;
}
```

Good luck!

**Comment by kevinkoenig** [comment]
Thank you for the rapid reply.  In fact i tired the nullable parameter but i did not set the default value to null which cased it to not work correctly.  I should have gotten this one myself

Thanks again
