### ISSUE TITLE
ClearScriptV8.win-x86.dll and ClearScriptV8.win-x64.dll missing on Publish

### ISSUE THREAD

**Issue by mauriciocirelli** [microsoft/ClearScript#566]
Dear,

I have an old project that used to run ClearScript v5, which we had to manually add native V8 libraries to the output directory.
Everything worked fine until we needed to upgrade this project to use recent VS2022, .NET Framework, etc...

We installed ClearScript from Nuget v7.4.4 and when we debug the app within VS2022, everything works.
However, when we Publish this app (Windows Form Application) from within VS2022 Publish Menu, those DLLs are not copied to the output directory.

In order to workaround it, I had to enter into the packages folder to get those dlls and copy them manually, the same old way we used to do.

Is it expected or this is something that should have been automated by NuGet scripts by now?

Thank you!

**Comment by ClearScriptLib** [comment]
Hi @mauriciocirelli,

>Is it expected or this is something that should have been automated by NuGet scripts by now?

It's expected if you're still targeting .NET Framework, which doesn't publish native libraries from NuGet packages.

ClearScript now supports the cross-platform, open-source .NET platform, which correctly publishes the native libraries.

Thanks!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or findings related to this topic. Thank you!
