### ISSUE TITLE
Question: ScriptEngine.HostData

### ISSUE THREAD

**Issue by dementcore** [microsoft/ClearScript#569]
Hi!

I have a doubt about `ScriptEngine.HostData` property. 
What is the intended form of using it??

Thanks!!!

**Comment by ClearScriptLib** [comment]
Hi @dementcore,

`HostData` allows the host application to associate arbitrary data with a script engine. The script engine does nothing with the property value except hold onto it on the application's behalf – something that could be useful in applications that manage multiple script engines. 

Allowing the host to associate arbitrary data with library objects is a common API pattern.

Good luck!

**Comment by dementcore** [comment]
Thanks for your answer!

There is a way to obtain the executing scriptengine when a host exposed method is invoked from script?

**Comment by ClearScriptLib** [comment]
>There is a way to obtain the executing scriptengine when a host exposed method is invoked from script?

Yes, you can use [`ScriptEngine.Current`](https://microsoft.github.io/ClearScript/Reference/html/P_Microsoft_ClearScript_ScriptEngine_Current.htm).

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions related to this topic. Thank you!
