### ISSUE TITLE
Add support for Xamarin.Android

### ISSUE THREAD

**Issue by ackava** [Microsoft/ClearScript#57]

**Comment by ClearScriptLib** [comment]
Closing as duplicate of Issue #9.

**Comment by ackava** [comment]
@ClearScriptLib Will .NetStandard work on Xamarin.Android? or will it only be specific to windows?

**Comment by ClearScriptLib** [comment]
@ackava .NET Standard is an API specification that Mono should support eventually if it doesn't already. However, ClearScript is unlikely to work on platforms other than Windows due to its reliance on [mixed assemblies](https://msdn.microsoft.com/en-us/library/x0w2664k.aspx).
