### ISSUE TITLE
Question: try pattern from script

### ISSUE THREAD

**Issue by dementcore** [microsoft/ClearScript#570]
Hi!

It is possible to invoke a host function with out parameters from script and get the value in script after invoke?

Example host code:

```csharp
public int tryread(int count, out string result) 
{
    result = "Test";
    return 10;
}
```

Example script code:
```js
let variable= '';
var result = myhostobj.tryread(5,variable);
variable == 'Test'; //the host method invocation fills this script variable from the out parameter of tryread host method???
```

Thanks in advance!

**Comment by ClearScriptLib** [comment]
Hi @dementcore,

You can use a [host variable](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_newVar__1.htm) for this purpose.

First, you'll need a [`HostFunctions`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_HostFunctions.htm) object:

``` C#
engine.AddHostObject("host", new HostFunctions());
```

Once you have that, you can do the following in JavaScript:

``` JavaScript
let variable= host.newVar('');
var result = myhostobj.tryread(5,variable.out);
variable.value == 'Test'; // true
```

Good luck!

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional thoughts or questions about this topic. Thank you!
