### ISSUE TITLE
VBScript will be discontinued, can clear script be a solution?

### ISSUE THREAD

**Issue by Ddiidev** [microsoft/ClearScript#580]
Knowing that VBscript will be discontinued, I would like to understand if **ClearScript** is an intermediary between **C#** and **WSH**, or is it really a VBS code interpreter.

Because if ClearScript is just an intermediary, we won't be able to use VBS in the ClearScript library anymore, right, or am I wrong?

**Comment by ClearScriptLib** [comment]
Hello @Ddiidev,

>I would like to understand if ClearScript is an intermediary between C# and WSH, or is it really a VBS code interpreter.

Technically, it's neither. The VBScript interpreter is a Windows feature, and ClearScript provides a convenient .NET API for it. ClearScript is unrelated to WSH, which also uses the VBScript interpreter under the covers.

>we won't be able to use VBS in the ClearScript library anymore, right, or am I wrong?

According to the information [here](https://techcommunity.microsoft.com/t5/windows-it-pro-blog/vbscript-deprecation-timelines-and-next-steps/ba-p/4148301), the VBScript interpreter will become an opt-in feature sometime around 2027, and starting sometime after that, new Windows versions won't include it.

If your application relies on the VBScript interpreter, it won't work on those future Windows versions unless a 100% compatible replacement is installed.

Good luck!

**Comment by Ddiidev** [comment]
Thanks!
