### ISSUE TITLE
Runtime support appears incorrect

### ISSUE THREAD

**Issue by danpetitt** [microsoft/ClearScript#586]
> Support for .NET 5.0+, .NET Framework 4.5+, .NET Core 3.1, and .NET Standard 2.1.

I don't think this is correct, the library is net standard 2.1 which means it can't be used on .net framework (any version) as far as I am aware and nuget only has a version that is standard 2.1

**Comment by ClearScriptLib** [comment]
Hello @danpetitt,

The NuGet packages contain multiple builds for different frameworks and runtimes. For example, if you open the `lib` folder [here](https://nuget.info/packages/Microsoft.ClearScript.Core/7.4.5), you'll see subfolders holding ClearScript.Core.dll builds for the following TFMs: `net45`, `net471`, `net5.0`, `netcoreapp3.1`, `netstandard2.1`, and `uap10.0`. Those should cover the targets and runtimes listed on the home page.

Cheers!

**Comment by danpetitt** [comment]
Thanks for that; any chance they can get published to nuget as part of the normal release cycle?

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you have additional questions or comments on this topic.
