### ISSUE TITLE
License ambiguity between git repo and NuGet

### ISSUE THREAD

**Issue by martinknafvework** [microsoft/ClearScript#587]
I have a question about which licenses applies to this library.

On https://www.nuget.org/packages/Microsoft.ClearScript.Core/7.4.5/License, it lists a large number of licenses, such as:

* MIT License
* GNU LESSER GENERAL PUBLIC LICENSE
* ICU License
* The BSD License

In the License.txt in this git repo, only MIT is included.

My interpretation of this is that the code in this git repository is covered by MIT, but if I use ClearScript with Google V8 (via the Microsoft.ClearScript.Core NuGet package), then a number of other licenses are also applicable since I would need to include Google V8 in my application (which have a longer list of licenses). Is that interpretation correct?

**Comment by ClearScriptLib** [comment]
Hello, @martinknafvework,

>Is that interpretation correct?

Yes. The V8 build pulls in a variety of libraries covered by a number of licenses, some of which require that the license text be included with any binary distribution.

The ClearScript code itself is covered by the MIT license.

Good luck!

**Comment by martinknafvework** [comment]
Thank you :)
