### ISSUE TITLE
Wait for event

### ISSUE THREAD

**Issue by balazsszekely** [Microsoft/ClearScript#6]
Hi!

How can i wait for an event, and then continue execution? If I just  connect a host event source to a script handler function, the script execution finished before it is raised. How can I solve it?

I would like something like this:

```
var obj = new StatedObject();

//...

//do process...

//wait obj.Status changed to "Stopped"

//continue process...
```

Thanks!

**Comment by ClearScriptLib** [comment]
@balazsszekely Yes, the script that set up the event connection will terminate, but the script handler function will be invoked when the event is raised. Is that not the expected behavior?

**Comment by balazsszekely** [comment]
Yes, the problem was that I disposed the ScriptEngine before event was raised. Thanks.
