### ISSUE TITLE
Version 5.5.2 adds new properties to the objects

### ISSUE THREAD

**Issue by HSyr** [Microsoft/ClearScript#60]
When an empty object is created and retured by:
`function Test()
{
   return {};
}`

and then used at C# it contains the following properties:
`__defineGetter__`
`__defineSetter__`
`__lookupGetter__`
`__lookupSetter__`
`__proto__`
`constructor`
`hasOwnProperty`
`isPrototypeOf`
`propertyIsEnumerable`
`toLocaleString`
`toString`
`valueOf`

When such object is for instance serialized using _Newtonsoft.Json.JsonConvert.SerializeObject_ and exception _Process is terminated due to StackOverflowException_ occurs.

The same code at version 5.5.1 returned a real empty object without these properties and the serialization worked as expected.

**Comment by nloewen** [comment]
As a workaround, you can use `Object.create(null);` to create objects without these properties, or use a serializer that supports loops. The exception occurs because __proto__ references the object being serialized.

**Comment by HSyr** [comment]
Unfortunately using `Object.create(null);` is not feasible for me as I receive objects from the source code(s) that is out of my control. Also I have to stick with the serializer.
Question - will the future ClearScript releases keep creating objects with these properties?

**Comment by ClearScriptLib** [comment]
Hi @HSyr,

ClearScript doesn't add those properties; they're intrinsic to V8 JavaScript objects created in the normal manner (that is, with the standard prototype).

These properties are not enumerable on the JavaScript side, but ClearScript 5.5.2 exposes them to .NET dynamic enumeration in order to make them accessible in some scenarios (see Issue #47).

ClearScript doesn't officially support script object serialization via Json.NET, but we're investigating. It may be possible to make it work without breaking property access in all supported scenarios.

Thanks!

**Comment by HSyr** [comment]
Hi,
I understand the properties are intrinsic to V8 but I do not need them at the C# side at all. Not only because of failing JSON serialization.

I will keep using older version 5.5.1 or Microsoft.ClearScript.Windows that does not generate these properties.

**Comment by ClearScriptLib** [comment]
@HSyr, can you specify what problems, besides Jdon.NET serialization failures, these properties are causing? That would help us gauge the severity of this issue. Thanks!

**Comment by HSyr** [comment]
The "problem" is, that they (the properties) are simply there but they are not expected, because as I pass the objects to the other components (that are out of my control) of our system and these components process all available object properties...

Let’s use analogy: when I call `new object()` at C# (or at many other languages), then all I get is really an empty object without any unwanted properties ,fields, ... I expect the same behavior in our scenario. 

And this is what Microsoft.ClearScript.Windows.JScriptEngine does!

I thank you too!

**Comment by HSyr** [comment]
These components are not .NET based. They receive the objects via JSON, so there is no DynamicObject and IReflect available. They use JSON schemas. I do not want to "dirty" the object passed to these components with unexpected and useless properties.

When I call `new object()` then from my perspective I do not see any public properties. There are some public methods only. So you are right, there are members, but we talk about properties that are to be serialized, not methods.

I am aware there might be private (and often undocumented) members in objects (I used them with reflection e.g. when making copy of Controls including events settings), but this is not case we are talking about.

I thank you too.

**Comment by ClearScriptLib** [comment]
> These components are not .NET based. They receive the objects via JSON, so there is no DynamicObject and IReflect available.

Is the conversion of script objects to JSON always done via Json.NET?

**Comment by HSyr** [comment]
Yes, always.
The conversion WAS ALWAYS available with version 5.5.1. The conversion IS NOT available with 5.5.2 for the reasons we discuss.
Thank you.

**Comment by ClearScriptLib** [comment]
Thanks for your help. Version 5.5.3 should have a fix for this issue.

**Comment by HSyr** [comment]
I THANK YOU a lot. Looking forward to 5.5.3.

**Comment by ClearScriptLib** [comment]
[Version 5.5.3](https://github.com/Microsoft/ClearScript/releases/tag/5.5.3) has been posted.

**Comment by HSyr** [comment]
Thank you very much.
When will the 5.5.3 be available via NuGet from VisualStudio?

**Comment by ClearScriptLib** [comment]
Hi @HSyr,

We don't release ClearScript binaries. If you're using a NuGet package, consider contacting its owners or building ClearScript yourself as outlined [here](https://microsoft.github.io/ClearScript/Details/Build.html).

Good luck!

**Comment by HSyr** [comment]
The NuGet Package "ClearScript.V8 by Microsoft, Google" does not specify Owner(s), the field is empty. It says Author(s) is "Microsoft, Google" and project URL is https://github.com/Microsoft/ClearScript. So who do you recommend to contact?
Thank you.

**Comment by HSyr** [comment]
Thank you again. Hynek
