### ISSUE TITLE
Tutorials don't help!

### ISSUE THREAD

**Issue by apostrophesoftware** [Microsoft/ClearScript#61]
Hello

I am trying to evaluate ClearScript against JInt, and unfortunately I am unable to get ClearScript to work with some simple examples, and I find that typically for Microsoft, the documentation is underwhelming and only helpful if you know how the library works.

I am trying to get a script to work that constructs an object and performs some actions on the object.  I have looked at the tutorial and am unable to get my object constructed.  I get Invalid constructor invocation or cannot find constructor errors.

My object constructor has the following signature: Blah(0, 0, null, 'Test Product', '', 0, 0, 0, false, null, false, null, null, null, null)

How do I call this from JavaScript?

I am using the following code

`            var engine = new V8ScriptEngine();

            engine.AddHostObject("host", new HostFunctions());
            engine.AddHostType("blah", typeof(MyType));
`
and the script is as follows

`var newBlah = new host.newObj(blah, 0, 0, null, 'Test Product', '', 0, 0, 0, false, null, false, null, null, null, null);`

Any help greatly appreciated

**Comment by ClearScriptLib** [comment]
Hi @apostrophesoftware,

You should be able to use one of two patterns:

``` JavaScript
var newBlah = host.newObj(blah, ...);
```

Or simply:

``` JavaScript
var newBlah = new blah(...);
```

Please let us know if neither works for you.

**Comment by apostrophesoftware** [comment]
Hello

As stated in my original messages, neither of the two methods work and Exceptions are thrown

**Comment by ClearScriptLib** [comment]
Your original message reads:

``` JavaScript
var newBlah = new host.newObj(blah, ...);
```

That pattern is incorrect. If the two we posted don't work either, please check your constructor signature. If you still can't get it to work, please post your class code (or just the full constructor signature), and we'll be happy to investigate.

Thanks!

**Comment by apostrophesoftware** [comment]
Hello

The constructor signature is as follows:
```
public Product([int? Id = null], [int? Version = null], [System.Collections.Generic.List<IO.Tripletex.Model.Change> Changes = null], [string Name = null], [string Number = null], [decimal? CostExcludingVatCurrency = null], [decimal? PriceExcludingVatCurrency = null], [decimal? PriceIncludingVatCurrency = null], [bool? IsInactive = False], [IO.Tripletex.Model.ProductUnit ProductUnit = null], [bool? IsStockItem = False], [IO.Tripletex.Model.VatType VatType = null], [IO.Tripletex.Model.Currency Currency = null], [IO.Tripletex.Model.Department Department = null], [IO.Tripletex.Model.Account Account = null])


```
Product is defined in the IO.Tripletex.Model namespace, which is in the IO.Tripletex.dll

The following code generates the error below
`            var engine = new V8ScriptEngine();

            engine.AddHostObject("host", new HostFunctions());
            engine.AddHostType("ttProduct", typeof(IO.Tripletex.Model.Product));


            string script = @"var p = new ttProduct(0, 0, null, 'Test Product', '', 0, 0, 0, false, null, false, null, null, null, null);
                              var result = p.toJson();";
            engine.Execute(script);
            var result = engine.Script.result;
`

**"Error: Constructor on type 'IO.Tripletex.Model.Product' not found."**

And the following code generates the exception below

`            var engine = new V8ScriptEngine();

            engine.AddHostObject("host", new HostFunctions());
            engine.AddHostType("ttProduct", typeof(IO.Tripletex.Model.Product));


            string script = @"var p = new host.newObj(ttProduct, 0, 0, null, 'Test Product', '', 0, 0, 0, false, null, false, null, null, null, null);
                              var result = p.toJson();";
            engine.Execute(script);
            var result = engine.Script.result;`

**"Error: Invalid constructor invocation"**

Thanks

**Comment by ClearScriptLib** [comment]
Hi @apostrophesoftware,

The problem has to do with the `decimal?` parameters in your constructor signature.

ClearScript invokes constructors via Reflection, which has limitations dealing with both `decimal` and nullable types. Specifically, it can't convert other numeric argument types to `decimal`, and only supports nullable arguments that are either null or of the exact underlying value type.

You can work around this problem as follows:

``` JavaScript
var p = new ttProduct(
                0, 0, null, 'Test Product', '',
                host.toDecimal(0), host.toDecimal(0), host.toDecimal(0),
                false, null, false, null, null, null, null);
```

Note that this issue applies only to constructors.

Thanks!

**Comment by apostrophesoftware** [comment]
Hi

Thanks for the update, I will have a look at your suggestion later.

Maybe an update to the documentation describing these "limitations" would be advisable

Thanks

**Comment by apostrophesoftware** [comment]
Hello

The code below now results in the following exception
`            var engine = new V8ScriptEngine();

            engine.AddHostObject("host", new HostFunctions());
            engine.AddHostType("ttProduct", typeof(IO.Tripletex.Model.Product));


            string script = @"var p = new ttProduct(host.toDecimal(0), host.toDecimal(0), null, 'Test Product', '', host.toDecimal(0), host.toDecimal(0), host.toDecimal(0), false, null, false, null, null, null, null);
                              var result = p.toJson();";
            engine.Execute(script);`

**"Error: Constructor on type 'IO.Tripletex.Model.Product' not found."**

Product class source file attached

[Product.zip](https://github.com/Microsoft/ClearScript/files/2237925/Product.zip)

**Comment by ClearScriptLib** [comment]
The first two parameters are of type `int?`, but you're forcing the arguments to `decimal`. Please try as suggested above:

``` JavaScript
var p = new ttProduct(
                0, 0, null, 'Test Product', '',
                host.toDecimal(0), host.toDecimal(0), host.toDecimal(0),
                false, null, false, null, null, null, null);
```

Thanks!

**Comment by apostrophesoftware** [comment]
Hi

Thanks for that, now I have correctly read your answer and sent the correct parameter types in I can construct the object.  I should be able to correctly use my objects in scripts now!

I now have a question about debugging.  currently I am using JInt for JavaScript interpretation in an ASP MVC dot net application,   Users are able to write scripts in the UI using the ACE editor and then step through to debug as JInt offers a step option.  During each step I can access the variables in the script and display the values to the user.  Is this type of "interactive" debugging available in ClearScript_

Thanks

**Comment by ClearScriptLib** [comment]
Hi @apostrophesoftware,

ClearScript supports script debugging with V8. For details, see Section V in [Building, Integrating, and Deploying ClearScript](https://microsoft.github.io/ClearScript/Details/Build.html).

Good luck!
