### ISSUE TITLE
How do I build V8 with an unreliable Internet connection?

### ISSUE THREAD

**Issue by AnsisMalins** [microsoft/ClearScript#612]
I'm on a slow mobile Internet connection. The V8Update script fails at some point during one of the "downloading X" steps. If I re-run it, it seems to start from the beginning every time. How do I resume from the last successful step, or how do I download all the things myself by hand and feed them to the V8Update script?

**Comment by ClearScriptLib** [comment]
Hi @AnsisMalins,

>How do I resume from the last successful step, or how do I download all the things myself by hand and feed them to the V8Update script?

Unfortunately, we don't have a simple solution for you. All we can suggest is that you take a look at the **main** and **download** sections of the V8Update script and execute those commands manually until they succeed. Once you've completed the **download** section, you can run "V8Update /n" to skip the download and proceed to the build.

Good luck!

**Comment by AnsisMalins** [comment]
That will have to do.
