### ISSUE TITLE
error: '_Set_ptr_rep_and_enable_shared' is a private member of 'std::shared_ptr<bool>'

### ISSUE THREAD

**Issue by AnsisMalins** [microsoft/ClearScript#613]
V8Update fails at the "Building V8" step. Here's the log file I found: [build-Win32-Release.log](https://github.com/user-attachments/files/17935967/build-Win32-Release.log)

Please advise.

Windows SDK version as seen in "C:\Program Files (x86)\Windows Kits\10\SDKManifest.xml": 10.0.26100.0
Visual Studio version as reported by Visual Studio Installer: 17.12.2

**Comment by ClearScriptLib** [comment]
Hi @AnsisMalins,

We tested V8Update in ClearScript 7.4.5 with those exact Visual Studio and Windows SDK versions and did not encounter any issues.

A couple of possibilities:

1. Are you making any modifications to V8 or ClearScript prior to building?
2. Are you invoking V8Update in a Visual Studio Developer Command Prompt?
3. Do you have the "Desktop development with C++" Visual Studio workload installed?

Thanks!

**Comment by AnsisMalins** [comment]
Ah-ha! I was trying to build version 7.4.2. It is not great that older versions become unbuildable so quickly, but okay, 7.4.5 builds fine, I'll update to it.
