### ISSUE TITLE
Is V8 `ContinuationCallback` work without host data access?

### ISSUE THREAD

**Issue by JJLovesLife** [microsoft/ClearScript#617]
I saw this comment in a test:

https://github.com/microsoft/ClearScript/blob/1d2800b2575863b4de9cc2cb6d05c4b2623b49f4/ClearScriptTest/V8ScriptEngineTest.cs#L546

But based on my test, I don't need to access host data to be able to terminate execution. And this is using `v8::Isolate::TerminateExecution`, which I am not very familiar with, but I am not seeing a reason why it cannot terminate without access host data.
Was these an out-of-data comments? Or is there more complex reason behind?

**Comment by ClearScriptLib** [comment]
Hi @JJLovesLife,

>Was these an out-of-data comments?

It's a very old comment. It's likely that we were encountering issues like that with V8's aggressive JIT optimizer, but the V8 team has overhauled the JIT compiler several times since then.

Good luck!

**Comment by JJLovesLife** [comment]
@ClearScriptLib Thanks for answering.
