### ISSUE TITLE
VBScriptEngine, security issues

### ISSUE THREAD

**Issue by andreyzapt** [Microsoft/ClearScript#63]
I have an issue with all computers in AD:

I'm getting this error after creating VBScriptEngine with debugging flag:
  either a required impersonation level was not provided, or the provided impersonation level is invalid. (Exception from HRESULT: 0x80070542)

The problem is around this line: 
  if (processDebugManager.TryAddApplication(debugApplication, out debugApplicationCookie))

Any ideas which restriction could it be?

**Comment by ClearScriptLib** [comment]
@andreyzapt Are you aware of any policy settings that affect users' ability to debug applications?

**Comment by andreyzapt** [comment]
@ClearScriptLib "Run As Administrator" -> same result. What policies are you talking about?

**Comment by ClearScriptLib** [comment]
There's [SeDebugPrivilege](https://docs.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/debug-programs), but that shouldn't be required for debugging one's own processes.

The error code appears to be `HRESULT_FROM_WIN32(ERROR_BAD_IMPERSONATION_LEVEL)`, but that isn't listed in the [`AddApplication` documentation](https://docs.microsoft.com/en-us/scripting/winscript/reference/iprocessdebugmanager-addapplication).

The odd thing is that `TryAddApplication` simply returns `false` for any error code, so it isn't clear how an exception is being raised. Can you provide a stack trace?

**Comment by ClearScriptLib** [comment]
Please reopen this issue if you can provide further information.
