### ISSUE TITLE
NuGet package for version 5.5.3

### ISSUE THREAD

**Issue by boukestam** [Microsoft/ClearScript#64]
The new version (5.5.3) has not been published to NuGet yet. Will this still be done or do I need to build the source code myself?

**Comment by Taritsyn** [comment]
Hello!

See the [“Update Nuget to 5.5 please!!”](https://github.com/Microsoft/ClearScript/issues/28) discussion.

**Comment by boukestam** [comment]
Ah, I didn't know that. Thanks for the quick reply!
