### ISSUE TITLE
XML Documentation missing in NuGet package

### ISSUE THREAD

**Issue by c-s-n** [Microsoft/ClearScript#69]
You don't bundle the XML Documentation in the current `Microsoft.ClearScript.5.5.3` NuGet package, although the project contains pretty good documentation and the XML Documentation file is even generated on build.

Could you please add that in the next NuGet package release? It's just a `file` tag in the `.nuspec`. Thanks.

**Comment by ClearScriptLib** [comment]
We'll take care of it. Thanks!

**Comment by ClearScriptLib** [comment]
Fixed in the [Version 5.5.4 NuGet package](https://www.nuget.org/packages/Microsoft.ClearScript/5.5.4).
