### ISSUE TITLE
MSBuild targets file in NuGet package incompatible with Visual Studio 2015

### ISSUE THREAD

**Issue by c-s-n** [Microsoft/ClearScript#74]
When including the current `Microsoft.ClearScript.5.5.3` NuGet package in a Visual Studio 2015 (Update 3) project, the following error occurs upon install or clean/build:

> The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.	

It comes down to file `build/Microsoft.ClearScript.targets` in the NuGet package, where the `<Project>` line should instead be `<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">`. This ensures compatibility to Visual Studio 2015 and 2017.

**Comment by ClearScriptLib** [comment]
Thanks for reporting this!
