### ISSUE TITLE
ASP.NET MVC/Web API incompatibility due to native DLLs

### ISSUE THREAD

**Issue by c-s-n** [Microsoft/ClearScript#75]
**Background**
Using `Microsoft.ClearScript.5.5.3` NuGet package with an ASP.NET MVC/Web API project. The contained MSBuild targets file copies the native DLLs to the output directory and is executed "BeforeTargets" `PrepareForBuild`.

**Problem**
There are multiple issues with this at compilation and runtime, all resulting in either of the following errors, both for the 32 and 64 bit DLL:

> Could not load file or assembly 'ClearScriptV8-32.DLL' or one of its dependencies. The specified module could not be found.

> Could not load file or assembly 'ClearScriptV8-32.DLL' or one of its dependencies. An attempt was made to load a program with an incorrect format.

Compilation time means the ASP.NET Compilation Tool (`aspnet_compiler.exe`) that is e.g. invoked when setting `<MvcBuildViews>` to true, leading to a build failure ("error ASPCONFIG").
Runtime means that ASP.NET MVC/Web API always loads all the libraries from the bin folder on startup, essentially leading to a yellow screen of death.

**Solution/expected behavior**
The **runtime problems** can be circumvented by adding to the project's `Web.config` and _all Area's_ `Views/Web.config` the following:
```XML
<compilation>
  <assemblies>
    <remove assembly="ClearScriptV8-64" />
    <remove assembly="ClearScriptV8-32" />
  </assemblies>
</compilation>
```
That should be either automated from within the NuGet package installer, or at least be documented properly (otherwise people will look into various unrelated `BadImageFormatException` topics...).

The **compilation problems** would imho require that the native DLLs are ensured to only be copied upon publish, and must not be present at build time. That should be possible with the MSBuild pipeline, however ASP.NET projects would need to be distinguished from projects of another type.

**Comment by ClearScriptLib** [comment]
Hi @c-s-n,

Thanks for providing so much information about this issue.

In the past we recommended that ASP.NET users copy the ClearScriptV8 assemblies to the deployment root rather than `bin`, but the `Web.config` change is probably a better solution, especially for consumers of the NuGet package. We'll update the documentation and add a link in the package description.

We were not aware of the compilation-time issue and will investigate that.

Cheers!

**Comment by ClearScriptLib** [comment]
@TehWardy Your ASP.NET code should be able to consume V8; it's just that the initial compilation loads all assemblies in `bin` by default, and for some reason this procedure is tripped up by the presence of mixed-mode assemblies such as ClearScriptV8. Normal on-demand loading of such assemblies (or explicit loading in ClearScript's case) should work just fine. At least, that's our understanding.

**Comment by ClearScriptLib** [comment]
We've added a section on the NuGet package in the [deployment document](https://microsoft.github.io/ClearScript/Details/Build.html).
