### ISSUE TITLE
Allow to expose types within custom namespaces

### ISSUE THREAD

**Issue by c-s-n** [microsoft/ClearScript#76]
**Background**
Host types are by default exposed to script code in the global namespace, i.e. as global script items, optionally with a custom name.
The `HostTypeCollection` allows to add types that are exposed in a JavaScript "namespace"/object hierarchy. The exposed types however are available under the name given from `ScriptEngine.AddHostObject(string, object)`, combined _with their real C# namespace_.

**Problem**
No custom script namespace hierarchies are possible. This prevents designing proper script APIs that don't expose the internal structure.

**Feature request**
Extend `HostTypeCollection` with a way to add types with a custom name plus optional namespace hierarchy.

**Comment by c-s-n** [comment]
If someone is interested, I could share a way that at least allows a "NamespacedHostObject", making use of the `PropertyBag` class, like `HostTypeCollection` does. That works sufficiently, because `PropertyBag.SetPropertyNoCheck(string, object)` can add arbitrary objects without having to wrap them.

It would still be nice to also have native support for that...

**Comment by ClearScriptLib** [comment]
Hi @c-s-n,

You can hide the managed namespace hierarchy very easily. Consider this managed class:

``` C#
namespace MyNamespace {
    public class Util {
        public static void doSomething() {
            // do something
        }
        public static void doSomethingElse() {
            // do something else
        }
    }
}
```

Suppose also that you want to expose a logging method based on `Console.WriteLine`. Here's how you might do that:

``` C#
var lib = new HostTypeCollection();
lib.AddType(typeof(MyNamespace.Util));
lib.AddType(typeof(System.Console));

dynamic installApi = engine.Evaluate(@"(
    function (lib) {
        myApi = {};
        myApi.util = lib.MyNamespace.Util;
        myApi.console = { log: lib.System.Console.WriteLine };
    }
).valueOf()");

installApi(lib);
```

Your script code can then do this:

``` C#
engine.Execute(@"
    myApi.util.doSomething();
    myApi.console.log('Hello!');
");
```

As you can see, you can expose classes and even individual members nested arbitrarily within native script hierarchies.

Good luck!

**Comment by c-s-n** [comment]
Dear @ClearScriptLib,

this approach indeed works as expected! Thank you for this idea.

Still, it might be beneficial to have that configurable solely on the C# side, so let's leave the "request" label in place.

_Note: I'm using that with a modified ClearScript.Manager (that now uses your latest NuGet package) and that also works fine, as I can gain raw access to the ScriptEngine before running the actual script._

**Comment by ClearScriptLib** [comment]
We believe that the combination of [`PropertyBag`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_PropertyBag.htm) and [`ToHostType`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_Extensions_ToHostType.htm) provide the means to expose arbitrary host type hierarchies entirely from managed code. Please reopen this issue if you have further questons or concerns on this topic.
