### ISSUE TITLE
"toString()" of "DateTime" returns unexpected result in script 

### ISSUE THREAD

**Issue by dwanboweb** [Microsoft/ClearScript#77]
I wrote the code such as:
          engine.Execute(@" Console.WriteLine(DateTime.Now.toString('yyyy-MM-dd'))");
but it returns "[object HostObject]";
![problem](https://user-images.githubusercontent.com/17172451/47554772-ad168700-d93c-11e8-96f7-750171709f39.png)
      the version is 5.5.2,I am confused about it

**Comment by c-s-n** [comment]
Dear @dwanboweb,

you are using the native JavaScript `toString` method on an object (which happens to be a ClearScript wrapper, namely `HostObject`). Instead, you need to use the exposed C# `ToString`.

See following difference:
```C#
@"
Console.WriteLine(DateTime.Now.toString(""yyyy-MM-dd""));
Console.WriteLine(DateTime.Now.ToString(""yyyy-MM-dd""));
";
```
Output:
> [object HostObject]
> 2018-10-26

**Comment by dwanboweb** [comment]
> I wrote the code such as:
> engine.Execute(@" Console.WriteLine(DateTime.Now.toString('yyyy-MM-dd'))");
> but it returns "[object HostObject]";
> ![problem](https://user-images.githubusercontent.com/17172451/47554772-ad168700-d93c-11e8-96f7-750171709f39.png)
> the version is 5.5.2,I am confused about it
