### ISSUE TITLE
Debug V8

### ISSUE THREAD

**Issue by balazsszekely** [Microsoft/ClearScript#8]
I tried to debug my javascript code executed by V8ScriptEngine. But when I tried to install Chromedevtools in Eclipse, the following error message appeared: "Could not find http://chromedevtools.googlecode.com/svn/update/dev/". Are there any other possibilty? Maybe in VS Code?

**Comment by balazsszekely** [comment]
Ok, I tried in VS Code with Node Debugger and I could attach. It's not perfect, but it works :).

**Comment by ClearScriptLib** [comment]
@balazsszekely Yes, unfortunately it looks like the Google Chrome Developer Tools package, deprecated for a while, has now been removed.

Newer V8 versions no longer support the corresponding protocol, which is why ClearScript still uses V8 5.5. We're hoping to support the new "V8 Inspector" protocol in the next release; in the meantime it's great to know that VS Code supports the original protocol. Thank you!

**Comment by ClearScriptLib** [comment]
We've posted [ClearScript 5.5](https://github.com/Microsoft/ClearScript/releases/tag/5.5.0). This release adds support for local and remote debugging via Inspector, enabling the use of Chrome DevTools and other JavaScript debuggers.

**Comment by anonhostpi** [comment]
So I haven't been successful in getting Chrome's Inspector to attach to ClearScript, is there a guide somewhere detailing how to do it, so I can see where I messed up?

**Comment by ClearScriptLib** [comment]
>So I haven't been successful in getting Chrome's Inspector to attach to ClearScript, is there a guide somewhere detailing how to do it, so I can see where I messed up?

Sorry we missed your message last week. Were you able to resolve your issue?

If you've configured Chrome's Inspector page (chrome://inspect) to monitor the appropriate ports (ClearScript uses 9222 by default), active applications with V8 debugging enabled should appear on that page dynamically. Click the desired application to launch and attach Chrome's debugger.

**Comment by anonhostpi** [comment]
No problem. I was able to figure it out. Don't remember what I did differently. I think I changed the port number that I was using.
