### ISSUE TITLE
How to call instance methods in System.String such as StartWith,Split？

### ISSUE THREAD

**Issue by dwanboweb** [Microsoft/ClearScript#80]
Hello:
 I try to write Code in my script like:
`var str='a*b*c'
str.Split('*')
str.StartWith('a')`
OR
`var str=clr.System.String.Copy('a*b*c')
str.Substring(1)
`
But the egine tell me that 'str.Substring is not a function'
I also tried:
`var a=3.0
a.ToString()
` and similar thing happens.and it Seems that the type of a is Int32?

Thank you very much

**Comment by ClearScriptLib** [comment]
Hi @dwanboweb,

Managed strings and numbers are some of the very few data types that ClearScript converts automatically to their script equivalents. It would be very difficult to use if it didn't.

However, you can use a [host variable](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_HostFunctions_newVar__1.htm) to preserve the managed data type across the boundary. This example extends the JavaScript `String` prototype to set up an easy-to-use conversion method:

``` C#
dynamic initApi = engine.Evaluate(@"
    (function (host) {
        String.prototype.toClr = function () {
            return host.newVar(this.valueOf());
        }
    }).valueOf()
");

initApi(new HostFunctions());
```

With this setup, you can do this:

``` C#
engine.Execute(@"
    clr.System.Console.WriteLine('abc'.toClr().StartsWith('ab'))
");
```

Good luck!

**Comment by dwanboweb** [comment]
Thank you~
