### ISSUE TITLE
Specifying Multiple Files for Execution

### ISSUE THREAD

**Issue by ezolotko** [Microsoft/ClearScript#82]
Please advise on how to use ClearScript in a scenario with multiple JavaScript files which are referencing each other. Let's say we have the following two files:

Second.js:
function func() {}

Main.js:
func();

When we make a call like this:
engine.Execute("Main.js", File.ReadAllText("Main.js"));
we get an exception: "'ReferenceError: secondFunction is not defined'", because the engine doesn't have the information about Second.js.

One way we could make the engine to know about the func function is to execute the Second.js before executing Main.js:

engine.Execute("Second.js", File.ReadAllText("Second.js"));
engine.Execute("Main.js", File.ReadAllText("Main.js"));

However we hesitate to use this approach because of potential undesired side effects, in case if a script author puts some "global" code in addition to function definitions into the files like Second.js

Also, we don't like the idea of sticking all files together into one in an "#include"-like manner, because it makes debugging the scripts harder and also requires us to introduce the include directives into the script code.

What is the best way of specifying the "function library" JavaScript files to be used by the code being executed by the engine?

**Comment by ClearScriptLib** [comment]
Hi @ezolotko,

Unfortunately there's no getting around the sequential, interpreted nature of JavaScript execution. It seems like you're looking for a way to do two things:

1. Ensure that scripts are executed in the correct order.
1. Ensure that independently authored scripts work correctly together.

If so, then you're probably looking for a module system of some kind - specifications and conventions for scripts to declare dependencies and expose public interfaces.

Here are some links to get you started:

- [JavaScript module loaders and bundlers – Past, Present and Future](https://javascriptstore.com/2018/04/13/javascript-module-loaders-and-bundlers-past-present-and-future/)
- [History and Background of JavaScript Module Loaders](https://appendto.com/2016/06/the-short-history-of-javascript-module-loaders/)

Note that a JavaScript module system can be extremely simple. The language provides great flexibility, and any API you expose via ClearScript can leverage all .NET facilities.

Good luck!

**Comment by ClearScriptLib** [comment]
Please let us know if you have additional questions on this topic. Thanks!
