### ISSUE TITLE
How do I get this working?

### ISSUE THREAD

**Issue by TehWardy** [Microsoft/ClearScript#83]
Apparently pulling in the nuget package "Microsoft.ClearScript" is not enough to start doing what the examples say can be done.

Can someone explain how i'm supposed to correctly install this package in to my app stack since all it seems to want to do is complain about dependencies not loading right no matter what i seem to do.

I'm running a standard .Net 4.6 compile and the package is basically being imported in to a small project that contains a few DTO's but there's nothing special about it.

Having done that i'm trying to unit test the imported stuff by writing some code that uses it in my DTO project then creating a reference to that in my unit test project and calling my code which of course in turn calls up a new instance of a V8ScriptEngine and attempts to execute some js on it.

**Comment by ClearScriptLib** [comment]
Hi @TehWardy,

Please make sure your Visual Studio installation includes the **Desktop development with C++** workload.

Thanks!

**Comment by TehWardy** [comment]
Ok weird ... I created a new Console app, and did literally nothing else but pull in the "Microsoft.ClearScript" nuget package and then put this in main ...

```
using (var engine = new V8ScriptEngine())
{
    engine.Execute("var x = 1 + 2");
}

Console.ReadKey();
```

... and it worked ... 
Something must be up with my project / solution that's causing a problem for it.

**Comment by TehWardy** [comment]
Ok i've beaten it!
Took a lot of removing and re-adding the reference ... not sure why but it seems to have gone now.
