### ISSUE TITLE
Make it possible to dump the heap

### ISSUE THREAD

**Issue by erik-kallen** [microsoft/ClearScript#85]
It would be nice if it were possible to dump the v8 heap similar to how https://github.com/bnoordhuis/node-heapdump works.

**Comment by dejx** [comment]
It is by design and described in #84  and #194 we cannot detect OOM from host application.
Having ability to create a memdump would be appreciated and useful tool when debugging mem issues.  

Is there a way to bump this issue up and can we help with solving it?

**Comment by ClearScriptLib** [comment]
Hello @dejx,

ClearScript 7.1, which should be out very shortly, adds heap dump methods to`V8Runtime` and `V8ScriptEngine`.

Thanks!

**Comment by ClearScriptLib** [comment]
We've posted [ClearScript 7.1](https://github.com/microsoft/ClearScript/releases/tag/7.1.0).
