### ISSUE TITLE
Set properties in classes with NoDefaultScriptAccess

### ISSUE THREAD

**Issue by mas-ck** [Microsoft/ClearScript#88]
Hello,

I am using a public .NET-Class in Clearscript that has a NoDefaultScriptAccess-Attribute.
This class has a public property with the ScriptMember-Attribute.

When I'm trying to set this property from script I get the following exception:
Microsoft.ClearScript.ScriptEngineException: 'Error: Property set method is unavailable or inaccessible'

To avoid this issue you have to add the ScriptMember-Attribute not only to the property but also to the setter:

    [NoDefaultScriptAccess]
    public class TestObject
    {
       [ScriptMember]
        public string Foo
        {
            get;
            [ScriptMember]
            set;
        }
    }
                
This issue seems to be new since version 5.5.4. I assume it was introduced when fixing issue #68 

Thanks for your support.

Best regards
mas-ck

**Comment by ClearScriptLib** [comment]
Hi @mas-ck,

We agree that a property's scriptability should apply to its accessors despite the lack of any hierarchical relationship between them.

In the next ClearScript release, the accessors of a scriptable property will be scriptable unless explicitly blocked via [`ScriptUsage`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptUsageAttribute.htm) or a derived attribute.

Thanks for reporting this!

**Comment by ClearScriptLib** [comment]
Fixed in [Version 5.5.5](https://github.com/Microsoft/ClearScript/releases/tag/5.5.5).
