### ISSUE TITLE
Could load D:\home\site\wwwroot\v8-x64.dll The specified module could not be found

### ISSUE THREAD

**Issue by suwatch** [Microsoft/ClearScript#89]
We have 2 host machines running the same application with clearscript.dll v5.4.9.0.   Both do not have  v8-x64.dll files.  However, on one host machine it works fine while another there is an issue attempting to load the file.  Is there a condition where ClearScript decide to or not to load the v8-x64.dll? 

```csharp
D:\local\Temporary ASP.NET Files\root\e84994be\14224e7c\assembly\dl3\a1b76e05\007421cc_d6d4d201\v8-x64.dll: The specified module could not be found
D:\home\site\wwwroot\v8-x64.dll: The specified module could not be found
D:\home\site\wwwroot\bin\v8-x64.dll: The specified module could not be found]
   Microsoft.ClearScript.V8.V8Proxy.LoadNativeLibrary() +812
   Microsoft.ClearScript.V8.V8Proxy.LoadAssembly() +64
   Microsoft.ClearScript.V8.V8Proxy.GetAssembly() +33
   Microsoft.ClearScript.V8.V8Proxy.GetImplType(Type type) +33
   Microsoft.ClearScript.V8.V8Proxy.CreateImpl(Object[] args) +150
   Microsoft.ClearScript.V8.V8Runtime..ctor(String name, V8RuntimeConstraints constraints, V8RuntimeFlags flags, Int32 debugPort) +262
   Microsoft.ClearScript.V8.V8ScriptEngine..ctor(V8Runtime runtime, String name, V8RuntimeConstraints constraints, V8ScriptEngineFlags flags, Int32 debugPort) +181
   JavaScriptEngineSwitcher.V8.V8JsEngine..ctor(V8Settings settings) +193
```

**Comment by ClearScriptLib** [comment]
Hi @suwatch,

>Is there a condition where ClearScript decide to or not to load the v8-x64.dll?

Yes.

Like many managed components, ClearScript's core library is packaged as a single assembly that works in both 32-bit and 64-bit processes. V8 however is a native component that comes in separate 32-bit and 64-bit variants.

When first instructed to create a V8 script engine or runtime, ClearScript detects the "bit-ness" of the current process and loads the assembly containing the appropriate V8 variant. In a 32-bit process, that's `v8-ia32.dll`. In a 64-bit process, it's `v8-x64.dll`.

Good luck!

**Comment by suwatch** [comment]
Thanks for the info.  We debugged more and the issue wasn't about V8 engine missing dlls.  We are running on Windows and we are supposed to use Msie Chakra JS engine (and should not have reached the code throwing error).   

For some reason, the Msie JS evaluates JS succeeded on a host but not on another.   We are debugging it.   Close this issue for now.
