### ISSUE TITLE
Calling AddHostObject throwing Invalid host item

### ISSUE THREAD

**Issue by JohnLudlow** [Microsoft/ClearScript#90]
A colleague reported that a C++/CLI sample app (which was previously working) using ClearScript was failing when calling AddHostObject with an InvalidOperationException "Invalid host item".

I've been able to reproduce the error on my computer, with 
 * the same C++/CLI project
 * a new C++/CLI project
 * a new C# project

I've also reproduced in 5.5.3 (which is what we use) and 5.5.4 (in a new project using the Nuget package) and with .NET 4.6.1 and 4.7.2.

![image](https://user-images.githubusercontent.com/1769289/49955507-d85c3200-fefa-11e8-9abe-cd030fcdd7b0.png)

Here's the code for my new C# project:

```csharp
static void Main(string[] args)
{
      using (var engine = new V8ScriptEngine())
      {
           engine.AddHostObject("message", "hello world");
      }
}
```

Given how it was working and suddenly seems to not be working it may be an environmental thing like Windows Updates but I'd appreciate some pointers.

I was trying to attach a sample but Github was unhappy with the size. When I get chance (might be Monday) I'll attach a Dropbox link or something.

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

`AddHostObject` doesn't work with fundamental values such as numbers and strings. Because these values are converted automatically to their script equivalents, they can't support some features of `AddHostObject`.

Instead of `AddHostObject`, you can do this:

``` C#
engine.Script.message = "hello world";
/* OR */
engine.Script["message"] = "hello world";
```

In fact, as this works for all objects, we recommend it over `AddHostObject` in most situations.

Good luck!

**Comment by JohnLudlow** [comment]
@ClearScriptLib Ah I thought that was just for convenience and the "correct" way would be to call the method. Thanks for the clarification. We'll update our code to work with it like a dictionary.

Thanks again

**Comment by JohnLudlow** [comment]
@ClearScriptLib Great we'll give that a shot

Thanks

**Comment by JohnLudlow** [comment]
That seems to work as a workaround.

Sort of a side question - are there any considerations for working with ClearScript across host application threads? Is it just the normal thread stuff like `lock()`

**Comment by ClearScriptLib** [comment]
>are there any considerations for working with ClearScript across host application threads? Is it just the normal thread stuff like `lock()`

`V8ScriptEngine` is thread-safe, so there's no need for manual locking, but you have to be aware of a few things.

V8's unit of isolation is not an engine but a _runtime_. When you use the [`V8ScriptEngine` constructor](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8ScriptEngine__ctor.htm), you get an engine with a private runtime, whereas all engines created by a runtime's [`CreateScriptEngine`](https://microsoft.github.io/ClearScript/Reference/html/Overload_Microsoft_ClearScript_V8_V8Runtime_CreateScriptEngine.htm) method share that runtime.

Each runtime can be active (executing script code) on one thread at a time, so ClearScript serializes most calls into a given runtime ([`Interrupt`](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Interrupt.htm) is an exception).

JScript and VBScript are very different, as they have thread affinity, meaning that they can only be active on the thread that constructed them. ClearScript supports this requirement by associating each instance with a [`Dispatcher`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.threading.dispatcher); let us know if you need more information on that.

**Comment by ClearScriptLib** [comment]
Please reopen if you encounter additional issues with `AddHostObject` or C++/CLI.

**Comment by JohnLudlow** [comment]
@ClearScriptLib will do. Is this the best way to ask general questions?

**Comment by ClearScriptLib** [comment]
@JohnLudlow Yes, unlike the old CodePlex site, GitHub doesn't have separate sections for issues and discussions.
