### ISSUE TITLE
V8 parser

### ISSUE THREAD

**Issue by BlackGad** [Microsoft/ClearScript#92]
Is it possible to use V8 (JavaScript) parser from managed side via clearscript?

Maybe you can suggest some javascript parser with prediction for custom intellisense implementation?

Backup plan is to use antlr and https://github.com/antlr/grammars-v4/tree/master/javascript

**Comment by ClearScriptLib** [comment]
Hi @BlackGad,

Neither V8 nor ClearScript expose JavaScript parsing or editing services.

ANTLR and [Esprima](http://esprima.org) seems like good options.

Good luck!
