### ISSUE TITLE
Enable JSON.stringify(HostObject)

### ISSUE THREAD

**Issue by JohnLudlow** [Microsoft/ClearScript#94]
Hi,

We have an object which we give to the ClearScript engine. It happens to be an ExpandoObject we've built up dynamically and then add to ScriptEngine.Script using the technique you described in #90.  Everything's happy until our script needs to do `JSON.stringify(o)`, and we get `undefined`. This is similar to the issue described in #37.

Do we need to build translations from the .NET objects to proper JS ones? (I hope not - we already go from our native objects to `std::map`s then to `ExpandoObject`s!). Or is there a JSON.stringify that can traverse .NET objects?

Thanks

**Comment by ClearScriptLib** [comment]
Hi @JohnLudlow,

V8's `JSON.stringify` always returns `undefined` for ClearScript's host objects. The reason for that is unclear but unimportant, as the built-in `JSON.stringify` isn't the right tool for serializing host objects for a number of reasons.

Are you using [Json.NET](https://www.newtonsoft.com/json)? It's the recommended JSON library for .NET projects. Here's how you might leverage it in this scenario:

``` C++
engine->AddHostType(JsonConvert::typeid);
engine->Execute(
    "(function () {"
    "    let js = JSON.stringify;"
    "    let clr = JsonConvert.SerializeObject;"
    "    JSON.stringify = (v, r, s) => js(v, r, s) || clr(v);"
    "})()"
);
```

With this simple setup, `JSON.stringify` can serialize both JavaScript and host objects:

``` C#
msclr::auto_handle<IDictionary<String^, Object^>> dict(gcnew ExpandoObject);
dict->Add("bar", 123);
dict->Add("baz", "qux");
engine->AddHostObject("foo", dict.get());

engine->AddHostType(Console::typeid);
engine->Execute("Console.WriteLine(JSON.stringify(foo))");
engine->Execute("Console.WriteLine(JSON.stringify({ a: 1, b: 2 }))");
```

This is obviously a simple example that ignores `JSON.stringify`'s optional arguments when serializing host objects, but it should provide a starting point.

Good luck!

**Comment by JohnLudlow** [comment]
Hi @ClearScriptLib 

Yes we use Json.NET. I tried that earlier because I wondered if that was going to be the answer, and it works (for getting things into the engine, haven't looked at the other direction yet).

I think this just changes 2 things:

- how we add things to the engine (at the moment, use reflection to give expandos to `engine.Script`, and we'll probably have to switch to serialising the object to JSON, and passing it to `Evaluate`).
- how we get things out of the engine (again, at the moment we use reflection to pass expandos to `engine.Script`, and we'll have to switch to... something - probably use reflection to traverse the tree of `V8ScriptItem`s)

**Comment by ClearScriptLib** [comment]
>at the moment, use reflection to give expandos to `engine.Script`

Why use reflection to create expandos? Can you not expose the original objects?

If you're just trying to pass structured data into (or out of) the script engine, then yes, JSON is a much better medium than a tree of expandos (or script objects). You get all the data over to the engine (or the host) in a single hop across the boundary.

**Comment by JohnLudlow** [comment]
@ClearScriptLib 

 * Well, we don't really use reflection to create expandos - we build them as a dictionary and add elements that way. We use reflection to add the expandos to `engine.Script` and make them available.
 * In this case the "original object" is a native C++ object. 
 * The structure as it exists in the native application isn't exactly the same as what we need to represent in JavaScript (our root object has a collection which we need to treat as properties in JavaScript, so some translation was always going to be necessary).

Thanks

**Comment by ClearScriptLib** [comment]
@JohnLudlow That certainly seems like an interesting mix of native, managed, and script technologies! It sounds like you have things under control. Are there any unresolved issues remaining for this topic?

**Comment by JohnLudlow** [comment]
@ClearScriptLib Indeed!

Right now, I don't think there's much you can do from your side. I'll just use JSON in most cases and it should be OK

Thanks for your help
