### ISSUE TITLE
ScriptObject Dynamic Method invocation

### ISSUE THREAD

**Issue by halittiryaki** [Microsoft/ClearScript#96]
What is the best approach to dynamically invoke a method by name on runtime for a given ScriptObject in Host context?

I want to avoid additional Expression initializations or a in-script helper function I could invoke to further do the dynamic invoke by an eval() call in script context.

Wouldn't it make sense to have the `Microsoft.ClearScript.Util.IDynamic` `public`?

Then I'd be simply able to call 
```cs 
(mytargetObj as Microsoft.ClearScript.Util.IDynamic).InvokeMethod("myfunc", new[] {"foo", "bar"}); 
```

**Comment by ClearScriptLib** [comment]
Hi @halittiryaki,

You can use [`dynamic`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic):

``` C#
((dynamic)mytargetObj).myfunc("foo", "bar");
```

Another approach is to use [`IReflect`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.ireflect):

``` C#
((IReflect)mytargetObj).InvokeMember("myfunc", BindingFlags.InvokeMethod, null, mytargetObj, new object[] { "foo", "bar" }, null, null, null);
```

Also, `ScriptObject` will have new members in ClearScript 5.5.5:

**Comment by ClearScriptLib** [comment]
Hi @halittiryaki,

You can use [`dynamic`](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/types/using-type-dynamic):

``` C#
((dynamic)mytargetObj).myfunc("foo", "bar");
```

Another approach is to use [`IReflect`](https://docs.microsoft.com/en-us/dotnet/api/system.reflection.ireflect):

``` C#
((IReflect)mytargetObj).InvokeMember("myfunc", BindingFlags.InvokeMethod, null, mytargetObj, new object[] { "foo", "bar" }, null, null, null);
```

Also, [`ScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_ScriptObject.htm) will have new members in ClearScript 5.5.5:

``` C#
((ScriptObject)mytargetObj).InvokeMethod("myfunc", new object[] { "foo", "bar" });
```

Good luck!

**Comment by halittiryaki** [comment]
`IReflect`.. missed that one. thanks.

> Also, ScriptObject will have new members in ClearScript 5.5.5:
great!

thank you!
