### ISSUE TITLE
Get Typename of wrapped ScriptObject

### ISSUE THREAD

**Issue by halittiryaki** [Microsoft/ClearScript#97]
Currently I have a lot of use for a in-script-context helper function, that returns me the actual typename of the scriptobject back to the host environment. So instead of dealing with a typename of `WindowsScriptItem` for all ScriptObjects, I can use the actual typename from the scriptcontext.

An example usecase in VBScript would be to have a global function:
```vbnet
Function VbType(obj)
    VbType = typename(obj)
End Function
```

so when I have ScriptItem whichs wraps a VBScript Object in Host context:
```vbnet
Class MyType
End Class
```

I call the global function to retrive underlying script typename:

```csharp
vbsengine.Invoke("VbType", scriptItemInstance);
```

From a quick view, I saw that the underlying script type name is readable internally by the script engine, having access to the Com-Obj wrapper.

Is there already an API available to directly read the wrapped script objects typename or would that be a feature request?

**Comment by ClearScriptLib** [comment]
Hi @halittiryaki,

We're not aware of any way to retrieve the type name of a VBScript object except via the `TypeName` function.

Unfortunately VBScript doesn't expose `TypeName` as a member of the global (root) object, but your technique of using a custom function to call `TypeName` is perfectly valid.

We'd just like to point out that instead using `ScriptEngine.Invoke`, you could simply do this:

``` C#
var typeName = (string)vbsengine.Script.VbType(scriptItemInstance);
```

Cheers!

**Comment by halittiryaki** [comment]
If you run a debug session and inspect a `WindowsScriptItem` you will find the property `<System.Dynamic.ComTypeDesc>ComTypeDesc` under:
*Non-Public members > target > Non-Public members > m_ObjectToDataMap > [{object}] > Value > ComTypeDesc > Non-Public members > TypeName*

If VisualStudio can access it, you might can do it too.


```csharp
var typeName = (string)vbsengine.Script.VbType(scriptItemInstance);
```
thanks! I guess that call won't make any difference in call footprint / speed but at least is better to read.

**Comment by halittiryaki** [comment]
thanks for further investigating. 

IMHO nearly twice as fast and the ease of access (at least for other consumers, as I have already some sort of access) is definitely worth it.

**Comment by ClearScriptLib** [comment]
Hi @halittiryaki,

For maximum flexibility, we'd prefer to expose the script item's underlying COM object instead of its type name. You could then call [`Information.TypeName`](https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.information.typename) or any other method that operates on COM objects.

Thanks again!

**Comment by halittiryaki** [comment]
That makes sense and would be very useful. Thank you

**Comment by ClearScriptLib** [comment]
[Version 5.5.5](https://github.com/Microsoft/ClearScript/releases/tag/5.5.5) includes [`IWindowsScriptObject`](https://microsoft.github.io/ClearScript/Reference/html/T_Microsoft_ClearScript_Windows_IWindowsScriptObject.htm).
