### ISSUE TITLE
Visual Studio Code connects with the engine but won't attach to script file.  

### ISSUE THREAD

**Issue by Audionysos** [Microsoft/ClearScript#99]
Hi
I configured VSC just like you said in https://microsoft.github.io/ClearScript/Details/Build.html 
The debugger is attached successfully (I can call my script function form "DEBUG CONSOLE") but I can't set breakpoints. It's saying 

> Unverified breakpoint, Breakponits set, but not yet bound

It used to work, about a year ago, on a different machine, but I believe it was on this "old" debugger...
I don't even know how it suppose to know which file is the one that is running but I don't recall to specify anything special, when it was working, other than passing file name to `Evaluate` method.

I've set up my program like this:

	class Program {
		static void Main(string[] args) {
			var sr = new ScriptRunner();
			sr.run();
			var l = ReadLine();
			while (l != "exit") {
				sr.run();
				l = ReadLine();
			}
		}
	}

and the run method

		public void run() {
			Console.WriteLine("______________________________executing script____________________________");
			Stopwatch stoper = new Stopwatch();
			object r = null;
			try {
				var c = File.ReadAllText("scripts/run.js");
				stoper.Start();
				r = engine.Evaluate("scripts/run.js", c);
				stoper.Stop();
				if (r.GetType() == typeof(VoidResult)) {
					log("Script executed in ", stoper.ElapsedMilliseconds, "ms");
				} else {
					log(r);
				}
			} catch (Exception e) {
				log(e);
			}
		}

Regardless of how I start program or debugger, the breakpoints all not active. Thank you for any help.
Also, will Visual Studio debugger be available soon? I've read that there are some issues with it and it's not fully supported.

**Comment by ClearScriptLib** [comment]
Hi @Audionysos,

Please try using [this](https://microsoft.github.io/ClearScript/Reference/html/M_Microsoft_ClearScript_ScriptEngine_Evaluate.htm) overload of `ScriptEngine.Evaluate`.

Good luck!

**Comment by Audionysos** [comment]
It works, thank you :)
